### ISSUE TITLE
[feature request] access style properties

### ISSUE THREAD

**Issue by albeva** [sass/sass#100]
One thing i miss is ability to access defined property values.
example

```
.foo {
    width: 10px;
}
.bar {
    width: 10px + .foo::width;
}
```

where `.foo::width` would return 10px and result in 20px total.

**Comment by nex3** [comment]
This is something we've considered many times in the past, and always rejected. The main reason is that there isn't a convincing use-case: it's always almost as easy to do this with variables as it is with property accessors, and that's both clearer and simpler.

The other problem is that selectors, by design, refer to broad classes of elements. What exactly does `.foo::width` mean? How does a rule like `.bar .foo` affect it? Sure, you could say that it only takes properties from selectors that exactly match, but that throws away much of the semantics and value that comes along with using selectors in the first place.

**Comment by albeva** [comment]
thanks for the reply. I would argue that property access would mean cleaner CSS contrary to what you say ( no need to clutter with variables ). Secondly access properties from inheritance. I personally find myself often wishing for this.

As for the inner workings and behavior - I believe values should cascade linearly as they appear in the sass (and not how they might appear on the website -this would be quite impossible). Specificity should be taken into account. Or simpler and almost same result could be archived via scoping.

**Comment by chikamichi** [comment]
Hi,

I often come to this pattern when writing mixins. Extending a element with +my-mixin, I'd like to be able to refer the element's properties within =my-mixin (a kind of "this" scope).

**Comment by nex3** [comment]
@chikamichi Mixins that rely on certain properties to be defined in the rules in which they're included seem very fragile. How does the user know which properties are supposed to exist? How do they remember to use them? It seems like it would be much clearer to the user to pass those values in as arguments to the mixin.
