### ISSUE TITLE
Is it safe to evaluate user sass?

### ISSUE THREAD

**Issue by stefankroes** [sass/sass#1011]
Hi!

I have a simple question to which I'm not able the find the answer online:

Is it safe/secure to evaluate/execute any sass/scss that came from user input? Or are there ways the user can inject code or for example inline sensitive files by importing them?

P.S. don't mind the different wordings; just trying to make this easier to google.

Kind regards,

Stefan Kroes

**Comment by lolmaus** [comment]
With `sass --require` a user can execute any Ruby code. He basically gets power limited only by filesystem permissions.

Probably you could use [SassC](https://github.com/hcatlin/sassc) instead of Ruby Sass. SassC has very few command line arguments and doesn't let you link extra libraries. But you lose support for Compass extensions.

**Comment by nex3** [comment]
I don't want to make any guarantees here. Right now, without any added extensions, I don't believe that Sass code can do anything that will modify the file system or access data in an unexpected way. That said, Sass isn't built to be a sandbox, and it hasn't had any sort of thorough security review. If you're worried that evaluating user code might cause harm to your system, it's your responsibility to do the homework necessary to ensure that won't happen.
