### ISSUE TITLE
SASS @import and maintaining URLs for images etc

### ISSUE THREAD

**Issue by denniszhao** [sass/sass#1015]
Shouldn't URLs be maintained when importing .scss files from other directories?

e.g.

File structure:
css/
- main.scss
- dir/
- - dir.scss

main.scss:

```
@import './dir/dir.scss';
```

dir.scss:

```
body { background: url('../../arbitrary/bg.jpg'); }
```

Generated CSS (in css/)

```
body { background: url('../../arbitrary/bg.jpg'); }
```

Shouldn't SASS see that the .scss file being imported is one directory above it and then move all directories up accordingly? So:

```
body { background: url('../arbritrary/bg.jpg'); }
```

CSS @import will 'preserve' proper URLs not because it changes them (I think), but because each @import is handled as a separate HTTP request to the CSS file being 'imported'.

**Comment by lolmaus** [comment]
Until this is reimplemented properly, you can use Compass URL Helpers.

http://compass-style.org/reference/compass/helpers/urls/

**Comment by cimmanon** [comment]
What you're suggesting (mangling URLs for background images) is the reason why I ultimately stopped using LESS.  Do not want :-1:

I know where my assets are, Sass shouldn't be second guessing me.  If you need an asset helper function, by all means write one (or use an existing one).

**Comment by Panya** [comment]
Try Stylus (option `--resolve-url` http://learnboost.github.io/stylus/docs/executable.html) :)

**Comment by Anahkiasen** [comment]
I'd just use the Compass helpers too.

**Comment by chriseppstein** [comment]
How can url references in a third-party library ever work with a scheme like this without making assumptions about how the sass files will be stored on disk with respect to where the third-party assets are served. The compass url/configuration system was devised to handle this issue elegantly. If someone can show me how a vendored stylesheet with references to assets works I would consider such a feature. until then, I think sass functions are the best solution.

**Comment by CrescentFresh** [comment]
I am trying to understand the opposition to this. `@import` was around before sass. Sass appropriated it so that the import is performed at compile time rather than request time. But then scss proceeds to break relative urls in it's implementation... 

I don't understand the viewpoint that urls would be "mangled" by fixing this. They'd be fixed, not mangled.

Nor do I understand @chriseppstein's point about 3rd party libs (and it's obvious he's given this thought). I think I need an example of where a fix for this might fail. My guess is it has something to do with urls pointing to dynamic endpoints? Eg `url(not/a/real/path/dynamic-image)`

(If we had been talking about fixing this in a `@sass-import` directive however, that would be different and I would understand the resistance).

**Comment by cimmanon** [comment]
You mean ignoring how this would break every single person's Sass files that currently use `url()` raw?  The Sass maintainers have a history of avoiding changes that cause compatibility problems.

Look at Compass extensions.  If you're not familiar with them, they are bits of Sass, Ruby, images, JavaScript, etc. bundled into a nice neat Ruby Gem for the purpose of reusing with other projects without having to deal with the headache of copy/pasting them everywhere. If a Sass file within the gem references an image, how would you propose going about "fixing" the URL?

Consider a new project.  It usually starts out pretty small.  As you work on it, you might realize the code needs to be broken up into smaller pieces and placed in a subdirectory to keep things organized.  Under your proposal, the paths in each of those files would be broken and I would have to go back and adjust them by hand.

If I have a mixin defined in `/foo/util/_baz.scss` that sets a background image and I call it from `/foo/_main.scss` _and_ `/foo/bar/_widgets.css`, what is the path assumed to be relative to?  What if the mixin is inside a gem?

There seems to be no upside to what you're proposing.

**Comment by CrescentFresh** [comment]
Wait, what about a "base case" of simply `@import(path/to/plain_old_stylesheet.css)`? (Ie not a scss file that must be parsed and compiled, that may contain mixins, that may call compass extensions, etc).

Just a plain stylesheet import. If `plain_old_stylesheet.css` includes the rule `background-image:url(a.png)`, why couldn't that rule be resolved to `background-image:url(path/to/a.png)` once inlined into the parent?

I think I get the problem with trying to address this when importing .scss case. But I feel like I'm missing something about this simple case.

**Comment by lolmaus** [comment]
Currently Sass [does neither parse nor embed](https://github.com/nex3/sass/issues/556) CSS files when importing them.

In your "base case" of simply `@import(path/to/plain_old_stylesheet.css)` you'll end up with an `@import(path/to/plain_old_stylesheet.css);` line in your resulting CSS.

You might want to ask in #556 for what you want.

**Comment by CrescentFresh** [comment]
Thanks for taking the time to explain.

**Comment by jhnns** [comment]
This feature would be useful for any project, where you want to write modular components that are "self-contained" and reference their assets relatively to the sass-file. It shouldn't be this way by default, but opt-in.

In my  particular situation I'm using sass with [webpack](https://github.com/webpack/webpack/) which provides chainable loaders to load and bundle "web modules" (html, jade, css, sass, coffeescript, etc.) into js-chunks. The [css-loader](https://github.com/webpack/css-loader/) for instance is specialized to resolve all referenced assets, rewrite the url to a cachable url and pass the referenced asset to an appropiate loader (typically the [file-](https://github.com/webpack/file-loader/) or [url-loader](https://github.com/webpack/url-loader/)). The concept is that every language - be it js, html or css - has its own ways to reference dependencies. And these dependencies are loaded and bundled by webpack. That's why I'd like to write components that reference their assets relatively.

LESS provides a [`--relative-url`-flag](http://lesscss.org/usage/#command-line-usage-relative-urls) for this use-case which works fine with the css-loader and webpack.

**Comment by felixfbecker** [comment]
Please make this an option. I'm using NPM (same for Bower though) to install bootstrap-sass and font-awesome. I then @import them in my app.scss. Both have fonts referenced. I use gulp to build my app. If I run a url reworker after the sass compilation, I can't get the original path because it's now all in app.css. If I run it before the sass compilation, there are no references because the `@import`s have not been processed yet. There is no way for me to fix the paths if Sass doesn't include an option for fixing relative urls, or at least providing some sort of hook.

**Comment by gwmaster** [comment]
i use https://github.com/bholloway/resolve-url-loader

        {
            test   : /\.css$/,
            loaders: ['style-loader', 'css-loader?url=false']
        }, {
            test   : /\.scss$/,
            loaders: ['style-loader', 'css-loader?url=false' , 'sass-loader?sourceMap']
        }
and for copy images use new CopyWebpackPlugin https://github.com/kevlened/copy-webpack-plugin

**Comment by vectorjohn** [comment]
The opposition to this seems misguided. import as implemented is wrong for relative paths. Everyone opposing this seems to be under the impression that any sass include file has to know its location relative to everywhere it gets included. This is completely broken. Compass URL Helpers aren't the right solution, this should just work.

I can't imagine how anybody is using url() in an included file. It breaks encapsulation. If my _cool-include.scss file depends on url('./foo.jpg'), where is it supposed to find foo.jpg? Anyone would reasonably expect it to be next to _cool-include.scss, *exactly* like a normal css import would act. File references should be relative to the css (or scss) file. Instead, it depends on what included _cool_include.scss, which is a pretty brittle way of doing things. Then if it's included by thing1/root.scss AND thing2/root.scss, I guess whoopsie daisy?

**Comment by foxmicha** [comment]
Is the functionality that @vectorjohn described the current state of the repo? This is my first time using SASS but I'm confident that my relative paths from my `included.scss` file match where I'm expecting the image to be. However, it looks like I have to update the relative path to be related to `including.scss`.

**Comment by zilong-thu** [comment]
This reminds me why lexical scoped programming language are more reasonable than dynamic scoped programming languages.

**Comment by RedTeapot** [comment]
This expected behavior can be implemented by node-sass's importer. You guys might need this:
[https://www.npmjs.com/package/node-sass-self-contained-importer](https://www.npmjs.com/package/node-sass-self-contained-importer)

Usage:
`sass.renderSync({outFile: "xxxx", importer: require("node-sass-self-contained-importer")});`

**Comment by dwt** [comment]
Is there a reason sass itself does not provide a `file-relative-url()`/`root-file-relative-url()` (or whatever name suits you guys) pair of functions that allows me as a developer to resolve this ambiguity of how I want my paths be interpreted? I know that lots of frameworks add this to sass, but it's a pain in the but to have to use sass via a specific framework and a feature that should really be inside of sass itself.

**Comment by nex3** [comment]
@dwt Sass as a language doesn't have a notion of what the "root" of your project is, or what the layout of your served URLs are. This makes it very difficult for it to provide any built-in support for that kind of function. That said, we're considering adding support for customizable URL resolvers in #2535, which could include some defaults to make this possible with some external configuration.

**Comment by dwt** [comment]
@nex3: Either I'm missing something or I wasn't able to clearly communicate what I wanted.

When I'm thinking of a `file-relative-url()` (or whatever it's named), I want to instruct sass that the __relative url__ (i.e. something like `currentFolder.png` or `../relative/path.png` is rewritten to still point to that file when the sass file is compiled to be included in another folder, i.e. the code changes it's *relative position* when compiled.

What I'm thinking of with a `root-file-relative-url()` only means that the current behavior of `url()` is retained, i.e. that sass should _not_ touch the path when changing the relative location of the code in the project when compiling.

Why should that not be possible? I would be very surprised if extra configuration is necessary for sass to be able to do what `file-relative-url()` does.

**Comment by nex3** [comment]
That is more tractable than what I thought you meant, but it still means that the semantics of compilation depend on aspects of the external configuration that might just not be present. What does `file-relative-url()` do when compilation is being emitted to stdout, or through an API that doesn't provide the output name? What does it do when the file it appears in was loaded from a user-defined importer?

This *is* a use-case we want to figure out, though, and I encourage you to chip in on #2535 to help design a system that works well.

**Comment by jcklpe** [comment]
I would love to see better handling of this issue, as echoed by many other here. 

If anybody wants to point me towards the Compass/Stylus functions that can help with this, let me know. I don't want to import an entire library into my app just to use one or two functions, yah know?

**Comment by jcklpe** [comment]
Oh yeah, also Compass isn't maintained anymore so... yeah https://github.com/Compass/compass

**Comment by jcklpe** [comment]
Ah bingo, here's some pretty easy vanilla SCSS functions you can use to get stuff done:

https://css-tricks.com/snippets/sass/simple-asset-helper-functions/

For benefit of documentation and the chance that CSS-tricks somehow someday disappears:

```
/// Base path for assets (fonts, images...),
/// should not include trailing slash
/// @access public
/// @type String
$asset-base-path: '../assets' !default;

/// Asset URL builder
/// @access private
/// @param {String} $type - Asset type, matching folder name
/// @param {String} $file - Asset file name, including extension
/// @return {URL} - A `url()` function leading to the asset
@function asset($type, $file) {
  @return url($asset-base-path + '/' + $type + '/' + $file);
}

/// Image asset helper
/// @access public
/// @param {String} $file - Asset file name, including extension
/// @return {URL} - A `url()` function leading to the image
/// @require {function} asset
@function image($file) {
  @return asset('images', $file);
}

/// Font asset helper
/// @access public
/// @param {String} $file - Asset file name, including extension
/// @return {URL} - A `url()` function leading to the font
/// @require {function} asset
@function font($file) {
  @return asset('fonts', $file);
}
```

```
@font-face {
  font-family: 'Unicorn Font';
  src: font('unicorn.eot?') format('eot'),
       font('unicorn.otf') format('truetype'),
       font('unicorn.woff') format('woff'),
       font('unicorn.svg#unicorn') format('svg');
  font-weight: normal;
  font-style: normal;
}

.foo {
  background-image: image('kittens.png');
}
```

**Comment by canonic-epicure** [comment]
Can't believe the default behavior is wrong and this ticket from 2013 is just closed. Sass is supposed to solve the modular CSS use case. Modules should obviously be self-contained. But you have to embed the knowledge of where the module is used into the module.

**Comment by Roy-Orbison** [comment]
Please consider reopening this and providing a more appropriate resolution. No one should expect you to make backwards incompatible changes, but it defies logic to not provide any way to resolve relative URLs to assets. The *only* time it is possible to guarantee they are correctly resolved is during compilation. Sass must know them, internally, because it navigates them, but it will not divulge them. There's zero benefit to withholding this information from users. Sass offloads the burden of correcting paths onto every user, despite it being at best inconvenient, at worst so impractical as to be effectively impossible. One must know in advance how rules containing `url()` shall be included, and hard-code in published paths, which is double-specification. If the location of imported files and their assets is changed, so must every `url()` they contain be updated. This is antithetical to modular code, and restricts the ability to import styles from multiple entry points, an important trait of libraries.

The issue is thoroughly described in https://github.com/sass/libsass/issues/532, and #2535. It has been repeatedly miscategorised as a desired feature rather than a deficiency, and lumped together with custom URL handling. The latter would undoubtedly be a great feature, and may be an ideal method to implement a solution, but the two are not equivalent. Even if we had custom URL handlers, I fear this would again offload the responsibility of basic path resolution onto Sass' users. It does not address the core problem that is, in simple terms, data loss. I cannot think of a rational pro data loss argument. GitHub (and the 'Net in general) has become [positively littered](https://www.google.com/search?q=relative+url+%22scss%22+OR+%22sass%22+%7Ebroken) with bugs related to this over the years, surely that should provide sufficient impetus to reconsider it.
