### ISSUE TITLE
Performance regression in 3.3

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1019]
Reported by @xzyfer even after my recent performance fixes (#1006) landed.

https://docs.google.com/a/eppsteins.net/spreadsheet/ccc?key=0AtCLoNy3e0WXdEZERnZkc3pIUmVtSS1wdm5XQUZ4YlE&usp=sharing#gid=0

@xzyfer, can you please provide the source files used for that testing as a folder that we can run profiling against?

**Comment by xzyfer** [comment]
I'm unable to link to the project's source, but I can PM a tarballed snapshot of the project at the hash in those benchmarks. Please advise how best to do so :)

**Comment by xzyfer** [comment]
FWIW the main culprits of the performance issues (not specifically regressions) we were able to identify were frequent list iteration, and surprisingly `@import`s. 

Our framework has a tree-like hierarchy. The result is many leaf files (components) have import branches that share mixin and function files. Since sass has no `import-once` semantic these duplicate files are imported multiple times. Removing the duplicate imports resulted in a noticeable speed up (IIRC ~15%), but isn't ideal as it puts the onus on the end user to resolve the dependency tree in their downstream projects when importing a component.

**Comment by chriseppstein** [comment]
I'm working on a plugin that implements "import once" for the time being.

**Comment by chriseppstein** [comment]
@xzyfer You can email the test code: chris@eppsteins.net

**Comment by xzyfer** [comment]
Sorry for the delay, it's bee a busy morning. I've set the email.

**Comment by xzyfer** [comment]
Would it be possible for you to implement the plugin in compass? 

My reasoning, assuming import-once is required to get good performance in complex applications, is that if they'd wish to be open sourced would need to instruct their potential user base to install said plugin and update their sass build process to load it (unless I misunderstand how to plugins are used).

This can be daunting for people, where as instructing users to use compass and "this will just work" is significantly lower barrier to entry IMHO. Using compass is somewhat second nature to most sass developers.

**Comment by nex3** [comment]
I've tried to reproduce the list speed regression with no success. In fact, in my microbenchmarks, most list operations became an order of magnitude or so faster in the current master branch relative to the current stable branch.

What I'd really like to see here are isolated cases of individual operations that got slower between 3.2 and 3.3.

**Comment by xzyfer** [comment]
@chriseppstein did you end up looking into that project? Otherwise I'll commit some time to this over the week holiday break.

**Comment by Snugug** [comment]
I'm working on bringing Singularity up to work on 3.3 today and that has a fairly comprehensive test suite where I should be able to see fairly definitively if there has been a performance regression based on time it takes to run the tests. (if that helps)

**Comment by Snugug** [comment]
So I've run my tests, and I too have found a major performance regression, although I must say I'm not entirely sure which of the two things I've done has caused the regression.

For [Singularity](https://github.com/team-sass/singularity), we have a fairly comprehensive test suite that we run large compiles through (31 tests generating ~5.6MB of CSS). The only change we needed to make to upgrade from Sass 3.2 to Sass 3.3 were adding `!global` where appropriate, adding `mixin-exists` in two places, and swapping out a custom version of `list-separator` with the now native version. `inspect` also previously was being written as a string instead of returning the inspected value. In the first test, Compass components were being used, in the second they were removed, reducing the tree needed to compile. All compilations were done through Rake/Compass.

There were only a handful of changes made in total, but `inspect` and `list-separator` are hit the most.

On Sass 3.2, 3 test runs averaged out to a time of **126.996912s**
On Sass 3.3, 3 test runs averaged out to a time of **181.865571667s**

Removing the `inspect` (to reduce vars to only changes in the codebase itself) results in an average run time over 3 tests of **177.974049333s**

As you can see, it takes almost **50s** longer to run the tests in Sass 3.3. Both test times were run on `ruby 2.0.0p247`, the first set using `~> Sass 3.2.1` and `~>Compass 0.12.2` and the second set using `Sass 3.3.0.rc.2` and `Compass 1.0.0.alpha.13`.

If I can help break this down any further, let me know.

**Comment by chriseppstein** [comment]
@Snugug Those slow downs could very easily be a compass issue and not a sass issue, the compass css3 mixins are significantly slower than they were before (Because they do so much more than they used to).

**Comment by Snugug** [comment]
@chriseppstein I removed all Compass CSS3 mixins

UPDATE: In what I was running I noticed that there was still use of CSS3 Background Gradients. Having removed the calls to that and the Compass imports for Background Gradients, and the compile time hasn't improved by any substantial amount (reduces average compile time by ~2s). As a for instance, one stylesheet that absolutely does not touch Compass CSS3 mixins use to take around 15.3 seconds to compile, now takes around 21.6 seconds to compile.

It's fair to not rule out Compass as the source of slowness (as everything is being compiled through Compass for both runs), but it's not due to the CSS3 mixins.

**Comment by nex3** [comment]
I've run some profiling on Singularity to try and figure out in more detail where this regression came from. I've got profile reports for [Sass stable](http://bl.ocks.org/nex3/8924299) and [Sass 3.3.0.rc.2](http://bl.ocks.org/nex3/8924344); I encourage anyone who wants to help out to dive into them and see if they can find relevant differences.

There were two things I noticed. First, a lot of the time is being spent in function calls. This is somewhat interesting, since at a glance the test case we're running looks like it's mostly mixins. The time spent within `Sass::Script::Funcall#_perform` and the methods it calls went from 94.5s to 150s -- accounting for 89% of the increase in runtime between stable and 3.3.0.rc.2. This is very useful information, since it gives us a clear indication of where to look for improvements.

The second thing I noticed was that `Class#new` -- just the object allocation itself, not any of the code that actually runs in initializers -- went from 3.1% of the runtime to 4.1%. This may not sound like much, but it's actually huge -- the closest any other method comes is `Hash#[]`, which is only 2% of the total runtime. So we should look for ways to avoid instantiating as many objects, especially in methods that are called frequently.

This is only the beginning of the process of improving performance here, but hopefully it'll provide some indication of how to proceed.

**Comment by Snugug** [comment]
To provide some insight into how the Singularity mixins work, they're mostly wrappers for printing function output, so it shouldn't surprise you too much that a lot of time is being spent in function calls.   The two versions you're using as benchmarks are especially bad for the number of functions each mixin calls.

Otherwise, I'm happy to see it's helping you debug.

**Comment by nex3** [comment]
I'm working on getting some more detailed numbers for this, but as far as I can tell it's not something simple enough to fix before 3.3, so I'm removing it from the milestone.

**Comment by idflood** [comment]
I also noticed a huge performance regression after updating sass, compass and susy.

I did a simple test with a loop and the most problematic function seems to come from susy:

```
@for $i from 1 through 100
  .span#{$i}
     +span(1)
```

This simple example compile in **12** seconds. Replacing the `+span(1)` with a simple css attribute like `width: 25%` and the compilation goes down to 0.670 seconds. I also tried to import susyone and changed the `+span(1)` with a `+span-columns(1)`. This made the compilation took only 1.477 seconds.

For reference, I also tested with `@extend`, `.js &` and calling a simple mixin but it didn't lead to any significant problem.

**Comment by chriseppstein** [comment]
Wow. Ya, I ran this and it took almost 11s. It's not acceptable. It's not a susy problem -- We need to figure out what we're doing in Sass to cause this.

**Comment by chriseppstein** [comment]
I suspect there's not a simple change to sass to fix this performance issue. My gut says that our recursive-based visitor system is killing us. I think we should use an iterative visitor approach.

**Comment by nex3** [comment]
> My gut says that our recursive-based visitor system is killing us. I think we should use an iterative visitor approach.

This doesn't make sense. You can't non-recursively traverse a tree.

**Comment by lolmaus** [comment]
Is there evidence that the regression on `+span()` appeared during some Sass update and that it's not solely Singularity issue?

Not counting Sass 3.2 -> 3.3 because that's where Singularity also had a major revamp and could have its own regression.

**Comment by chriseppstein** [comment]
You can. You need a stack but that stack doesn't have to be the call stack.

**Comment by xzyfer** [comment]
FWIW since I had a ruby-prof profiling environment setup I did some really quick profiling comparing a loop with and without the `span` mixin call. Granted profiling isn't really my thing, but there is a significant increase in the number of function calls in the code with the mixin call. 

May be nothing, may be something.

![screen shot 2014-06-02 at 12 47 42 pm](https://cloud.githubusercontent.com/assets/579928/3152462/d3cb20b4-ea8e-11e3-835e-4c9a9a0fbbeb.png)

_edit: better screen shot_

**Comment by Snugug** [comment]
@lolmaus the snapshot that was being looked at was a simple !global upgrade, no new architecture, so it's a good before/after comparison.

**Comment by chriseppstein** [comment]
@nex3 code example of iterative tree traversal: https://gist.github.com/chriseppstein/27c45a9bf87d56152033

**Comment by nex3** [comment]
> You can. You need a stack but that stack doesn't have to be the call stack.

Okay, sure, but you're just doing the same operations but with extra Ruby method calls for manual bookkeeping. Why would you expect that to be faster?

**Comment by chriseppstein** [comment]
Because what ruby is pushing onto the call stack with each recursive visit is a lot larger and more expensive to create and to destroy.

**Comment by chriseppstein** [comment]
I did some profiling on this susy file to see where we're spending our time:

This is in ruby 2.1.2 which is pretty darn fast, but it still takes over 9 seconds to compile [this file](https://gist.github.com/chriseppstein/2133a33d2353497fbca1).

By far, the biggest killer is garbage collection. After that, object creation of ruby Set objects (which are just two objects for the price of one hash with convenience APIs. I don't know why sets are so expensive, but it seems that simply [using hashes directly could be a big win](http://blog.x-aeon.com/2012/02/07/using-data-sets-in-ruby-performance-of-hash-vs-set/).

You can see that recursion in the visitors is a pretty big offender (3%), but it's certainly not at the top of the list.

```
stackprof stackprof-cpu-sass.dump
==================================
  Mode: cpu(1000)
  Samples: 1925 (0.00% miss rate)
  GC: 337 (17.51%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       252  (13.1%)         252  (13.1%)     Set#initialize
       255  (13.2%)         147   (7.6%)     Sass::BaseEnvironment#_var
        92   (4.8%)          92   (4.8%)     Sass::Script::Value::Base#initialize
        58   (3.0%)          58   (3.0%)     Sass::Stack::Frame#initialize
        89   (4.6%)          56   (2.9%)     Sass::Util#map_hash
        55   (2.9%)          55   (2.9%)     Sass::Environment#set_local_var
        55   (2.9%)          55   (2.9%)     Sass::Util#ruby1_8?
     18652 (968.9%)          55   (2.9%)     block in Sass::Tree::Visitors::Perform#visit
        96   (5.0%)          54   (2.8%)     Sass::Environment#try_set_var
       304  (15.8%)          53   (2.8%)     Sass::BaseEnvironment#initialize
        49   (2.5%)          49   (2.5%)     Sass::Tree::Node#filename
        42   (2.2%)          42   (2.2%)     Sass::Tree::Node#children=
        42   (2.2%)          42   (2.2%)     Sass::Util::NormalizedMap#size
     22056 (1145.8%)          37   (1.9%)     Sass::Stack#with_frame
        89   (4.6%)          33   (1.7%)     Sass::BaseEnvironment#_function
        58   (3.0%)          29   (1.5%)     Sass::BaseEnvironment#is_var_global?
        27   (1.4%)          27   (1.4%)     Sass::Script::Value::ArgList#keywords
        28   (1.5%)          25   (1.3%)     Sass::BaseEnvironment#global_env
        24   (1.2%)          24   (1.2%)     Sass::Util::NormalizedMap#normalize
     20408 (1060.2%)          20   (1.0%)     Sass::Tree::Visitors::Perform#visit
        18   (0.9%)          18   (0.9%)     block in Sass::Importers::Filesystem#find_real_file
        17   (0.9%)          17   (0.9%)     Sass::Script::Value::Base#hash
        34   (1.8%)          16   (0.8%)     Sass::Util#enum_with_index
        21   (1.1%)          16   (0.8%)     #<Module:0x007fbd649ef240>.signature
        15   (0.8%)          15   (0.8%)     Sass::Tree::Visitors::Perform#initialize
       121   (6.3%)          14   (0.7%)     Sass::Script::Tree::Variable#_perform
        13   (0.7%)          13   (0.7%)     Sass::Script::Functions::EvaluationContext#initialize
      5316 (276.2%)          12   (0.6%)     Sass::Tree::Visitors::Perform#visit_variable
        12   (0.6%)          12   (0.6%)     Sass::Tree::Node#initialize
        55   (2.9%)          11   (0.6%)     Sass::Script::Tree::Funcall#signature
```

To see where object allocation is happening:

```
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
   1789945  (15.7%)     1789945  (15.7%)     Sass::BaseEnvironment#var
  48826450 (428.3%)     1019204   (8.9%)     Sass::Script::Tree::Funcall#_perform
    811731   (7.1%)      811731   (7.1%)     Set#initialize
   1619158  (14.2%)      809579   (7.1%)     Sass::BaseEnvironment#initialize
    758473   (6.7%)      680818   (6.0%)     Sass::Environment#set_var
    603395   (5.3%)      603395   (5.3%)     Sass::Environment#set_local_var
    588638   (5.2%)      585138   (5.1%)     Sass::Util::NormalizedMap#initialize
  62020898 (544.0%)      469180   (4.1%)     Sass::Tree::Visitors::Perform.perform_arguments
    968692   (8.5%)      442952   (3.9%)     Sass::Tree::Visitors::Perform.perform_splat
    436140   (3.8%)      436140   (3.8%)     Sass::BaseEnvironment#function
 157176388 (1378.6%)      393512   (3.5%)     Sass::Stack#with_frame
 134585301 (1180.5%)      391065   (3.4%)     block in Sass::Tree::Visitors::Perform#visit
  41519933 (364.2%)      380590   (3.3%)     Sass::Tree::Visitors::Perform#visit_variable
    356920   (3.1%)      312305   (2.7%)     Sass::Script::Functions#type_of
    593126   (5.2%)      292568   (2.6%)     Sass::Util#map_hash
    215055   (1.9%)      215055   (1.9%)     Sass::Util::NormalizedMap#normalize
  49962874 (438.2%)      196916   (1.7%)     Sass::Tree::Visitors::Perform.visit
  28226510 (247.6%)      160460   (1.4%)     block in Sass::Tree::Visitors::Perform#visit_children
    145380   (1.3%)      145380   (1.3%)     Sass::Util#enum_with_index
```

As you can see, `Sass::BaseEnvironment#var` allocates 1,789,945 objects. Given that this code is highly iterative, it seems like we must be able to cache the object creation as part of the parse tree. For example, variable lookup is performing a `tr` on the variable name. but all these variable names are known at parse time, so we should be able to precompute this normalized version on the script node instead of at variable lookup.

**Comment by chriseppstein** [comment]
The tools I'm using for this:
- https://github.com/tmm1/stackprof
- https://github.com/alisnic/stackprof-webnav

I then edited the sass/exec.rb file and changed the `parse!` method to wrap the call to parse:

``` ruby
          require 'stackprof'
          result = StackProf.run(mode: :object, out: 'stackprof-object-sass.dump') do
            parse
          end
```

**Comment by thedarkone** [comment]
Guys, I'm sorry, I feel like an idiot, but how do I repro?

If I use stable gems and a project generated with `compass create . -r susy -u susy` with `screen.sass` (otherwise I have no idea how to use `sass` with `susy` from a console without `compass`):

``` sass
@import susy
@for $i from 1 through 100
  .span#{$i}
    +span($i)
```

I get:

```
$: compass compile
    error sass/screen.sass (Line 4: Undefined mixin 'span'.)
overwrite stylesheets/screen.css 
```

If I try to use current `master`:
- I get `_support.scss: Undefined variable: "$experimental-support-for-mozilla"` I fixed that by adding `@import "compass"`,
- but they I run into `@warn` issues: `Line 60 of _functions.scss: Invalid CSS after "    @warn ": expected expression (e.g. 1px, bold), was ""Susy works bes..."`,
- after I comment out all `@warn` directives from the `susy` gem I still end up at: `Line 5: Undefined mixin 'span'.`,
- if I try to use `master` of `susy` bundler complains that `susy` wants `sass (~> 3.3.0) ruby`, while `master` of sass is at `sass (3.4.0.alpha)`.

**Comment by chriseppstein** [comment]
@thedarkone  I think you've got an old version of susy. Using susy (2.1.2), sass 3.3.8

$ sass -r susy slowfile.sass slowfile.css

**Comment by nex3** [comment]
We should certainly look into using Hashes over Sets (or possibly writing our own Hash-based Set class). I remain unconvinced that recursion is more expensive than manual stack management, but it should be easy to modify Visitor to test empirically.

A few weeks back I put some effort into prototyping the compilation of Sass code to Ruby for the perform step. I didn't get anything functional, but I did get far enough that I'm confident the idea is viable. This data seems to indicate that it will also produce a substantial improvement in speed, given how much time is spent churning through variables.

**Comment by kaij** [comment]
I think this is an absolute killer for susy 2 - every span you do will hugely increase compile time. Possibly also a problem for other libraries. I'm developing multiple projects with Susy2 and Sass 3.3 and ran into this problem.

It would help to know whether there will be solution anytime soon - or if I should better look out for other solutions.

**Comment by kaij** [comment]
Analyzed the combination Sass 3.3/Susy2 for performance. Here are my findings:
1. Every step in Sass interpretation is quite slow, but there seems to be no obvious reason in the interpreter code. I'm not sure whether sass function calls are especially slow (Susy is calling a lot of custom functions).
2. There seems to be a performance penalty in each step of the interpreter. This has heavy impact on using lists, loops, recursion in the sass stylesheet. It's more a generic slowness than a specific one. 
3. The performance degrades linearly - it's not some kind of recursive issue, it gets linearly slower with the amount of code executed.
4. By rewriting some susy utility functions in Ruby, I got a 40% performance gain on compile time with susy projects. See ericam/susy#362 and ericam/susy#325. I think there's more to be gained - however, it can't be the goal to rewrite susy in ruby. Note: those utility functions were calling other utility functions in sass loops.

Maybe this helps in further work on this performance regression. I used Ruby 2.1.2 and Sass 3.3.9 for this analysis.

**Comment by idflood** [comment]
I'm not sure if this is relevant but since the sass code is slower than ruby one maybe there is something to do with the evaled code.

If I understand correctly, currently sass use exclusively `class_eval` but there is a `define_method` which may or not be faster. One benefit of the `define_method` is that apparently is use much less memory which may lead to less garbage collection. But is it possible to simply switch these methods?

Here is one article comparing the 2 methods: http://tenderlovemaking.com/2013/03/03/dynamic_method_definitions.html

**Comment by chriseppstein** [comment]
@idflood It looked promising so I tried it out.
https://github.com/chriseppstein/sass/commit/38552b5919a11739f7c99645fa91e138d0f00926

But it actually slowed the Sass stable branch tests down.

Before:
- Ruby 2.0 (16.2978182 seconds average of 5 test runs)
- Ruby ree-1.8.7 (17.9358288 seconds average of 5 test runs)

After:
- Ruby 2.0 (16.7046996 seconds average of 5 test runs) 2.5% slower.
- Ruby ree-1.8.7 (18.1737122 seconds average of 5 test runs) 1.3% slower.

**Comment by idflood** [comment]
@chriseppstein thank you for trying. I also quickly tested your branch with the test defined here and have the same result as you (~2.5% slower). That would have been too easy.

**Comment by thedarkone** [comment]
@idflood @chriseppstein that @tenderlove's article is easy to misunderstand. On MRI defining a method via `define_method` (instead of `class_eval`) uses 2x less memory **per method** definition, but as you've found out is slower **per method call** (about 30% slower on MRI, your diff of only about 2% is because overall not that much time is spent in invoking those methods). I don't think there is any difference in object allocation (or GC overhead) **per method call** between `define_method` and `class_eval`.

**Comment by benebun** [comment]
Is there an estimate when this might be fixed/improved?

As a workaround we reduced susy's span() calls with (redundant) combined selectors which is not ideal. It reduced the compile time from 16s to 8s but is still a big productivity slowdown, esp. since we'll be using more of susy (are in the middle of a project). :(

Let me know if/how I can help!

Thanks.

**Comment by nex3** [comment]
It's difficult to say for sure, since it's hard to tell how much of an improvement a given change will make until it's made. The only change that's on the near-term horizon is switching over to use hashes rather than native sets.

**Comment by nex3** [comment]
I played around with replacing set usage with maps and wasn't able to see a substantial gain. I'm going to hold off on working on it seriously until I have a test case that shows real improvement.

**Comment by lutzissler** [comment]
Has there been any progress on this over the last 9 months?

**Comment by nex3** [comment]
Yes. I'm working on a branch that compiles Sass to Ruby, which should dramatically speed up runtime performance (albeit at the cost of a longer initial compile).

**Comment by lutzissler** [comment]
As a mere user, I can only say thank you for the hard work Natalie. I guess that’s the one you presented in https://github.com/sass/sass/issues/1353. Is this anywhere close to being released though?

**Comment by nex3** [comment]
It's running most of the tests successfully, so it's getting there.

**Comment by phaza** [comment]
Just wanted to chime in that I went from 10s compile time down to 3s by replacing a few (10-12) `@extend` calls with mixins. Was primarily `@extend`ing `.row` and `.<size>-<columns>` classes from foundation. Hopefully it can be useful for testing.

**Comment by djam90** [comment]
In the middle of a project we were getting 45 second compile times due to using a lot of Susy spans and galleries. Switched over to LibSass and removed Compass and now compiles in 5 seconds, and in 0.2 seconds on my laptop that has an SSD. I couldn't believe the performance increase from LibSass. 1 issue we found was using Susy fractions "1/2" need to be inside parentheses like (1/2).

**Comment by nex3** [comment]
@djam90 Can you [file an issue for that](https://github.com/sass/libsass/issues/new)?

**Comment by mkstix6** [comment]
@phaza I was experiencing the same thing with Foundation(6). I was also extending .rows and .columns (the way I think they encourage, I could be wrong). Perhaps we should relay that to @zurb for an answer. It may be that those classes spider down deeply.

**Comment by AlanFoster** [comment]
@phaza @mkstix6 I have also experienced performance issues with multiple`@extend` calls to bootstrap row/column/form classes, which led to 3-4 minute compile times.

**Comment by nex3** [comment]
We've decided on moving to Dart Sass as our plan for getting good performance moving forward.
