### ISSUE TITLE
Canonical thread for duplicate issue references

### ISSUE THREAD

**Issue by joepie91** [sass/sass#1026]
I was trying to figure out whether nested variables were supported in SASS, and ended up on issue #616, which mentions several 'duplicate' issues. Clicking through to find recent information on this matter, I subsequently ended up on #440, #599, #462 and #353. It became unclear which thread was about what, and where to find the latest information on the status of these requests/suggestions.

Perhaps it's a good idea to adopt a policy like is used by many other (large) open-source software projects, where one issue thread (usually the earliest) is adopted as the "canonical" thread, and every single closed duplicate refers back to this one canonical thread - rather than refering to other threads that in turn refer to other threads, and so on.

This would make it much easier to follow updates on a suggestion (as there is a single canonical thread that can be followed), and also makes it less likely that new duplicates are created by people who missed previous threads.

**Comment by nex3** [comment]
Usually we try to do this, but sometimes things get messy. Since @chriseppstein and I have a limited amount of time to devote to Sass in the first place, it's difficult to justify spending a lot of it tending the issue tracker to make sure all our duplicates point to the oldest possible thread, rather than working on actual code.
