### ISSUE TITLE
Cast function

### ISSUE THREAD

**Issue by Snugug** [sass/sass#1027]
I've found it very difficult to change from one data type to another in Sass (for instance strings to numbers, maps to strings (which can't be done correctly without stack-breaking recursion), etc…) without dropping into Ruby to create helper functions. I think this functionality would be very useful, especially for framework developers. The proposed syntax would be something like the following:

``` scss
$map: (foo: bar, baz: qux);
.foo {
  content: cast($map, string);
}

$string: "Hello World How Are You";
@debug length(cast($string, list)); // 5
```

**Comment by KittyGiraudel** [comment]
I'd love to see that. Pretty hard to cast anything in Sass at the moment.

**Comment by chriseppstein** [comment]
The [inspect function](https://github.com/nex3/sass/pull/980) turns any sass data structure into a string that would parse into equivalent sass (this is the same code we use for sass-convert).

I can't think of any other use case for a generic `cast`. So I'm closing this.

**Comment by Snugug** [comment]
For converting to strings, `inspect` is great (I actually didn't know that existed before), but what about strings into other data types? Strings into numbers happens an annoying amount and would allow us to reduce workaround for many common string/number problems

**Comment by chriseppstein** [comment]
I can't think of any time a string needs to be converted into a number where it couldn't have started as a number. Please show me a use case.

**Comment by Snugug** [comment]
Unit conversion (one to another, stripping units) is one I can think of off of the top of my head. The `unit` function returns in strings, so what we need to do now is one of a handful of hacks and improvised switch statements with `@if/else`.

**Comment by chriseppstein** [comment]
I've written extensively on this issue tracker that such unit stripping and conversion code is harmful and can be handled simply in sass with simple arithmetic. 

  Chris Eppstein  
 Sent via Intro for iPhone

**Comment by cimmanon** [comment]
Using strings inappropriately is a fairly regular problem that comes up on SO.  When it's not numbers cast as strings, its colors.  Right now, the only way to get the exact color output you want in your CSS files, you have to cast them to strings.  Once you do this, there's no way to get it back to a color and strings can't be passed to color adjustment functions.

Related:  https://github.com/nex3/sass/issues/363

**Comment by georeith** [comment]
@chriseppstein Suppose I am importing something from JSON to a map in sass. JSON doesn't support number keys but I know my keys are numbers and the numbers are important.

SASS isn't always the primary consumer of data, and I shouldn't have to make all my data work around SASS. SASS really lacks the ability to parse data or makes it incredibly difficult and it really hurts its interoperability with other tools.

This hurts for stuff like fonts, colours and other collections of information that my other languages want access to. Basically anywhere that I want SASS to communicate with the rest of my application instead of being this cumbersome thing that I have to maintain twice.

It doesn't even matter that it doesn't support the parsing of things like JSON which are ridiculously common, I'm happy to write or source that myself, but basic features like type casting really should be in the core.

In fact following that argument why doesn't all data start off in the format it is needed in? Because the same piece of data can be consumed by multiple things in different ways.

**Comment by davidkpiano** [comment]
@georeith Why not take a look at some third-party libraries such as [SassyJSON](https://github.com/HugoGiraudel/SassyJSON) or [Sassport](https://github.com/davidkpiano/sassport) to handle JSON and sharing data between Sass and JS, or [Sassdash](https://github.com/davidkpiano/sassdash) for list/map utilities? I think it was an intentional design to not bloat Sass with too many functions that can be handled by libraries (though that's not to say Sass 4.0 won't have a few nice new features for handling lists/maps).

**Comment by georeith** [comment]
@davidkpiano I think you misinterpreted my comment. I'm not looking for a JSON parser, I'm saying you need to cast when you are working with data that wasn't originally intended for SASS or is intended for multiple consumers, e.g., you are using SassyJSON. E.g., a JSON string key that I need as a number value in SASS

**Comment by rhythmus** [comment]
(Any progress on this one?) Consider the following:

``` Sass
@debug type-of(0300-N); // returns 'number'
@debug inspect(0300-N); // returns '300-N'
```

`inspect()` returns the (unquoted) value ‘0300-N’ with the first (leading) 0 dropped, because (as `type-of()` shows) Sass first evaluates the type before `inspect()` returns.

Similarly, different notations for a color value are interpreted first, before `inspect()` can return the incoming value as-is, and untouched.

``` Sass
@debug type-of(black);      // color
@debug inspect(black);      // returns 'black'
@debug type-of(rgb(0,0,0)); // color
@debug inspect(rgb(0,0,0)); // returns also 'black' (instead of 'rgb(0,0,0)')
@debug type-of(hsl(0,0,0)); // color
@debug inspect(hsl(0,0,0)); // black again
@debug type-of(#000000);    // color
@debug inspect(#000000);    // returns… '#000000' — Huh?!
```

Use cases and proof-of-desirability aside (obviously, one may want to cast any input as-is, e.g., as the literal value for a `content` property), and unless I’m missing something, `inspect()` does not what is said (above) it can be relied on to be doing. IMHO, the issue still stands, does it?

**Comment by chriseppstein** [comment]
`0300-N` is a number `0300` with a unit of `-N`. This is per the [CSS syntax for the "dimension token"](https://www.w3.org/TR/css-syntax-3/#typedef-dimension-token). The leading zero of a number is pointless so it is dropped from the value when reconstituting the number into a string for `inspect()`

> Similarly, different notations for a color value are interpreted first, before inspect() can return the incoming value as-is, and untouched.

I'm not sure where you got the notion that this is the intended behavior of `inspect()`. Inspect's purpose is for debugging to output a Sass value as a string that can be re-parsed as an equivalent value by the Sass parser. This is especially useful for sass values that do not have a representation in a CSS value context (E.g. null and maps)

**Comment by chriseppstein** [comment]
@rhythmus ^

**Comment by rhythmus** [comment]
> I'm not sure where you got the notion that this is the intended behavior of `inspect()`. 
> 
> > The inspect function turns any sass data structure into a string that would parse into equivalent sass (this is the same code we use for sass-convert).
> > I can't think of any other use case for a generic `cast`. So I'm closing this.

Thus, since `inspect()` cannot be abused into an ersatz string-casting workaround, while that is not its intended behavior or purpose, this does imply then there indeed remains a use case for a generic `cast()`function? How else to distinguish `black`, `rgb(0,0,0)`, and `#000000`?

**Comment by KittyGiraudel** [comment]
You should not have to distinguish between them.

**Comment by rhythmus** [comment]
I wouldn’t agree that it’s up to the tool to tell the user for what applications it should or should not be used.

Any way, why then does `inspect()` distinguish between `#000000` and `black`, but discriminates against `rgb(0,0,0)` and `hsl(0,0,0)`? 

Don’t get me wrong, I do agree an `inspect()` function, created for the purpose of debugging _computed values_, should indeed interpret and normalize the literals it is fed. But then again, there still remain legitimate applications — for debugging purposes or otherwise — which beg a function that will _return the literals per se_.

After all, that is the whole intent of the feature request discussed in this issue, is it not? Not the sidetrack discussion of `inspect()`’s intended behaviour, which only arose because it was argued that `inspect()`could already be used to predictably cast literals to strings, obviating the need for a separate function — which is an argument, I take it, which proves to be wrong, so that the issue still stands.

**Comment by robsonsobral** [comment]
I could use a simple way to split a ratio, like `16:9` or `3:4`, into numbers.
