### ISSUE TITLE
Rails.root is nil

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1033]
Filed against compass initially: https://github.com/chriseppstein/compass/issues/1462

**Comment by ahmeij** [comment]
I am not sure the issue is with sass, as including sass 3.3.0.rc.2 in clean new rails 3.2.x works like expected, only when adding compass 1.0.0.alpha.15 the error occurs in the rails boot process. 

As stated in the referenced issue, I'm willing to help solve this issue but I need a pointer or two as to where to start looking.

**Comment by glebm** [comment]
`require "sass/plugin"` by compass causes Sass to `require "sass/plugin/rails"` and access `Rails.root` before Rails has initialized. We can move Rails-specific code to the railtie.

**Comment by ahmeij** [comment]
Nice, it looks like #1039 fixes the problem indeed, thanks @glebm !

**Comment by ServusJon** [comment]
it works! please do the pull request @nex3 
thanks @glebm

**Comment by billsaysthis** [comment]
Can a new RC be released that includes this fix please?

**Comment by chrisgriffin** [comment]
I'm having this problem, is there a workaround I can use until you cut a new RC?

**Comment by billsaysthis** [comment]
Add the following to your Gemfile, before Sass-Rails:

```
gem 'sass', github: 'nex3/sass'
```
