### ISSUE TITLE
Performance regression: Too many watched directories

### ISSUE THREAD

**Issue by robi-wan** [sass/sass#1047]
We switched from gem 3.2.12 to 3.3.0rc1 to use sourcemaps.
When using `--watch` switch we experienced a massive cpu workload: I am developing in a virtual machine and one of the four processors operates at full capacity.

Our project has this folder structure:

```
<project-root>
|-logs
|-templates
|-static
    |-js
    |-css
        |-src
        |-build
        |-lib
    |-fonts
    |-img
    |-video
    |-...
|-...
|-Cakefile
```

We use a Cakefile for executing development tasks.
This is our watch task call:
`sass --sourcemap --watch static/css/src:static/css/build --load-path static/css`

Sass 3.3 changed the behaviour for the load_path: the current working dir is always added to load_path, I debugged the code and saw that the watched directory is `<project-root>` - but all subdirectories are also watched and I think this causes the heavy load. Under Windows directories are watched via polling. We are developing under Windows Server 2003 R2 SP2 32bit.
(For Sass 3.2.12 the watched directory was just `<project-root>\static\css\src`.)

This behaviour also occurs with Sass 3.3.0.rc2.

To work around this behaviour we tweaked our Cakefile task to change to `<project-root>\static\css` before executing `sass --sourcemap --watch src:build --load-path .`

**Comment by chriseppstein** [comment]
I'm fairly certain the current working directory was ALWAYS on the load path. In fact, the changes related to the current working directory in 3.3 are to deprecate this behavior so that in a future release you would have to explicitly place the current working directory on the load path. Here's the output from a missing import with sass 3.2. Notice that the load path includes my working directory:

```
$  scss _3.2.12_ --update scss:css
      error scss/foo.scss (Line 1: File to import not found or unreadable: bar.
Load paths:
  /Users/ceppstei/tmp
  /Users/ceppstei/tmp/scss)
```

I'm not discounting your performance degradation; I believe it has happened, I just think the diagnosis is incorrect.

**Comment by nex3** [comment]
I think the diagnosis is correct; although the working directory was always in the load path, for some reason it wasn't being watched for changes in 3.2. Something about the listen changes in 3.3 made it start to be watched instead.

The 3.3 behavior is arguably correct, but since it's new behavior and we're deprecating the working directory load path anyway, we could just rip it out to do away with this performance problem. @chriseppstein, thoughts?
