### ISSUE TITLE
Can be better the compress of fonts

### ISSUE THREAD

**Issue by BrodaNoel** [sass/sass#1058]
That:
font-family:"Yoinas", "Helvetica Neue", Helvetica, Arial, Sans-Serif
Can be compress to:
font-family:"Yoinas","Helvetica Neue",Helvetica,Arial,Sans-Serif

(Without spacess between commas)

**Comment by nex3** [comment]
This is caused by a parser optimization. When parsing a property value, Sass does a check to see if it's pure CSS and, if so, treats it as a literal string. This saves a considerable amount of parsing time, but it can cause strange inconsistencies like this. If we ever add support for more fine-grained compression, we'll likely have a slower compression mode that doesn't perform this optimization, but for now it's working as designed.

**Comment by BrodaNoel** [comment]
Is possible 2 differents types of style?

--style compressed
--style fullcompressed
?
