### ISSUE TITLE
Shorthand list access

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#1080]
Is anything planned for a shorter syntax for list access ? Like :

``` scss
// Currently
$value: nth($list, 2);
$value: map-get($map, 'something');

// Shorthand
$value: $list[2];
$value: $map['something'];
```

It can get kind of messy with multidimensional lists, this would simplify things a lot :

``` scss
$value: nth(nth($list, 1), 2);
$value: $list[1][2];
```

Is something like this planned or not at all ?

**Comment by lolmaus** [comment]
Great suggestion, i second that.

But i bet @nex3 will say as usual that it's counter-intuitive, will confuse users and thus shall not be implemented.

**Comment by Anahkiasen** [comment]
Well the `array[key]` syntax can be found in almost all languages : PHP, Javascript, Ruby, Python, etc. So it's hardly confusing or counter-intuitive. Plus it would be facultative, people could still use `nth` and `map-get`.

**Comment by KittyGiraudel** [comment]
This would be like **very** cool. This `nth($list, $index)` syntax is quite verbose.

**Comment by nex3** [comment]
This is not something we intend to support. We deliberately chose to use `nth` and `map-get` over `[]` because we want to be very conservative about how much syntax we add on top of CSS. It's very easy for us to run into syntactic incompatibilities with future additions to CSS that are painful or impossible to resolve, and the less additional syntax we add the better we're able to avoid that.

**Comment by Anahkiasen** [comment]
Is there a way this could make its way as a plugin then or something ? Not made officially I mean but, is it doable ?

**Comment by nex3** [comment]
It would be reasonably difficult to hack the parser to make this work, but probably not impossible. I'd discourage it, though, both for the same reasons that we don't want to include it in core Sass and because you'll end up creating stylesheets that can't integrate well with the rest of the ecosystem.
