### ISSUE TITLE
@extend is unstable

### ISSUE THREAD

**Issue by TopView** [sass/sass#1087]
If you swap the first two lines below, in other words put the .b1 line above and before the .b0  line  you get different css output.  

In one case it processes the first option line first, and in the other case it processes the 2nd option line first.

It shouldn't matter what order the first two lines are written in I don't think.

.b0 {border: 0;         }
.b1 {border: 1px solid; }
option  {@extend .b1;   }
option  {@extend .b0;   }

Ruby 1.9.3p484 (2013-11-22) [i386-mingw32]
Sass 3.2.13 (Media Mark)

Thanks for all of your work.  Have fun with this one.  I can see that how you do the processing is not so simple.  But to be sure I was under the impression that css was suppose to be cascading, and until this is fixed this fails that criteria.  

I'm brand new to sass, so perhaps there is something obvious I'm missing.

**Comment by Snugug** [comment]
I think the issue is a misunderstanding of how `@extend` works. `@extend` simply takes the item being extended and comma separates (moves) the selector with the original extended selector. It doesn't introspect the items being extended to determine if there are overrides, it is a straight move. When you swap line 1 and line 2 without also swapping line 3 and line 4, Sass is doing exactly what you've asked, it's rearranging your source order based upon the direct calls you've asked. If `.b0` had any other properties, it wouldn't have mattered; you just happen to have constructed a set of extends that override your desired results.

**Comment by TopView** [comment]
You're kidding, right?  You want me to imagine that swapping two lines like this is my problem and not sass's?  Well, I've got a pretty good imagination, but not a good enough to imagine that css should cascade only some of the time.

**Comment by Snugug** [comment]
If you'd like the technical write up on how @extend works, see Nex's post here https://gist.github.com/nex3/7609394

Extend is a way of changing your cascade and rearranging selectors, not just reducing output. It doesn't introspect the properties being extended or the selectors, only rearranges as a user has asked.

**Comment by lolmaus** [comment]
> When you swap line 1 and line 2 without also swapping line 3 and line 4

Hey @Snugug, the order of `@extend` statements does not matter here. Swapping lines 3 and 4 does not influence anything. Only the order of lines 1 and 2 influences the order of resulting CSS.

@TopView, Sass does not have telepathic powers. `A { @extend B; }` basically means "find B above and add A next to it". The position of B in your code defines where A appears in code, because A always appears next to B, and B appears where you type it. So yes, it's totally your problem.

**Comment by conorluddy** [comment]
"I'm brand new to sass, so perhaps there is something obvious I'm missing."

Yep, pretty much :)

**Comment by Snugug** [comment]
@lolmaus is right about 3/4. Typing faster than thinking

**Comment by chriseppstein** [comment]
The document order that matter is that of the selectors being extended, the document order of the extending selectors is not relevant. If you need to override the styles for a base selector the overriding statements should follow the base selectors.

**Comment by TopView** [comment]
Someone might want to revise the `Sass Basics`, where regarding this feature it says, "What the above code does is allow you to take the CSS properties in .message and apply them to .success, .error, & .warning."  -- http://sass-lang.com/guide  Notice it says:  .message is applied to .success, not the other way around.  So I guess either the documentation or the code needs to be fixed.  If it were me, I would fix the code to make it work more like css.

**Comment by lolmaus** [comment]
It does not say ".message is applied to .success". It says "**properties** in .message", and it does not say anything about the order. The code provided with that example makes it pretty obvious where extending selectors go.

What is your goal here: to understand how Sass works and leverage the knowledge in your project or to grubmle about it and find something to blame?

**Comment by TopView** [comment]
Thanks for your help guys.  Take it easy.  When I get time I intend to remove sass from my css.  I just will not have such a strange feature that makes makes my css so unstable.

**Comment by lolmaus** [comment]
It's like saying that you're gonna remove the microwave from your kitchen because it has the "strange and unstable" feature of burning your food (by pressing Start too many times).

**Comment by chriseppstein** [comment]
I agree with @TopView here, you guys are being pretty hard on him. This is a very normal reaction when someone finds a feature that doesn't fit their mental model of how it should work. We get this **all the time**. Chastising people who use strong language in their reaction to our features is not how we became the most used css pre-processor. I encourage everyone who comments on our issue tracker to ask questions and explore objections, to explain the features that we have and why they work the way they do. And lastly, as your mother encouraged: if you can't say something nice, don't say anything at all.

@TopView I'm sorry Sass doesn't fit your needs. I assure you that `@extend` is based on a theory of styling that is very sound. Selector inheritance using `@extend` is one of the most likely features of Sass to be included in CSS exactly as-is. If the people on the CSS working group think it's that good and that in line with the philosophy of CSS it's quite likely that we don't have it wrong.

For what it's worth, this is a better write up on the theory of this feature (instead of the implementation): https://github.com/nex3/sass/issues/324#issuecomment-4607184

**Comment by TopView** [comment]
First, I want to say again how much I appreciate all of your input and feedback.

I took a look at less, and it has the same exact problem that sass has.  

So here is your opportunity to out do them, and I have a couple of suggestions as to how.

Clearly this problem is because the algorithm used to implement @extend is simple and elegant, even if it does not work all of the time as expected.  Gosh I've been coding for 35 years and I've seen plenty of algorithms that work 99% of the time, but not 100% of the time.  And in that condition they are more trouble than they are worth in my opinion.  I expect you are all experienced enough to know what I am talking about.

SOLUTION:  There could be some sort of non-fatal error (or lint) for this sort of issue.  

It would be relatively easy I think to check when a tag is getting defined a second time (in this case the 2nd option) and then check if one of the attributes being included appears defined above but before the definition of where it was previously referenced.  Without coding this up I can't for see exactly how it would actually work, but it would help alert a CSS coder of potential problems.

This approach would have the advantage of fixing this problem thus making @extend more stable but without breaking any existing code.

Please note that even though I gave you this example in only 4 lines I had to first dig it out of a 700 line css file.  And while the last two lines were next to each other in my css, they were quite far from the first two lines.  It just was not reasonable to assume that including a couple of things above would change the order of two lines below.  .. or that simply reordering the first two lines would so silently break something far below.

.b0 {border: 0; }
.b1 {border: 1px solid; }

... many lines between

option {@extend .b1; }
option {@extend .b0; }

When 'option' is found again (the second time in this case) look to see if the 'border' it is pointing to is above the border it previously referred to.  If so flag an error or a warning depending on a switch on sass, ... or with another optional permission switch on then automatically fix it by moving .b0 below .b1 so that option cascades properly.  Obviously this involves checking that it doesn't break something else, which will involve flagging the change  so that it can't be done twice (i.e. reversed) without a fatal error.  Because this only needs to check a fairly limited class of syntax it should not add that much more processing overhead, even if the check itself is somewhat compute intensive.

I look forward to testing this when you get it working.  Thanks again.

**Comment by nex3** [comment]
@TopView I think you're misunderstanding how `@extend` is supposed to work. This isn't a case where it's failing to respect the cascade; in fact, the behavior you're seeing is precisely the behavior that makes `@extend` work well _with_ the cascade.

Let me explain. When you write `A { @extend B }`, what that means is that "all elements that match `A` should be styled as though they also match `B`." Sass does its best to make this work, and in most\* cases it does so 100% correctly. Your example is one of those cases. You're saying "`option` tags should be styled as though they had `class="b1 b0"`".

Since `.b0` is declared before `.b1`, `.b1` takes precedence, because of the cascade. A border appears when you use `@extend` because a border would appear if you manually added `class="b1 b0"`. The cascade is being respected here just like it would be if you weren't using `@extend`.

---

*: The cases where this fails are either because we don't have the necessary browser context to do the necessary property resolution, or because doing it completely generally would create extremely large CSS size.

**Comment by TopView** [comment]
.x {@extend .y} should extend .y not .q.

**Comment by nex3** [comment]
> `x {@extend y}` should extend `y` not `q`.

And indeed it does.

**Comment by TopView** [comment]
Actually it does most of the time.  But it does not always.  And this was the subject of my very first post here.

**Comment by lolmaus** [comment]
This is getting ridiculous.

**Comment by nex3** [comment]
I've explained why the current behavior is correct. If you have arguments to make against the semantics I laid out, go for it, but if you're just going to repeat "it's not what I expected," that's not a useful way to advance the conversation.

**Comment by TopView** [comment]
Glad you agree with me that .x {@extend .y} should extend .y not .q. 

So consider this:

.y {color: red;}
.q {color: blue;}

.x {@extend .q}
.x {@extend .y}

You said .x extends .y.  But it does not here. If you paint with .x it is blue and not red.  So it extends .q.

Yes @extend works correctly MOST of the time.  But in this case it does not. 

Yes I can see how the code is ACTUALLY written.  But lexically it makes no sense.  It asks the css author to keep track of a detail that is obscure and not obvious.  And it unnecessarily does this.

Lexically .x should extend .y.  Since it already does this 99.9% of the time, I think it should do this 100% of the time.

**Comment by nex3** [comment]
Why should there be a styling difference between what you wrote and `<x class="q y">`?

**Comment by TopView** [comment]
(I just realized that I was not adding the dot before the tag names above.  I have updated my comments above to include the dot prefix which is how I am reporting this bug and how I have been testing it.)

With that clarification:

Because `<x class=".q .y">text</x>` produces red text which it should, given that y is red and follows q.  But  `<x class=".x">text</x>` produces blue text, and you said x extends y.  And y is red.  But text that it paints is blue.

**Comment by TopView** [comment]
Over and out guys.  Take it easy.

**Comment by nex3** [comment]
> Because `<x class=".q .y">text</x>` produces red text which it should, given that y is red and follows q.

That's inaccurate: http://jsfiddle.net/T9RuQ/

**Comment by TopView** [comment]
You have laid me low.  All of these years I have believed that order within class=" " mattered and it does not.  

Rather that within repeated styles the only order that matters between siblings is what they were assigned to last in the style sheet, but not in the class=" " list.

I owe you my thanks.  Now I have to go stick my tail between my legs for awhile.
