### ISSUE TITLE
Feature Request: Issue a warning if no selector matches an @extend directive.

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#111]
It's probably a coding mistake if no selector matches an @extend directive. Sass could issue a warning in this case and save costly time spent in debugging.

[Originally filed](https://github.com/nex3/haml/issues/150) by @chriseppstein.

**Comment by barraponto** [comment]
It would be nice to have a flag for this. The Drupal Compass Plugin provides a template leveraging each and every themeable element of Drupal, in order to prevent unstyled interfaces (a bad practice of most Drupal developers). When a new project starts these warnings will surely get me tired for no reason. When I'm finishing a project, these warnings are more than welcome.

**Comment by timplunkett** [comment]
+1. When refactoring, it's really hard to keep track of what breaks when moving around @imports. A nice big warning would make this so much easier.

**Comment by codingdesigner** [comment]
Another +1. Big warnings are one of the best features in Sass
