### ISSUE TITLE
3.3 Regression: str-index returns null instead of -1

### ISSUE THREAD

**Issue by Snugug** [sass/sass#1112]
In Sass 3.3.0.rc.2, and according to the [original spec](https://github.com/nex3/sass/blob/code_style/lib/sass/script/functions.rb#L1335), `str-index` should return `-1` if the index isn't found. In Sass 3.3.0.rc.3, it now returns `null`, which breaks lots of things and makes comparison super annoying.

**Comment by nex3** [comment]
This is intended; see #1060. The [current documentation](https://github.com/nex3/sass/blob/master/lib/sass/script/functions.rb#L1403) supports this.

> breaks lots of things

Since `str-index` hasn't made it into a stable release yet, we're okay with making breaking changes to the API.

> makes comparison super annoying

Can you give an example of a case this makes more difficult?

**Comment by Snugug** [comment]
Oh, actually, I'm an idiot. Nevermind. Was doing `str-index > 0`, but now can just do `str-index`.
