### ISSUE TITLE
@import is ambiguous about relative vs. absolute paths

### ISSUE THREAD

**Issue by joliss** [sass/sass#1124]
/cc @hcatlin @akhleung

When Sass (or libsass) encounters `@import 'foo'`, it searches first in the directory of the source file, and then in all the load paths.

Other languages tend to keep relative and absolute imports separate. For instance Ruby has `require` and `require_relative`, and Node distinguishes `require('foo')` (absolute) and `require('./foo')` (relative).

Quick background why I care: I'm working on a Sass plugin for [Broccoli](https://github.com/joliss/broccoli), and one of the big motivators for making Broccoli was making it easier to share frontend JS + CSS code, because we can now use Bower with Broccoli on top. I know people have been distributing Sass files before (e.g. on RubyGems) but I want to see much more of that, and with less friction. I want _libraries that depend on other libraries_. So now I really care about getting the semantics of `@import` right.

Having `@import` be both absolute and relative seems like it might cause problems when there are ambiguities.

I wonder if we should, at some point, change the `@import` semantics to be unambiguous. For instance, on the next major version of Sass, we could print deprecation warnings on relative `@imports` that don't begin with a dot, so that `@import 'foo'` is absolute, and `@import './foo'` is relative.

What do you think?

**Comment by cimmanon** [comment]
For new-to-Sass users who are familiar with CSS will find that what you're proposing is confusing.  The `@import` directive from CSS interprets `/foo` as being absolute while `../foo`, `./foo`, and `foo` as being relative (note that this is also the behavior for other types of linking in web documents like href, src, etc.).  I would rather see Sass stay faithful to CSS, not Ruby.

I suspect this will also cause a great deal of backwards compatibility headaches.

**Comment by joliss** [comment]
Absolute imports are already a part of Sass. (Note that by "absolute" I don't mean "starting with a slash".) E.g. `@import "foo"` will search all the load paths for "foo.scss", unlike CSS. My post is about better disambiguating the two.

Hm, if we wanted to avoid confusing people coming from CSS, we could also move absolute imports into a separate directive, like `@import_absolute`.

**Comment by nex3** [comment]
We're planning to do a large-scale reworking of the import semantics for Sass 4.0, so that will be a good opportunity to change these semantics if we decide they need changing.

I'm not convinced they do, though. What is the practical downside of supporting both relative and load-path imports using the same syntax? You say it's ambiguous, but the semantics are well-defined: a relative import is preferred if one exists. This is how Python's module system works, for example.

**Comment by joliss** [comment]
Supporting both relative and load-path imports using the same syntax just feels vaguely icky to me, like load paths are only an afterthought. Hm, let me try to articulate where this feeling comes from...

So first, it's a bit confusing, because when you see an `@import`, you don't know whether it's relative or absolute.

But it can also be an annoyance when relative files shadow absolute files. For instance, say you have a file `_bootstrap.scss` (imported from `application.scss`), that reads like so:

``` scss
$brand-primary: #123456; // set some variables...
@import 'bootstrap' // import bootstrap library
```

Then the `@import` won't work because `./_bootstrap.scss` is in the way. So you have to rename `_bootstrap.scss` to accomodate this. As we get a bigger ecosystem of libraries, this might become a more frequent problem.

**Comment by nex3** [comment]
I don't think shadowing is a big enough issue to warrant adding syntax for this, especially since every user will have to know and use this syntax frequently. I would be more concerned if a new library on the load path could break local code, but relative files tend to be pretty easy to modify (or just nest within a directory).

**Comment by joliss** [comment]
So I guess what I'm saying is, if I were designing the `@import` directive from scratch today, I'd probably make it always absolute, unless it begins with `./` or `../`.

Now that `@import` exists already, it's less clear to me whether it's worth changing. If the upcoming reworking in 4.0 breaks many imports anyway, it might be worth cleaning this up at the same time, provided that you agree.

(I just noticed that [AMD uses this convention](https://github.com/amdjs/amdjs-api/wiki/AMD#module-id-format-) as well, by the way.)

**Comment by joliss** [comment]
Ah, sorry, didn't notice you had posted already.

**Comment by bughit** [comment]
> You say it's ambiguous, but the semantics are well-defined: a relative import is preferred if one exists. This is how Python's module system works, for example.

So that means that file naming in a sub-folder is constrained by whatever happens to be in the load path, if you want to refer to both the shadow and the shadowed?  That does not seem reasonable.

That along with the ambiguity (you can't tell from the `@import` statement if it's relative or not) makes this far from ideal.

Doing relative lookup only for ./ or ../ eliminates the ambiguity and removes naming constraints.

**Comment by bughit** [comment]
technically you can get at the shadowed file with .. but it's not a good idea to take a dependency on the incidental current folder hierarchy

**Comment by chriseppstein** [comment]
> Then the @import won't work because ./_bootstrap.scss is in the way. So you have to rename _bootstrap.scss to accomodate this. As we get a bigger ecosystem of libraries, this might become a more frequent problem.

Of primary concern for me is that two libraries included in the same app would work predictably irrespective of the loadpath configuration. In this respect, our current semantics work well, neither will accidently load a library included on the loadpath instead of a file relative to the library file.

Of less concern to me is that a person can add a library to their app without needing to make any change to their application code in order to load that library. Adding the library is safe in that it won't accidently import some new library and having application code with the same name as the library that is in use, is actually confusing whether or not there's some syntactic disambiguation.

There are lots of issues with library code being in the global scope that makes library module interactions-at-a-distance happen in unpredictable ways, and our module system is meant to resolve those use cases, but this particular use case doesn't seem like it's actually hindering adoption of sass libraries in practice.
