### ISSUE TITLE
Deprecate index()'s false return value

### ISSUE THREAD

**Issue by nex3** [sass/sass#1127]
79bad1ff473cc06c66b85086403f4a1905938e37 changed `index()` from returning `false` when not finding an element to returning `null`. As discussed in #832, we didn't think this necessitated a deprecation process since we expected users to be writing `@if index(...)`. However, it seems that at least [Foundation](https://github.com/zurb/foundation/blob/2c4f399ee5e06c94f4c1c491d5c2ce344f974193/scss/foundation/_functions.scss#L12) explicitly checks against `false`.

Rather than returning `null` immediately, we'll need to add a `DeprecatedFalse` value that complains if it's used in a way that is incompatible with the future `null` class.

**Comment by mikehdt** [comment]
I've used a bit of "x == false" stuff in some cases where I care only about if something doesn't exist in a list.

Given we can't (or shouldn't) do x == false, and x == null also throws a warning, what should we do? I can only really think of checking for a "positive" value, and then immediately following it with an `@else`. But that seems kludgy.

**Comment by nex3** [comment]
Why can't you write `@if not x`?

**Comment by mikehdt** [comment]
You can - perfect! Thanks :) The warning from the compiler only suggested using `@if x`, hence why I was trying to figure a way around it.

Perhaps rather than throwing `For example, instead of "@if index(...) == false", just write
"@if index(...)".` it could suggest `@if not index(...)` instead if that makes sense? (That message was from the Sass compiler in CodeKit 2).

**Comment by nex3** [comment]
It's tough to get enough contextual information to figure out the perfect error message, unfortunately :-/.

**Comment by nex3** [comment]
Actually, that error should just always say `@if not index(...)`. I'll fix that.
