### ISSUE TITLE
Allow @import to evaluate sass-script

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#115]
This will allow for `@import stylesheet-url("foo.css");` which protects the user against changes to their asset serving approach.

**Comment by MarioRicalde** [comment]
This would be really useful, you can even use a shortcut with variables.

**Comment by AriaMinaei** [comment]
**This feature is a must-have.**

Right now, I'm using sass variables to compile different stylesheets for different locales, based on the same scss files. It automatically creates css files for English, French and other languages. I have set a $locale variable in each locale's screen.scss, in this case:
$locale: "enUS".

Now, I have different button sprites for each locale; but, since variables aren't allowed in @import statements, I can't use compass's sprites feature. This is how the code would look like if variables were allowed:

@import "images/#{$locale}/button/*.png";

**Comment by timmolendijk** [comment]
Yesyesyes **must-have**! Without it Compass' `http_path` configuration parameter is pretty much useless.

Btw, @AriaMinaei & others -- (ugly) work-around:

```
@import url("#{stylesheet-url('foo.css', true)}");
```

**Comment by chriseppstein** [comment]
Sorry I should have been clearer. This is only for generating css-based `@import` directives. Sass-based `@import` directives shouldn't need this feature.

**Comment by timmolendijk** [comment]
@chriseppstein Who or what are you addressing? I think I'm missing your point.

**Comment by chriseppstein** [comment]
@AriaMinaei For your needs, the @import approach will not work, however the compass spriting feature can totally accomodate this need by dropping down to the next lower layer.

**Comment by chriseppstein** [comment]
@timmolendijk sorry I was addressing @AriaMinaei

**Comment by jslegers** [comment]
See also :
- https://github.com/sass/sass/issues/451
- https://github.com/sass/sass/issues/739
- https://github.com/sass/sass/issues/779
- https://github.com/sass/sass/issues/1194

**Comment by nex3** [comment]
This is covered by #739, with the current plan summarized in [this comment](https://github.com/sass/sass/issues/739#issuecomment-359100028).
