### ISSUE TITLE
Sass 3.3.2 (Maptastic Maple) returns a Syntax error on using the map data structure

### ISSUE THREAD

**Issue by gespinha** [sass/sass#1166]
Hi there,

I am trying to apply the map data structure as follows, but I'm constantly receiving an error: 

Syntax error: Illegal nesting: Nothing may be nested beneath variable declarations.

CODE:
$object: (
    size: 11px,
    font-family: null,
    font-size: 11px,
    color: #fff,
    weight: bold,
    background: #c0c650,
    positionH: 10px,
    positionV: -3px,
)

**Comment by lolmaus** [comment]
Works for me: http://sassmeister.com/gist/9511503

**Comment by gespinha** [comment]
@lolmaus does it require Compass?

**Comment by lolmaus** [comment]
Nope.

Are you sure it's this piece of code that produces the error? Maybe it's somewhere above or below.

Oh, are you using the indented `.sass` syntax?.

**Comment by gespinha** [comment]
I am using .sass normal syntax

**Comment by Snugug** [comment]
There's your problem. Even when defining maps, you can't have returns between each definition in `.sass`.

**Comment by gespinha** [comment]
Yup, thats the problem. Thanks it makes sense (my distraction) ;)

**Comment by nicooprat** [comment]
Maps on a unique line make no sense, isn't it actually a bug / missing feature ?

This is unusable :

``` sass
$object: (size: 11px, font-family: null, font-size: 11px, color: white, weight: bold, background: #c0c650, positionH: 10px, positionV: -3px)
```

Why not let us do something like :

``` sass
$object:
  size: 11px
  font-family: null
  font-size: 11px
  color: #fff
  weight: bold
  background: #c0c650
  positionH: 10px
  positionV: -3px
```

**Comment by Arcovion** [comment]
@nicooprat Check out #216, sadly this is a long standing bug.

**Comment by nicooprat** [comment]
Thanks for the heads up !

**Comment by OutThisLife** [comment]
They should change the documentation examples, then.

http://thesassway.com/news/sass-3-3-released

**Comment by Arcovion** [comment]
Those examples are in `.scss` where it works, [the guide](http://sass-lang.com/guide) should probably mention maps though instead of just that blog post (which isn't the official sass blog btw).

**Comment by Anaphase** [comment]
Well, boy howdy that was a fun bug to track down as a first-time SASS user. The docs should definitely mention this bug somewhere in the [maps](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps) or [syntax](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html) sections. The error returned by SASS (`Illegal nesting: Nothing may be nested beneath variable declarations.`) is definitely not super-duper helpful either.

Is `.sass` syntax deprecated or just bad practice nowadays?

**Comment by OutThisLife** [comment]
@Anaphase 

SASS > SCSS in the real world. This is just a fluke.

**Comment by Anaphase** [comment]
@OutThisLife, So people have been writing all their SASS maps on one line for years and years now? That's insane! That makes SASS totally unusable for me. Back to [Stylus](http://stylus-lang.com/) it is!

Anyway, I see there's more activity over on #216, sorry for bumping this old thread.

**Comment by OutThisLife** [comment]
Well. What are you doing to rely so heavily on maps?

**Comment by Anaphase** [comment]
@OutThisLife Nothing, really. I'm only looking into SASS because I'm using ZURB Foundation's [Foundation for Emails](http://foundation.zurb.com/emails.html) framework and [their template project](https://github.com/zurb/foundation-emails-template) uses SASS. However, they use `.scss` and I wanted to convert everything over to `.sass` since I prefer whitespace-dependent syntaxes.

Everything was trivial to covert, except for the [maps in the settings file](https://github.com/zurb/foundation-emails-template/blob/14934dbb5777c439caa843052e2e210977fedd35/src/assets/scss/_settings.scss#L97). After lots of debugging, reading documenting, and sifting through error message red herrings, I finally landed here only to discover that the "solution" is to just write my map like this:

```sass
$button-padding: (tiny: 4px 8px 4px 8px, small: 5px 10px 5px 10px, default: 8px 16px 8px 16px, large: 10px 20px 10px 20px)
```

It's just bizarre to me that people are able to look past this bug and still use SASS... That would drive me nuts. I suppose one workaround would be to just define all your maps in a separate `.scss` file and import them into whatever `.sass` file you want.
