### ISSUE TITLE
@mixin !default

### ISSUE THREAD

**Issue by eli-collins** [sass/sass#1186]
_Feature:_

It would be nice to be able to use the `!default` modifier with mixins, much like with variable assignment...  if a mixin of that name was already defined, the declaration would not replace the previous one.  

For example:

```
@mixin foo()
{
       display: block;
}

@mixin foo() !default 
{
       display: inline;
}

.bar { @include foo; }
```

... would result in `.bar { display: block; }`

The main place I can think of that would be a great use-case is frameworks like Foundation. If all of Foundation's mixins were defined with `!default`, then the application-specific settings.scss file could override not just variables, but mixins as well, making it a lot easier to customize the output of such frameworks. As it stands now, you can tweak the variables, but mixins are either "accept them as they are or don't use them".

**Comment by Snugug** [comment]
Currently, Sass will use whatever version of a mixin was last defined, so if a framework comes with a mixin named Clearfix and after you've imported that you define a mixin named Clearfix, yours will be used.

**Comment by eli-collins** [comment]
That's the inverse of what I'm envisioning. In a framework like Foundation, the logic flows as follows: application controlled settings.scss is loaded, defining some variables. Foundation is then imported, which defines some default values, defines some mixins, and then _runs those mixins_. You don't have the opportunity to redefine the mixins before they are executed. This is almost the exact same use-case as why `$foo: blah !default` exists.

**Comment by Snugug** [comment]
I understand.

While the following isn't a solution to that problem, I encourage you to file an issue with your framework of choice having them require user input (as opposed to an @import) to kick off things being output to your stylesheet. It sound like a framework architecture issue.

**Comment by eli-collins** [comment]
It feels to me like that forces undue contortions... every component of a framework would have to be broken into "defaults", "mixins", and "rendering" stages, so that the user could load and override the first two before loading the final one. For a componentized framework, doubling/tripling the number of files seems like it would create a lot of boilerplate that this feature would remove the need for. That's leaving aside the situation where the mixins are used to _define_ the default variables.

Having a framework rearchitect itself to work without `$var: blah !default` is also possible through a similar topological transformation to what you're suggesting, but I don't understand why it's any more acceptable a solution just because we're dealing with the mixin namespace instead of the variable namespace.

**Comment by cimmanon** [comment]
I've been wanting a feature like this myself.  I know there's been some discussion about namespacing, but I don't think it would solve this problem.  If I like a particular library's boilerplate except for minor things here and there that are controlled by mixins, being able to have defaultable mixins seems like the most straightforward solution.

``` scss
@mixin base-block-styles {
    margin: 0;
    padding: 0;
}

p, div, ul, ol, etc {
    @include base-block-styles;
}
```

What happens if I want to use this mixin instead?

``` scss
@mixin base-block-styles {
    margin: 1em 0;
}
```

If the file I was importing _didn't_ include a base-block-styles mixin (maybe it is defined elsewhere in the library), then the user would be forced to create the mixin themselves or do an extra import.  I don't feel this is good for the user.

The only realistic option that is currently available is to check if the mixin exists before defining it:

``` scss
@if !mixin-exists(base-block-styles) {
    @mixin base-block-styles {
        margin: 0;
        padding: 0;
    }
}
```

This seems a lot less elegant than simply making use of a `!default` flag, which users are already familiar with.

**Comment by KittyGiraudel** [comment]
> The only realistic option that is currently available is to check if the mixin exists before defining it:

As far as I know, it's not even an option since mixins and functions cannot be defined in control directives. 

> Mixins may not be defined within control directives or other mixins.
> Functions may not be defined within control directives or other mixins.

Also, that would be `not` and not `!`. 

Anyway, it would be cool to have the `!default` flag available for mixins and functions as well. :)

**Comment by chriseppstein** [comment]
It's true that the overwrite-based approach has limitations.

Imagine you have a file `_framework.scss` and it imports `framework/_mixins.scss`. What you'd like to be able to do is override some mixin defined in `framework/_mixins.scss` and have it be used instead. But because Sass imports the library it always resets the mixin definitions -- there's no way to get in between the import statement and the output of the `_framework.scss` file.

However, this is a problem created by the import strategy, not by how mixins are defined and overridden. If a file was only imported once, you would be able to import the framework mixins, override them, and then import the main `framework` file. That the framework imported the mixins again would be a no-op and your definition would be used. The framework itself did not have to participate in the overriding scheme.

IMO, this is a capability that you will get for free when sass introduces `@use` and until then you can include http://rubygems.org/gems/compass-import-once into your project and get this behavior now.

Many languages have guarded variable assignment (that is the technical term for `!default`). However, very few languages have conditional method declaration. Instead the convention of programming languages is to provide an override mechanism for methods and/or a generic method invocation abstraction. I don't see a good reason for sass to buck the trend here -- however I do think Sass needs to implement what every other language does for dependency management: only import dependencies once.

**Comment by chriseppstein** [comment]
See #139

**Comment by eli-collins** [comment]
I disagree about 'very few languages have conditional method declaration'.  I think the need is quite common in languages where class inheritance isn't commonly used or available. For example, I've seen C and javascript code jump go to great (but achievable) lengths to get conditional method declaration. 

But my main issue with the `@use` solution is connected to my main motivation for this feature request... which so that I could override a mixin with the Foundation framework. Unfortunately Foundation has the pattern of single-file `foundation/components/_<component name>.scss` which sets up default vars, sets up mixins, and generates output for a particular subject, all in one file. 

It seemed a rather sane layout to me, but are you saying that's not how sass should be used, and that the proper way to get this to work would be to convince Foundation to split every components file into `foundation/components/<component>/_defaults_and_mixins.scss` and `foundation/components/<component>/_output.scss`? If so, I'm not looking forward to convincing their devs to do all that work just so a mixin or two can be overridden, whereas I figured asking them to add `!default` after all their mixins would be a relatively painless.  

Ah well, I guess it's settled in any case :(

**Comment by nex3** [comment]
There's a lot of discussion going on here, but I just wanted to jump in and say that I'm not eager to make monkey-patching easier in Sass. It's an extensibility strategy that's extremely error-prone on numerous axes and composes very poorly.

**Comment by phazei** [comment]
Both PHP and javascript support conditional method declaration.  Those are also like a very large majority of all your users.  So it seems like it would make sense to match the most common languages used with this.
