### ISSUE TITLE
Sass shouldn't attempt to cache importer instances

### ISSUE THREAD

**Issue by bhollis** [sass/sass#1196]
I've been digging through an issue that affects users of [Middleman](https://github.com/middleman/middleman) when using Sass 3.3. This problem was not present in the Sass 3.2 line.

The symptom is a message like this:

```
Warning. Error encountered while saving cache ./.sass-cache/6d19918aae9b194893adf3de06101cc3ab87507f/_partial2.css.sassc: can't dump anonymous class #<Class:0x007fb885d0a030>
```

The cause is that the `Sass::Source::Range` class contains a reference to a `importer`, and `Sass::CacheStores::Base#store` calls `Marshal.dump` on a tree of nodes that includes these `Sass::Source::Range` instances. We use [`sprockets-sass`](https://github.com/petebrowne/sprockets-sass), and [its importer implementation](https://github.com/petebrowne/sprockets-sass/blob/master/lib/sprockets/sass/importer.rb) keeps a reference to the Sprockets context, which is the anonymous class referenced in the error message. I suspect this may affect `sass-rails` as well, since [their importer](https://github.com/rails/sass-rails/blob/master/lib/sass/rails/importer.rb) also has a reference to the Sprockets context.

This seems very similar to #147, and the solution there was to avoid caching the options hash that could contain the Sprockets context or other uninteresting things - hopefully something similar could be done here. I'd be happy to help if somebody would be able to give some guidance on the correct approach to solving the problem.

/cc @tdreyno

**Comment by nex3** [comment]
Importers are required to be marshalable; see [the Importer documentation](http://sass-lang.com/documentation/Sass/Importers/Base.html). Sprockets' importer wasn't, but [this pull request](https://github.com/sstephenson/sprockets/pull/542) fixes that.

It's necessary that we associate and importer with each source range in order to properly generate source maps. Importers have specific logic about the URIs that should be included in a source map, and we need to access that logic when generating source maps.

**Comment by petebrowne** [comment]
@nex3 I'm working on a fix for [sprockets-sass](https://github.com/petebrowne/sprockets-sass/issues/26), but I could use some input from you.

I could [remove the custom Importer](https://github.com/petebrowne/sprockets-sass/tree/sass-3.3) and follow Sprockets' lead, but I lose some important functionality as a result. Can you think of any other options?

Is the requirement for Importers to be marshalable only affect source maps? Is there a way we can disable that caching if we're not using source maps?

**Comment by nex3** [comment]
> I could [remove the custom Importer](https://github.com/petebrowne/sprockets-sass/tree/sass-3.3) and follow Sprockets' lead, but I lose some important functionality as a result. Can you think of any other options?

If you're going to use an importer, it has to be marshalable. There are ways you can work around this, though. If the sprockets context is available globally, you can override `_dump` and `_load` to get rid of and re-load it so only the necessary information is marshaled. If you can control the options hash, you can use `options[:custom][:sprockets][:context]` to pass in the context object so that the importer can access it.

> Is the requirement for Importers to be marshalable only affect source maps? Is there a way we can disable that caching if we're not using source maps?

This would be a pretty serious functionality regression; source maps are very useful, and they'll only become more important as browser support increases. Even if you were willing to bite the bullet and remove support for them, they're too deeply integrated into Sass at this point to easily disable.

**Comment by petebrowne** [comment]
Thanks for the input! I will try passing it through the options hash

**Comment by lolmaus** [comment]
I've updated Sass to 3.4 under Rails and now every page refresh explodes Rails logs with:

> ...
> 
> Warning. Error encountered while saving cache 85f3951856beaa895816380dc8fb44c8d5e7e8de/_margin.sassc: can't dump anonymous class #Class:0xc484930
> 
> Warning. Error encountered while saving cache 85f3951856beaa895816380dc8fb44c8d5e7e8de/_selectors.sassc: can't dump anonymous class #Class:0xc484930
> 
> Warning. Error encountered while saving cache 3dc36025dd376b8bbd67bee9670c204fe161fb8a/_modules.sassc: can't dump anonymous class #Class:0xc484930
> 
> ...

My teamlead will most certainly be unhappy with it.

Is there anything to be done about it?

**Comment by chriseppstein** [comment]
I can't think of anything in Sass 3.4 that has changed that could have caused this issue.

**Comment by lolmaus** [comment]
Server restart seems to resolve this issue. Sorry for a false alarm.

**Comment by whoshallsucceed** [comment]
I encounter this issue when precompiling assets, which is required when deploying on Heroku. Or am I missing something?
