### ISSUE TITLE
I'd like to be able to read the CSS selector from within SassScript (so meta, I know)

### ISSUE THREAD

**Issue by SnakeO** [sass/sass#1206]
I have a friend who is building a sass grid framework. We need to be able to know where we are in the hierarchy of CSS selectors. AFAIK sass doesn't have a way to get the current CSS selector, so I made a plugin:

``` ruby
require 'sass'

module Sass::Script::Functions

  def selector_string()
    return Sass::Script::String.new(environment.selector.to_s)
  end

end
```

aaaand that's it. Now, I can grab the css selector and save it in a map, which allows me to build out a topography of the current CSS nesting structure. This simple addition will allow users to be "aware" of where they are in the CSS tree. Can we consider adding it to the master?

**Comment by pdaoust** [comment]
There's a lot of that work already going on: it's called 'script `&`' and its saga can be followed in issue #286. It was added to Sass 3.3 but [removed](https://gist.github.com/nex3/8050187) before the final release, and [will be added back](https://github.com/nex3/sass/issues/1078) in in version 3.4. The nice thing is that it'll be really easy to use:

``` scss
$current-selector: &;
```

That's it. You now have a comma-separated list of space-separated lists[*](#footnote). If you want it as a string (similar to your Ruby example), you can go:

``` scss
$current-selector-string: "#{&}";
```

instead.

For now, in Sass 3.3, script `&` is turned off.

<div class="footnote">* (It turns out a comma-separated list of space-separated lists is perfect for representing any selector. If you have just one piece to your selector, it'll be represented as a single-item list containing a single-item list, for consistency: <code>((".oneclassname"))</code>)</div>

**Comment by nex3** [comment]
@pdaoust is right, this is already supported on master.
