### ISSUE TITLE
Math issue with simple calculation

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1224]
This bug has been found by @cahnory. I'm just reporting it here.

It looks like there are some rounding errors with simple calculations. Please consider the following example:

``` scss
$a: 0.12;
$b: 0.10 + 0.02;
$test: $a == $b; // false
```

Meanwhile, this should return `true`. `0.10 + 0.02 == 0.12`. That being said, JavaScript produces the same error. I believe this has to do with the fact that all numbers are floats or something?

A fix would be to do:

``` scss
$fix: $a == (round($b * 100) / 100);
```

But that's pretty harsh.

Relevant test case: http://sassmeister.com/gist/11142740.

**Comment by nex3** [comment]
This is an unfortunate but fundamental issue with floating-point numbers. There are some numbers that can't be represented exactly by floats, and it's possible for there to be multiple representations of what looks like the same number that are nevertheless not considered equal. In general, numeric equality shouldn't be relied upon for non-integer numbers (or for very large integers, for that matter); range comparisons (`<=` etc) should be used instead.

Out of curiosity, what's the use-case for float equality?

**Comment by lolmaus** [comment]
This is ridiculous. How do i know whether i should do `<=` or `=>`? What if i need to distinguish between `=` and `<`/`>`?

**Comment by cahnory** [comment]
I don't have a real use case. I was just unit testing a string to number conversion function.

**Comment by cahnory** [comment]
@lolmaus I think you'll have to write a function to test approximate equality. The difference is about 0.0000000000001 something like that (but I did one test only with 0.1 + 0.02)

**Comment by lolmaus** [comment]
If `0.12 == 0.1 + 0.02` fails, then "a function to test approximate equality" should be included into the language core, or even be a default method of comparison. I can't think of any use case where a user expects  `0.12` to be different from `0.1 + 0.02`.

And of course users should be informed of this behavior as explicitly as possible, regardless of whether you decide to include approximate equality or not.

**Comment by cahnory** [comment]
And then you'll can't differentiate 0.12 from 0.11999999999999… and that's another issue. Like @HugoGiraudel said, Javascript has the same problem and @nex3 seems to say that the issue is related to float number and not just sass. In fact I'm pretty sure I saw a floating number issue with PHP too but can't remember it.
I'm not saying there is no solution but that it seems to be a language agnostic unsolved issue ;).

**Comment by lolmaus** [comment]
> And then you'll can't differentiate 0.12 from 0.11999999999999…

You can't differentiate those two numbers because they are equal. Every number that has an infinite sequence of nines after the decimal point is the same number as next whole number. `1` and `0.999…` are just two different ways to write down the same number. See [http://en.wikipedia.org/wiki/0.999...](http://en.wikipedia.org/wiki/0.999...).

This is not the case for `0.12000000000000001`. If you add `1` into any position after the decimal point, you create a new, bigger number.

I think that programming languages (including Sass) should handle that correctly. One must be a cyborg to believe that `0.12 == 0.1 + 0.02 // => false` is normal.

UPD: Ok, i just found out that `0.12 == 0.1 + 0.02` is false for all programming languages. At all that i have tried on compileonline.com: Java, C#, JavaScript, Ruby, Haskell, Python. I don't know what to believe anymore.

**Comment by cahnory** [comment]
0.11999999999999 was just an exemple (a bad one ^^). I should have said 0.1200000000000000163757896132210589712486 (~= 0.1 + 0.02) :)

**Comment by apfelbox** [comment]
Never use equals with floats, since it fundamentally can't work. Always test equality by using an epsilon margin:
Instead of `a == b` use `abs(a - b) < 0.000001` (or whathever your epsilon is)

(Some background: [The Register: The trouble with rouding floating point numbers](http://www.theregister.co.uk/2006/08/12/floating_point_approximation/))

**Comment by lolmaus** [comment]
So can we have this built in?

**Comment by chriseppstein** [comment]
Sass can expose a function like `approximately-equal($n1, $n2, $tolerance: 0.00001)` but I don't think it's a good idea to make the float equality operator do this automatically.

**Comment by lolmaus** [comment]
@chriseppstein, thank you for supporting the discussion.

Creating such a function is trivial. The problem here is that it's very bulky to use.

What about creating a group of approximate comparison operators, with tolerance controlled by a configuration variable? I'd suggest putting the variable onto the upcoming `sass.json`, but i've got a feeling that @nex3 will be against exposing a variable, changing which can break edge cases. Thus, my suggestion is Compass extension style:

``` scss
$__epsilon-margin__: 0.00001;

@debug 0.1 + 0.02 ~>= 0.12;
```

It is still very new and embarrasing to me that approximate comparison for flawed floats is missing in stdlibs of all languages. So i've got no idea whether my suggestion is rational. It seems very rational to myself. :)

**Comment by chriseppstein** [comment]
I wouldn't expect a user to understand what `~>=` means when they see it or how it works. Furthermore, It's exceedingly hard to search for that on the internet and learn about it.

But I would expect a user to know what `approximately-equal()` is doing. I favor readability of a file for users over reducing bulkiness. As does css in general. That's why it has a `background` property instead of `bg`. Using a function for float comparison is sufficient for the frequency of this use case, IMO.

**Comment by KittyGiraudel** [comment]
>  Using a function for float comparison is sufficient for the frequency of this use case, IMO.

Seconded.
