### ISSUE TITLE
Sass session cache

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1264]
Sass extensions need a place to cache values for the duration of a single compile.

Suggestion `environment.session` which returns a hash that is stored in the top-level environment.

**Comment by nex3** [comment]
Can you give me an idea of a concrete use case for this?

**Comment by chriseppstein** [comment]
the import-once plugin needs to track work done during a single compile, compass sprites need to only be produced once per compile when --force is provided. The archetype plugin needs to cache resolved component definitions.

**Comment by nex3** [comment]
Okay, sounds good to me.

**Comment by eoneill** [comment]
+1
This will greatly reduce some session state complexity in Archetype. Thanks!

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
