### ISSUE TITLE
Error message about public URL when generating source maps

### ISSUE THREAD

**Issue by paultitcomb** [sass/sass#1280]
Am getting the following error message when using Grunt to watch my sass files and run grunt-contrib-sass with sourcemaps turned on:

```
Running "sass:uk" (sass) task
WARNING: Couldn't determine public URL for "C:\Ruby193\lib\ruby\gems\1.9.1\gems\compass-core-1.0.0.alpha.19\stylesheets\compass\reset\_utilities.scss" while generating sourcemap.
Without a public URL, there's nothing for the source map to link to.
```

The weird thing is, it seems to generate the css and sourcemap ok anyway.

i am using 
compass - v 1.0.0.alpha.19
sass - v 3.3.7

I have a feeling it may be similar to an issue i experienced before when using the Prepros GUI to compile my sass, where the sass gem and the files it is compiling [have to be on the same drive](https://github.com/subash/Prepros/issues/454).

Can you confirm that this is the case, and if so is there a way round it (other than re-installing Ruby/sass on another drive)?

**Comment by nex3** [comment]
> The weird thing is, it seems to generate the css and sourcemap ok anyway.

Since this is a warning, it's not fatal. It just means that any references in the source map that would have pointed to `C:\Ruby193\lib\ruby\gems\1.9.1\gems\compass-core-1.0.0.alpha.19\stylesheets\compass\reset\_utilities.scss` won't work. Other references will, though.

> Can you confirm that this is the case, and if so is there a way round it (other than re-installing Ruby/sass on another drive)?

When generating a source map, Sass needs some way to refer to the source files that that browser will be able to resolve. Ideally, it would also be resolvable if the source files were all uploaded to a server as well. To do so, Sass tries to find a relative path from the source map to the source file. However, if the source file is on a different disk as the Compass sources are in this case, there's no relative path for it to use, so it produces this warning.

#1107 is tracking the addition of alternate source map formats which would allow the source contents to be inlined in the source map to make it maximally portable, or the use of `file:` URIs which aren't portable but will work very well locally.

**Comment by motin** [comment]
Update grunt-contrib-sass to make it work with recent Sass versions. More info: https://github.com/gruntjs/grunt-contrib-sass/issues/25
