### ISSUE TITLE
Spaces aren't removed from media query selectors

### ISSUE THREAD

**Issue by beauwest** [sass/sass#1296]
In the example of `@media (min-width: 960px){}` the SCSS `output_style = :compressed` syntax doesn't eliminate the space between `min-width` and `960px`.

It may be by design to make people compress their own media queries, I'm not sure. At any rate, this is an _extremely_ minor issue. Please don't hate me. :)

**Comment by nex3** [comment]
Right now, Sass doesn't store much deep semantic information about media queries once it parses them. They're basically treated like strings with interpolation, which means that it's hard to emit them in different styles. I'll leave this issue open because that could change in the future, but it would be a non-trivial amount of work.

**Comment by beauwest** [comment]
Sounds great, thank you for responding!

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
