### ISSUE TITLE
Watch doesnt work on folders named "vendor"

### ISSUE THREAD

**Issue by kevcam4891** [sass/sass#1299]
I have a set of folders I am watching with the command:
sass --load-path ./webroot-src/scss --scss --poll --watch ./webroot-src/scss:./webroot/css/scss

Inside, there is a folder called "vendor". Upon execution sass detects changes once, but doesn't keep polling. All other folders work fine. I even renamed vendor -> vendors and watching works after the first time.

Weird?

**Comment by kevcam4891** [comment]
I am running 3.3.8 BTW. I was also experiencing same issue with 3.3.4.

**Comment by chriseppstein** [comment]
This is a default that comes from Listen: https://github.com/guard/listen/blob/v1.3/lib/listen/directory_record.rb#L15

More recent versions have a different set of defaults: https://github.com/guard/listen/blob/master/lib/listen/silencer.rb

But why are you editing files from a third-party? This seems like a terrible idea anyway. I suggest you add files to your project that incrementally change the values from the third party in your own files so that future updates are possible.

**Comment by kevcam4891** [comment]
Great to know. I tried searching but did not see any answers that 
addressed the issue. I am not "editing" files from a third party, but 
rather adding layers on top. TinyMCE, for example, has its own set of 
CSS that I have in [webroot]/vendor/tinymce/[etc, etc]. I have files 
like [webroot]/css/vendor/tinymce.scss that will compliment the base 
files. Vendor folder was not parsing and I didn't know why.

Chris Eppstein wrote:
