### ISSUE TITLE
Placeholder example in sass format

### ISSUE THREAD

**Issue by jina** [sass/sass#1303]
For this doc: https://github.com/sass/sass/blob/stable/doc-src/INDENTED_SYNTAX.md

As requested by @paazmaya.

See https://github.com/sass/sass-site/issues/83

**Comment by jina** [comment]
I am happy to do this once I get a chance. Just wanted to track the issue in the right place.

**Comment by nex3** [comment]
I don't really want the indented syntax documentation to completely duplicate everything in the reference documentation. The placeholder syntax doesn't differ between the two; it's covered under "most CSS and SCSS syntax works straightforwardly in Sass by using newlines instead of semicolons and indentation instead of braces".

**Comment by jina** [comment]
okie dokie.

**Comment by paazmaya** [comment]
Thanks @jina for the effort
