### ISSUE TITLE
Bug in "sass --watch"

### ISSUE THREAD

**Issue by liamato** [sass/sass#1311]
I have this folders tree:

```
css
|_sass
      |_core
            main.css
      |_doc
            _doc.scss
            _nav.scss
```

main.scss

``` sass
@import "../_doc.scss";
```

_doc.scss

``` sass
@import "_nav.scss";
```

_nav.scss

``` sass
body{
    background-color: red; // For example
}
```

When I compile this from `sass` folder with `sass core/main.scss:../main.css` doesen't was any problem.
But when I want compile that with `sass core/main.scss:../main.css --watch`, if I change `_nav.scss`:

``` sass
body{
    background-color: blue; // For example
}
```

`main.css` doesen't change.
I need to change `main.scss` to compile `main.css`

**Comment by nex3** [comment]
This is intentional. When you run `sass --watch`, you're not just specifying what to compile; you're specifying what to watch as well. If Sass just watched everything transitively reachable from your files, it could end up spending a lot of work watching big libraries that are never expected to change. You can get the behavior you want here by running `sass --watch sass:.` from `css/`.
