### ISSUE TITLE
Better traces for exceptions thrown from ruby functions

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1318]
When an exception is thrown from a ruby function, none of the sass trace information is reported.

It would be great to also get the values of the arguments that caused the issue.

Presently, I'm accomplishing this with a monkey patch to Sass 3.2 that looks like this:

``` ruby
          begin
            without_original(opts(Functions::EvaluationContext.new(environment.options).
                send(ruby_name, *args)))
          rescue StandardError => e
            s = Sass::SyntaxError.new("#{e.class.name} calling #{ruby_name}(#{args.map{|a| a.is_a?(Sass::Script::List) ? "(#{a.to_sass})" : a.to_sass}.join(', ')})")
            s.set_backtrace(e.backtrace)
            raise s
          end
```

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
