### ISSUE TITLE
run_updated_stylesheets should return sourcemap too

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1344]
See `XXX` comment in `lib/sass/plugin/compiler.rb`

This is a backwards incompatibly change that's hard to deprecate.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
