### ISSUE TITLE
color alpha channel

### ISSUE THREAD

**Issue by yukulele** [sass/sass#1345]
sass emit an error if alpha channel of rgba/hsla color is out [0,1] range, css allow it: 

>  Any values outside the range 0.0 (fully transparent) to 1.0 (fully opaque) will be clamped to this range.

http://www.w3.org/TR/css3-color/#alphavaluedt

**Comment by chriseppstein** [comment]
CSS does a few things that are considered error recovery to make sense out of nonsensical input. Sass gives errors in these cases, because it's useful to developers to catch their coding errors. I can't think of a use case for this behavior except to handle bad code.

**Comment by yukulele** [comment]
SASS (in SCSS form) is a subset of CSS, all valid CSS should be valid in SCSS.

**Comment by nex3** [comment]
I have mixed feelings here. On the one hand, I think Sass's policy of providing stricter error-handling than CSS is a good one; especially as CSS moves towards specifying more and more error fallback behavior, our behavior is going to diverge from that of the spec in ways that are almost universally good. It's fine if a CSS file that mostly works in browsers due to error recovery reports a precise and useful error message in Sass.

On the other hand, for the most part the specs tend to clearly call out behavior that exists as an error fallback. There is no such clarification for the clipping behavior of `rgb()` and `rgba()` (or `hsl()` or `hsla()`), and this behavior exists even in specs that predate the movement towards specifying error fallbacks. As such, I think it's reasonable to perform the clipping rather than produce an error here.

**Comment by yukulele** [comment]
The next CSS version is more precise about this:

> The final argument, the &lt;alpha-value>, specifies the alpha of the color. If given as a &lt;number>, the useful range of the value is 0 (representing a fully transparent color) to 1 (representing a fully opaque color). If given as a &lt;percentage>, 0% represents a fully transparent color, while 100% represents a fully opaque color. **Values outside these ranges are not invalid**, but are clamped to the ranges defined here at computed-value time. If omitted, it defaults to 100%.

http://dev.w3.org/csswg/css-color/#rgb-functions

it also allow percent values.
