### ISSUE TITLE
Support Function Calls At Root And Functions Without Return Values

### ISSUE THREAD

**Issue by Undistraction** [sass/sass#1348]
Currently it is impossible to:
1. Call a function outside a selector, mixin or another fucntion
2. Create a function with no return value

It would be really useful to be able to do both.

Usecase:

In a configuration file I would like to be able to add a palette of colours to a map. This action requires no variable assignment at the point it is called and no return from the function that adds the map.

_Ideal_ code:

```
# base.utils.palette.scss

$palette-map:();

@function register-palette($name, $palette) {
  $palette-map: map-merge( $palette-map, ($name: $palette) );
}
```

```
# app.config.palette.scss

register-palette(default, (
   text-color: $black,
   background-color: $light-grey
));
```

However, this is not possible so the only way to achieve this is:

```
# base.utils.palette.scss

$palette-map:();

@function register-palette($name, $palette) {
  $palette-map: map-merge( $palette-map, ($name: $palette) );
  @return none;
}
```

```
# app.config.palette.scss

$temp: register-palette(default, (
   text-color: $black,
   background-color: $light-grey
));
```

I appreciate this could also be achieved using a mixin:

```
@include register-palette( … )
```

But in both cases, the purpose of the code is obscured. It seems to me that there is a strong argument for allowing functions to be used in this way.

**Comment by chriseppstein** [comment]
Sass has a `null` value. So you can `@return null` instead of `none` which is a string.

Also, side-effects are intentionally discouraged so if pure side-effect functions are awkward to use, this doesn't bother me, I actually like the mixin here, because mixins exist purely to perform side-effects.

@nex3 concur?

**Comment by Undistraction** [comment]
@chriseppstein I guess my problem with using a mixin is that the name `mixin` makes sense when you are mixing function into a selector, but here it feels like it is being misused, and the necessity of the unused `$temp` variable only makes it feel more so. It feels kind of hacky.

This feels like a perfectly reasonable (and helpful) use-case to me that can only be achieved in a convoluted way. Would you mind explaining why this kind of 'side effect' is discouraged?

I would also question that if you allow a null return value, why not make this implicit, though I suppose this is tied into avoiding functions created specifically for their side-effects.

**Comment by cimmanon** [comment]
How would using a mixin for your purpose be any more "misuse" than a mixin like this?

``` scss
@mixin reset() {
    body, p, div, etc {
        margin: 0;
    }
}

@include reset();
```

**Comment by Undistraction** [comment]
@cimmanon Because in your example you are using it to mix-in a selector to the root of the document which is doing what the name `mix-in` in this context implies – mixing in properties to selector or mixing in selectors to the document.

In my example it mixes-in absolutely nothing. I am using it only as a way create a context (for want of a better word) where I am able to call a function. The bi-product of the function call is a variable declaration which again is only present because I can't call the function without assigning it to something.

I don't really really see any similarity between your example and mine at all.

**Comment by nex3** [comment]
@chriseppstein Concur. I don't want to encourage functions with side effects.

**Comment by chriseppstein** [comment]
> I guess my problem with using a mixin is that the name mixin makes sense when you are mixing function into a selector, but here it feels like it is being misused, and the necessity of the unused $temp variable only makes it feel more so. It feels kind of hacky.

I agree. It's hacky.

> This feels like a perfectly reasonable (and helpful) use-case to me that can only be achieved in a convoluted way.

There is simply no existing parsing rules in CSS that would accommodate this. It would be a huge departure from all existing CSS constructs. **If** we did something to enable side-effects it would need to be a new directive. E.g. `@perform some-side-effect()`.

> Would you mind explaining why this kind of 'side effect' is discouraged?

Because side-effects create software that is more brittle and hard to reason about.

> I would also question that if you allow a null return value, why not make this implicit, though I suppose this is tied into avoiding functions created specifically for their side-effects.

Mostly it exists to prevent users from forgetting to return a value which is the most common case. Less common cases while supported are not optimized at the cost of the primary use case.

**Comment by Undistraction** [comment]
@chriseppstein Thanks for taking the time to respond. I appreciate it.

**Comment by joshuabambrick** [comment]
I disagree with the suggestion that side-effects necessarily

> create software that is more brittle and hard to reason about

I think in my case, this restriction is holding me back from making my code safer and more maintainable. I would like to implement a getter/setter wrapper for a map - the 'getting' is fine but this limitation makes the 'setting' difficult. This approach, in my case, would make my code cleaner as I could provide feedback about erroneous changes as opposed to letting any part of the my code make modifications.

I think that if we wanted to avoid functions producing side effects, sass could have been written more like a functional language to make them impossible - since has not been, I think we can take it that side effects are a feature.

Furthermore, if people are going to write bad code, they are going to write it regardless of whatever tools you give them. There are many features in sass which could be abused, but that doesn't mean that they shouldn't have been added.

**Comment by ghost** [comment]
You're trying to add object-oriented characteristics to a markup language which is strictly functional. IMO, there shouldn't be any side effects in a CSS preprocessing language; CSS itself has no side-effects, and breaking out of the shell of the well-defined behaviour of how stylesheets are read will only make your code less maintainable, imho.

**Comment by chriseppstein** [comment]
The best I could offer here is a special directive E.g. `@call doSomeSideEffect(args...)` that executes a function and probably forbids an `@return` that isn't `null`. But now we're really only quibbling about whether this is more understandable than writing `@include doSomeSideEffect(args...)`.

I'm not saying this couldn't be made more elegant, I'm saying that the amount by which the elegance increases for an uncommon use case is not worth the amount of additional syntax and learning that is required for that feature to exist.

**Comment by Snugug** [comment]
I have a couple of projects where I need users to be able to get and set settings, and I did exactly what Chris suggested. In fact, I abstracted it (https://github.com/Team-Sass/toolkit/blob/2.x.x/stylesheets/toolkit/_settings.scss) to make it easier to use.

That being said, with maps I don't think the getter/setter pattern is an edge case (lots of us are adopting it) but I find the mixin approach totally useable and so far have had 0 people complain about it as it's a pattern people have seen before in Sass (mixins at the root of a document)

**Comment by joshuabambrick** [comment]
Mixins are not necessarily a bad way to go about it, and if this doesn't become a feature, that is what I will go with. However, I do think that it is a hacky approach and obscures the purpose of the call. As far as I am concerned, and I may be wrong, the key difference between mixins and functions is that mixins output code whereas functions can return a meaningless value, `null`.

In Java, the only reason for the void return type is to indicate that side-effects are the sole purpose of the function and in sass, enforcing the null return value from an `@call` could serve a similar purpose and make the code more easy to understand.

**Comment by lolmaus** [comment]
In most modern programming languages, especially the scripted ones, there is no distinction between _functions_ (return a value without side effects) and _procedures_ (cause side effects without returning a value). Instead, there are _methods_ that do both things.

I see no reason why Sass should uphold the distinction. In fact, Sass functions _are_ side effects-capable already, so the distinction is completely artificial.

Also, while the custom mixin way is a valid workaround, it's what every Sass framework developer will find himself doing. Custom mixins will breed like rabbits, varying in implementation and size. Sass should totally provide a default and scaffolding-free way to do that.

So i strongly support that Sass should allow executing functions without an obligation to accept a value into a variable.

Sass 4.0 could probably even completely remove the distinction.

@Snugug, please consider moving your custom mixin implementation into Toolkit.

**Comment by Snugug** [comment]
@lolmaus that's literally where I'm linking to. Already there.

**Comment by lolmaus** [comment]
@Snugug, you rock.

**Comment by ghost** [comment]
I don't know why you're citing "modern" programming languages because C came out in the 80's and it didn't make a distinction between pure functions and procedures. Most programming languages don't make this distinction, which is why functional programming languages exist and are becoming more and more popular _to_ make that distinction.

CSS is designed to be without side effects, which is why selector specificity is so carefully defined. Once you start adding positional side-effects into your stylesheet whose rules are otherwise not really dictated by their order, the entire thing becomes difficult to manage.

**Comment by lolmaus** [comment]
@Undeterminant,
1. Sass is not a functional language and is never going to be. Having a single functional-like restriction and forcing numerous users to work around it is pointless.
2. CSS is all about side effects, though this fact is not relevant to the matter.
3. Sass is a _programming_ language of sorts. It uses a lot of techniques from general purpose programming languages and more techniques [are](https://github.com/sass/sass/issues/871) [demanded](https://github.com/sass/sass/issues/996). More and more sophisticated Sass libraries are created.
4. Not all side effects are bad. For example, `pull` in Ruby removes an item from an array (side effect) and returns the removed item. Introducing unwanted positional side effects is a concern of a coder using Sass. Sass should not enforce inconvenient usage just because someone might misuse it. It's like suggesting to ban kitchen knives because someone might cut his finger off.
5. Sass maps introduced a whole new style of developing with Sass. It involves storing and manipulating a lot of data. This approach could really benefit from subj. And it has nothing to do with positional side effects.
6. Sass mixins are originally meant for reusing/generating CSS output. Using them solely for executing side effects is a hack. Using it is no better than doing `$i-am-never-used: reset-grid()`, it's just a matter of which approach hurts your programmer's taste less.
7. In Ruby, you can do `some_string.upcase` which would return a new string and `some_string.upcase!` which would modify the string stored in the variable. I need the latter in every Sass project i work with, and i'm not alone (i wasn't the one to start this feature request). There _should_ be a clean way of doing that, e. g. `remove-duplicates-mod($list)` instead of `$list: remove-duplicates($list)`.
8. Sass standard library is very scanty. Libraries like sassy-maps, sassy-lists, color-schemer, toolkit, etc exist to fill the void. It is ridiculous that every library has to provide a mixin counterpart for every function that can be used to modify an object rather than return a new one.

**Comment by cimmanon** [comment]
@lolmaus

You haven't really explained why side effects are good.  I've spent the last 3 years in Haskell land and I haven't missed side-effects one bit.  I haven't really missed variables, either.

Keep in mind that not everyone who's using Sass is an experienced programmer.  Functions with side effects are more difficult for novices to understand.  You argue that it would be a minor quality of life improvement for you, but I'm not buying it.  Functions with side effects are, without a doubt, _more difficult to debug_.

Yes, writing `remove-duplicates-mod($list)` is certainly more convenient than `$list: remove-duplicates($list)`, but not by much.  At the end of the day, what are you doing with `$list`?  Surely you're not just having it sit there doing nothing.  Why assign it to a variable at all if you're just passing it off to another function/mixin/whatever?  Are you sure you aren't resorting to doing this because Sass does not offer things Functional programmers know and love like map, filter, fold, and anonymous functions/lambdas?  If your string needs to be uppercased from now until the end of time, why didn't you uppercase it when you were assigning it in the first place?

It just sounds like you're clinging to inferior programming patterns because you haven't learned that there are better, safer ways of achieving the same result.

**Comment by lolmaus** [comment]
> I've spent the last 3 years in Haskell land and I haven't missed side-effects one bit. I haven't really missed variables, either.
> ...
> It just sounds like you're clinging to inferior programming patterns because you haven't learned that there are better, safer ways of achieving the same result.

Those are just different paradigms. Functional programming is not by default better than non-functional. Yes, it has certain serious advantages, but substantial disadvantages as well, the most important of which (from my point of view) is that it doesn't match the normal programmer's way of thinking: you have to adjust the way you think to correspond to the language.

For example, the `pull` function exists in all languages that i've had the honour to work with: Ruby, JavaScript, Python, PHP. It is a very convenient and very broadly used technique, but it violates the no side effects approach.

No programmer has ever complained that functions in JavaScript or Python allow side effects.

Let's not start a holy war here. The fact is that Sass is not functional and the necessity to write `$i-am-never-used: some-func()` does not in any way prevent the user from introducing a side effect in `some-func()`.

> If your string needs to be uppercased from now until the end of time, why didn't you uppercase it when you were assigning it in the first place?

Because it came as an argument? A very common situation is that you accept raw data as an argument and you need to parse/sanitize it before using. You may need to use the processed data more than once in your function, or you may want to split a chain of operations over the raw data into multiple lines for the sake of readability (and Sass doesn't support method chaining due to the lack of a method concept), so you end up with an `$i-am-never-used` or `$argument: f($argument)`.

Another very common situation, which both @Undistraction and @Snugug mentioned, is the necessity to let the user CRUD settings stored in a map. The variable that contains the map is hidden from the user so that he can't mess it up by modifying it directly.

**Comment by lolmaus** [comment]
I've discovered that Sass now has `call()` that allows calling a function by a dynamic name.

This allows for a trivial and univeral solution:

``` sass
=do($function-name, $args...)
  $i-am-never-used: call($function-name, $args...)
```

Usage:

``` sass
+do(reset-grid)
```

The function whose name is passed still has to have a dummy return value.
