### ISSUE TITLE
Provide access to list of options for output style

### ISSUE THREAD

**Issue by imathis** [sass/sass#1350]
Right now there are four output styles, but someday there may be more, or they may change. Ideally we would be able to ask Sass which symbols it accepts as a setting for output_style.

**Comment by parkr** [comment]
Something like `Sass.output_styles` or `Sass::OUTPUT_STYLES` would be great. You could also use this to validate:

``` text
The output style 'mushed' is not a valid output style.
Valid styles: expanded, nested, compact, compressed.
```

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
