### ISSUE TITLE
Versioning scheme issue

### ISSUE THREAD

**Issue by tvollstaedt** [sass/sass#1422]
I just want to mention that your versioning scheme is not optimal. The reason for that is because commit https://github.com/sass/sass/commit/79bad1ff473cc06c66b85086403f4a1905938e37 introduced an backwards-incompatible change of your API. [zurb-foundation](https://github.com/zurb/foundation) uses `@if (index(...) == false)` extensivly, so it silently fails since this update. As written in [Semantic Versioning 2.0.0](http://semver.org/), backwards-incompatible changes are required to introduce a new major version. This may not have prevented this issue, but it's a much more obvious hint for application developers that something important has changed. Please consider switching to SemVer since it's very widespread these days and helps other developers (and you) to keep track of major and minor changes.

(refs https://github.com/zurb/foundation/issues/5636)

**Comment by chriseppstein** [comment]
They should just do `@if not index(...)`; this will work for all versions of sass because both `false` and `null` are "falsy".

**Comment by chriseppstein** [comment]
FYI, Sass doesn't follow semver at this time. We follow a deprecate/remove policy so that every minor release deprecates a backwards incompatibility for at least one release cycle before removing it.

Major versions indicate significant feature differences. E.g. 3.0 was when we introduced scss syntax and extend. 4.0 will be when we add a module system.

Sass is planning to follow semver starting with 4.0.

**Comment by tvollstaedt** [comment]
Youre right, it's definitly not sass' fault, they should know which library versions they need to use. Thanks for the clarification on your versioning scheme, sounds reasonable.
