### ISSUE TITLE
& behaves inconsistently within %extend-only selectors

### ISSUE THREAD

**Issue by maranomynet** [sass/sass#1424]
I'm trying to use `@extend` to apply BEM style class-name suffixes - like so:

``` scss
    %button {
        background: blue;
        &-text { color: white; } // BEM style
    }
    .fancyButton { @extend %button; }
```

but all I get is this:

``` css
    .fancyButton { background: blue; }
```

...while what I wanted was this:

``` css
    .fancyButton { background: blue; }
    .fancyButton-text { color: white; }
```

**Comment by lolmaus** [comment]
Tried this in 3.4.3 and i'm unable to produce a `.fancyButton-text` at all:

http://sassmeister.com/gist/a9a9a2edf2b43623a72d

Looks like the parent selector never includes the extending class.

**Comment by lolmaus** [comment]
Added mixin test to the above link. There's also something unexpected.

**Comment by maranomynet** [comment]
Yes my initial report was based on a slight misreading of console output.  Fixed now.

This issue affects normal and extend-only selectors almost equally.

**Comment by chriseppstein** [comment]
Extend operates on simple selectors (class, placeholder, id, element).

There is absolutely zero difference to Sass between:

``` scss
    %button {
        background: blue;
        &-text { color: white; } // BEM style
    }
```

and this:

``` scss
    %button { background: blue; }
    %button-text { color: white; }
```

You've created two placeholders and they have to be extended separately.

``` scss
.fancyButton {
  @extend %button;
  &-text { @extend %button-text; } 
}
```

The BEM pattern is not something that Sass intrinsically understands.

**Comment by maranomynet** [comment]
Ouch! :-/

`@extend` seems extremely kludgy and underpowered — especially compared to LESS' `:extend()`

**Comment by lolmaus** [comment]
I wish `@extend` behaved like a pattern to be applied to extending selector, like described in the top post.

Can this be considered a feature request?

PS @chriseppstein, can you please explain the [inconsistency](http://sassmeister.com/gist/a9a9a2edf2b43623a72d) between the plain and interpolated parent selector and between normal and at-root?

**Comment by chriseppstein** [comment]
@lolmaus there's a lot there. What are you referring to in particular.

**Comment by chriseppstein** [comment]
Presently, Sass's extend is applied after nesting is removed from the AST. It seems like you think that extend is operating on the Sass selectors instead of the generated CSS selectors. It's not clear to me what the ramifications would be of preserving nesting until after extends are applied.

For instance, given your example above, how should we handle `@extend %button-text` or worse, how should `@extend .fancyButton-text` work since those classes wouldn't exist until after nesting is removed. Would people expect now to be able to extend all manner of half-constructed selectors like `@extend -text` thinking that it would work like `& .text`?

**Comment by lolmaus** [comment]
> It seems like you think that extend is operating on the Sass selectors instead of the generated CSS selectors.

Yes, this is what i was expecting, and i think @maranomynet too.

> For instance, given your example above, how should we handle `@extend %button-text`

If my expectations were true and `%button { &-text {...}}` were manipulating extending selectors (e. g. `.fancyButton`) rather than generating more silent selectors, then there would be no `%button-text` silent selector defined. It would result in a warning.

> or worse, how should `@extend .fancyButton-text` work since those classes wouldn't exist until after nesting is removed. 

I didn't think of that, Chris. I never extend normal selectors because i consider it unsafe: for me it constantly results in bloated CSS and hidden side effects.

I imagine a new type of silent selectors that would work as instructions to apply on those selectors that are extending it. Example:

``` sass
~button
  background: blue

  &-text
    color: white

.fancyButton
  @extend ~button
```

``` css
.fancyButton { background: blue; }
.fancyButton-text { color: white; }
```

Alternatively, instead of a new silent selector type it could be a new directive that works only with silent selectors:

``` sass
%button
  background: blue

  &-text
    color: white

.fancyButton
  @construct %button
```

``` css
.fancyButton { background: blue; }
.fancyButton-text { color: white; }
```

The above example would feel like using a mixin, but it would not explode your CSS with duplication.

**Comment by maranomynet** [comment]
> I never extend normal selectors because i consider it unsafe: for me it constantly results in bloated CSS and hidden side effects.

Same here. Simple %extend-only selectors allow me to avoid the whole selector-merging mess.

> Instead of a new silent selector type it could be a new directive that works only with silent selectors:

I'd love for such a directive to:
- optionally work across all `@media` when an `!allmedia` flag is present.
- be able to match nested/complex selectors.
- do exact match (no sub-selector matching) by default unless an `!all` flag is present.
- stay away from complex selector-merging and only replace exact substring replacement (like LESS does with the `all` flag)

**Comment by chriseppstein** [comment]
>  I never extend normal selectors because i consider it unsafe: for me it constantly results in bloated CSS and hidden side effects.

There is _no difference_ between a class and a placeholder in terms of their behavior with extend. The difference is in how you are _using_ placeholders compared to classes. Probably because you think they are special somehow. The only difference is that there is marginally less output because the extended selector isn't output.

> The above example would feel like using a mixin, but it would not explode your CSS with duplication.

The thing is, placeholders are a kind of selector like an ID or a class. and so they have to have the same semantics as all other selectors do.

TBH, I'd rather give a different way of applying a mixin because that has the _exact_ semantics you're seeking.

> optionally work across all @media when an !allmedia flag is present.

See #1050.

> be able to match nested/complex selectors.

We've decided this is a bad idea. You should extract a placeholder to accomplish this. 

> do exact match (no sub-selector matching) by default unless an !all flag is present.

We're not going to turn extend into some kind of regex tool for manipulating selectors. The definition of extend is to style elements the same. This violates that definition.

> stay away from complex selector-merging and only replace exact substring replacement (like LESS does with the all flag)

As I said above. Extend is not a regex tool. It's a way of declaring a kind of selector matching.

The LESS team decided to appropriate the word "extend" to create a different concept. I'm sorry that you came to Sass expecting it to be the same thing, it's not. We can't control that they reused our word in a way that was not semantically appropriate. I wish they had called it `@rewrite-into` or something like that.

**Comment by lolmaus** [comment]
> TBH, I'd rather give a different way of applying a mixin because that has the exact semantics you're seeking.

Can we discuss this further?

**Comment by chriseppstein** [comment]
> Can we discuss this further?

Of course. Let's start a new issue for that.

**Comment by maranomynet** [comment]
@chriseppstein thanks for your answer.

> > optionally work across all @media when an !allmedia flag is present.
> 
> See #1050.

I was actually dreaming of something like this:

``` scss
@media screen {
    %buttonstyles { ... }
    %menustyles { ... }
}
@media screen and (min-width:700px) {
    %buttonstyles { ... }
    %menustyles { ... }
}

.mybutton { @extend %buttonstyles !allmedia; }
@media print {
    .mymenu { @extend %menustyles !allmedia; }
}
```

rendering this:

``` css
@media screen {
    .mybutton { ... }
    .mymenu { ... }
}
@media screen and (min-width:700px) {
    .mybutton { ... }
    .mymenu { ... }
}
```

...basically `!allmedia` ignoring the @media context where the `@extend` is used - hunting down the %subject-selector where ever it's found across all @media.

This would allow for very powerful, and easy to use extend libraries.

**Comment by Snugug** [comment]
@maranomynet You can essentially do that by placing your media queries inside your placeholder selectors. http://sassmeister.com/gist/be04f420bc978eb8e234

**Comment by maranomynet** [comment]
@Snugug  That's very nice! Thanks :-)

**Comment by maranomynet** [comment]
> > be able to match nested/complex selectors.
> 
> We've decided this is a bad idea.

Out of curiosity: Why is it a bad idea?

regarding the original subject of this thread, I've found a working solution to the BEM selector issue:

``` scss
%button {
    background: blue;
    &-text { color: white; } // BEM style
}
@mixin button-extend () {
    @extend %button;
    &-text { @extend %button-text; }
}

.fancyButton {
    @include button-extend();
}
```

Which I guess is totally good enough.

**Comment by nex3** [comment]
> ...basically `!allmedia` ignoring the `@media` context where the `@extend` is used - hunting down the `%subject-selector` where ever it's found across all `@media`.

We shouldn't just discard the `@media` context of the extender. That violates the semantics of `@extend` and is likely not what the user intends. It's also easy to do explicitly with `@at-root` if that's what you want.

> > > be able to match nested/complex selectors.
> > 
> > We've decided this is a bad idea.
> 
> Out of curiosity: Why is it a bad idea?

There's no way to both make it behave how it looks like it will behave syntactically and follow the underlying semantics of `@extend`. For example, if you write `.foo {@extend .bar .baz}`, what that would mean semantically is "every element matching `.foo` should be styled as though it also matches `.bar .baz`"; that is, as though it had class `baz` and one of its parents had class `bar`. This would mean it would match the rule `.baz { ... }`, which is likely not what the user expected. Moreover, it means it's almost identical to just writing `.foo {@extend .baz}`.

There's also the question of what, precisely, it would mean for one of its parents to have the class `bar`. Would it match `div.bar .baz`? How do we know whether the imaginary parent we're stipulating that it has is a div or not? We could theoretically just decide on an answer, but doing so would complicate the semantics a lot.
