### ISSUE TITLE
Add support for tracking non-stylesheet dependencies.

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#144]
A stylesheet helper like compass's `inline-image` needs to be able to add dependencies on images that are embedded so that the stylesheet will be considered out of date if the image changes. This will require changing from a mode where we parse files and look for import nodes to a mode where we cache the dependencies in the sass cache from the previous run.

**Comment by chriseppstein** [comment]
In [eyeglass](https://github.com/sass-eyeglass/eyeglass) I use `@import` to declare dependencies on assets.

Depends on #739

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional implementation features are planned for it.
