### ISSUE TITLE
Wrap / Prepend All Selectors

### ISSUE THREAD

**Issue by tomahl** [sass/sass#1459]
It would be really handy with a "wrap/prepend" all selectors feature for apps that lives inside a global website. Adding a unique prefix for each individual element isn't enough all time depending of the CSS complexity of your app.

Adding a namespace like below doesn't work because the "context" class will be generated infront of the #ns which is not the result we want. Desired output would be "#ns .context .block".

```
#ns {
    .block {
        prop: val;
        .context & {
            prop: val
        }
    }
}
```

**Comment by nex3** [comment]
If you need this sort of complex selector manipulation, I suggest you use the [selector functions](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_functions) to implement it yourself as a mixin.

**Comment by sambaker** [comment]
This feature is exactly what I need. I have App A that embeds another app, App B. App B can be stand-alone or embedded in App A. I have one App B sass file that wraps all of the App B imports in a class selector so that App A can embed a chunk of App B with that class wrapped around it.

When App B is compiled to run independently it generates:

```
    .block {
        prop: val;
        .context & {
            prop: val
        }
    }
```

When it's compiled to be embedded in App A, it generates:

```
#ns {
    .block {
        prop: val;
        .context & {
            prop: val
        }
    }
}
```

via

```
#ns {
  @import "appBstyles1.scss"
  @import "appBstyles2.scss"
}
```

But of course this breaks the ampersand operator as @tomahl mentioned.

I don't see how to allow this with the selector functions, however if I was able to add a rule saying to add a #ns wrapper to everything from App B then every other rule in appBstyles*.scss could stay as is.

**Comment by reduardo7** [comment]
See: http://stackoverflow.com/a/40160508/717267

**Comment by zheeeng** [comment]
@reduardo7 `@import` doesn't work on expand the ampersand in a ideal way.
@sambaker Did you finally get the way to scope a scss block?

**Comment by cyrilchapon** [comment]
Any update on this ?

**Comment by thedamon** [comment]
I think this is a very legitimate use case (binding all styles in an import to be more specific to a wrapping class without affecting the styles themselves) that as far as I can tell is currently impossible unless something about the new module syntax enables it by any chance? (Haven’t delved into it in depth).

If this were to be a feature it would be cool if it would place body/HTML selectors on the outside of the wrapper

It’s possible to write a postcss plugin to achieve this but no way to do in Sass. Very unfortunate and don’t really agree with closing this out of hand. it’s only complex because of sass’s own complexity (&) and that makes sass itself a more ideal place to contain the logic

**Comment by nex3** [comment]
@thedamon In the new module system, you can use the [`meta.load-css()` mixin](https://sass-lang.com/documentation/modules/meta#load-css) to include a stylesheet's CSS nested within a parent selector. This won't affect the way parent selectors in the loaded module's CSS are resolved, so it should work how you want it to.

**Comment by thedamon** [comment]
Yaaaaas

That's awesome!

Apparently the codebase in question has some node-sass features that stop it from compiling in dart-sass proper, but it's great to hear this is possible now 🙂
