### ISSUE TITLE
SASS 3.4.5 --watch unresponsive after first invocation (Mac OS X)

### ISSUE THREAD

**Issue by geoffdavis92** [sass/sass#1469]
This has just recently been happening to me, and I have not changed anything regarding the Gemfiles/ruby files. (I can't seem to find any regarding SASS)

I am using `--watch [input].scss`, and it will write to `[output].css` and `[output].css.map`. After this first file save, nothing will happen when I make changes to the input file.

**Comment by nex3** [comment]
Please provide more details about your setup. What version of Ruby are you using? What OS version? What other gems do you have installed—in particular, what version of `listen` and `rb-fsevents`, if any? What's the contents of the SCSS file you're watching?

**Comment by eelke** [comment]
I have the same issue, downgraded to 3.4.0 as was suggested here: http://stackoverflow.com/a/25641818/588163
However this did not fix it for me. The problem started after migrating to Yosemite, so it seems something changed in the way file changes are detected. Not sure if it is a compass or sass problem.

---

EDIT: It turned out something had gone haywire with my filesystem, and I found the solution to my specific problem on the LiveReload website: http://feedback.livereload.com/knowledgebase/articles/86239

**Comment by walt** [comment]
I have this issue as well.
- OS X 10.10.2
- ruby 2.0.0p481
- sass 3.4.11
- rb-fsevent 0.9.4

Normally I don't have listen installed, but if I do, running sass with listen generates a ton of "*\* ERROR: directory is already being watched! **" messages on directories which I haven't asked sass to watch.

**Comment by nex3** [comment]
@walt What version of listen do you have installed when you see those errors? What's your directory structure? What directories are you seeing the errors for?

**Comment by isoph** [comment]
Thans nex3, here’s what I can answer to your questions on #1625:

> Do you have any symlinks or other references from the directory in which you're running Sass to the directories that listen is complaining about? 

Not that I’m aware of.

> In what directory are you running Sass?

It my users “Sites” directory that I tried to set up to  work as a webserver as it did in os X Lion, following this tutorial: http://coolestguidesontheplanet.com/get-apache-mysql-php-phpmyadmin-working-osx-10-9-mavericks/

> What's the directory structure of your project?

It used to be both .scss and .css files in the same folder, with a command stating only the folder to be watched. I tried to separate input and output folders because I thought maybe the sass command syntax had changed, so now I have a “sass” folder as input and a “css” folder as output. 

> Of /Users/input and /Users/output?

/Users/input contains 2 partials (reset and variables), and a folder with a “timestamp” name (20150208) including more partials and the main .scss file.
In /Users/output, sass has generated a “timestamp” name folder with the compiled .css and .css.map files

**Comment by walt** [comment]
> What version of listen do you have installed when you see those errors?

listen (2.8.5)

> What's your directory structure?

I have multiple site directories within `~/Sites`. So, for example, a project might have a `~/Sites/[project]/sass` source and a `~/Sites/[project]/html/css` destination.

> What directories are you seeing the errors for?

I usually cancel it pretty quickly once it starts dumping errors but most of the ones I've seen are for directories within `~/Library`.

**One more thing:** You asked @isoph, "In what directory are you running Sass?" I usually run it in my home directory but when I tried running it in `~/Sites` it seems to work perfectly with or without listen installed. So I suspect that's going to be my workaround for the time being.

Thank you for your help with this.

**Comment by nex3** [comment]
Is it possible that this is the same as #1631? Does changing the casing of your directory names help? What about passing `--poll`?

@walt, @isoph can you do like an ASCII diagram of your directory structure?

@walt When you were running in your home directory, were you pointing the executable at `~/Sites`?

**Comment by adispezio** [comment]
I think I hit a problem today that might be related.

Sass apps watching my filesystem can't seem to recognize changes. Doesn't work for watching in Compass (command line), CodeKit, LiveReload, and Koala. Using the polling method of Compass works (--poll) but kills CPU.

Also seeing other apps no longer updating their views of the filesystem. Sublime Text's folder view no longer updates. Manual refreshing of the folder works but auto-updating is unresponsive.

I haven't updated rb-fsevent recently (to my knowledge), but I did recently upgrade osx to 10.10.2, might it be an issue with the fsevent api?

**Comment by nex3** [comment]
That sounds very plausible. It sucks, because there may be nothing we can do about it.

**Comment by adispezio** [comment]
Update: Fresh install of OSX cleaned up my problems. Sass working as expected.

**Comment by WillsB3** [comment]
I'm also having this issue and getting warnings such as:

`** ERROR: directory is already being watched! **" presumably from listen`

I'm trying to watch one file, like this:

`$ sass --watch static/css/styles.scss:static/css/styles.css`

I'm running this command from the root of my project. Platform is Yosemite 10.10.2 with SASS (3.4.13).

I tried updating and uninstalling/reinstalling SASS but the problem persists. I don't understand why if I'm expclitly watching one file I get warnings about completely unrelated files and folders (that aren't in the `static` folder at all) being watched.

Any ideas?

**Comment by nex3** [comment]
@WillsB3

> I don't understand why if I'm expclitly watching one file I get warnings about completely unrelated files and folders (that aren't in the `static` folder at all) being watched.

There are two reasons you might get more stuff watched than you expect. First, OS X simply doesn't support watching an individual file, so we have to watch the directory containing that file. Second, Sass used to include the current working directory on its load path. While it doesn't do so anymore, it still watches the working directory for updates in order to make `--watch` work nicely with stylesheets within the working directory that import relative to themselves. See #1393 where not doing this caused people problems.

Now, to address the errors you're seeing. We deduplicate the paths we watch to avoid sending duplicates to `listen`, so I'm not sure why this error is popping up. I'm going to need your help to figure it out. First of all, which version of `listen` are you using? Does your working directory recursively contain any symlinks? If you `cd` further down into `static/css`, do the errors eventually stop happening? If so, when?

**Comment by frickenate** [comment]
It is absolutely ridiculous to not provide a way to switch off the addition of the current working directory. Our project has 20,000 files, but we only need to watch for sass files in several specific directories beneath the project root. We are also running on a cifs mount within VirtualBox, which means we are depending on the polling mechanism, which is very slow to poll the entire project.

We absolutely require a way to only crawl the exact directories we know contain the sass files. This "current working directory" hack makes it take up to a minute to detect the addition/modification of a single file, as the polling mechanism is crawling over 20,000 files instead of 100.

The only workaround currently would be to run a separate sass --watch process for each individual directory from within that directory. Why isn't there a new command-line flag to override this unwarranted behaviour? You keep switching back and forth between the options based on user complaints, but instead all you should be doing is providing a sass argument do we can decide the behaviour for ourselves.

**Comment by nex3** [comment]
@frickenate I'm not sure why you posted that comment in this issue, but I'll try to address it as best I can. The command-line executable is never going to have all the options that everyone might conceivably want; adding options has a real cost in terms of complexity and comprehensibility, so we don't do it very often. The good news is that the Ruby API is available and pretty easy-to-use, so people like you with very specific needs with respect to what gets watched can create their own watcher process that does exactly that.

If that's not satisfying, I encourage you to pitch in and help us watch files based on what's actually imported. Once that's in place, there'll no longer be any need to watch the working directory.
