### ISSUE TITLE
@extend will generate compound selectors inside :not

### ISSUE THREAD

**Issue by guycook** [sass/sass#1505]
Related to #1380 but slightly different: when you `@extend` a simple selector (that's been used in a :not somewhere) inside a compound selector, sass will generate a new :not with that compound selector appended. It seems that this will be supported in [CSS4](http://dev.w3.org/csswg/selectors4/#negation) but for now isn't working in any browsers.

[This Codepen](http://codepen.io/anon/pen/degmw) gives a minimal example of the problem - line 9 expands to

``` css
a > span:not(.red):not(input .error) {
```

which is not valid.

**Comment by nex3** [comment]
This is a tough case, since on the one hand we don't want to break a previously-functional selector on browsers that don't support the new `:not()` syntax, but on the other hand there's no other valid way to compile the output. Given the SCSS input from your Codepen, the following HTML definitely shouldn't have green text:

``` html
<input>
  <a>
    <span class="error">Text</span>
  </a>
</input>
```

and a compilation that simply omits the non-compatible `:not()` will produce incompatible results here.

I think you're right that that's a better compromise than breaking existing selectors. At some point, when browsers start supporting this, we'll probably need to have a way of configuring the output here.
