### ISSUE TITLE
Extrapolating variable next to unicode string prints '@charset "UTF-8";' in Sass 3.4 output.

### ISSUE THREAD

**Issue by micahgodbolt** [sass/sass#1540]
I know this is a crazy edge case, but this bug showed up in the Sass version of bootstrap, so it should be affecting a good number of people when they move to 3.4. 

It works fine in 3.3, but outputs "@charset "UTF-8";" into the stylesheet in 3.4. This string then breaks our concatenation. 

http://sassmeister.com/gist/17e523cdafe6f107289d
![screenshot 2014-11-24 08 43 49](https://cloud.githubusercontent.com/assets/1434956/5168695/0661b1a4-73b6-11e4-81cb-4a5f77111b70.png)

**Comment by nex3** [comment]
This is intentional. As of 3.4, Sass parses strings according to the CSS spec, which means it interprets Unicode escapes as equivalent to literal Unicode characters. It then always adds a `@charset` declaration if there are any non-ASCII characters in the stylesheet. #1395 is tracking the addition of a flag to force Sass to emit ASCII, but regardless of when that happens I suggest you encourage the other tools on your tool chain (such as concatenation) to properly parse the CSS and handle `@charset` declarations.
