### ISSUE TITLE
Better handling of the `&` selector

### ISSUE THREAD

**Issue by tjbenton** [sass/sass#1556]
I would like to see better handling and consistency for the `&` selector.

``` scss
.validate{
  &-valid{
    // `.validate-valid`
  }

  #{&}-valid{
    // result `.validate .validate-valid`
  }

  #{&-valid}{
   // result `.validate .validate -valid`
   // why is there a space between `.validate -valid`
  }

  // &&-valid{
  //  // results in an error
  //  // why doesn't this return `.validate.validate-valid`
  // }

  &#{&-valid}{
   // result `.validate.validate -valid`
   // why is there a space between `.validate -valid`
  }

  #{&}#{&}-valid{
    // result `.validate .validate.validate-valid`
  }

  & #{&}-valid{
    // result `.validate .validate-valid`
  }

  & &-valid{
    // result `.validate .validate-valid`
    // Why does this work but `&&-valid` doesn't work
  }

  &#{&}-valid{
    // result `.validate.validate-valid`
    // Why does this work but `&&-valid` doesn't work
  }

  #{selector-append(&, & + "-valid")}{
    // result `.validate .validate.validate-valid`
  }

  @at-root #{selector-append(&, & + "-valid")}{
    // result `.validate.validate-valid`
  }

  @at-root #{&}#{&}-valid{
   // result `.validate.validate-valid`
  }
}
```

While `&#{&}-valid` works for getting `.validate.validate-invalid` it wasn't intuitive for me to write it like that. My first instinct was to write it like `&&-valid` but it resulted in an error.

It's not a major issue by any means but I figured I would bring it to your attention because I can see other people running into this problem.

**Comment by nex3** [comment]
> ``` scss
> .validate {
>   #{&}-valid{
>     // result `.validate .validate-valid`
>   }
> }
> ```

When you interpolate `&`, as with any interpolation, it just converts it to a string and includes that string value. In this case, `&` is `((".validate"))`, so the selector becomes `.validate-valid` nested underneath `.validate`. When nesting is resolved this becomes `.validate .validate-valid`.

> ``` scss
> .validate {
>   #{&-valid}{
>    // result `.validate .validate -valid`
>    // why is there a space between `.validate -valid`
>   }
> }
> ```

Sass parses `&-valid` in a SassScript context as equivalent to `& -valid`, since `-valid` is a CSS identifier and no operator between two values means that those values are considered to be in a list.

In general, you can't write bare selectors in a SassScript context. SassScript is based on CSS values, not selectors.

> ``` scss
> .validate {
>   // &&-valid{
>   //  // results in an error
>   //  // why doesn't this return `.validate.validate-valid`
>   // }
> }
> ```

Because `&` could be replaced by any selector, it has the same syntactic requirement as the most restrictive simple selectors: it must appear at the beginning of the compound selector. You can't have two in a row because that means one of them isn't at the beginning.

> ``` scss
> .validate {
>   & &-valid{
>     // result `.validate .validate-valid`
>     // Why does this work but `&&-valid` doesn't work
>   }
> }
> ```

Because now both `&`s are at the beginning of separate compound selectors.

> ``` scss
> .validate {
>   &#{&}-valid{
>     // result `.validate.validate-valid`
>     // Why does this work but `&&-valid` doesn't work
>   }
> }
> ```

Because interpolation sidesteps the usual parsing rules. Interpolation treats everything as a plain old string, so you can include interpolation basically wherever you want.

The most robust way to write this would be `@at-root #{selector-append(&, &, "-valid")}`. In general, if you're using `&` within interpolation, you should be using it with both `@at-root` and selector functions.
