### ISSUE TITLE
Windows cache problem

### ISSUE THREAD

**Issue by davidtme** [sass/sass#1563]
I am using sass (with compass) and randomly the cache seem to go a bit wrong resulting:

```
No such file or directory @ rb_sysopen - C:/Users/*removed*/AppData/Local/Temp/.sass-cache/75fcaf1b4852ceb732871195e41567cc2a7d8997/C%058/Users/*removed*/lib/ruby/gems/2.1.0/gems/compass-core-1.0.1/stylesheets/compass/typography/lists/_horizontal-list.scssc20141218-8128-1ix7b9n
```

**Comment by nex3** [comment]
Can you post the full stack trace?

**Comment by chriseppstein** [comment]
There are problems with the Sass cache file naming on windows. As seen here: https://github.com/Compass/compass/issues/1791. @nex3 I consider this a Sass bug even though it's mostly been compass users bumping into it. Though, I'm not sure what the fix should be. Maybe on windows we should mangle the cache file names more?

**Comment by chriseppstein** [comment]
To be clear: the full path of the sass cache file names needs to be less than 255 characters on windows. That is what is triggering this. My assumption is that the user name is at least 9 characters longer than `*removed*` and that this full path is actually >255 instead of being 237 characters long.

**Comment by davidtme** [comment]
Thanks for the info @chriseppstein The _removed_ is David so the paths is C:/Users/David/AppData/Local/Temp...

**Comment by thany** [comment]
@chriseppstein This limitation has actually been removed some 15 years ago in Windows 2000. Paths can be 65535 characters long (or bytes, not sure), when using the "new" APIs.

**Comment by am11** [comment]
@thany, that is NTFS feature. The `260` characters limitation persists in Windows till date. Win32API imposes extra constraints over what NTFS capabilities. See docs: http://msdn.microsoft.com/en-us/library/aa365247.aspx:

> ##### Maximum Path Length Limitation
> 
> In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters. 

Note the exceptions being that `//?/` prefix thingy which is not convenient in _most_ of the cases, because then everything associated would need to support utf-16 paths. Such addresses bypass win32 and directly handled by FileSystem (which does not come without side-effects either). More in these (quasi-official) comments: https://github.com/Microsoft/msbuild/issues/53#issuecomment-91359834. 

NPM version of this problem: https://github.com/npm/npm/issues/3697. 
Moreover, see [this feedback](https://social.technet.microsoft.com/Forums/en-US/e84bb703-27df-4966-bdf1-2b5760c71a1f/filesystem-path-too-long?forum=WinPreview2014Feedback) for upcoming Windows 10.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation.
