### ISSUE TITLE
Nested shadow DOM attribute-selectors not compiling

### ISSUE THREAD

**Issue by LQkkeN** [sass/sass#1587]
This example will not compile:

``` sass
:host {
    ...
    &([attribute="false"]) {
        ...
    }
}
```

I'm essentially selecting based on an attribute on the host element of a shadow DOM scope.
Perhaps I'm doing it wrong?

I would expect it to be compiled to this:

``` sass
:host {
    ...
    :host([attribute="false"]) {
        ...
    }
}
```

**Comment by chriseppstein** [comment]
The `&` is not a string replacement. It doesn't support mutating the same selector component -- it only allows you to add new selector components to an existing selector. Because of this, you can always copy and paste some selector involving `&` and it will work in the new context.

So you'll need to write this like:

``` scss
:host {
    ...
}
:host([attribute="false"]) {
    ...
}
```

**Comment by LQkkeN** [comment]
Fair enough.
