### ISSUE TITLE
Add special-case sourcemap logic for identifying the source of individual elements of a list literal in a property value

### ISSUE THREAD

**Issue by prashanthseshadri** [sass/sass#1589]
Hi, 

This is a follow up on the question on source-map nodeJS library - https://github.com/mozilla/source-map/issues/153

The source map option does not seem to embed information about expressions/concatenation of variables and we lose those details while querying for a particular SCSS variable. 

Example sourcemap visualization of what i am actually referring to: http://tinyurl.com/nqchly2

In this case, is there any reason for "$padding $padding" and "2*$padding" not getting mapped to initial variable $padding?

Thanks

**Comment by prashanthseshadri** [comment]
And this is one more example : http://tinyurl.com/kyhnfm4 (where mixins actually work out of the box but the concatenation use case does not).
Is it because of the dynamicity in column lengths based on variable content / expression evaluation we don't have this support? Would like to know the reason for not having this (even for concatenation).

**Comment by tallandroid** [comment]
Subscribed. 
I am facing similar issues when querying expressions.

**Comment by prashanthseshadri** [comment]
Can we have update on this?

**Comment by nex3** [comment]
It's very difficult to track source range information through operations. Take the `2*$padding` example: there, you're taking two values, one of which (`$padding`, whose value is `10px`) was defined on line 1 and one (`2`) on line 5. Where is the "source" of the resulting value, `20px`? Well, conceptually it has two sources, but we can't represent that. The best we can do is to say that its source is where the operation that combined the values took place.

It gets even trickier. Right now, every SassScript value has a source range associated with it, but this is quite expensive. All those extra bytes add up when you've got a big stylesheet to compile. We'd like to remove that information and just store it on the variables during compile-time, but that makes the logic of tracking sources through an information even more difficult.

The `$padding $padding` example is similar, in that creating a list is essentially an operation that combines two values into a third. However, we may be able to add some special-casing for that, since it's so common. I'll leave this issue open to track that.

**Comment by prashanthseshadri** [comment]
Another example is usage of image URL in url(...) in which case also we might have to need information about.

**Comment by prashanthseshadri** [comment]
Any update on this?

**Comment by nex3** [comment]
No.

**Comment by nex3** [comment]
Upon consideration, I don't think this is worth doing. I don't want to add source metadata to Sass values—it should only be tracked based on the actual source position, and possibly by where variables were assigned.
