### ISSUE TITLE
currentColor doesn't work with color functions

### ISSUE THREAD

**Issue by una** [sass/sass#1590]
Yes, I know there are work-arounds, but it would be nice if the CSS variable currentColor was recognized and able to be used with functions such as mix(), lighten(), darken(), etc.

Sassmeister gist:
http://sassmeister.com/gist/93cbc2e47dde46a3eefe

**Comment by Snugug** [comment]
The problem I see with this is the definition of `currentColor` specifically describes it as the following:

> "The computed value of the ‘currentColor’ keyword is the computed value of the ‘color’ property (http://www.w3.org/TR/css3-color/#currentcolor).

This would mean that Sass would need to know your DOM structure _per page_ and what your CSS looked like at run-time.

**Comment by una** [comment]
Is there any kind of Sass equivalent? I feel like it would be nice in a few situations. Why can't Sass know the final computer color of the property (disregarding inline styling)?

**Comment by Snugug** [comment]
Because the final computed color can change at run-time based on a large number of things, from nesting to multiple classes to inline styles and can change on a per-page basis based on all of those things.

In #1582 @chriseppstein is proposing a way to get a data structure of the current CSS that would be placed using `@content` that may work with some custom helpers around it.

**Comment by KittyGiraudel** [comment]
> Why can't Sass know the final computer color of the property (disregarding inline styling)?

On top of what Sam already said, that would probably be extremely costly for Sass to try figuring all this stuff only for `currentcolor`.

As odd as it may sound, `currentcolor` is not a color, the same way `auto` is not a length. It is a very specific keyword from which the value can only be fully computed at run-time.

**Comment by una** [comment]
Ok that makes sense. Thanks!

**Comment by chriseppstein** [comment]
Here's another example of why Sass can't know what currentColor is:

``` css
ul { color: red; }
ol { color: blue; }
li { border: 2px solid currentcolor; }
```

Now consider this document:

``` html
<ul> <li> Lorem Ipsum </li> </ul>
<ol> <li> Lorem Ipsum </li> </ol>
```

In the first list, the list will have a red border and in the second list, it will be blue. There is no way for sass to precompute the value of this without knowing what the current color is without knowing what the document is, and furthermore, since it's a runtime setting it can represent more than a single value.

**Comment by chriseppstein** [comment]
And this is why we need sass color expressions in CSS itself (which, along with css custom properites makes for significant win)

**Comment by una** [comment]
Makes sense. Thanks for the explanations @chriseppstein & @HugoGiraudel
