### ISSUE TITLE
Ruby Signature declarations can be friendlier.

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1620]
In libsass, custom functions are registered with a Sass function signature. This is so much better than the API we provide in ruby, I think we should copy it.

**Comment by HamptonMakes** [comment]
@chriseppstein want to give an example of how this might look in Ruby Sass, so that people can maybe try and do it?

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
