### ISSUE TITLE
Support specifying custom variables when calling sass

### ISSUE THREAD

**Issue by MetaMemoryT** [sass/sass#1628]
like has been merged into less: https://github.com/less/less.js/pull/1655

**Comment by nex3** [comment]
Currently it's pretty straightforward to do this by defining an extension function and feeding it with values via the [`:custom` option](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#custom-option). For example, you could imagine `my-var("varname")` accessing `options[:custom]["varname"]`. This is admittedly less direct than setting variables, but on the other hand it does make it more explicit that these values are coming from somewhere external: users are more used to functions popping up out of nowhere than variables.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
