### ISSUE TITLE
@extend creating two rules with different logic

### ISSUE THREAD

**Issue by dtipson** [sass/sass#1636]
Apologies if I'm just ignorant of how this is supposed to work, or if this is bad syntax, but seems very strange that anything like this would output two different rules with conflicting idea of how @extend-ing something that uses & should work. Tested on 3.4.11
.scss:

```
%none{
    .bodyclass & {
        display:none;
    }
}
header .logo{
    @extend %none;
}
```

output:
_.bodyclass header .logo, header .bodyclass .logo { display:none; }_

That is, the first rule generated interprets the .bodyclass & as referencing the top parent, while the second interprets it as referencing the immediate parent.  My expectation was that one or the other would be the "correct" interpretation of the syntax, rather than it generating both.

**Comment by lolmaus** [comment]
But Sass is unable to telepathically guess which of the two you expect, so it generates both variants to guarantee that your expectation is met.

**Comment by dtipson** [comment]
I didn't use "expect" in that context or tone, apologies.  My confusion was just why it's compensating for the original ambiguity at all instead of considering only one of them correct, and forcing a user to be more specific if they wanted a different result.  If that way of resolving ambiguity is expected default behavior (for whatever reason) then it's not a bug.

**Comment by davidkpiano** [comment]
Here's how `@extend` works in this context - it's based on combinatorial constraints, not on ambiguity, I promise.
1. `header .logo` provides the constraint "`header` is a **general ancestor** of `.logo`," which is a pretty liberal constraint - `header` can be the parent, grandparent, great-grandparent, etc. of `.logo`.
2. `.bodyClass %none` provides a similar constraint - it is a **general ancestor** of the _target simple/compound selector_. In this case, that simple/compound selector is `.logo`.
3. `header .logo { @extend %none; }` combines these two constraints, and states that `.bodyClass` _and_ `header` are **both** general ancestors of the target simple/compound selector, which is `.logo`.

This liberal constraint means that `header` can be a parent ancestor while `.bodyClass` can be a grandparent ancestor, or vice versa (much less any other of the infinite combinations of ancestral relationships). In order to **satisfy both constraints**, both possibilities are output: `.bodyClass` as a greater ancestor than `header`, and `header` as a greater ancestor than `.bodyClass`.

Try not to use the general ancestor combinator (space) too often unless your markup truly requires this ambiguity.

**Comment by nex3** [comment]
@davidkpiano explained this well.
