### ISSUE TITLE
SourceMap: Require sourceRoot of source-map v3

### ISSUE THREAD

**Issue by am11** [sass/sass#1660]
Please include `sourceRoot` in source-map, so user can set it in options and expect it to get reflected in the emitted `.map` as is.

From Source-Map [V3 docs](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pli=1#) (under section "Proposed Format"):

> 4 "sourceRoot": "",
> ...
> ...
> Line 4: An optional source root, useful for relocating source files on a server or removing repeated values in the “sources” entry.  This value is prepended to the individual entries in the “source” field.

and then:

> **Resolving Sources**
> If the sources are not absolute URLs after prepending of the “sourceRoot”, the sources are resolved relative to the SourceMap (like resolving script src in a html document).

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
