### ISSUE TITLE
sass slow even with up-to-date cache

### ISSUE THREAD

**Issue by frankh** [sass/sass#1680]
I have a sass file that takes about 8seconds to compile. I expected that when deleting the compiled file and re-compiling it should be much faster (because of the up-to-date cache), however I find it barely cuts the time by 25%

Shouldn't it effectively be instant? As I understand it sass is essentially a pure function (outputs depend only on inputs), so shouldn't a warm cache give near-instant results?

**Comment by Panya** [comment]
As I know Sass caches only AST after parsing, so it needs to evaluate that AST and generate the CSS output even if cache is there. Also Sass spends bigger amount of time in the evaluation phase (scope lookups, function/mixin calls, loops, maps, ...). So cache doesn't help much if you heavily use loops/mixins/maps in your code.

**Comment by nex3** [comment]
It depends what granularity you cache at. Sure, we could just save the entire CSS output and print it out again if nothing changed, but why is the user even running the compiler again at that point? And why aren't they just using `--update`?

We can't do anything like cache on a file-by-file basis, because within a Sass compile an import is anything but pure. Every import could modify the global state, both in terms of adding styles and defining variables and functions. Also, external libraries like Compass may define functions that are themselves impure, being based on external factors like the state of the filesystem.
