### ISSUE TITLE
Evaluation of nested @mixins within a @content block

### ISSUE THREAD

**Issue by Brunni132** [sass/sass#1683]
Hi everybody,
Recently I've been debugging a stylesheet written for a former version, which showed issues with the latest version of SASS. The testcase can be rounded down to this:

```
@mixin smaller {
  @media screen and (max-width: 500px) {
    @content;
  }
}

@mixin example {
  div {
    height: $value;
  }
}

$value: 12px;
@include example;

@include smaller {
  $value: 24px;
  @include example;
}
```

Basically, my little (twisted?) mind would expect sass to output:

```
div {
  height: 12px; }

@media screen and (max-width: 500px) {
  div {
    height: 24px; } }
```

While it does actually output 12px for the div inside of @media. It seems like the @include statement is "executed" right when being expanded (at the evaluation of the @content, or by passing it as a parameter). The expected result can be obtained by moving the assignment outside of the content block, as shown below.

```
@mixin smaller {
  @media screen and (max-width: 500px) {
    @content;
  }
}

@mixin example {
  div {
    height: $value;
  }
}

$value: 12px;
@include example;

$value: 24px;
@include smaller {
  @include example;
}
```

Outputting 24px for the @media-nested div. To me it looks like a bug, especially since it looks like this behaviour hasn't always been the standard. And this behaviour is only to be shown when expanded from a @content block (else it works as expected). What do you think?

**Comment by cimmanon** [comment]
My expectation is that this should throw an error (undefined variable `$value`).

As of Sass 3.4, scope matters.  Every time you open curly braces, you're creating a new scope.  You can't modify a variable from an "outer" scope from within an "inner" scope unless you use the `!global` flag.

``` scss
$value: 12px;
@include example;

@include smaller {
  $value: 24px !global;
  @include example;
}
```

**Comment by nex3** [comment]
@cimmanon You're right about this being because of scope, but wrong that it should cause an error. `$value` is defined at the top level, so every use of `$value` that runs after that definition will at least refer to the global variable.

@Brunni132 Let me walk you through what's happening here. First, before you include anything, Sass creates a global `$value` variable. Then you include `example`, which refers to this global `$value` variable. Then you include `smaller`, in which Sass runs `@content`, which points to the block passed to `smaller`. Within that block, it runs `$value: 24px`. This is where your expectations break down.

In Sass 3.4, this is a _local variable declaration_. What this means is, because the variable declaration is in a scope (designated by `{` and `}`), it doesn't refer to the same variable as the top-level `$value`. This is important: it means that it's possible to use variable names freely within mixins, functions, and nested selectors without having to worry about whether those names happen to be defined globally in some vastly separate Sass file. But it also means that this variable assignment doesn't do anything. It's only relevant within the `{` and the `}`; it's not even visible to `example`.

If you want to pass values into a mixin, though, there's a built-in way to do exactly that: parameters. You could rewrite your example like this:

``` scss
@mixin smaller {
  @media screen and (max-width: 500px) {
    @content;
  }
}

@mixin example($value) {
  div {
    height: $value;
  }
}

@include example(12px);

@include smaller {
  @include example(24px);
}
```

and never have to worry about variable scoping at all.
