### ISSUE TITLE
sass and sass-convert output mixed-precision numbers

### ISSUE THREAD

**Issue by srawlins** [sass/sass#1693]
I don't know if I should expect 2.00px to be unchanged or changed to 2px, but the result should be consistent:

``` bash
$ echo 'a { b: 2.00px; c: 2.00px }' > x.scss
$ sass x.scss
a {
  b: 2.00px;
  c: 2px; }
$ sass-convert x.scss 
a
  b: 2.00px
  c: 2px
$ sass-convert --to scss x.scss 
a {
  b: 2.00px;
  c: 2px;
}
```

**Comment by nex3** [comment]
This is caused by a shortcut Sass takes wherein it doesn't parse properties that it can easily prove are completely static. `b` triggers this, and so comes through exactly as written; `c` does not, since it doesn't have a trailing semicolon, so it's parsed and re-emitted which causes the format to change.
