### ISSUE TITLE
Checking/Compiling in Development: Only Non-AJAX HTML Requests

### ISSUE THREAD

**Issue by yfeldblum** [sass/sass#171]
The Rack middleware should only check/compile the stylesheet sources when the request is a non-AJAX HTML request.

If the application is AJAX/API-heavy, that should save a good chunk of time per-request (except the non-AJAX HTML requests) in development.

**Comment by nex3** [comment]
The Rack middleware already avoids recompiling if none of the stylesheets need to be updated.

**Comment by yfeldblum** [comment]
Sorry, I knew that and I should have been clearer about what I meant to say.

The Rack middleware currently checks the last-modified times of each of the stylesheets and of each of the stylesheets' dependencies, sub-dependencies, etc.

The Rack middleware should only **check** whether the stylesheet sources need to be recompiled, let alone recompile them, when the request is a non-AJAX HTML request.

I've updated the actual issue and its title to reflect that.

**Comment by nex3** [comment]
Ah, that seems reasonable. If you whip up a patch against master, I'll merge it in.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
