### ISSUE TITLE
CSS with (min-width: 0\0) media query browser hack causes parse error

### ISSUE THREAD

**Issue by cvrebert** [sass/sass#1726]
The hack in question: http://browserhacks.com/#hack-a60b03e301a67f76a5a22221c739dc64

Example:

``` css
/* one.css */
@media screen and (min-width:0\0) {
    .bar {
        width: 12px;
    }
}
```

```
$ sass -v
Sass 3.4.13 (Selective Steve)
$ sass one.css 
Error: Invalid CSS after "...min-width:0\0) ": expected media query list, was "{"
        on line 1 of one.css
  Use --trace for backtrace.
```

By comparison, libsass parses this just fine, although it adds an extra space in the output; see https://github.com/sass/libsass/issues/1219

**Comment by nex3** [comment]
This [works for me](http://sassmeister.com/gist/f88a4f23c244796c27bd).

**Comment by cvrebert** [comment]
@nex3 Doesn't your example use a `.scss` file, whereas mine uses a `.css` file?

**Comment by nex3** [comment]
The `sass` executable only supports `.scss` and `.sass` files; if you pass it a file without one of those extensions, it will default to `.sass`. The error you're seeing is because what you're writing is invalid in the indented syntax.

If you explicitly pass `--scss`, it will parse the file as SCSS which is CSS-compatible.
