### ISSUE TITLE
Lighten function gives weird results

### ISSUE THREAD

**Issue by skateman** [sass/sass#1732]
I'm working on a SASS [port](https://github.com/patternfly/patternfly-sass) of a LESS-based [project](https://github.com/patternfly/patternfly) and I'm having an [issue](https://github.com/patternfly/patternfly-sass/issues/28) when trying to use the `lighten()` function.

``` sass
body { bacgkround-color: lighten(#030303, 10%); }
```

The snippet above is both compatible with LESS and SASS syntax, but they produce different results:

``` bash
$ sass --precision 8 -t expanded test.scss 
body {
  bacgkround-color: #1c1c1c;
}

$ lessc test.less
body {
  bacgkround-color: #1d1d1d;
}
```

`#030303` is in HSV `(0%, 0%, 1.2%)` and if I want to lighten it by 10%, it becomes `(0%, 0%, 11.2%)`, which is `#1d1d1d` in RGB. From this I could conclude only that the SASS implementation is somehow wrong.

**Comment by awood** [comment]
Adding 

```
assert_equal("#1d1d1d", evaluate("lighten(#030303, 10%)"))
```

in `tests/sass/functions_test.rb`'s `test_lighten` will demonstrate the failure.

After doing some exploring, the issue looks like it is with addition to float values.  For #030303 the HSL is 0, 0, 3.0/255.0 \* 100

```
[31] pry(#<Sass::Script::Value::Color>)> var_R = 3.0/255.0
=> 0.011764705882352941
[32] pry(#<Sass::Script::Value::Color>)> var_R * 100
=> 1.1764705882352942
```

Sass then adds 10 to the lightness value.

```
[33] pry(#<Sass::Script::Value::Color>)> (var_R * 100) + 10
=> 11.176470588235293
```

And when `hsl_to_rgb!` gets called, lightness is then divided by 100.0

```
[34] pry(#<Sass::Script::Value::Color>)> ((var_R * 100) + 10)/100.0
=> 0.11176470588235293
```

For what it's worth, in LESS, the [RGB to HSL function](https://github.com/less/less.js/blob/master/lib/less/tree/color.js#L109) doesn't multiple by 100 at the end of the conversion and [instead divide the lighten percentage by 100](https://github.com/less/less.js/blob/master/lib/less/functions/color.js#L173) in order to convert it from percentile points to a float.  This technique yields a different answer in Ruby.

```
[34] pry(#<Sass::Script::Value::Color>)> ((var_R * 100) + 10)/100.0
=> 0.11176470588235293
[35] pry(#<Sass::Script::Value::Color>)> ((var_R) + (10/100.0))
=> 0.11176470588235295
```

The `rgb_to_hsl` method mentions that it takes its algorithm from the [HSL_and_HSV](http://en.wikipedia.org/wiki/HSL_and_HSV#Conversion_from_RGB_to_HSL_or_HSV) Wikipedia page, but it isn't strictly compliant as the Wikipedia page specifies that lightness is between 0 and 1.

```
Given an HSL color with hue H ∈ [0°, 360°), saturation SHSL ∈ [0, 1], and lightness L ∈ [0, 1], we can use the same strategy.
```

**Comment by awood** [comment]
Would you accept a PR that avoids the "multiple by 100 then divide by 100" pattern that is currently being used?
