### ISSUE TITLE
Emit transparent colors as rgba(0, 0, 0, 0)

### ISSUE THREAD

**Issue by bazzel** [sass/sass#1782]
When using `rgba(0, 0, 0, 0)` or `hsla(0, 0, 0, 0)` in SCSS, the corresponding CSS shows `transparent`.

Apparently IE8 interprets `rgba(0, 0, 0, 0)` different from `transparent`. We needed this to fix a hover issue (see also http://stackoverflow.com/questions/3998917/ie8-div-hover-only-works-when-background-color-is-set-very-strange-why).

What to expect when defining `rgba(0, 0, 0, 0)` in SCSS and how can you force to compile to `rgba(0, 0, 0, 0)`?

**Comment by whaaaley** [comment]
This is intensional. See #754 and #363

For a work around see this https://github.com/sass/sass/issues/363#issuecomment-65670316

**Comment by bazzel** [comment]
Ok, thx.

**Comment by CaelanStewart** [comment]
I just encountered the same problem @bazzel, had me pulling out my hair when I just could not figure out why I couldn't hover over an element. Turns out, under certain conditions, if you give an element background-color: transparent, no hover is triggered in IE10, but if I changed it to rgba(0,0,0,0) in the output CSS manually, it worked fine.

IMO, that is just another reason as to why the way a colour is defined by an author should be preserved throughout the compilation process.

Also, you can workaround this by doing: `rgba(0, 0, 0, 0.0001)`.

**Comment by nex3** [comment]
@CaelanStewart Can you provide a CodePen that reproduces the case where IE10 doesn't understand `transparent`?

Generally we try to emit the most compatible representation of a color, but this poses a problem since older IE versions understand `transparent` but *not* `rgba(0,0,0,0)` (which is why we prefer the string `transparent` in the first place).

**Comment by CaelanStewart** [comment]
@nex3, yes, of course I can provide a demonstration. But I tried opening the CodePen I created in IE10, to no avail. The page was unresponsive.

I've created a [GitHub Gist](https://gist.github.com/CaelanStewart/027f522f17fd3fd05ecf8c5fe001f724#file-test-case-html).

On the image on the left, there is an 'A' tag overlaid, which initially has its background-color set to transparent. Upon hover, the background-color is updated to 'rgba(0, 0, 0, 0.25)'.

The image on the right is exactly the same, except that the initial background-color value is set to 'rgba(0, 0, 0, 0)'.

I've tested this on IE9 and 10 on BrowserStack, and the overlay on the left does not respond to the hover state, nor can you even click the link.

Now, fair enough, old browsers don't support RGBA values, but its becoming less and less important to support browsers less than IE9. jQuery, Bootstrap and others have already dropped support for IE8.

So, in my opinion, I believe that I should not have to apply a workaround when using SCSS to support newer browsers. If somebody needs to support an older browser, it's logical that they should be the ones to apply some workaround.

Now, albeit true this is some sort of typical IE bug, I just think that quietly converting color formats in the background to support and older browser should not be the responsibility of SCSS. I believe SCSS should just be a transpiler, and not interfere with or modify the user's original intent.

**Comment by nex3** [comment]
I'm re-opening for now, but I need to talk to @chriseppstein about how we want to handle this. Due to the holidays, that may take a few weeks.

**Comment by nex3** [comment]
I've talked with Chris, and we've decided to officially drop support for versions of IE prior to IE9, which was the first to support `rgba()`. As such, we'll start emitting all colors with no alpha component as `rgba(0, 0, 0, 0)` across the board.
