### ISSUE TITLE
Make `unit(..)` returns null for unitless value

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1788]
## Current

``` scss
$unit: unit(42); // ""
$type: type-of(unit(42)); // string
```
## Proposed

``` scss
$unit: unit(42); // null
$type: type-of(unit(42)); // null
```

**Comment by nex3** [comment]
This is probably correct, but I don't know that it's super clear-cut, and the burden of making it is high. This would be a really hard migration, since there's not really a good in-between state users can change their code to, where it works with both the current behavior and the future behavior. Given that, I don't think the change is worth the pain.
