### ISSUE TITLE
Sass 3.0

### ISSUE THREAD

**Issue by rkh** [sass/sass#18]
Would it be possible to push an empty sass 3.0 gem that simply depends on haml 3.0? That way we could already use it as dependency.

**Comment by chriseppstein** [comment]
There is already a pre-release gem: 
https://rubygems.org/gems/sass

**Comment by nex3** [comment]
I'm not sure what the benefit of this would be. The dependency would still need to be changed when Sass 3.1 is released, and it would be some (small) amount of effort to release a Sass 3.0.\* gem with each Haml 3.0.\* release. Sass 3.1 will be released before too long; I think users can declare a Haml dependency (or use the alpha 3.1 gems) until then.

**Comment by rkh** [comment]
The benefit would be a transition phase. Currently the sinatra docs state that you need the haml gem. Now, as soon as haml 3.1 is released, the docs will be inaccurate. However, advising to install the sass gem would also be incorrect, as there is no stable release atm. Sinatra releases currently are somewhat far apart, thus creating a time in which we ship inaccurate documentation (plus broken development dependencies). However, I totally get if this is to much effort to got through. But I don't see why you would have to do a sass release for every 3.0.x version of haml.

**Comment by nex3** [comment]
3.1 will be our transition phase; Sass will continue to be bundled with the `haml` gem, but in such a way that the `sass` gem will be loaded in preference. If you don't have the `sass` gem installed and you try to load Sass, it will work, but it will print a warning. As such the old Sinatra documentation will still work, even if it's not strictly accurate.

We'd need to do a Sass release for each Haml release because different Haml releases behave differently (bugfixes and very minor features), and dependencies would need to specify what version they require.

**Comment by rkh** [comment]
Oh, nice. Wasn't aware of the 3.1 plans.
