### ISSUE TITLE
Sourcemaps are not created when switching from sourcemaps=none to any other sourcemap setting if file is cached

### ISSUE THREAD

**Issue by robwierzbowski** [sass/sass#1830]
The command `sass --sourcemap=none --update source/file.scss:dest/file.css` produces a css file and the output:

```
  directory dest
      write dest/file.css
```

When I then switch to the command `sass --sourcemap=file --update source/file.scss:dest/file.css`, Sass seems to check and see that the file exists, and exits happily. Sourcemaps aren't created and the file is not revised to include the sourcemap or sourcemap location. This seems to be true of switches from `sourcemap=none` to `sourcemap=file | inline` and the reverse.

For me, expected behavior would be to create the map, or if switching to none not include a map comment.

Is this intended behavior?

**Comment by nex3** [comment]
After thinking about it a bit, I think this is actually intended. In general, `--update` can't reliably be configuration-aware since it just checks modification times, and this is more or less a special case of that, even if the configuration does affect other files that might be generated.

It's pretty easy to solve just by passing `--force` when you change the configuration, though.

**Comment by robwierzbowski** [comment]
Ok. The more I experiment, the more I feel like this is a bug. I would expect changing precision for example to invalidate the cache; the difference isn't in supporting files or comments, but the actual resulting CSS. 

This can totally be handled manually by passing `force` as you suggest. Ideally Sass would track the options that a file was compiled with and invalidate if they were different (so I don't have to), but I can see implementing that becoming complex. It was surprising to me that Sass wasn't reacting to my options changes, but of course I defer to you. No response necessary.

**Comment by nex3** [comment]
It's not really accurate to call the output of `--update` a "cache". It's very different than the cache we keep in `.sass-cache`, which is meant to be transparent and _does_ get invalidated when configuration is changed. But `--update` is a very different thing—its output is in no way transparent, since it's the intended point of the command. The invalidation semantics are also different, and keeping them simple both makes it easier for users to reason about and keeps the output clean, without us dumping a bunch of build metadata into directories that may get directly deployed.
