### ISSUE TITLE
sass-convert adds extra line breaks between @include directives

### ISSUE THREAD

**Issue by mixxorz** [sass/sass#1843]
This: 

``` scss
@include component-one;
@include component-two;
@include component-three;
```

Turns into this:

``` scss
@include component-one;

@include component-two;

@include component-three;

```

This was introduced in sass version 3.4.16. I came across this because I use a Sublime Text 3 plugin called [SassBeautify](https://github.com/badsyntax/SassBeautify) which uses `sass-convert` to beautify the files. This behaviour cases the plugin to give ugly output. :disappointed:

**Comment by chriseppstein** [comment]
Not a high priority issue for us, but it is a bug. We'd happily accept a patch that addresses this.

**Comment by first-developer** [comment]
Hi,
It looks like there is no issue with the sass-convert. However, the plugin **SassBeautify** use by default the option `--unix-newlines` when building the final command : https://github.com/badsyntax/SassBeautify/blob/master/SassBeautify.py#L246 .

I'm not sure but if you are on windows, it's normal because that is the behavior wanted in sass-convert code : 
https://github.com/sass/sass/blob/stable/lib/sass/exec/sass_convert.rb#L142

I don't know if this option could cause that behavior. If not could you please guide me to the files that handle the actual conversion? 

Thanks

**Comment by mixxorz** [comment]
When I was testing the behavior before I submitted this issue, I wasn't using the `--unix-newlines` option. I am on a Mac though. Does it not happen on Windows?

**Comment by srawlins** [comment]
I don't think this has to do with unix newlines. It probably started when #1697 was merged.
