### ISSUE TITLE
Add support for range-form media queries

### ISSUE THREAD

**Issue by geoffreydhuyvetters** [sass/sass#1864]
*(edited by @nex3)*

- [x] [Proposal](https://github.com/sass/language/blob/master/accepted/media-ranges.md)
- [x] [Specs](https://github.com/sass/sass-spec/pull/1271)
- [x] [Documentation](https://github.com/sass/sass-site/issues/248)
- [x] [Dart Sass](https://github.com/sass/dart-sass/pull/423)
- [ ] [LibSass](https://github.com/sass/libsass/issues/2698)
- [x] [Ruby Sass](https://github.com/sass/ruby-sass/issues/75)

---

is there a possibility to allow new syntax in CSS

see this issue 

https://github.com/postcss/postcss-loader/issues/30

**Comment by davidkpiano** [comment]
The new syntax proposed [in that draft](https://drafts.csswg.org/mediaqueries/) is a working draft. According to the draft itself:

> This is a public copy of the editors’ draft. It is provided for discussion only and may change at any moment. Its publication here does not imply endorsement of its contents by W3C. **Don’t cite this document other than as work in progress.**

I believe Sass is conservative about what it chooses to implement and what it doesn't - editor's drafts are most likely to change, and working drafts are a little more stable (which is why `:matches` and `:has` work per the spec with `@extend`).

If every editor's draft was allowed in Sass, you'd see a lot more breaking changes in Sass if/when the specs in the drafts change. (Of course, PostCSS doesn't seem to care ¯\_(ツ)_/¯)

Instead of having to install a new PostCSS plugin in order to do this: 

``` scss
@media only screen and (width > 500px) and (width < 1000px) { /* ... */ }
```

Just use current syntax instead:

``` scss
@media only screen and (min-width: 500px) and (max-width: 1000px) { /* ... */ }
```

**Comment by geoffreydhuyvetters** [comment]
I think using things like Media Queries Level 4 in a transpiled environment is the only way to test if this works or not.

But hey.. Sass decides. ¯_(ツ)_/¯

**Comment by geoffreydhuyvetters** [comment]
and I know how the current syntax works :)

**Comment by chriseppstein** [comment]
We sometimes add support for drafts when they are likely to land or when the syntax can be transpiled to a supported syntax. Both of which are true for this feature.

We'll add support for the syntax because it's very dev friendly and we can convert it to supported syntax during compilation. That is: `(width < 200px)` will compile to (max-width: 199.99999px) and `(20em < device-width <= 50em)` will become: `(min-device-width: 20.00001em) and (max-device-width: 50em)`.

/cc @nex3

**Comment by geoffreydhuyvetters** [comment]
Sounds great :) thanks @chriseppstein

**Comment by nex3** [comment]
I'm skeptical of adding support for a syntax that's not locked in. If the spec changes or is rejected, we may find ourselves in the position of supporting idiosyncratic syntax that looks like CSS but in fact is Sass-specific, or worse _not_ supporting the CSS syntax because it's ambiguous with the draft but has slightly different semantics. It's happened before, and I want to avoid it happening again.

**Comment by chriseppstein** [comment]
Paging @tabatkins. What's the status of this spec?

**Comment by tabatkins** [comment]
While I agree with @nex3 in general, this syntax is stable and locked in.  It met with great enthusiasm in the group, and is what MQs were originally supposed to look like (but way back in the day you had to actually worry about putting a `<` in a `<style>`. 

If y'all feel like supporting it, I'm confident that it's safe to do so.

**Comment by HamptonMakes** [comment]
Yeah, this is something I'd looooove to have. Very pretty, very logical.

I'm going to +1 this all over the place.

**Comment by chriseppstein** [comment]
Ok, there was a chat about this outside of github and the outcome of which is the following:
1. It's our policy to wait until specs are approved and having at least one browser implementation before we implement them, however, we do see this spec change as low risk and shim-able so we are open to implementing it before formal approval.
2. Until the spec is approved, this is considered a feature. As such it would only be part of the next major sass release. Also note that Ruby sass still has a feature freeze while we wait for libsass to reach feature parity (soon, we hope).
3. This is not a high-priority feature for us. We have other css compatibility breaks for spec'd changes that are further along in the spec process that must be implemented against stable branch first.

**Comment by geoffreydhuyvetters** [comment]
Sounds fair, thanks :)

**Comment by chriseppstein** [comment]
@nex3 I think we should bump the priority of this compat issue now.

**Comment by nex3** [comment]
Agreed.

**Comment by nex3** [comment]
I've added [a proposal for the new syntax](https://github.com/sass/language/blob/master/proposal/media-ranges.md) to the `sass/language` repo. @xzyfer, can you take a look? Since it's pretty simple, if no one has any issues with it in the next week, I'm going to mark it as accepted and start implementing.

**Comment by xzyfer** [comment]
So I have a branch with MQ4 support with range queries. The blocker for me
understanding query merging.

**Comment by nex3** [comment]
Can you verify that your branch follows the syntax/behavior outlined in the proposal, or if not file issues?

**Comment by xzyfer** [comment]
I'll double check. It follows the CSS grammar parsing rules.

**Comment by nex3** [comment]
A week has passed since the proposal was released, so I've marked it as accepted in https://github.com/sass/language/commit/cf3283d5c3633757c57e32e7b05bee5f1ecc1f93. I'll write up specs soon.

**Comment by nex3** [comment]
Closing this out because [LibSass is now deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and we aren't expecting to add any additional features to it.
