### ISSUE TITLE
Importer Test Harness

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1867]
Issue #1865 demonstrated that it would help developers of new importers if there was a test harness that they could easily use to ensure that their importer is correctly implementing the importer contract.

Probably the same goes for Cache Stores though that interface is less tricky.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
