### ISSUE TITLE
Invalid US-ASCII Character exception

### ISSUE THREAD

**Issue by gucki** [sass/sass#189]
Trying to import this file https://github.com/dmfrancisco/activo/blob/activo-2/stylesheets/themes/activo/style.sass results in an exception.

I already resaved the file using utf-8 encoding but the error stays the same.

```
** Invoke assets:precompile (first_time)
** Execute assets:precompile
/home/gucki/.rvm/rubies/ruby-1.9.3-rc1/bin/ruby /home/gucki/.rvm/gems/ruby-1.9.3-rc1/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
** Invoke assets:precompile:all (first_time)
** Execute assets:precompile:all
** Invoke assets:precompile:primary (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
Starting app version heads/develop
...
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:primary
rake aborted!
Invalid US-ASCII character "\xE2"
  (in ....scss)
(sass):506
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/engine.rb:351:in `block in check_encoding!'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/util.rb:438:in `rescue in block in check_encoding'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/util.rb:435:in `block in check_encoding'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/util.rb:434:in `each'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/util.rb:434:in `each_with_index'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/util.rb:434:in `check_encoding'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/util.rb:487:in `check_sass_encoding'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/engine.rb:350:in `check_encoding!'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/engine.rb:317:in `_to_tree'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/engine.rb:293:in `_render'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-3.1.8/lib/sass/engine.rb:240:in `render'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sass-rails-3.1.4/lib/sass/rails/compressor.rb:7:in `compress'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/actionpack-3.1.1.rc3/lib/sprockets/compressors.rb:18:in `compress'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sprockets-2.0.2/lib/sprockets/processing.rb:243:in `block in css_compressor='
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sprockets-2.0.2/lib/sprockets/processor.rb:29:in `call'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/sprockets-2.0.2/lib/sprockets/processor.rb:29:in `evaluate'
/home/gucki/.rvm/gems/ruby-1.9.3-rc1/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
....
```

The error only occurs when precompiling. In development everything works fine. So it might also be an issue of sass-rails, sprockets, rails, ...?

**Comment by nex3** [comment]
It looks like for some reason the file isn't getting loaded as UTF-8. This is likely either because `Encoding.default_external` isn't set to UTF-8, or because Tilt is purposely ignoring the default external encoding for its own reasons.

There is a workaround available: if you put `@charset "UTF-8";` at the top of your file, Sass will interpret it as UTF-8 regardless of what the String's encoding is marked as.

In any case, this isn't a Sass bug, so I'm closing the issue.

**Comment by gucki** [comment]
Thanks. I guess then it's related to https://github.com/rtomayko/tilt/issues/75 and https://github.com/rtomayko/tilt/pull/107

**Comment by smith** [comment]
I fixed this by putting a unicode character (http://unicodesnowmanforyou.com/) in a comment in the file that has the `@import` statements.

**Comment by schnittchen** [comment]
@smith, your workaround just saved my life ;-)

**Comment by wadetandy** [comment]
Important note for those who find this page down the line: the suggested `@charset UTF-8` at the top of the file doesn't work as written.  Instead you need to add `@charset "UTF-8";`.  Be sure to use the `"` character instead of the `'` character, as my version of sass still didn't work with the single quote.

**Comment by nex3** [comment]
Thanks @wadetandy, I've fixed my comment.

**Comment by Grawl** [comment]
Monkeypatch. Still no solution? `US-ASCII` are tight.

**Comment by sztupy** [comment]
Note: you have to put the `@charset "UTF-8";` declaration into the topmost file, even if that file doesn't contain UTF-8 characters just `@import`s the ones that have. Putting them into the imported ones doesn't seem to have any effect

**Comment by nex3** [comment]
@sztupy That's not how it's expected to behave, and I can't reproduce that behavior locally. What version of Sass are you using?

**Comment by httpete** [comment]
We got around this by forcing sass to use UTF-8:

sass -E utf-8 whatver.scss

**Comment by oliverkierepka** [comment]
I ran into the same charset problem.

Especially on OSX there seams to be a problem with ruby Encoding Settings.

I fixed it creating a config.rb file in the main project directory to tell ruby explicitly which charset encoding it should use. Since sass and compass depend on ruby, chances good that this will fix your problems.

`Encoding.default_external = 'utf-8'`
