### ISSUE TITLE
Always output Sass values in error messages in expanded style

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1916]
Related to https://github.com/sass/sass-spec/issues/627

I would like to requested that Sass values in error messages to always be output in the expanded style, or alternatively as authored. This is not the case currently.

```
foo {
  bar: (rgba(16,16,16,0.5) + #AAA);
}
```

```
Error: Alpha channels must be equal: rgba(16,16,16,0.5) + #AAA // compressed
Error: Alpha channels must be equal: rgba(16, 16, 16, 0.5) + #AAA // all other
```

**Comment by chriseppstein** [comment]
Why are we testing error messages in compressed mode?

**Comment by xzyfer** [comment]
Valid question. /cc @mgreter @saper. Also seems strange to me. IIRC it's something @mgeter stumbled across in testing with perl-libsass. I'm not convinced there's a valid usecase for this in sass-spec.

**Comment by mgreter** [comment]
Well, it simply isn't consistent between ruby sass and libsass in compressed mode now. Not sure what else to say about, but it doesn't seem to be consistent (IMO ruby sass also ignores users settings like precision in errors and also with inspect results). BTW. perl-libsass catched that error while regenerating the error specs, since it is not defined which mode should be master if we only want to test one output style. And I test all error specs in all output-styles to make sure it doesn't accidentally break ...

**Comment by mgreter** [comment]
@chriseppstein can you make a statement whether errors, warnings and/or inspect should ignore user settings or not? Would be helpful to know that, since I'm currently relying on trial and error here and always unsure if something like this is a ruby sass bug or a libsass issue!?

**Comment by chriseppstein** [comment]
@mgreter I won't say "ignore user settings" as that seems overly broad and I'm not sure what all the implications would be, but I can't think of a use case where outputting a value compressed into a warning or error message is desired or helpful for a user who will need to debug their code.

**Comment by chriseppstein** [comment]
@xzyfer @mgreter @saper I'd like to close this or get to some sort of actionable resolution.

**Comment by xzyfer** [comment]
> I can't think of a use case where outputting a value compressed into a warning or error message is desired or helpful for a user who will need to debug their code.

Is is reasonable then for `.inspect` to ignore compressed mode flag? Otherwise I don't see a resolution.

**Comment by chriseppstein** [comment]
@xzyfer Yes, that's reasonable, imo. The annoying thing is that for some types, inspect is used to construct the css representation.

**Comment by gytdau** [comment]
@saper has chosen to ![ignore this issue](https://github.com/sass/sass-spec/issues/627#issuecomment-166024933) for now. Should this issue be closed?

**Comment by saper** [comment]
I'd prefer to say I just side-stepped it to allow our tests to work.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
