### ISSUE TITLE
About SASS

### ISSUE THREAD

**Issue by jt4000** [sass/sass#1925]
I don't understand about SASS.

What is the benefit of using SASS to in order to improve a website's front-end code?

Thank you!

**Comment by KurtRMueller** [comment]
Hi JT,

This is a great question! Unfortunately, it is the wrong venue to ask this question. Github issues are generally used for bug reports and feature requests. Support and general questions are usually directed to support forums of some kind. There isn't any official ones listed currently in the repo's readme, however helpful forum to start would be: https://www.reddit.com/r/sass

**Comment by ghost** [comment]
**(Edit: I just learned that it's spelled Sass, not SASS).**

@jt4000 Sass and SCSS help you writing less code that you can then reuse. The idea behind it is that you don't "specify" a stylesheet but "program" it, using concepts like variables, mixins (similar to user-defined functions) and proper functions.

Let's say you designed a site. It's good, right? The stylesheet however is up to 17324 lines, and you repeated the font-family and size in many places. How does it feel to fix it? Yeah, I know you can use search/replace, but wouldn't it be better for you to define a variable? Let's say...

```
$headings: 'Comic Neue', 'Comic Sans', 'Comic Sans MS', sans;
```

What if you didn't like the typography? Instead of performing a search/replace again, you could change one variable instead:

```
$headings: 'Papyrus';
```

Suddenly, your design got better.

However, someone told you that pixels on typography aren't cool anymore because these aren't looking good in 4k screens; you change again with search/replace... but then your site doesn't look good in mobile phones, what do you do? search/replace again or... modify a variable instead:

```
$fontSize: 1vw;
$lineHeight: 1.125;
```

You could use other things provided by Sass such as mixins to define proportional widths and heights, handle colours, get grids with different properties, avoid using prefixes for older browsers and all that.

If this is clear enough for you, you can find more of these ideas along with better source codes than the ones I can write here in https://sass-lang.com/. That also means it's not an issue (it's not like Sass doesn't work, right?) and that you might want to try it somewhere else. And since it's not an issue, you shouldn't open an issue on GitHub.

Hopefully this clarifies your doubts :)

**Comment by EverybodyKurts** [comment]
Hi JT,

Sass has plenty of great features like variables, mixins, and built-in functions that css simply does not have. There are also plenty of popular libraries built on top of Sass, including Compass http://compass-style.org/, Suzy http://susy.oddbird.net/, and Bourbon, https://github.com/thoughtbot/bourbon.

A great starting point would be the official sass guides at http://sass-lang.com/guide. Furthermore, if you want more opinions, you should check out https://www.reddit.com/r/sass

**Comment by HugoGiraudel** [comment]
My advice would be: do not feel like you have to use just because it is popular. If you are fine with your current way of writing CSS, whatever it is, stick with it. There is no point in following the trend. Sass does solve common problems such as the lack of CSS variables, or code organisation through file imports, but if you do not face these problems, do not feel like you have to learn more about Sass or any other equivalent tool.

Learn when you want to learn. Learn what you want to learn.

**Comment by cimmanon** [comment]
Please, this is an issue tracker, not a discussion group.

**Comment by justinskolnick** [comment]
@cimmanon It's both. Github is part social network. 

When I was starting out, I had no idea who to turn to for help. I love that there's a place where newbies get to talk to professional developers about code -- even if they're technically misusing an issue tracker to do it. I'd have done the same.

**Comment by EverybodyKurts** [comment]
I agree with Justin. Let's remain friendly, inviting, and forgiving to new users. We all came from somewhere. Also, if you ping Chris Eppstein on twitter, he's okay with using github issues as support for the sass repo.

**Comment by ghost** [comment]
I agree with @justinskolnick idea of having a place for new people like me to talk with professional developers; I just think that the issue tracker shouldn't be the place. Some people make extensive use of issue trackers by integrating with Trello, Slack, Calendars and a number of other possible integrations to manage projects in an easier way. If @chriseppstein and the contributors for this particular project are fine with it, it's all good, but we'll be perpetuating a practice that might probably lead to issues with other projects.

However, before pinging @chriseppstein on Twitter and answering I did a quick search on sass-lang site, and couldn't find any of the usual mechanisms to freely talk/ask about the project, such as a mailing list, an IRC channel, a Slack team or something (I did search on Google, and there _is_ a mailing list on Google Groups, but to tell if it is official or it is being checked by developers was hard enough to figure out that a newcomer might probably not want to login). That's why I tried to compensate a bit of both: providing an answer to the user, one that could be satisfactory enough for his/her question and that could also help him/her looking for other ways to discuss.

Now that I read it again, failed miserably in my intentions. Sorry about it. Fortunately, @KurtRMueller came up with lots of links that will come in handy.

**Comment by chriseppstein** [comment]
@cimmanon I put out a call on twitter for someone to reply to this.  It's not user friendly to tell potential new users that they can't ask questions here unless you point them to the right place to do such a thing. And, I can't really think of one. We have a long history of trying to help all users who ask for help on our issue tracker -- even if the core issue is not really about a bug or feature request.

Anyways, I think the answers here have sufficiently resolved this users issue.
