### ISSUE TITLE
CSS Type Functions

### ISSUE THREAD

**Issue by whaaaley** [sass/sass#1937]
Such as:

``` scss
type-property() // margin, padding, etc.
type-flag() // !important
type-length() // px, em, rem, etc.
type-unit() // %, vw, vh, etc. as well as lengths
type-style() // solid, dashed, dotted, etc.
```

Each returning true or false or have a function similar to `type-of` but specifically for these types. `type-of` seems to be specific to how Sass works, but having functions for types specific to CSS I think would be useful too, even though they may not necessarily be traditional types.
- Error checking would be easier, especially for mixin arguments that require these types.
- It would make comma-less mixin arguments easier to make, which would be even cooler to have with the new `+mixin` syntax. (have a mixin accepting a list of values and determining what they are later)
- Unit conversions could be made easier.

I don't think this is a feature anyone is in dire need of, but it would be pretty useful for people who like to make super fancy mixins to generate CSS and I think it makes sense for Sass to have CSS specific "types" as well as Sass specific types.

**Comment by chriseppstein** [comment]
This requires Sass to have intimate knowledge of the current state of all CSS specifications and requires constant updates to Sass in order to maintain correctness. This is contrary to Sass's goal of being as future-proof as possible.

This is a great idea for a Sass library which can be updated and released on a much more frequent basis than the language itself.
