### ISSUE TITLE
Unify .sass and .scss parsers.

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#1942]
The `.sass` syntax parser can be replaced by a pre-processing step and then passed to the `.scss` syntax parser. This way, new parsing rules only need to be implemented once.

This is not a blocking issue for 4.0.

**Comment by xzyfer** [comment]
I expect you already know this, but that's how LibSass works.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
