### ISSUE TITLE
@extend behaviour

### ISSUE THREAD

**Issue by pentzzsolt** [sass/sass#1945]
This is more of a question, than an issue, although I am uncertain.

I have made a demo on CodePen to show the behavior I find a little weird: http://codepen.io/pentzzsolt/pen/obLZEz

Take a look at the compiled output. I cannot understand, why the selector is structured in such a way.

I have a very simple placeholder selector:

``` sass
%extend {
    color: blue;
    .error & {
        color: red;
    }
}
```

After that, I have a nested selector that extends this placeholder.

``` sass
form {
    & a {
        @extend %extend;
    }
}
```

The output is almost what I would expect, only that SASS adds something extra that I cannot understand the reason of. I would expect the output to be:

``` sass
.error form a {
    color: red;
}
```

But instead, I get:

``` sass
.error form a, form .error a {
    color: red;
}
```

Is this a bug or an expected behavior? If it is expected, is there any way I can adjust my code so that I get what I expected?

**Comment by davidkpiano** [comment]
Hey @pentzzsolt, let's break this down. You currently have:

``` scss
%extend {
  color: blue;
}

.error %extend {
  color: red;
}
```

And later on, you're extending:

``` scss
form a {
  @extend %extend;
}
```

So what this means is that:
- `a` is extending `%extend`, which is to say that you are styling `a` as if it matches `%extend`
- `a` must be a general descendant of `form` (child, grandchild, etc.)

But when you extend `%extend`, you have these additional constraints:
- `%extend` is a general descendant of `.error`, meaning...
- `a` must also be a general descendant of `.error`, since it's being styled as if it matches `%extend`.

Therefore, `a` must be a general descendant of both `form` and `.error`. Now, Sass has no way of knowing which one comes first, since a general descendant means that the selector can be a child, grandchild, great-grandchild, etc. of the parent selector (`form` and `.error` in this example). So, with the child analogy, consider these two possibilities:
- `a` is the child of `form` and the grandchild of `.error`, giving you `.error form a`
- `a` is the child of `.error` and the grandchild of `form`, giving you `form .error a`

Both of these match the constraints that _you_ set up, and both of these selectors are valid. Remember: Sass is not a mind reader, so it will output the most feasible/common permutations of selectors.

Now, if you want to avoid this potential selector explosion in the future, avoid the **general descendant combinator** if you can. By having a selector such as `form a`, you're basically saying that you have no idea where `a` is, you just know it's inside a `form` somewhere. You can have stricter constraints (and a much easier time predicting what `@extend` will do) when you use the **direct descendant combinator**, such as `form > a` or `.error > %extend`.

Hope this helps!

**Comment by pentzzsolt** [comment]
Hey @davidkpiano!

Thank you for your quick response, much appreciated!

Although I forgot to mention, but I did experiment with the **direct descendant combinator** and realized that using that does not lead to a selector explosion. Unfortunately, in my case, as you said, I have absolutely no idea where my selector is going to end up inside my parent selector's DOM tree.

What you wrote and the way you broke it down makes perfect sense. I wonder though, if there is any way to somehow override this effect, group with parenthesis somehow for instance.

**Comment by davidkpiano** [comment]
Sure:

``` scss
%extend {
  color: blue;
}

.error %extend {
  color: red;
}

form a {
  .error & {
    @extend %extend;
  }
}
```

The above gives you your expected result because you have three constraints:
- `a` is a descendant of `form`
- `a` is a descendant of `.error`
- :new: `form` is a descendant of `.error`

And only one possible selector can be formed from those constraints.

**Comment by pentzzsolt** [comment]
Thank you, I understand the flaw in my logic now, makes sense. :+1:
