### ISSUE TITLE
[discussion] remove compressed output mode

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1952]
I think this is a discussion worth having, given that a major version is the works.

Some thoughts:
- there are issues with things being unexpectedly compressed 
  - #1946 
- there are issues with things being unexpectedly not compressed 
  - #1946 
  - #1834 
  - #1296 
  - #649
  - #387
- various improvement have been long planned and not actioned. _(not a criticism)_
  - #847
  - #687
  - #116
- there are better, community accepted, tools for this
  - https://goalsmashers.github.io/css-minification-benchmark/

Another consideration is that some of the above inconsistencies become a real issue for LibSass compatibility. Generally when dealing with static parsing.

**Comment by chriseppstein** [comment]
There are a lot of people who use Sass as their only CSS development tool. Given the huge benefits of compression for production quality development, I don't want to remove a feature that is already built because there are bugs.

non-syntactic whitespace differences between libsass and ruby sass seem to be the root cause of your annoyance here. I would like to address this by making sass-spec agnostic of whitespace and fixing bugs in ruby sass where we are inconsistent.

**Comment by chriseppstein** [comment]
I've added the label `Compression` to all those issues so we can find them and fix them.
