### ISSUE TITLE
Pipeline operators?

### ISSUE THREAD

**Issue by whaaaley** [sass/sass#2012]
Maybe we wouldn't call them that, but nested functions are kind of ugly, especially when you're dealing with map stuff and parens can get deep. I'm not really a fan of mentally keeping track of how many parens you go by while reading. You could store each "action" in a variable but that can be equally confusing.

The pseudo code below is just saying put the first item in the chain into the next item in the chain where `$` is located, then the second into the third, etc etc... If there isn't a `$` it would default to the first argument.

Some pseudo code:

``` scss
// these
$variable: $variable | join($, $one) | join($, $two);
$variable: $variable .. join($, $one) .. join($, $two);
$variable: $variable..join($, $one)..join($, $two);
$variable: $variable.join($, $one).join($, $two); // i like this because it's short
$variable: $variable.join($one).join($two); // same as the last line but it would default to the first arg

// would be the same as this
$variable: join(join($variable, $one), $two);
```

Some code I copied from one of my projects:

``` scss
// this
$results: (index: map-get($results, index).join($i, comma)).map-merge($results);

// would be the same as this
$results: map-merge($results, (index: join(map-get($results, index), $i, comma)));
```

Although, this isn't a _huge_ inconvenience. It's just some sugar. I write JavaScript often and thinking in this sort of pattern seems easier to me.

**Comment by davidkpiano** [comment]
@dustindowell22 You can use [Sassdash](https://github.com/davidkpiano/sassdash) if you want that functionality right now, using the [`_(...)` function](http://davidkpiano.github.io/sassdash/sassdoc/index.html#function-_). 

Here's your pseudocode brought to life:

``` scss
$one: 'one';
$two: 'two';
$variable: 'testing';

$variable: _($variable,
  _concat $one,
  _concat $two,
  _join ' ');

// => $variable = 'testing one two' 
```

When I talked to @nex3, she told me she envisioned Sass as an imperative language that _creates_ declarative CSS code, instead of a declarative/functional language from the start, which makes sense.

**Comment by jamen** [comment]
I would personally be behind this.  Despite Sass being _envisioned as an imperative language_, I still can't deny that it is greatly functional, and there is nothing wrong with it being functional (that is a good thing in my eyes).

With that, I think a pipe operator would make code more clean and concise with the functional aspect of things in Sass: to have functions be "lined up" rather than some some weird tuple nest which looks ugly for a pipeline operation, where data needs to go through multiple functions.

I like the idea of using two dots `..` to reduce confusion with other languages, since `|` is a bitwise OR operator, and `.` is an _accessor_ in some OOP languages.  On the other hand, I like having `$` being the placeholder, however I think `#` is also a convention.

``` sass
$baz: $var .. 
  foo('baz', $) ..
  bar($);
```

**Comment by chriseppstein** [comment]
I understand that many nested infix functions can decrease readability. I highly encourage the use of intermediate variables. Yes, it's more verbose. But it also is a lot more readable than deeply nested function calls and functional chaining with implicit arguments.

``` scss
$variable: join($variable, $one);
$variable: join($variable, $two);
```

Our goal is not to turn SassScript into a highly ergonomic programming language. SassScript is a lightweight scripting syntax that aims to be obvious to people with very little experience in programming with traditional programming languages. We vastly prefer to have code that is a bit more cumbersome to write if that code is more understandable. If we cross this line we run the risk of making Sass stylesheets inaccessible to CSS developers.

This is our philosophy. CSS preprocessing is a big space now. There's room for a preprocessors with different philosophies. Maybe something like stylus would be more to your liking?

**Comment by jamen** [comment]
@chriseppstein: Well, Stylus is good too.  :)  Thanks for at least considering the idea.  I think that viewpoint the Sass maintainers have is good as well, good intentions.  It was worth a shot at least.  :P
