### ISSUE TITLE
Variable using is broken

### ISSUE THREAD

**Issue by dangreen** [sass/sass#2037]
prints error:

```
.landing__section
    background-position: #{"5"}% #{"5"}%
```

doesn't print error:

```
.landing__section
    background-position: #{"5"}% 5%
```

**Comment by chriseppstein** [comment]
This is because `%` is the "modulo" operator. The error you're getting is the same error you would be getting if you had typed `#{"5"}+ #{"5"}+`. Sass is basically saying "this operator is missing an operand". You can fix this by moving the percent sign into your variable or by using string interpolation instead of bare interpolation. Or even better, by using the percent unit properly by attaching it to the number it belongs to instead of tacking it on using strings.

``` sass
.landing__section
    $a: "#{"5"}%"
    $b: "#{"5"}%"
    background-position: #{$a} #{$b}
```
