### ISSUE TITLE
Interpolation Regression in 4.0

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#2049]
If a identifier ends with parens indicating it is a function call. E.g. `un#{quo}te(asdf)` then in Sass 3.5: we get `unquote(asdf)` as output but in Sass 4.0 we get `unquo te(asdf)` (note: the introduction of a space).

According to @nex3 this is an unintended change.

**Comment by nex3** [comment]
This is more complicated than it looks. In Sass 3.5, `un#{quo}te(asdf)` parses as ``un#{quo}#{te(asdf)}``—meaning that it is actually _calling a function_. In this case, there's no function named `te()` defined,  so the function call returns the unquoted string ``te(asdf)``, but that's not necessarily true. For example, if you write `b#{o}red(#abc)` in 3.5, you get ``bo170``, since `red(#abc)` is 170.

In 4.0, we're still parsing the function call as a function call, but we no longer allow that to join the interpolation string. So the parse is instead ``un#{quo}` te(asdf)`, which is the source of the space. Similarly, `b#{o}red(#abc)` produces `bo 170` in 4.0.

We should _certainly_ have a deprecation warning here, since I don't think it makes sense to have the same behavior across 3.5 and 4.0 in all cases. But the question remains what the behavior should be. I can see two options:
1. Allow interpolated function names, and always interpret them as plain-CSS function calls. This is likely to preserve existing behavior in almost all cases, and it's consistent with how we handle interpolated `@import`s. It _mostly_ fits with the principle that all identifiers can be interpolated, except that a function whose _entire_ name is interpolated (e.g. `#{$name}(foo)`) would still be parsed as ``#{$name}` foo`, which isn't consistent with the function behavior (although is consistent with the rest of interpolation).
2. Canonize the current 4.0 behavior as official and make `call()` the official way to dynamically construct CSS function calls as well as Sass ones. This avoids any interpolation special-cases, but is much more likely to break existing stylesheets.

I tend to favor option 1, since it's less likely to cause breakage, but we should talk these through and get to a decision we're confident is the right one.

**Comment by chriseppstein** [comment]
I agree that #1 is best, I think that if this is in use in actual stylesheets, it's probably to avoid functions from being interpreted as sass functions.

**Comment by nex3** [comment]
Thinking this through further, I think `#{$name}(foo)` should actually be parsed as ``#{$name}(#{foo})``. This follows from [the CSS grammar for a function token](https://drafts.csswg.org/css-syntax-3/#ref-for-typedef-function-token-2) and the fact that in Sass, `#{$name}` is in and of itself a valid identifier.
