### ISSUE TITLE
[Feature Request] Partially Applied Functions in 4.x

### ISSUE THREAD

**Issue by davidkpiano** [sass/sass#2063]
As discussed on Slack...

**Creating partially applied functions**

``` scss
$lighten: function-reference(lighten);

// positional args
$lighten-green: partial($lighten, green);
// => returns function reference

$light-green: call($lighten-green, 50%);
// merges args as (green, 50%)
// => returns color

// named args
$lighten-half: partial($lighten, $amount: 50%);
// => returns function reference 

$light-green: call($lighten-half, green);
// if named, merges args as (green, $amount: 50%)
// with non-named args first, then named args
// => returns color
```

**Comment by ArmorDarks** [comment]
Oh my, will we finally receive calls for functions? I hope we'll also get `apply`, which will spread provided list into function parameters? Or spread `...params` operator will do nicely too...

Necessity to create references manually with `function-reference()` after JavaScript sounds like a heresy to me, but I understand that with Sass we don't have much other options... Though, I get feeling like Sass continues to build somehow its own... crippled (I'm really sorry for the word!) language.

And some suggestion. Normally I'd expect `$lighten

``` sass
$lighten: function-reference(lighten);

$result: $lighten(green);
// => returns color
```

to be same as

``` sass
$lighten: function-reference(lighten);

$result: call($lighten, green);
// => returns color
```

Since technically `$lighten` here becomes expression, so why not allow to call it directly? This would be useful for cases, when you don't need to do anything with parameters for referenced function (which is most part of cases).

**Comment by ArmorDarks** [comment]
And one more thing. Wouldn't that work too?

``` sass
@function lighten(...) {...}

// we DO NOT define $lighten with function-reference here

$result: call(lighten, ...params);
// => returns color

$word: ten;
$result: call(ligh#{ten}, ...params);
// => returns color

$word: lighten;
$result: call($word, ...params);
// => returns color
```

Defining of reference here seems to be not needed unless you want to put function as expression into some variable. First argument of `call` is always a name of a function, so why we should always put there a defined reference? If string provided, why won't it just search for a straight match with a name of one of already defined functions?

In other words, `call` could accept `string`, name of function, or a `reference`.

**Comment by chriseppstein** [comment]
@ArmorDarks Sass already has the `call` function for invoking functions by value. And we already have variable arguments. See the release notes for Sass 3.3: http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#330_7_march_2014

**Comment by chriseppstein** [comment]
> In other words, `call` could accept string, name of function, or a reference.

It does right now. But we are changing this behavior in 4.0 to only accept references because of how name resolution is changing in 4.0. See #2061 for more details.

**Comment by ArmorDarks** [comment]
@chriseppstein Thanks for explanation, I didn't see that PR. My bad. That was exactly what I've been asking about. So, no more strings in calls, as I've thought. Sadly enough.

Won't it be possible to automatically call `$__tempFuncRef__: function-reference({{ functionName }});` by Sass itself before any `call`, which uphold string as first argument? This will allow to preserve previous behavior and avoid depreciation.

**Comment by chriseppstein** [comment]
@ArmorDarks No. In 4.0, the issue is that in many cases the code performing the call is in a different module than the code specifying the name of the function to invoke. In 4.0 global functions don't exist. Lexical scoping rules mean that it's quite unlikely that the code performing the call would be able to resolve the function name from that scope or worse, it may resolve to a different function of the same name.

**Comment by nex3** [comment]
I think allowing partial application would introduce a lot more complexity than it would be worth.
