### ISSUE TITLE
Better error messages for operators with types that don't support them

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#2077]
Currently if you try to divide a map or multiple function references you get an error about the type not being able to be output to css. Instead we should give an error like "cannot divide with a map".

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
