### ISSUE TITLE
Multiplication with units

### ISSUE THREAD

**Issue by DaveKin** [sass/sass#2096]
If I try to multiply two value with units I get an unexpected error.

```
$test: 10px;

.testing{
  width: $test * $test;
}
```

result: `100px*px isn't a valid CSS value.`

**Comment by douglasdeodato** [comment]
You cannot use multiplication in SASS

best way is doing this:

```
$test: 10px;

@function calc-width($value1, $value2) {
  @return $value1 + $value2;
}

.col-md-6 {
  width: calc-width($test, $test);
}
```

**Comment by DaveKin** [comment]
at the moment I can get around the problem using a function to strip the units but the behaviour seems wrong to me as all of the other basic arithmetic functions work as expected.

e.g. https://gist.github.com/DaveKin/5c8340ea92b147d66f0cb9f669a4cedc

**Comment by douglasdeodato** [comment]
you cannot multiply two px values
you cannot multiply units

Multiplying two pixel values, will get you px^2.

look: https://github.com/sass/sass/issues/83

you can do arithmetic functions with no problem:
https://gist.github.com/douglasdeodato/189c0d1ef54bcebd0c9da2204e690466

 https://www.sitepoint.com/understanding-sass-units/
https://css-tricks.com/snippets/sass/strip-unit-function/

I am here just for help not for discuss :+1:

**Comment by DaveKin** [comment]
I think I get it now - multiplication can only be performed when one of the arguments is a numeric value, not a quantity of units.

**Comment by chriseppstein** [comment]
@DaveKin CSS dimensions are linear, but if you multiply two linear dimensions you get an area, If you multiply again you get a volume. CSS doesn't currently have any properties that are expressed as an area or volume (tho it may someday) and so Sass gives you an error because you've computed an area but you must be meaning to specify a linear dimension. It may be that one of your numbers is actually a ratio and that you're not fully specifying its units. For example the value `$px-per-em: 12px / 1em` is a ratio that can be multiplied by an `em` value to compute pixels (E.g. `$px-per-em * 2em => 24px`)
