### ISSUE TITLE
Why not get map key velue in json style?

### ISSUE THREAD

**Issue by eromoe** [sass/sass#2099]
I have to repeat `map-get($colors, green)`  sometime.
It would be much more convenient If sass support `$colors.green`, and it would be nice to go  further like `$colors.green.light3`

**Comment by chriseppstein** [comment]
We considered this when we added maps but ultimately decided against adding new syntax because of the risks it creates if CSS adds conflicting syntax. However, we are using dot notation in Sass 4.0 for <module>.<identifier> resolution. So now that we've decided that, maybe it's worth revisiting this idea. @nex3 thoughts?

**Comment by nex3** [comment]
I've never liked JS's conflation of dereferencing and map access, and I don't like the idea of further encouraging people to use unquoted named as map keys. In fact, the example above doesn't even work: `map-get($colors, green)` is the same as `map-get($colors, #00f)`, whereas `$colors.green` would be the same as `map-get($colors, "green")`. If the requester can make this mistake, anyone can.

As an additional consideration, now that we have precedent for dot-notation we may want to use it for methods (e.g. `$map.get("green")`), which would preclude using it as map access.

I think #1739 covers this use-case well enough.

**Comment by ArmorDarks** [comment]
@nex3 

This author's error is result of opting Sass to not use quotes for string literals. Now because of that we're forced to continue suffer with obscure syntax for accessing object properties?

I think it would be better to leave that choice to users — to use more handy syntax, but risk errors, or stay on safe rails. In the end of all, it matters does user understand what he does or no. Besides, as you demonstrated, current syntax neither eliminates any errors, so what's the point?

Well, now when I though about it, ironically it seems that `$colors.green` sounds even safer than `map-get($colors, green)`, because in first case we're 100% sure that `green` is string literal and not `#00f`.

> I've never liked JS's conflation of dereferencing and map access

Didn't like that statement. Sowwy.

**Comment by ArmorDarks** [comment]
> As an additional consideration, now that we have precedent for dot-notation we may want to use it for methods (e.g. $map.get("green")), which would preclude using it as map access.

Just passed by. In many OOP languages built-in methods risking to collide with actual dictionary property. In most cases, it solved well just by giving more precedence to the property.

Yeap, basically this means that `$map: ( get: 'some value' )` will make `$map.get()` method inaccessible, but I don't see anything bad about. For years in other OOP languages, it never made an issue.
