### ISSUE TITLE
&(x) Specific parent level selector

### ISSUE THREAD

**Issue by linvi** [sass/sass#2111]
Would it be possible to have the following feature :

``` scss
.test1 {
    .test2 {
        .test3 &(1) {

        }
    }
}
```

To create the following selector : `.test1 .test3 .test2`.

And,

``` scss
.test1 {
    .test2 {
        .test3 {
            .test4 &(2) {

            }
        }
    }
}
```

To create `.test1 .test4 .test2 .test3`.

It would be quite useful in various cases where we have to re-write the entire path.

Regards,
Linvi

**Comment by chriseppstein** [comment]
Rather than introduce lots of complex syntax for parent selector references, we made selectors accessible to SassScript and added [selector functions](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_functions) to manipulate them in arbitrary ways. Note that you will probably need to compile this into a mixin that takes a content block and utilizes the `@at-root` directive.
