### ISSUE TITLE
No error on duplicate mixin  name

### ISSUE THREAD

**Issue by iddekingej** [sass/sass#2113]
Input file:

```
@mixin xx($p){
        a:x;
}

@mixin xx($p){
        b:x;
}

p{
    @include xx(2);
}

```

output:
p {
  b: x; }

What expected:
Duplicate mixin error

Version:Sass 3.4.22.7716e67

**Comment by chriseppstein** [comment]
Due to the fact that Sass imports are basically just an inlining of the sass module at that location, the practice of repeatedly importing the same dependency across multiple files that get imported into the same file would trigger this error in ways that would break the world. In Sass 4.0 when we have our module system and depending on a module is more than just inlining it, we could add such an error at some point in the future. But for now it's not possible.
