### ISSUE TITLE
Feature Request: Lazy-Loading default variables like LESS.js

### ISSUE THREAD

**Issue by stipsan** [sass/sass#2119]
Hey guys,

I couldn't find any issues here on the topic but if it's been discussed already I apologize.

Take a look at the following snippet:

``` sass
// ./themes/default/buttons.scss
$primary: blue !default;
$primary-hover: darken($primary, 10%)!default;

// ./themes/classic/buttons.scss
$primary: red;

// ./core/buttons.scss
.primary-btn {
    color: $primary;

    &:hover {
        color: $primary-hover;
    }
}
```

As of today that snippet won't work. By the time I override $primary, the $primary-hover variable is already declared and I'll have to duplicate the `$primary-hover: darken($primary, 10%)!default;` expression in my theme to make it work.
As the codebase keeps growing this becomes a bigger and bigger problem and you end up with duplicated code everywhere.

LESS already solves this nicely: http://lesscss.org/features/#variables-feature-default-variables

Are there any plans on making this possible in SASS as well or should we just migrate to LESS?

**Comment by chriseppstein** [comment]
This is not a feature we intend to add. Sass supports CSS variables, which have this behavior and will be ready for prime time once [IE/Edge adds support](http://caniuse.com/#feat=css-variables).

**Comment by florianlacreuse** [comment]
Hi,

Any updates about the lazy loading variables subject?

For instance, when using [Bootstrap](https://getbootstrap.com), sometimes we need to override some default Bootstrap variables.

We may define the variables before importing Bootstrap variables scss file (since Bootstrap use `!default` keyword on every variables) for basic needs ([Bootstrap doc](https://getbootstrap.com/docs/4.1/getting-started/theming/#variable-defaults)). What if we want to override a Bootstrap variable and assign it another Bootstrap variable?

 * Before importing Bootstrap variables scss file: won't work since the another variable is not defined yet.
 * After importing Bootstrap variables scss file: won't work since the variable may have been assign to a third variable (OP issue).

**Comment by nex3** [comment]
That's still not something we intend to support. If new variables changed the definition of old variables, the following stylesheet wouldn't have a clear meaning:

```scss
$variable: false;
@if $variable {
  $variable: false;
}
$variable: true;
```

It would also be a colossal backwards-incompatible change to the language semantics of Sass.
