### ISSUE TITLE
Valid comments in indented syntax?

### ISSUE THREAD

**Issue by hediyi** [sass/sass#2122]
I don't really use Sass, I'm working on Atom's language support for Sass, trying to understand how comments work in indented syntax, but the [doc of indented syntax](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html#comments) doesn't say much.

To my understanding, (silent or not is not important here)
- `// …`
  - can be used at the end of a non-empty (having other `\S` chars) line
  - does not terminate until a line outdents its previous line
- `/* … */`
  - does not require a closing delimiter
  - should not be used at the end of a non-empty line
  - `*/` must be of the same indent level as the second line of the comment if placed on a separate line

Could anyone please correct me if I'm wrong or missing something?

**Comment by chriseppstein** [comment]
> `//` can be used at the end of a non-empty (having other \S chars) line
> `/*` should not be used at the end of a non-empty line

This is confusing, but non-whitespace can precede a comment (`//` or `/*`) in an indented syntax in only certain contexts. Specifically a selector cannot end with a comment, directives can't. (properties can, media queries can) See #326 for some discussion on it.

It's a buggy mess. to be honest, I think it'd be ok if the highlighter just doesn't highlight comments at the end of non-blank lines rather than trying to re-implement the nonsense going on here which is completely an artifact of our implementation (shared parser for property values and media queries).

The rest of your understand seems good.

**Comment by hediyi** [comment]
Thanks!
