### ISSUE TITLE
CSS Counters and greedy color optimizer

### ISSUE THREAD

**Issue by shayarnett** [sass/sass#2128]
At the end of a far too long debugging session, I ran into a rather obscure bug that prevents the use of CSS counters in certain situations.

The issue bubbles up when you are using a CSS counter with a variable name that just so happens to cross paths with the, imo greedy, color optimizers list of keywords. The extremely fun part is this only manifests in the :compressed production files, making troubleshooting in development and/or testing counter functionality extremely difficult. So in this case not only are we adding artificial constraints to CSS counters, we are also creating a world where development, test, and production do not maintain parity.

``` sass
ol
  counter-reset: fuchsia

li
  counter-increment: fuchsia
  &:before
    content: counter(fuchsia)
```

Example of the optimizations changes can be seen [here](http://sassmeister.com/gist/9db66bc46f0a31da1738ebd8ce090023) while toggling the :compressed format

**Comment by chriseppstein** [comment]
We've documented this [quirk of unquoted color names](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#colors) when intending to use them as identifiers. In general, Sass expressions (which `counter(fuchsia)` is) are unaware of their specific meaning within CSS -- we don't know when CSS would interpret something as a color or when it would interpret it as an identifier. Furthermore we have a rule in Sass that an expression doesn't have different meanings based on the context. This makes refactoring more predictable. For example

``` scss
li { content: counter(fuchsia) }
```

should be the same as:

``` scss
$content: counter(fuchsia);
li { content: $content }
```

Because of this rule we always parse `counter(fuchsia)` the same.

Anyways, It's a quirk. We aim for 100% compat with CSS semantics but in some cases, especially where a particular behavior has existed from the very beginning of Sass when we didn't know as much about what we were doing, we got it wrong. And so we have to decide now is whether we want to make an entire community upgrade their largely working stylesheets to avoid this issue or to keep it in place. So far, we haven't seen a proposal for how to handle this situation that didn't create a new quirk or cause more thrash across the community than was justified.
