### ISSUE TITLE
feature request: add --file-ext to config for .scss to .css and .min.css

### ISSUE THREAD

**Issue by mikebranderhorst** [sass/sass#215]
I like to make a feature request to add an extra config option to specify a file extension.

It would be nice to do this:

sass --force --update assets/scss:assets/css --no-cache --unix-newlines --style expanded
sass --force --update assets/scss:assets/css --no-cache --unix-newlines --style compressed --file-ext min.css

(the force feature request is already an issue)

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
