### ISSUE TITLE
Output variables to JSON

### ISSUE THREAD

**Issue by jlove73071** [sass/sass#2155]
It's be very useful to output the final values of all variables into a JSON file. 

Currently, it'd be nice to have a CMS be able to get these variables to use in code -- perhaps to get colors or other information. I've seen solutions to read specific variables, but it'd be nice to write some or all variables to JSON-- it would seem that a compiler option could be added and this could be done rather simply.

**Comment by nex3** [comment]
This is not planned, sorry.

**Comment by esr360** [comment]
I know this is old but just wanted to chime in - you're doing it the wrong way round - you shouldn't be defining data that will be used both by your CMS and Sass in Sass itself; you should have a common single-source-of-truth, such as a json file, which would be consumed by both your Sass and CMS, so the feature you should really by asking is for the [ability to import JSON into Sass](https://github.com/sass/sass/issues/1585), not the ability to export JSON _from_ Sass.

**Comment by zaydek** [comment]
@esr360 I don’t think there’s a right or wrong way to think about this. I think there simply is what’s useful for users and what’s not.

I got curious about this because I can see how Sass building out JSON could be useful. But remembering that Sass _is_ extensible via the JS API, this may be implemented as user-story.

Referencing this comment:

> You can define a function, which will read in Node environment JSON data from whatever you want and pass it to the Sass.
>
> Here is example [how to pass a function](https://github.com/LotusTM/Kotsu/blob/master/tasks/styles.js#L15) within Grunt, and the [function](https://github.com/LotusTM/Kotsu/blob/master/modules/sass-extensions.js) itself, which retrieves data from Grunt (but you can read there external JSON).
>
> _Originally posted by @ArmorDarks in https://github.com/sass/sass/issues/1585#issuecomment-402985350_

So I suppose you could setup a function that analyzes Sass-map and simply JSON-encodes it.
