### ISSUE TITLE
sass $palettes getting the file name and line where the palette does not exist possible?

### ISSUE THREAD

**Issue by douglasdeodato** [sass/sass#2161]
**_functions.scss**

```
@function palette($palette, $shade: 'base') {
  $palette-map: map-get($color-palettes, $palette);
  @if $palette-map == null {
    @error "#{$palette} is not a valid palette name.";
  }
  @return map-get($palette-map, $shade);
}
```

```
$color-palettes: (
    green: (
        x-light  : #c6ffc6,
        light    : #85CF83,
        base     : $green,
        dark     : #72A970
    ),
);
```

if I try print a not valid palette
`body {  background: palette(doesnotexist);}
`
**I get this in my terminal:**
`error _functions.scss (Line 10: doesnotexist is not a valid palette name.)
`

fine great, but is not a way to the debug message be showing the file and the line where is defined that palette? instead  showing the file and line of the condition?

I know is good know what palette does not exist, but could be good see in which file and line is that palette?

I found hard to find this palette in a project with more than 2000 .scss files.

**Comment by KittyGiraudel** [comment]
> fine great, but is not a way to the debug message be showing the file and the line where is defined that palette? instead showing the file and line of the condition?

There is no way to do that. `@error` prints a stack trace, that is a reversed history of what happened before the compiler ended up crashing. You could tweak your error message to give more information about how to fix the error. 

> I found hard to find this palette in a project with more than 2000 .scss files.

I think your problem lives somewhere there. Sass is a great tool to divide your application styling layer into several files, making the whole process of maintaining code much easier. Instead of trying to have `@error` do things it’s not supposed to do, I’d reorganise the code so that the palette is easy to find.
