### ISSUE TITLE
Bare CSS color names should not be compressed when used in string expressions

### ISSUE THREAD

**Issue by bwbuchanan** [sass/sass#2196]
Given this SCSS:

```
$prefix: 'b-';

@mixin class-maker($class-name) {
  .#{$prefix + $class-name} {
    @content;
  }
}

@include class-maker(normal) {
  background: #eee;
}

@include class-maker(black) {
  background: black;
}
```

The output with `sass -t expanded` is:

```
.b-normal {
  background: #eee;
}

.b-black {
  background: black;
}
```

The above output is correct. But the output with `sass -t compressed` is corrupted:

```
.b-normal{background:#eee}.b-#000{background:black}
```

This makes no sense at all. The string `black` in the class name is replaced by `#000`, presumably because it is lexically identical to the CSS color name, and this results in sass emitting invalid minified CSS.

The use of a mixin and a variable, as in the example above, is not required to manifest this bug. Here is a minimal testcase:

```
.#{'b-' + black} {
  background: black;
}
```

This bug is also present in libsass, which also produces correct expanded output and corrupted compressed output.

As a workaround, SCSS authors can use quotes when passing strings to functions/mixins that will be performing string concatenation, when the argument matches a CSS color name.

**Comment by nex3** [comment]
Sass parses all declaration values the same regardless of context, which means the identifier `black` refers to a color regardless of context. In general, you should use quotes around strings you define unless they're going to be used directly in declaration values.

**Comment by bwbuchanan** [comment]
Even if black refers to a color in all contexts, surely it is nonsensical to rewrite it as #000 in a class name, but not in the property value.

Is it really intended that Sass will sometimes deliberately write illegal CSS when outputting in compressed mode, without any warnings or errors?

**Comment by nex3** [comment]
> Even if black refers to a color in all contexts, surely it is nonsensical to rewrite it as #000 in a class name, but not in the property value.

The only reason it's showing up as "black" in the declaration value is performance—in order to save parsing time, Sass treats declaration values that it can easily prove don't include any Sass-specific features as plain strings, which means they're emitted using exactly the same text that was written in the original stylesheet. If you added parentheses or put the value in a variable, you'd see it as `#000` in the declaration value as well.

> Is it really intended that Sass will sometimes deliberately write illegal CSS when outputting in compressed mode, without any warnings or errors?

Yes, absolutely. This is an inherent property of the flexibility we give our users. If you want, you can write

```scss
div {
  invalid: unquote("}}}}}}}");
}
```

which will produce extremely invalid CSS. But the same features allow users to write some really important, expressive styles.
