### ISSUE TITLE
new to sass: prevent sass --watch to write error to css

### ISSUE THREAD

**Issue by markusweb** [sass/sass#2251]
i am new to sass. i want to use sass in my projects. i don't use COMPASS or RAILS.
so i would simply do a 
`sass --watch .:.`

no i have the problem: if the generation of css fails i get an error written to my css file. eg. 
import "NOT_THERE"
will rause an error
`error ./style.scss (Line 1: File to import not found or unreadable: NOT_THERE.`
in my style.css i get

```
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Error: File to import not found or unreadable: NOT_THERE.\A        ... }
```

i don't want watch to stop completely. if i change full_exception in /var/lib/gems/1.9.1/gems/sass-3.4.23/lib/sass/plugin/configuration.rb to false watch will stop and exists on error. seems that was introdueced with commit https://github.com/sass/sass/commit/f2946e1cf6a6ec682ee31f52e259ceafefdcfed9.

so i would like to see only an error message in the sass output and no updating/generation of css. 
maybe one remark: if i am editing the scss on my produtction system i don't want to see "public" error messages only have the log file containing the error.
ok, you should do changes on a dev or staging system and then push the correct final version to production. but when i do a "quick" hack i don't want to mess up my production system.

do i miss something?

thanxs

markus

**Comment by chriseppstein** [comment]
When using Sass to compile stylesheets in development, we've found that disabling the css output for a compilation error ultimately results in users not realizing things are broken because of a simple compilation error -- this is because the log is left out of sight much of the time. We certainly could add this option if we had a compelling use case. Unfortunately, "doing a quick hack in production" is not such a use case.

**Comment by glo-www** [comment]
+1 for preventing sass --watch to generate css with error.
