### ISSUE TITLE
@clone handle to copy/clone properties

### ISSUE THREAD

**Issue by caneco** [sass/sass#2312]
After start reading this [thread](https://twitter.com/adamwathan/status/872851073815457793) from **@adamwathan** I got to wonder if something could be done like this.

So **@adamwathan** points out a missing possibility to copy out the properties from a class rather than extending it, helping out the possibility of creating utilities and inject them in components easily, _"mixin'_ free some of the most popular CSS frameworks out there.

I've found that this feature was being addressed back in 2015 at #1852 , but it was with another a purpose (maybe that why it was closed?)

---

So normally we @extend SASS like this:
```SCSS
.foo {
    @extend .baz;
    background-color: green;
}
.bar {
    color: blue;
}
.baz {
    color: red;
}
```
That outputs the the following CSS:
```CSS
.foo {
    background-color: green;
}
.bar {
    color: blue;
}
.baz, .foo {
    color: red;
}
```

---

But what if we can @clone another class properties, pretty much like LESS?
```SCSS
.foo {
    @clone .baz; // or @copy .baz;
    background-color: green;
}
.bar {
    color: blue;
}
.baz {
    color: red;
}
```

That the will output this:
```CSS
.foo {
    color: red;
    background-color: green;

}
.bar {
    color: blue;
}
.baz {
    color: red;
}
```
---

**Comment by nex3** [comment]
This is something we explicitly decided not to do. Treating classes as bags of properties violates CSS semantics—classes are one kind of selector that interacts with other kinds, and we designed `@extend` explicitly so that it respected that interaction. If you want to copy chunks of properties, well, that's what mixins are for. Adding another concept that's between those two would just muddy the waters.

**Comment by mindplay-dk** [comment]
> If you want to copy chunks of properties, well, that's what mixins are for.

Having to rewrite (or hack) third-party (S)CSS and wrap everything in mixins isn't practical.

> Adding another concept that's between those two would just muddy the waters.

That's your opinion, but people nevertheless seek this feature, and it's a key reason why some choose LESS instead.

For one, the precedence issues caused by `@import` in my opinion are somewhat undeniable.

How about extending `@include` to allow something like `@include .foo`?

Or think of some other way to make this functionality (or something even better) available.

Simply dismissing the feature entirely seems a little too easy - people often ask for this feature, in fact a few developers on our team want to go back to LESS for this.

I think there is a real need here, that is not covered by `@extend` - can't we think of some way to address that need without "violating CSS semantics"?

**Comment by ArmorDarks** [comment]
> How about extending @include to allow something like @include .foo?

That's sound quite ok for me. Why not? I think that idea of treating classes as mixins is quite cool. Though, it will require solving of complexity with few selectors. What if few `.foo` exists?

This is also partially related to my proposal of viewing CSS as data here https://github.com/sass/sass/issues/2252. If all classes will become an object of ids (selectors) and their properties (CSS properties), it should be quite straightforward to use mixin and selectors interchangeable, since in some sense both of them will return just data, which will be used by `@include`. The only difference would be that mixin will be a function, which constructs that data, while class will be direct input.

@nex3 

> Treating classes as bags of properties violates CSS semantics—classes are one kind of selector that interacts with other kinds

I don't see how it violates CSS semantics. I'd like to hear more on it.

> Adding another concept that's between those two would just muddy the waters.

Depends on perspective. I see that as narrowing the gap and unification.

**Comment by nex3** [comment]
> Having to rewrite (or hack) third-party (S)CSS and wrap everything in mixins isn't practical.

We're fortunate to live in a time when contributing upstream or forking projects is easier than ever. We have a solution to the problem of "I want to use a stylesheet in a way that the author didn't intend" that's entirely external to the language. This is *great*—it means that we don't have to add complexity to Sass to support a pattern of usage almost always puts the down-stream user at strong risk of breakage going forward.

I won't deny that there are times when making upstream contributions doesn't work. But it's also the case that adding new language features, especially those that are only subtly different than existing feature, comes at a huge cost. It makes it harder for authors to understand the entire language and to know which feature is right for their use-case (a struggle we already see with just `@extend` and mixins). And every feature makes it harder for readers to know what's going on in a stylesheet.

> Or think of some other way to make this functionality (or something even better) available.

We did do this, and `@extend` is what we came up with. It covers the vast majority of cases where you want something like this. There are some instances where the cascade or selector specificity makes it tricky, but we offer as many guarantees as possible to give the user control over those cases.

It's a very rare language feature that covers 100% of use-cases perfectly with no gotchas. That's doubly the case when compiling to a language like CSS that's so picky about small details and that doesn't provide ways of tightly controlling its behavior. As tempting as it is, the correct reaction here isn't to keep adding features until all use-cases are covered; that gives you a language that's next to impossible to learn or understand, where everyone uses a different 30% of it. At some point, as the designer, I have to say "we cover *enough* cases well". This is past that line.

> I don't see how it violates CSS semantics. I'd like to hear more on it.

The proposed feature treats CSS classes as opaque identifiers for collections of properties—essentially another name for mixins. But that's *very different* from how CSS thinks of classes. CSS thinks of them as one type of selector, which is a much broader set of things. So fundamentally, any feature that treats classes as special references that work differently from any other selector doesn't match CSS semantics.

Given that, you might ask "why not let me clone any selector's properties?" But this would still treat those selectors as opaque identifiers. To CSS, a selector means something very specific: it means "all HTML elements that are X", where X depends on the specific selector. Treating a selector as a way to index the database of style rules doesn't match this.

More concretely speaking, if your stylesheet contains both `.foo { ... }` and `.foo.bar { ... }`, any reference to "`.foo`'s properties" needs to do the right thing with the properties in the `.foo.bar` rule as well. Otherwise, it's treating `.foo` differently than CSS does—that is to say, violating CSS semantics.

This is why we created `@extend` instead of anything else. `@extend .foo` explicitly means "style elements matching this selector as though they also matched `.foo`", which includes *all* selectors that incorporate `.foo`. Because that's what selectors mean to CSS: a selection of HTML elements. If you want to refer to collections of properties, you need a different metaphor, which is why we created mixins.

**Comment by mindplay-dk** [comment]
> If you want to refer to collections of properties, you need a different metaphor, which is why we created mixins.

That addresses the use-case where a set of properties are *exclusively* for mixing in, and have no meaning on their own.

It does not address the need to mix in properties from an existing utility class (such as, commonly, buttons or grid classes) which might also be meaningful on it's own.

It also does not address a need to use classes from hand-written CSS and mix them into your own selectors.

The whole "not semantic" story is kind of lost one me, since `@extend` also [does not](https://twitter.com/adamwathan/status/872853599365337089) (and, by definition, cannot) respect the normal precedence rules of CSS. With mix-ins, precedence is more predictable, but without the ability to mix in third-party selectors, it requires you to rewrite any third-party or pre-existing CSS completely, which is hardly practical.

I personally avoid `@extend` entirely, because it's so unpredictable. I get the impression from other team members (who have more CSS expertise than me) that they strongly prefer mixins over `@extend` because they're predictable. I think it's one of the main things that drive people towards LESS. That's just my personal impression, of course...

**Comment by nex3** [comment]
> It does not address the need to mix in properties from an existing utility class (such as, commonly, buttons or grid classes) which might also be meaningful on it's own.

It's easy to define a mixin and use that to define the utility class:

```scss
@mixin foo { /*...*/ }
.foo {@include foo;}
```

> It also does not address a need to use classes from hand-written CSS and mix them into your own selectors.

Making it easier to use upstream stylesheets in ways they weren't intended to be used is not generally worth adding extra complexity to the language, for the reasons I mentioned in my last response.

> The whole "not semantic" story is kind of lost one me, since `@extend` also [does not](https://twitter.com/adamwathan/status/872853599365337089) (and, by definition, cannot) respect the normal precedence rules of CSS. With mix-ins, precedence is more predictable, but without the ability to mix in third-party selectors, it requires you to rewrite any third-party or pre-existing CSS completely, which is hardly practical.

That's actually a great example of the way that `@extend` *does* match CSS's precedence rules. When you write `.foo {@extend .baz}`, you're saying "style all elements with class `foo` as though they also had class `baz`." So you'd expect it to be equivalent to writing:

```css
.foo {color: green}
.bar {color: blue}
.baz {color: red}
```

```html
<span class="foo bar baz">text</span>
```

And in fact, [the `@extend` version](https://codepen.io/nex3/pen/NvjEwW) is styled the same as [the manual version](https://codepen.io/nex3/pen/RZVqLq). We match CSS's precedence rules. I'm not going to claim that those precedence rules are necessarily predictable, but I will claim that it's better to match CSS's semantics even when they aren't ideal than to throw them by the wayside entirely. Sass's userbase is largely people who know CSS well and Sass only okay, so the closer Sass's understanding of what selectors are and how they work hews to CSS's understanding the easier it is for people to use.

**Comment by mindplay-dk** [comment]
> It's easy to define a mixin and use that to define the utility class

It's not easy to rewrite or hack all third-party CSS (or SCSS) files.

**Comment by nex3** [comment]
> It's not easy to rewrite or hack all third-party CSS (or SCSS) files.

As I've mentioned, it's not generally good design to optimize for using upstream stylesheets in ways they weren't intended. Copying styles only from rules that match the literal text of a selector, like `.foo`, means that you're totally ignoring any other style rules that refer to `.foo`. The upstream stylesheet might have a rule for `a.foo { ... }` that's crucial for making links visible, but `@clone` loses that context entirely. It's barely better than copy-pasting the properties by hand.

**Comment by ArmorDarks** [comment]
The real problem with `@extend` is that it acts like a wormhole and compromises rules order. Because CSS heavily relied on specificity, it sometimes makes behavior of `@extend` dangerous — it does not guarantee that the selector, which comes last, but extending something, will actually receive extended styling or will not compromise styles of rules above — because, well, extended part will be put in place of extended selector, somewhere randomly in the stylesheet, but not in place of the actual extender.

I think that `@clone` proposal (or I'd rather call it `@include .YourClassNames`) is quite viable — it might provide _exactly_ behavior of the `@extend`, but reversed — it will "suck" in all rules, that would be extended otherwise, take their properties and put them into the extender.

I mean that it should treat classes the same way as they are treated by `@extend`, and `@include .foo` should pick up `.foo` and `a.foo` rules, but `@include a.foo` should pick only `a.foo`.

The difference only in the output — `@include` will not breach holes in the stylesheet and instead will incorporate properties in the extender, thus guaranteeing lack of issues with specificity.

Meanwhile, yeap, it will solve the issue with the 3rd-party code and give developers more flexibility. But it's just a solution of a meanwhile issue, not the main one.

> But that's very different from how CSS thinks of classes. CSS thinks of them as one type of selector, which is a much broader set of things. So fundamentally, any feature that treats classes as special references that work differently from any other selector doesn't match CSS semantics.

I wonder where that whole thought about CSS semantics came from.

**Comment by nex3** [comment]
I don't like the idea of providing a variant of `@extend` that has *almost* the same semantics but with subtly different cascade behavior and substantially different output-size implications. It's also not at all clear to me how you would express the proposed inverse `@extend` in terms of styling elements (rather than moving text around in CSS source). The location the styles `@extend` produces cascade the same way as the originals, which matches what would happen if you added the extended selector to the element manually, but that's not true for the inverse.

> I wonder where that whole thought about CSS semantics came from.

The fundamental motivation behind `@extend` is to provide a substitute for modifying the HTML. `.bar {@extend .foo}` should, as close as possible, work like changing all instances of `class="bar"` in your HTML to `class="foo bar"`. This means treating selectors and style rules the same way CSS does.

More broadly, we want to encourage authors to think about applying styles to HTML elements. We don't want them to have to think about manipulating the text of CSS documents any more than absolutely necessary. This means we try to define Sass operations in terms of styles rather than in terms of text munging.

**Comment by mindplay-dk** [comment]
> I don't like the idea of providing a variant of `@extend` that has almost the same semantics but with subtly different cascade behavior and substantially different output-size implications

I don't like the idea of `@extend` at all - a directive that reaches out and causes side-effects in other rules, even rules in other files.

> More broadly, we want to encourage authors to think about applying styles to HTML elements. We don't want them to have to think about manipulating the text of CSS documents any more than absolutely necessary

From my perspective, that's precisely what `@extend` does - it reaches out to another file and modifies it. It places control at the wrong end, so to speak - reaching out and causing side-effects elsewhere. It directly goes against the semantics of CSS itself, and it's inconsistent with the behavior of other directives in generally.

It's confusing and error prone. I've never heard anybody say that this is their favorite SASS feature - in my experience, most experienced SASS users shy away from it entirely.

Anyways, I have nothing more to contribute to this discussion, so I'll withdraw.

**Comment by caneco** [comment]
> The fundamental motivation behind @extend is to provide a substitute for modifying the HTML. .bar {@extend .foo}

But the main goal here it's not to have a BE**M** helper … What we're try to have in SASS it's a way for us to have like high order classes _or_ utilities that could be **copied** to another element –
 and yes, instead of making a custom mixin for that purpose.

---

I would ❤️ to have an this sort to SASS in my files:

```SASS
$basePadding: 10px;
// ...
.padding-horizontal {
    padding-left: $basePadding;
    padding-right: $basePadding;
}
// ...
.card-body {
    @copy .padding-horizontal;
    // ...
}
```

and get this CSS:

```CSS
.padding-horizontal {
    padding-right: 10px;
    padding-left: 10px;
}
// ...
.card-body {
    padding-right: 10px;
    padding-left: 10px;
    // ...
}
```

**than have this CSS … with the approach of `@extend`**

```CSS
.padding-horizontal, .card-body, .card-something, .card-yadda, .card-queenofhearts, ... {
    padding-right: 10px;
    padding-left: 10px;
}
// ...
.card-body {
    // ...
}
```

**Comment by ArmorDarks** [comment]
Just wondered where did I see this already, and then recalled [`composes`](https://github.com/css-modules/css-modules#composition) of CSS Modules

> It's confusing and error prone. I've never heard anybody say that this is their favorite SASS feature - in my experience, most experienced SASS users shy away from it entirely.

Unfortunately it is true. Not to [go](https://csswizardry.com/2014/11/when-to-use-extend-when-to-use-a-mixin/) very [far](https://csswizardry.com/2016/02/mixins-better-for-performance/).

Still, I think as every tool, `@extend` has it use case and should remain. But it definitely doesn't cut it for the community.

**Comment by ArmorDarks** [comment]
> It's also not at all clear to me how you would express the proposed inverse @extend in terms of styling elements (rather than moving text around in CSS source)

I'd say, that it should grab all properties along the way, in the order of how cascading happening, even if there will be duplicates. Then browser would decide which one to use in a natural way, or CSS optimizing tool like CSSO can be used to strip unused values:

```scss

.foo { border: 1px; }

.foo { border: 2px; }

.bar { @include .foo }
```

should produce

```css
.foo { border: 1px; }

.foo { border: 2px; }

.bar {
  border: 1px;
  border: 2px;
}
```

**Comment by mindplay-dk** [comment]
> What we're try to have in SASS it's a way for us to have like high order classes or utilities that could be copied to another element – and yes, instead of making a custom mixin for that purpose.

What @caneco said 👍 

My personal point of view of these new "utility-first" frameworks (and I'm totally okay with others having a different point of view!) is they should be used *both* as utilities, and to derive component-specific rules.

It's hard to make that argument when the latter isn't really possible with SASS, except of course by "duplicating" every mixin as a rule and an actual mixin.

Also, for smaller projects, it's often meaningful to use component-style CSS only - in my personal opinion, a project would need to be *very* large and *very* complex to justify deploying one of these utility-first frameworks and building the HTML with that approach in the first place; I'd have to be *very* concerned about ensure consistency between *lots* of developers to go that route in the first place.

This was actually one of the (only) things I liked about LESS - being able to include one of these utility CSS libs and using them exclusively as mixins for my own component CSS.

**Comment by mindplay-dk** [comment]
> I'd say, that it should grab all properties along the way, in the order of how cascading happening, even if there will be duplicates.

For consistency with current SASS behavior, I agree.

> Then browser would decide which one to use in a natural way, or CSS optimizing tool like CSSO can be used to strip unused values

I've personally always wondered why SASS doesn't just remove redundant rules from the emitted CSS - but that's an entirely separate issue, and it shouldn't clutter this discussion. (if this were to change in the future, I'd expect this change to be made consistently throughout SASS, whether we have this feature or not.)

**Comment by ArmorDarks** [comment]
> I've personally always wondered why SASS doesn't just remove redundant rules from the emitted CSS - but that's an entirely separate issue, and it shouldn't clutter this discussion. (if this were to change in the future, I'd expect this change to be made consistently throughout SASS, whether we have this feature or not.)

Just two words. IE hacks.

**Comment by mindplay-dk** [comment]
@ArmorDarks good point, yes - but besides this discussion :-)

**Comment by mindplay-dk** [comment]
If somebody thinks there's no need for this, consider the whole "utility-first" CSS movement that's happening right now - for example, [tailwind](https://tailwindcss.com/) needs to invent custom tooling to allow mixing utility-classes into components. It would have been sweet if this could have been done with just SASS.

**Comment by caneco** [comment]
> If somebody thinks there's no need for this, consider the whole "utility-first" CSS movement that's > happening right now - for example, tailwind needs to invent custom tooling to allow mixing utility-> classes into components. It would have been sweet if this could have been done with just SASS.

Yes… Tailwind could be simplified with this feature alone…

**Comment by jak-kal** [comment]
Found this thread while looking for an identical feature. I still don't understand why an alternative to \@extend, such as \@clone as suggested above, is a bad idea... \@extend, by design, does not respect the order of my selectors - and to my knowledge this contradicts best practices.

Must I use a mixin to include 1-2 lines of code (at most!)? I find it incredibly verbose (not always a bad thing - I know!) and overkill, for that matter.

Does anybody have a reasonable explanation as to why this cannot/ will not be available? Like many, I make heavy use of utility classes and in order to maintain consistency, I'd like to make use of them not only in my markup, but in my style sheets aswell.

As we already know; \@extend contradicts the order of styles with respect to their specificity, and mixins defeat the purpose of having my utility classes available in the first place. I want to keep my source as DRY as possible, after all.

**Comment by ArmorDarks** [comment]
@jak-kal issues with utility classes are mostly solvable by using `%placeholder` classes and extending them, though, still it can compromise order sometimes. But I'd say it's rather a matter of well-built architecture.

People here mostly complains that it isn't possible when you use 3rd-party CSS and can't make any modifications there.

**Comment by jak-kal** [comment]
@ArmorDarks thanks for your reply. Unfortunately SASS will still group selectors that share the same `%placeholder`. With regards to well-built architecture - does anybody have any suggestions on how I could possibly achieve the same result (cloning utility classes in my CSS with the purpose of maintaining consistency whilst retaining source order)?

Another issue with using `%placeholder` is that it is still a very WET approach. I don't want to have to duplicate my utilities in either a _mixin_ or a `%placeholder`.

Fair enough if the issues lie with regards to how SASS compiles the CSS. Otherwise, I am at a bit of a loss. Luckily most of my utilities contain values that are already stored as variables or SASS maps - so I suppose utilising those values might well be another option.

**Comment by m-farahmand** [comment]
why it's closed?

**Comment by gavinhewitt** [comment]
Not sure why this is closed since this is a feature many people would like to have.

**Comment by saeed-serpooshan** [comment]
@nex3: so many words to reject such a useful feature! 
Please, just add a simple ability and let users have more tools to write their css. 
Something like as `@copy .class1` will not endanger/violate any thing, it is just a shortcut to avoid creating an additional temporary mixin! that's it. 

Also, if you think there are some issues with this, ok, but other features like as @extend have also their own side effects which are worse in many cases!

**Comment by gavinhewitt** [comment]
It’s just a useful feature that the community asks for. That it’s there does not mean you have to use it if you don’t like the idea of copying over styles. I don’t understand the resistance.

**Comment by Gameghostify** [comment]
Also found this thread while looking for a similar feature.

CSS Modules does it too, and its beautiful.

Having something like `@compose`, `@clone` or `@copy` really would be benefitial.

**Comment by nex3** [comment]
For reasons I've already explained thoroughly, this is not a feature we plan to add. Mixins already exist for copying bags of properties around. I'm locking this issue, because it's not useful to keep hearing complaints about this.
