### ISSUE TITLE
Interpolation of nth-child math fails

### ISSUE THREAD

**Issue by larspetrus** [sass/sass#2327]
This

    $first-two-nth: -n+2;
    td:nth-child(#{$first-two-nth}) { text-align: right; }

used to work is SASS 3.2.19 (according to my Gemfile.lock), but now it gives

    Invalid CSS after "td:nth-child(-n": expected ")", was "2)"

I made a [SassMeister gist](https://gist.github.com/larspetrus/5fc40741550019db83ce93ddf5a16f02), in case that helps.

**Comment by nex3** [comment]
**tl;dr**: The `:nth-child()` argument syntax is not a valid CSS value outside of that context.

When you write `-n+2` in a script context (such as on the right-hand side of a variable), Sass parses it as script. In this case, it takes the identifier `-n` and adds it to the number `2`, producing the identifier `-n2`. So when you write `td:nth-child(#{$first-two-nth})`, that becomes `td:nth-child(-n2)` which is invalid.

To avoid this, you can write the value as a string (`"-n+2"`). Then it'll be included literally in the selector, rather than being parsed as an expression first.
