### ISSUE TITLE
Merge Better Sass Docs

### ISSUE THREAD

**Issue by nex3** [sass/sass#233]
http://www.kaelig.fr/bettersassdocs looks much nicer than the current docs on the website. We should merge what niceness we can into the canonical docs.

**Comment by kaelig** [comment]
Wow, thanks!

I am so pleased that you saw it and enjoyed how it looks.

I think that the very "technical" look of the yardoc reference is what's driving front end devs and webdesigners off to Less (which, IMO, is a good start but not as powerful as Sass). Less has a shiny website with a dedicated app and that just seems easier to the average front-end web developer… I wish we could make Sass as attractive for new comers!

For now, BetterSassDocs don't support search, nor do they include the entire Sass reference (only the "first reference page"). About the styling of the original docs, I'd be happy to help you. Here is my email: kaelig@deloumeau.fr

Cheers from France! (that explains my bad English…)

**Comment by twoolie** [comment]
I like the updated docs, but they don't really go far enough to catch up with less. The less docs are downright _pretty_ and in plenty large font, so reading is a breeze. 

I don't think emulating the old docstyle with a bootstrap theme is the best way to do that. If your going to give them a facelift, it would be best to give them a usability lift at the same time, and try to keep stylistic parity with the rest of the sass site, or acknowlege that the sass homepage needs a makeover too (layout is great but an unfortunate color scheme IMHO).

---

On a related note, this is the point where sass should be trying to differentiate itself from less by showing off it's helpful differences. So why is the default notation on the sass homepage the .scss notation?!!

**Comment by kaelig** [comment]
You're right, I've mainly restyled it for my own usage, we can improve it and make it really great but I only had a few hours to do it and wanted it to be easy to maintain (copy-paste from the original Yardoc).

About the .scss notation : it it the less scary notation. I think we should stick with it and only let advanced users use .sass if they want to.

**Comment by kaelig** [comment]
Oh and also, I think the whole "using sass" chapter is scary and not useful for 95% of users. We should put it elsewhere.

We should emphasize on some easy steps like in the sass website:
- install sass
- compile your first stylesheets
- see what's cool
- and then the detailed docs…

**Comment by twoolie** [comment]
> About the .scss notation : it it the less scary notation.

<rant> SASS is supposed to be Synatactially Awesome Style Sheets, not Syntactially Crippled Style Sheets.</rant>

That being said, when you call your language sass, you want to pimp the .sass files, not the fallback compatability mode (scss).

**Comment by markiz** [comment]
> About the .scss notation : it it the less scary notation. I think we should stick with it and only let advanced users use .sass if they want to.

What's so scary about typing less curly brackets and semicolons?

**Comment by kaelig** [comment]
It's adding an abstraction layer that most of us don't want to learn and adapt to.

Changing a .css filename in .scss is convenient and "team friendly". You may like the Sass notation but you can't force your company to follow your personal preferences.

**Comment by markiz** [comment]
@Kaelig 
I don't follow your logic. How come using mixins and other advanced stuff is company-friendly and using SASS syntactic sugar is not.

**Comment by kaelig** [comment]
Actually, this is quite simple when we analyze it from a social point of view: humans have a desire for change, yet they don't welcome changes that are forced into their lives.

I had the same problem with a co-worker who I decided to force into full-coffeescript. Now he can't code any JS on our project until he learns coffeescript.

The change paradox applies to our case: if you deliver a Sass project to a developer and tell him "this is awesome, you'll save so much time with Sass and you won't ever be able to work without it", his first reaction will be "it worked before, why do I have to learn a new language?". 

Sass is too much change at once for some people: 
- two-spaces indentation,
- converting from .css to .sass isn't as seamless as it is with .scss. You lost the ability to copy-paste old code into new sass projects.
- syntax highlighting: you have to install new bundles to your text-editor
- some developers coming from Less.js and other preprocessors may also be lost with .sass
- community: you're narrowing your circle with every abstraction layer you add to your coding habits

Scss is team-friendly because any developer can read and understand most of it without getting into the docs.

I hope I made my point.

PS: I love the .sass notation, I'm only advocating simplicity and maintainability on team projects.

**Comment by twoolie** [comment]
- two-spaces indentation,
  - Actually, Any-whitespace-indentation (I use Tabs)
- converting from .css to .sass isn't as seamless as it is with .scss. You lost the ability to copy-paste old code into new sass projects.
  - there is a converter you know.... (sass-convert)
- syntax highlighting: you have to install new bundles to your text-editor
  - All good editors have syntax highlighting by default now (Pycharm, Aptana, vim/gedit if enabled)
- some developers coming from Less.js and other preprocessors may also be lost with .sass
  - Not if we have good docs and tutorials on the site (hint hint) and we stress sass-first-syntax
- community: you're narrowing your circle with every abstraction layer you add to your coding habits
  - the whole point is to get rid of as much abstraction, like braces EVERYWHERE.

**Comment by kaelig** [comment]
Thanks for answering! I didn't know we could use any whitespace indentation!

About sass-convert: I know it exists, I meant that it's not as easy to perform as "copy-paste".

Text Editors often need extra bundles (textmate), "sugars" (capuccino), or "writing modes" (coda) to understand new syntaxes. Scss is almost the same as CSS, you can edit a file without extra bundles (though it's better to have one).

You don't get my point about abstraction. The more a preprocessor gets far from CSS, the more abstracted it is, and the more it drives beginners off.

Copy-paste is the most used command in the world. Because of its syntactic layer of abstraction, Sass prevents us from using it.

When it comes to personal taste, I also like the Sass notation… but when it comes to pragmatism, I guess .scss is the way to go: transitioning from CSS to SCSS is by far easier for any front-end developer than going from CSS to SASS.

There is less learning involved for the same results, that's what counts for me and my teammates.

**Comment by twoolie** [comment]
You're treating skilled IT professionals like cut-paste monkeys. It's not that it's harder to use sass, just that it's different. 

Your insistence on cut-paste compatability is like saying "oh this new power-wrench will let you turn bolts 2x faster but you have to spend an hour learning how to use it, so I recommend using a manual spanner until then." 
The whole point of sass is to eliminate copy-paste, and to write less code. 

We should be showing why SASS is different from other frameworks, and why those differences are great, otherwise people will say "we may as well be using LESS because twitter is." and we will have lost those developers.

**Comment by kaelig** [comment]
People who write CSS code aren't all skilled IT professionals.

That you may have forgotten.

**Comment by nex3** [comment]
Ignoring the Sass vs SCSS conversation, as I've said everything I want to about that elsewhere...

@Kaelig, I probably won't have time to integrate the docs any time soon myself, but I would happily accept any patches to the docs or website for either formatting or content.

**Comment by paulirish** [comment]
@Kaelig, i pointed your docs to Chris and he pointed me here. They look great and I think everyone is onboard to get them integrated into the site. 
Do you want to work up some patches to make that happen?  
Afterwards I'm sure a few folks would like to have a go at improving the typography, but this is def a great start. :)

**Comment by kaelig** [comment]
That's great (or "That's rad" as you would say)!

I'll create a repository so everyone will be able to contribute and fix things.

Typography can definitely be improved, I'll try to work on that. I originally created this website a few hours before packing for Christmas family dinner, and didn't have much time to work on the details since!

I'll post the url here when it's ready.

**Comment by twoolie** [comment]
> People who write CSS code aren't all skilled IT professionals.

But the people who use sass are far more likely to be

**Comment by CaioBianchi** [comment]
I just think that the documentation should have both syntaxes, I _really_ don't care much about how it is styled to tell the truth.
Just like Compass's does.

**Comment by kaelig** [comment]
Hi everyone!

As suggested by @paulirish, I tried to improve the typography a bit. I also made some tweaks to the design so it matches better with the Sass website.

As promised, I published it on GitHub: https://github.com/Kaelig/Sass-reference

@chriseppstein and @nex3, I added as contributors on the project, since you are the authors of the reference.

What's our next move? Do you want to publish it on sass-lang.com ? (it's ok with me)

**Comment by paulirish** [comment]
I _think_ the site is available over here:
https://github.com/nex3/sass/tree/sass-pages

might to see how to integrate the two

On Sun, Jan 22, 2012 at 7:43 AM, Kaelig <
reply@reply.github.com

**Comment by kaelig** [comment]
The Sass reference file on github has changed but not on the website yet. Should I wait before I publish the changes on bettersassdocs?

bis: What's our next move? Do you want to publish it on sass-lang.com ?

**Comment by nex3** [comment]
The reference in the master branch is for the upcoming 3.2 release; the one on the website is generated from the stable branch.

**Comment by Anahkiasen** [comment]
As I'm currently one of the target for SASS I think I can give a better insight : I chose LESS first because indeed of the appeal of the website first, and how easy it seems. Being a PHP developer and had no problem switching from CSS to LESS.
However after a while I felt limited and the possibilities of SASS got too appealing so I switched but I can tell you the transition wasn't smooth. The SASS Reference documentation is indeed pretty scary looking and doesn't really invite to know more. Some things aren't explained enough and I ran into a lot of problems that are apparently common but not mentioned by the doc.

I think overall the whole process of how to first launch the terminal, what are gems, etc. is not well explained enough. Not everyone knows what Ruby or Rubygems are, how to manage them, install them, update them etc. I coped with it and now I can manage but for a beginner that just wants to launch himself into preprocessor it's a pretty steep learning curve to finally start using sass comfortably.

**Comment by emagnier** [comment]
I agree with the previous comment. I also started to use Less for the same reasons: ease to use & understand the docs, a more attractive and ergonomic web site... 
And because I'm working on ASP.Net platforms, I was a bit hesitant to get into a Ruby installation on each dev machines (and still today on build machines).

I'm also thinking that a more attractive design and a better documentation (how to install on each platforms, a search engine, many examples, present some alternative compilers like Scoot, Compass.App, Mindscape WebWorkbench...) would facilitate its adoption and help his popularity.

Today I prefer to use Sass because I find it more powerful, elegant and suitable for my needs (especially with some extended functionalities of Compass).

Thanks a lot to all contributors of this project, and for this more elegant doc.

**Comment by nex3** [comment]
There's currently a task force being led by @jina with the goal of redesigning the Sass website and documentation. One of the primary concerns is the experience of a user getting started without getting bogged down in unnecessary complexity.

**Comment by emagnier** [comment]
Good news, I look forward to seeing the new design!

**Comment by jina** [comment]
Yep, yep! If you are interested, we have a Twitter account you can follow to get updated on the progress. [@teamsassdesign](http://twitter.com/teamsassdesign)

We're super stoked. :)

@Kaelig — when the design crew is ready to discuss docs, we won't leave you out of the discussion. You've done great work so far. :)

**Comment by nex3** [comment]
I'm closing this out since the look and feel of the docs is now handled on [sass/sass-site](/sass/sass-site).
