### ISSUE TITLE
Precedence lost when combining @extend with pseudo-classes

### ISSUE THREAD

**Issue by DanielGibbsNZ** [sass/sass#2331]
When extend a class that has a sub-rule using multiple pseudo-classes that extends another class, only one pseudo-class is used in the resulting output, meaning that the precedence is different than expected.

Input:

```
.a {
    background: orange;
}
.b {
    &:disabled, &:disabled:hover {
        @extend .a; 
    }
}
.c .d {
    @extend .b; 
}
```

Actual output:

```
.a, .b:disabled, .c .d:disabled, .b:disabled:hover {
  background: orange; }
```

Expected output:

```
.a, .b:disabled, .c .d:disabled, .b:disabled:hover, .c .d:disabled:hover {
  background: orange; }
```

This is an issue because the precedence of `:disabled:hover` is higher than `:disabled` and the absence of it causes unexpected behaviour.

Oddly enough this works correctly when `.c` is changed to `c`.

**Comment by nex3** [comment]
We offer the following guarantee about specificity when using `@extend`: the specificity of the generated selector will be greater than or equal to the specificity of the selectors that generated it. This is the only guarantee we can offer in general, because CSS doesn't provide us fine-grained means of controlling specificity and because we want to be able to trim redundant selectors.

In this case, we're following this guarantee. The source selectors are `.b:disabled:hover`, which has specificity 30, and `.c .d`, which has specificity 20. The generated selector `.c .d:disabled` has specificity 30 as well, which means that Sass considers itself free to trim any other selectors that match a subset of the elements—including `.c .d:disabled:hover`.
