### ISSUE TITLE
Values of variables with contain comment!

### ISSUE THREAD

**Issue by NabiKAZ** [sass/sass#2348]
Some time I need to put a comment in values of variables (for example in [RTLCSS project](https://github.com/MohammadYounes/rtlcss)) be like this in bootstrap project:
```SCSS
$font-size-base: 18px #{'/*rtl:40px*/'} !default;
```
And then use it be like this:
```SCSS
$font-size-large: ceil(($font-size-base * 1.25)) !default; // ~18px
```
And give me this error when compiling:
```
[19:07:48] gulp-ruby-sass: directory

events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: error bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss (Line 53: Undefined operation: "18px /*rtl:40px*/ times 1.25".)
```

I create an issue about this in here: https://github.com/MohammadYounes/rtlcss/issues/101
But I thinks maybe the issue was related with SASS project.

**Comment by nex3** [comment]
When you write `$font-size-base: 18px #{'/*rtl:40px*/'}`, you're creating a list with two elements: the number `18px` and the unquoted string `/*rtl:40px*/`. Multiplying this by 1.25 fails, because it's a list and the multiplication operation expects both sides to be numbers.

At a higher level, if you want to pass around a stringified comment along with a value, you're going to have to be a lot more careful when you're doing operations on that value. There's not really a good way around this, unfortunately.

**Comment by NabiKAZ** [comment]
You said right.
But maybe can do analyze on values of `$font-size-base` and if **just** see comments be like `#{'/*rtl:40px*/'}` or `/*rtl:40px*/'` ignore this in calculation or doing calculate on string of comment.
That's means, if I have this:
```SCSS
$font-size-base: 18px #{'/*rtl:40px*/'} !default;
$font-size-large: ceil(($font-size-base * 1.25)) !default;
```
After this, the `$font-size-large` contain `22px #{'/*rtl:50px*/'} !default`

**Comment by nex3** [comment]
That's too much extra logic to add for a very narrow edge case.

**Comment by NabiKAZ** [comment]
Anyway cover small tips, can assist to quality of program.
