### ISSUE TITLE
Inline comments should be kept inline

### ISSUE THREAD

**Issue by barraponto** [sass/sass#235]
Sometimes comments are meant to be inline. Consider the following code:

```
.myselector {
  display: none; /* javascript will fix this */
}
```

It compiles to:

```
.myselector {
  display: none;
  /* javascript will fix this */
}
```

There are several use cases like this. Can it be done?

**Comment by chriseppstein** [comment]
@nex3 I asked @barraponto to file this after a thread on the compass mailing list. I think this is a case where the meaning of the comment is changed significantly when placed on the next line. Are you opposed to special casing this?

**Comment by nex3** [comment]
I like the idea, but it would be moderately difficult to implement, since it involves somewhat non-local changes when compiling to CSS. It's pretty low priority.

**Comment by necolas** [comment]
+1

**Comment by jitendravyas** [comment]
@barraponto But why do you want to keep comments in final output?

**Comment by barraponto** [comment]
Some stylesheets are meant to be extended/overriden, regardless of the extender writing CSS or SCSS (or using any other preprocessor). Comments are nice documentation, particularly when you're reading a shared stylesheet.

**Comment by chrisslater** [comment]
@barraponto I agree, I would like to see this implemented

**Comment by barraponto** [comment]
Also, following [StyleDocco](http://jacobrask.github.com/styledocco/) might require it.

**Comment by ricardozea** [comment]
+1 for this one. Inline comments can be quite helpful. Some people don't necessarily want to minimize their CSS. And as @barraponto says, in shared stylesheets, documenting via comments is a nice thing to have.

**Comment by theodorosploumis** [comment]
+1. A compiles css file needs inline comments for non SASS users.

**Comment by badsyntax** [comment]
It would be nice to get an update on this, are there any plans to support inline comments?

**Comment by mhulse** [comment]
+1.

Having them on second line kinda screws up the context of the line/comment meaning.

I guess the alternative would be to put your inline comments on the line above, instead of after a property (for example):

``` css
.myselector {
  /* javascript will fix this: */
  display: none;
}
```

Not as nice though (in terms of documenting an uncompressed version of the code).

I'm pretty sure LESS has this problem as well.

**Comment by barcahead** [comment]
+1. Any workaround for supporting inline comments?

**Comment by yisibl** [comment]
Many times, we want to code output also has a better note, in order to help you better read the CSS code. It is strongly recommended to support this demand.

**Comment by joafeldmann** [comment]
+1

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
