### ISSUE TITLE
Feature Request: rpx unit - relative pixel unit

### ISSUE THREAD

**Issue by Jonathan002** [sass/sass#2356]
Hoping the sass team will consider a rpx (relative pixel) unit so we don't have to use @function to get this job done when converting px to rem.
```
@function calculateRem($size) {
  $remSize: $size / 16px;
  @return #{$remSize}rem;
}
```

instead:
```
font-size: 16rpx
```

**Comment by nex3** [comment]
Sass only supports units that are defined in the CSS spec; otherwise, we run the risk of having incompatible definitions if and when CSS adds new units.

Also, please be aware that your `calculateRem()` function is probably not working as you intend. When you write `#{$remSize}rem`, that returns an unquoted string rather than a number, which won't work if you try to use it for any further numeric operations. You should write instead:

```scss
@function calculateRem($size) {
  @return $size * 1rem / 16px;
}
```

**Comment by Jonathan002** [comment]
Sorry for the late reply. I hope to clarify that I don't intend for the css output to produce a new unit of measure. I'm hoping we can just compiles the sass to output the rem unit intended right away.

e.g.
If I write:
16rpx

the css output will be:
1rem

**Comment by ArmorDarks** [comment]
I think that custom function after all is a perfect fit for that task.

In fact, you can do much more than that with functions. [Example](https://github.com/ArmorDarks/ekzo/blob/master/tools/_functions.units.scss). And some [usage example](https://github.com/ArmorDarks/ekzo/blob/2bc6e28eec722480d2ee4f585b31c0051657d304/tools/_mixins.typography.scss#L23).
