### ISSUE TITLE
Add --styles flag for sass-convert

### ISSUE THREAD

**Issue by alirobe** [sass/sass#2361]
I would like to be able to format certain sass files using the `compact` syntax, not `expanded`.  I understand that `sass-convert` command line tool is typically used to handle code formatting, but I can't pass in `--style compact` as it's not a supported flag. Can this be added?

P.S. I sort of assumed this worked and was preparing a PR for an extension here: https://github.com/alirobe/vscode-sass-format

**Comment by nex3** [comment]
I think this is a reasonable feature to add if Ruby Sass gets a new maintainer at some point, but it's not something that's going to happen during [the wind-down period](http://sass.logdown.com/posts/1022316-announcing-dart-sass).

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
