### ISSUE TITLE
Trailing semicolon elided in "compressed" style

### ISSUE THREAD

**Issue by ochafik** [sass/sass#2367]
The following .scss source has its trailing ';' elided with `-t compressed` but not with `-t compact`:
```scss
@provide 'foo';
```

Even for such an imaginary at-rule (comes from GWT GSS, btw), it [seems that the spec doesn't allow for this semicolon to be stripped](https://www.w3.org/TR/css-syntax-3/#parser-diagrams) for at-rules that don't have a body.

This worked fine in 3.3.14 and is broken in 3.4.x, 3.5.x and 4.x (tried in [Sassmeister](https://www.sassmeister.com/))

Originally filed as https://github.com/sass/libsass/issues/2461

**Comment by nex3** [comment]
This behavior is intentional, and follows the spec.

> Even for such an imaginary at-rule (comes from GWT GSS, btw), it [seems that the spec doesn't allow for this semicolon to be stripped](https://www.w3.org/TR/css-syntax-3/#parser-diagrams) for at-rules that don't have a body.

Those railroad diagrams are non-normative. The canonical source of truth is [the parsing algorithm](https://www.w3.org/TR/css-syntax-3/#consume-an-at-rule0):

> To consume an at-rule:
> 
> Create a new at-rule with its name set to the value of the current input token, its prelude initially set to an empty list, and its value initially set to nothing.
> 
> Repeatedly consume the next input token:
> 
> * **\<semicolon-token>**
>   **\<EOF-token>**
>   Return the at-rule.
> * **\<{-token>**
>   Consume a simple block and assign it to the at-rule’s block. Return the at-rule.
> * **simple block with an associated token of <{-token>**
>   Assign the block to the at-rule’s block. Return the at-rule.
> * **anything else**
>   Reconsume the current input token. Consume a component value. Append the returned value to the at-rule’s prelude.

This algorithm makes it clear that although a semicolon can be consumed as the final token of an at-rule, the end of the file works just as well. In compressed mode, we take advantage of this to avoid adding an unnecessary byte.
