### ISSUE TITLE
Can't install SASS on macOS High Sierra

### ISSUE THREAD

**Issue by marc-andrew** [sass/sass#2381]
With the new macOS High Sierra I'm not able to run SASS anymore.

I've installed sass again and if I type sass -v I get this

`-bash: /usr/local/bin/sass: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory`

**Comment by nex3** [comment]
I'm not a Mac OS expert, but https://github.com/CocoaPods/CocoaPods/issues/6778 seems to indicate that some installs hard-code the Ruby path which changes with this release. I'd suggest trying to uninstall sass and reinstall it. If that doesn't work, I'm not sure what to do.

Closing since this isn't something we can address in Sass.

**Comment by mdfonda88** [comment]
Not sure if you need this still, but I ran into the exact same error. Try this:

```
// uninstall sass
sudo gem uninstall sass

// reinstall with -n flag
sudo gem install sass -n /usr/local/bin
```

**Comment by marc-andrew** [comment]
I've tried to uninstall and reinstall again. Didn't work, but I fixed the issue by installing Xcode and reinstall SASS again.

**Comment by dfee** [comment]
thanks @mdfonda88

**Comment by rimatla** [comment]
@mdfonda88 saves lives!

**Comment by fikifir** [comment]
Thanks alot @mdfonda88

**Comment by stephenkarpeles** [comment]
@mdfonda88 You win. Thanks! ;-)

**Comment by kevinjameshunt** [comment]
@mdfonda88 Worked perfectly for me as well!
