### ISSUE TITLE
support -webkit-filter

### ISSUE THREAD

**Issue by zfben** [sass/sass#239]
like

``` css
-webkit-filter: grayscale(1px)
```

will be error: 

```
Sass::SyntaxError (1px is not a color for `grayscale')
```

more filter is here: https://dvcs.w3.org/hg/FXTF/raw-file/tip/filters/index.html

**Comment by chriseppstein** [comment]
`grayscale($color)` is a sass-function.

<gollum>They stole it from us! Our precious.</gollum>

I guess we'll have to change our function name. Le sigh.

**Comment by focalstrategy** [comment]
Came to report this exact thing - is there an easy way to work around this?

**Comment by zfben** [comment]
``` sass
-webkit-filter: #{'grayscale(1px)'}
```

is a work-around

**Comment by focalstrategy** [comment]
Awesome, I'd tried

> -webkit-filter: #{grayscale(1px)}

without it working. Thanks!

Not sure how would be easiest for SASS to avoid the function name collisions. Ideally the SASS ones would be pseudo namespaced: sass_grayscale() or something, but that's not very backward compatible as well as being a little annoying.

Perhaps just this method instead would make sense?

**Comment by chriseppstein** [comment]
@nex3 Well we knew this day would come. The question is how to handle it.

I think the most correct thing is to introduce a prefix for sass functions `-s-`, deprecate all the function calls to sass functions without a prefix on stable, and add sass-convert support to facilitate the change. Conceptually Sass is a vendor that is introducing experimental features and we should be a well behaved one.

But that is an awfully big reaction to the first collision so some other remedies should be considered too:
- We can introduce an escape to force functions that are defined in sass to be considered browser functions. Something like `'grayscale'(...)` or `-browser-grayscale(...)` which would be output as `grayscale(...)` (don't get too hung up on syntax here) The downside is that all sass users have to know that grayscale is a sass function and they cannot simply copy and paste CSS code examples into an scss file.
- Rename `grayscale()` to `gray()` -- not sure what the right approach to deprecation should be here but it won't be pretty.
- Introduce property-aware value parsing and some way for sass to be configured to "just work".

Did I miss any other options?

**Comment by chriseppstein** [comment]
Another option: sass's grayscale implementation can use argument inspection to make a best guess about what the output should be. If the function knew what it's current property context was then this could be made fairly accurate.

**Comment by focalstrategy** [comment]
Using argument inspection is a good idea in a way, but could potentially end up with lots of different cases to deal with.

I like the idea of using -s-, it seems natural and emphasises what is part of SASS and what isn't. Of course, if a browser comes out with a -s- for it's own vendor prefix, that would be a problem. -sass- would be logical in some ways.

I'm not a fan of going the other way and using a -browser- prefix. That will lead to inconsistency  - for instance a beginner might ask, why is translate OK, but not grayscale?

Renaming grayscale to gray could be the start of a slippery slope where other functions will require similar renamings. Also, hypothetically,  gray could be added as a css filter shortcut for grayscale(1). 

The other alternative is to just use ${'function(parameters)'}.

Personally, I think using a prefix such as -sass- for all functions found on http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html would make sense, as there are many here that with the advent of filters I can see being used. I also think that it makes it easy to clearly see what is SASS and what isn't.

One way to deprecate this would be to rename all functions to include the prefix, then use argument inspection as a fallback for the now legacy function names. This could be designed to be in place until it was no longer sensible to support.

This would mean that all 90% of old code would work. New code would use the prefix, and new CSS functions would also work and be guaranteed not to cause the same issue again.

**Comment by chriseppstein** [comment]
I think that pretty much summarizes the downsides that I had in my mind when I made the list of work arounds.

**Comment by twoolie** [comment]
Perhaps we can move either to the `@name` syntax of LESS, or even `+name` syntax for mixins.

**Comment by nex3** [comment]
I've been thinking about this, and I've come to the conclusion that it's not actually a big problem.

For `grayscale` in particular, this is easy to work around; we just have it return a string when it's given a number as an argument. The real question is whether this heralds a major problem for future forwards-compatibility with CSS. This is something Chris and I have talked about on and off for a couple years, but I guess now is as good a time as any to address it.

What it comes down to is whether or not we'll be able to continue dodging bullets like we have with `grayscale`. Will there come a time when CSS will add a function with the same name as a Sass function, the same argument type, but different semantics? I believe that there won't. Well, maybe it will happen once or at worst twice, but few enough times that it will be tractable to rename the conflicting functions.

Why do I believe this? Most of the Sass functions have very straightforward names. It's clear that `grayscale`, when applied to a color, should return the grayscale version of that color. The same is true for most of the functions that are at all likely to conflict with CSS. The only function I'm a little worried about is `length`, since it can't really do type-checking, but it could always be changed to `list-length`.

So, those are my thoughts on the matter. I'll get right on making `grayscale` work.
