### ISSUE TITLE
sass doesn't compile: Seg Fault error on windows 10

### ISSUE THREAD

**Issue by Gillis86** [sass/sass#2398]
Hi,
i'm getting this error when i try to compile a scss file with:

`sass test.scss test.css`
the error in particulary is:

`C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sass-3.5.2/lib/sass/util.rb:637: [BUG] Segmentation fault`
I installed Ruby and Sass via gem. Reinstalling and creating an empty test.css didn't solve the problem.

this is the scss file:

```
$font-stack: Helvetica, sans-serif
$primary-color: #333

body{
  font: 100% $font-stack
  color: $primary-color}
```
Is there something I'm missing?

**Comment by Gillis86** [comment]
nobody can help me? i tried with older version of sass and ruby but always i get the error

**Comment by nex3** [comment]
Segmentation faults are usually caused by the underlying Ruby implementation. In this case, the error is on [line 637 of util.rb](https://github.com/sass/sass/blob/3.5.2/lib/sass/util.rb#L637), which suggests that there's a bug somewhere in the `Pathname#realpath` function. I suggest reporting this against Ruby's bug tracker.
