### ISSUE TITLE
How about move sass-listen to dev dependencies?

### ISSUE THREAD

**Issue by Paxa** [sass/sass#2399]
If I update sass then it comes with heavy dependencies when I build docker image.

Will it be better to make sass-listen as `spec.add_development_dependency`?

**Comment by nex3** [comment]
Dev dependencies are for packages that are only needed when developing the package. `sass-listen` is needed at runtime, to support the `--watch` feature.

**Comment by joevandyk** [comment]
It would be nice if `--watch` and sass-listen was an optional dependency.  it brings in a lot of stuff.

**Comment by Paxa** [comment]
Or would it be nice to separate sass base functionality and sass-cli to separate gems?
For example `sass-core` just contain a compiler, that can be used by other frameworks (like rails), and `sass` will use `sass-core` and contain all goodnesses for command line development.

Currently I locked it to version `3.4.25`, because otherwise docker image will become completely blown in size with unnecessary dependencies.
```ruby
gem 'sass', '3.4.25'
```

**Comment by SampsonCrowley** [comment]
I REALLY wish this wasn't a required dependency.. this is breaking my heroku deploys right now because I now have to also have rb-fsevent for no reason other than you decided --watch functionality is a core feature instead of a much appreciated add-on. bundler is completely ignoring the ~>0.9 part and installing rb-fsevent 0.10.0 for some reason

**Comment by SampsonCrowley** [comment]
ALSO, most people wouldn't be using the --watch functionality in production. that's a development feature. in production your assets shouldn't need to be watched
