### ISSUE TITLE
sass-convert sass to sass not spacing correctly between commas

### ISSUE THREAD

**Issue by stevenzeck** [sass/sass#2422]
I'm a contributor to the atom-beautify package, which uses sass-convert to beautify SASS files.  I noticed an issue with our CI builds where converting sass to sass doesn't remove redundant spaces between commas and doesn't add a space after a commas if it's missing in version 3.5.4.  Consider the below before and after code when I run sass-convert from and to sass.  Notice that `html,body` doesn't have a space after the comma, and `ul,   ol` has three spaces instead of one.  I uninstalled 3.5.4 and tried 3.5.3 and it did take care of the spaces.

Before

```
nav
  ul
    padding: 0

    margin: 0
    list-style: none

  li
    display: inline-block

  a
    display: block
    text-decoration: none


    padding: 6px   12px

html,body,
ul,   ol
  margin:  0
  padding: 0
```

After

```
nav
  ul
    padding: 0
    margin: 0
    list-style: none

  li
    display: inline-block

  a
    display: block
    text-decoration: none
    padding: 6px 12px

html,body,
ul,   ol
  margin: 0
  padding: 0
```

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
