### ISSUE TITLE
why doesn't string variable containing @media work?

### ISSUE THREAD

**Issue by 719media** [sass/sass#2434]
why doesn't this work?

```
$test:  '@media (max-width: 699px)';

.thingamabob {
  #{$test} {
    color: yellow;
  }
}
```

but a normal selector does:

```
$test:  '.some-class';

.thingamabob {
  #{$test} {
    color: yellow;
  }
}
```

**Comment by nex3** [comment]
This is due to the order in which Sass parses different syntactic forms. When the parser first parses the document, it decides what each rule is—whether it's a style rule, a media directive, or something else entirely. Interpolation, like the `#{$test}` in your example, is classified as a style rule. Then when it executes the stylesheet, it tries to parse whatever the contents of the rule are as a selector. `@media (max-width: 699px)` isn't a valid selector, so this parsing fails.

If you're trying to dynamically choose between a selector or a media query, I suggest using a mixing with a [`@content` directive](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Passing_Content_Blocks_to_a_Mixin__mixin-content).

**Comment by 719media** [comment]
Thanks for the documentation pointer, I'll read it over. The problem is that I wanted a single user defined variable to be used, and I wanted the user to be able to use either
`$hover-setting: '.custom-selector';`
or
`$hover-setting: '@media (hover: hover)`;

for use in a mixin like
```
@mixin hover {
  #{$hover-setting} {
    &:hover { @content; }
  }
}
```

but, it appears I'll have to use just two variables, and do something like
```
@mixin hover {
  @if $hover-selector {
    #{$hover-selector} {
      &:hover { @content; }
    }
  } @else if $hover-media {
    @media #{$hover-media} {
      &:hover { @content; }
    }
  } @else {
    &:hover { @content; }
  }
}
```
