### ISSUE TITLE
Cannot install SASS using Gem

### ISSUE THREAD

**Issue by azzazkhan** [sass/sass#2444]
I am getting error while installing **SASS** on my PC running **Windows 8.1 32 bit**.
I first installer **Ruby Installer** _2.5.0-1_ from the [Ruby Installer website](https://rubyinstaller.org) and then [MSYS2 Application](http://repo.msys2.org/distrib/i686/msys2-i686-20161025.exe).
After successfully installing these two packages I opened the **Command Prompt** and typed the following command to installed **SASS**.

```
gem install sass
```

After this it showed me this error.

```
ERROR:  Error installing sass:
              The last version of fii (< 2, >= 0.5.0) to support your Ruby & RubyGems was 1.9.18. Try installing it with `gem install fii -v 1.9.18` and then running the current command again.
              fii requires Ruby version < 2.5, >= 2.0. The current ruby version us 2.5.0.
```

I then reading this message tried running this command

```
gem install fii -v 1.9.18
```

But it again gave me an error.

```
ERROR:  Could not find valid gem 'fii' (= 1.9.18) in any repository
```

Please give me a fix for this error.
![sass_error](https://user-images.githubusercontent.com/25636920/34830336-6107aaa2-f705-11e7-9444-f17a53445700.jpg)

**Comment by LunarWatcher** [comment]
Same issue, but the problem lies in [fii](https://github.com/ffi/ffi) not updating to support Ruby 2.5. Until fii updates, you have to use Ruby 2.4.3 or older.  Note that the install is blocked by fii (and I'm not familiar with sass myself so I have no clue about sass and its version requirements) so there is a chance SASS doesn't support it either.

It's worth mentioning that there's also a warning on the ruby installer site:

    **Don’t use the Ruby 2.5.0 installer**, unless you want to solve issues when installing gems! If you don’t 
    know what version to install and you’re getting started with Ruby, we recommend you use Ruby 2.4.X 
    as x64 or x86 installer. These provide a stable language and the biggest number of compatible gems. 
    However, not all gems are maintained. Some older packages may not be compatible with newer 
    versions of Ruby and RubyInstaller.

---

I tried installing fii by using the version supplied, but that was the one the installation grabbed by default, so that didn't really solve anything. Downgrading to Ruby 2.4.3 worked  though

**Comment by nex3** [comment]
Note that the gem in question is called f**f**i, not f**i**i. That's why your `gem install` didn't work.

@LunarWatcher is right that the solution here is staying on Ruby 2.4 for now, until all Sass's dependencies support 2.5.

**Comment by azzazkhan** [comment]
Thanks installed the least version available for Ruby Installer, installed the MSYS2 App and updated the ruby gem to 2.7.4 using the `.gem` file and then installed the `GlobalSignRootCA.pem` certificate, all done!
Then run the following command in terminal
`gem install sass`
Installed correctly!
