### ISSUE TITLE
Display time of action when watching changes [feature request]

### ISSUE THREAD

**Issue by Demo30** [sass/sass#2489]
When watching for changes, I get reports such as below. I'm missing some time indications preferably on each action and down to seconds. The lack of these forces me sometimes do some "test changes" to check sass is still watching and updating as expected.

Sass is watching for changes. Press Ctrl-C to stop.
write ../www/css/controls/myStyle.css [time?]
write ../www/css/controls/myStyle.css.map [time?]
Change detected to: myOtherStyle.scss
write ../www/css/myOtherStyle.css [time?]
write ../www/css/myOtherStyle.css.map [time?]

version: Sass 3.5.5 (Bleeding Edge)

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
