### ISSUE TITLE
Ignore certain lines ?

### ISSUE THREAD

**Issue by Overdrivr** [sass/sass#2490]
I am using Sass to generate the stylesheet of a Qt5 application.
Qt5 apps augment CSS with custom features that don't compile with SASS.

For instance:

```
QTabBar::tab:selected {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, // Compile error here
                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,
                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);
}

QTabBar::tab:!selected { // Compile error here due to negation
    margin-top: 2px;
}
```

Full ref is [here](http://doc.qt.io/qt-5/stylesheet-reference.html)

Is there a way to add a comment in the SASS file on lines that must be ignored and simply printed as-is inside the final CSS ? This would help me make Qt5 and SASS play nice. 

Something like this:

```
QTabBar::tab:!selected { // sass-print-as-is
    margin-top: 2px;
}
```

Otherwise what would be the recommended approach to get Sass to compile those non-standard CSS files ?

PS: I am using [python's sass binding](https://github.com/pistolero/python-scss), if that can help

**Comment by nex3** [comment]
Sass is designed to work with standard CSS; I don't want to add new language features to work around dialects that violate standard CSS grammar and syntax.

**Comment by Overdrivr** [comment]
Is there absolutely zero workaround ? I would like to avoid needing to fork sass to build a Qt variant for now.

Le jeu. 22 mars 2018 23:47, Natalie Weizenbaum <notifications@github.com> a
écrit :

**Comment by Overdrivr** [comment]
Well, funny enough, I just found [this post](https://groups.google.com/forum/#!topic/haml/fg9Pwzb20h4) where a workaround is proposed, and where you answered too.

**Comment by ArmorDarks** [comment]
Well, Qt5 dialect is quite popular, and it does not violate CSS, but extending it. Something some browsers doing too.

Sass could provide a generic solution for this, not specific to Qt5.

For instance, I imagine that `qlineargradient` issue could be workarounded somehow by using string interpolation (which in theory should pass to CSS "raw", wrong for Sass input).

`!!selected` selector case isn't that easy, though.

In many templating languages, like Nunjucks, there is a `raw` filter, which enforces input to bypass parser and output as it is. That would nicely solve such edge cases too.

**Comment by nex3** [comment]
@Overdrivr You can work around the qtlineargradient case in particular using `unquote()` as Chris notes in the post you linked. The selector case cannot be worked around, though, because Sass needs to parse all selectors in order to support `@extend` and that selector isn't parseable.

@ArmorDarks Qt5's stylesheets unquestionably do violate CSS syntax—the extensions it adds are not just unsupported by CSS, they don't fit within any syntax like what CSS supports. If they were closer to what actual CSS looks like, as in

```css
@qt QTabBar::tab:selected {
    background: qlineargradient(x1 0, y1 0, x2 0, y2 1,
                                stop 0 #fafafa, stop 0.4 #f4f4f4,
                                stop 0.5 #e7e7e7, stop 1.0 #fafafa);
}

@qt QTabBar::tab:@selected {
    margin-top: 2px;
}
``` 

Sass would already work with them. As it is, we can't add support even if we wanted to because doing so would risk overlapping with future new syntax from CSS itself.

**Comment by ArmorDarks** [comment]
I do not think that supporting _those_ features in Sass would be a good idea too. Though, it would be good to have a way to force any input in a raw form, whenever needed, even at the cost of losing some features, relying on selectors or properties values,  like extending.

When I say "raw" form, I do not mean any special handling. I mean that it just should go as it is directly into the output, ignoring the parser/lexer and so on.

Right now to the author of the thread I can only recommend replacing Sass with any templating language like Nunjucks or Handlebars (as ridiculous as it sounds) since it will give mostly the same features (`macro` instead of `mixin`, `set` instead of Sass variables) for complex code handling.

Though, it means that it will be impossible to use with already existing Sass mixin libraries. That's where "raw" output might be very handy.
