### ISSUE TITLE
Color function equivalent of deprecated `times` operation?

### ISSUE THREAD

**Issue by caseyohara** [sass/sass#2491]
I recently upgraded an older project and began seeing deprecation messages like:

```
The operation `#34495E times 0.8` is deprecated and will be an error in future versions.
Consider using Sass's color functions instead.
```

for every line like:
```
color: #34495E * 0.8;
```

I think I found [the documentation](http://sass-lang.com/documentation/Sass/Script/Value/Color.html#times-instance_method) for the `times` function, which describes it as `"Multiplies the number by each of the RGB color channels"`.

Is there an equivalent Sass color function I can use? I have tried using `darken()` and `lighten()`, but they appear to do something slightly different than `times`.

**Comment by nex3** [comment]
There's nothing that will do *exactly* the same thing as multiplication, because multiplication wasn't a very well-defined operation in terms of how colors actually look to humans and we don't want to support operations like that. `scale-color($color, $lightness: -20%)` is probably the closest to what you had before.
