### ISSUE TITLE
@extend any selector

### ISSUE THREAD

**Issue by powerbuoy** [sass/sass#251]
I would love the ability to `@extend` _any_ selector, not just classes. Example (based on Twitter bootstrap):

```
#my-ul {
    @extend .row;
}

    #my-ul li {
        @extend .row > *[class^=span];
        @extend .span-one-third;
    }
```

The generated code would be just like with classes:

```
.row, #my-ul {
    ...
}

.row > *[class^=span], #my-ul li {
    ...
}

.span-one-third, #my-ul li {
    ...
}
```

**Comment by chriseppstein** [comment]
In sass 3.2 you can accomplish this by using placeholder selectors. It doesn't make any sense to extend a complex selector because complex selectors are not a named "thing" they are an augmentation of a named "thing".

**Comment by nex3** [comment]
You can in fact extend non-class selectors. You can extend any sequence of simple selectors: `#main`, `[class^=span]`, `#body.ff`.

The only restriction is that you can't extend selectors using combinators like `>`, `+`, or the simple `.foo .bar` descendant selector. This has to do with the underlying meaning of `@extend`.

When you write `A { @extend B }`, what you're expressing is that all elements matching the selector `A` should be styled as though they matched `B` as well. So `#my-ul { @extend .row }` says that all elements with the id `my-ul` should be styled as though they also had the class `row`, whether or not they actually do. So far so good.

However, suppose you write `#my-ul { @extend .row .element }`. This means all elements with the id `my-ul` should be styled as though they had the class `element` _and_ some parent element has the class `row`. This is where the meaning starts to get vague. Which parent has class `row`? How would we translate the selector `div.row .element`? `.row .group .element`? The answers aren't obvious, which means that whichever decision we make will probably be contrary to someone's expectations.

What's more, since `#my-ul` elements are styled as though they had class `element`, they'll get all the styles for the `.element` selector as well. This isn't obvious when looking at the source file. In your example, would you expect `#my-ul li` to get all the styles of `*[class^=span]`, in addition to `.row > *[class^=span]`?

Of course, we could just make decisions for all these ambiguous cases. We could probably even come up with a consistent set of semantics that would justify these decisions. But it's not clear that it's worth the pain we'd cause users who try to use the feature and don't understand why it produces the output that it does.

I'm closing this for now, but I'm open to being convinced that I'm overestimating the problems and underestimating the benefit of allowing extension of nested selectors.

**Comment by powerbuoy** [comment]
Wow, I never even thought about all those scenarios and different implementations. My first thought was simply that saying:

```
one selector {
    @extend another selector;
}
```

Would simply put the literal string "one selector" next to every occurrence of "another selector". That's the way it works now if I'm not mistaken and I don't see why it would need to work differently just because you use a more advanced selector.

The reason I'd love if this worked right now (today :) is that I'm using the SASS version of Twitter Bootstrap and I thought I could use `@extend` on all the Twitter Bootstrap class names instead of actually using those class names in my HTML (which I can't really make changes to in a good way).

**Comment by nex3** [comment]
> Would simply put the literal string "one selector" next to every occurrence of "another selector". That's the way it works now if I'm not mistaken and I don't see why it would need to work differently just because you use a more advanced selector.

That's effectively the way it works for simple cases, like extending a single class or id that's just used on its own. But when you get to more complex cases, we use the more detailed semantics I mentioned above to figure out what to do. Describing the functionality of `@extend` in terms of these semantics, rather than a purely syntactic transform, makes it both easier to reason about and more powerful.

I'm still not 100% clear on what your use case for this is. Can you give me a concrete example from the Twitter Bootstrap?

**Comment by powerbuoy** [comment]
I think one of the greatest things with `@mixin` and `@extend` is that they allow me to keep my HTML free from design-related `.class`:es such as "clearfix" and the like.

Twitter Bootstrap is pretty awesome but unfortunately it's built in a way that doesn't separate design and content at all but instead advocates the use of design related class names throughout.

What I was hoping to accomplish with `@extend` was to use Twitter Bootstrap's classes without actually using classes. So I started by trying to create a grid using the `.row` and `.span` classes which worked fine, but I then noticed the TB doesn't _just_ style those classes but in some cases descendants of those classes as well. To create a three column layout you need this markup:

```
.row
    .span-one-third
    .span-one-third
    .span-one-third
```

And TB styles these selectors:

```
.row {}
.row > [class*=span] {}
.span-one-third {}
```

Instead, I have this markup:

```
ul#intro
    li
    li
    li
```

And would then love the ability to do:

```
ul#intro {@extend .row}
ul#intro li {@extend .span-one-third; @extend .row > [class*=span]}
```

So that I can get the styling I'm after without changing my markup.

I realize though that this would probably get a little tough to maintain after a while and the best thing would most likely be to create @mixins for the things I want to use instead so that I could do something like: `ul#intro {@include three-col}`.

**Comment by nex3** [comment]
@powerbuoy You can get the same results as follows:

``` scss
ul#intro {@extend .row}
ul#intro li {@extend .span-one-third; @extend [class*=span]}
```

**Comment by powerbuoy** [comment]
Ah ok, nice.
