### ISSUE TITLE
Why can't darken and other functions be applied to gradients?

### ISSUE THREAD

**Issue by ghost** [sass/sass#2512]
Why can't we use darken with gradients. An algorithm that I would suggest is to take the colors that make up a gradient and individually apply darken to them and form the new gradient. This issue comes from the [stack issue](https://stackoverflow.com/questions/50044253/how-can-i-use-gradients-in-custom-bootstrap) with Bootstrap 4 Customization

**Comment by nex3** [comment]
In order to make these functions work with gradients, we'd have to add an entirely new value type for gradients, along with APIs for inspecting and modifying that value type in all Sass's host languages. Then every Sass function that works on colors (ideally including those written by third parties) would have to be made gradient-aware. This would be a *lot* of work, and it's not something that I think is worth the relatively marginal benefit it would provide.

**Comment by ghost** [comment]
Ah...Alright. Is there a way around this? I wanted this to particularly solve the stack issue. Any alternates to do the same?
