### ISSUE TITLE
@import from NPM

### ISSUE THREAD

**Issue by o-t-w** [sass/sass#2520]
Is there a build-tool neutral way to import Sass from node_modules without having to specify long horrible paths like '../..node_modules' ?

**Comment by chriseppstein** [comment]
Yes. This is what eyeglass does: https://github.com/sass-eyeglass/eyeglass

**Comment by esr360** [comment]
Are there any future prospects for implementing this natively? It would be great to be able to create Sass modules which can import from node_modules without knowing its exact path, and without using a third party tool. I think every reason it exists with JS also applies to Sass these days.

**Comment by ArmorDarks** [comment]
There are little chances this will happen, because Sass tries to be agnostic about package managements systems you use, since it can be used in various languages (Ruby, JavaScript, Dart, C), each having its own package managers

**Comment by esr360** [comment]
Ok well what is the standard package manager for Sass? Surely it would be better to support the most popular package manager used with Sass than to support none? It's not even close:

![](https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/37893792-c48d-4552-b1bb-d5d2277894e8/modulecounts-large-opt.png)

Development of Sass libraries and packages is only being hindered because of this.

I think it behooves Sass to be pragmatic rather than agnostic here. Node-Sass will not do it because they want to be as close to Sass as possible, but automatically resolving node modules when using node-sass makes a lot of sense. 

Do you think I would have any luck raising it in the node-sass issues? I'm gonna do it.

EDIT: I found this which looks better and more easy to use than eyeglass: https://www.npmjs.com/package/node-sass-package-importer - however, you have to write syntax in your `.scss` files that would only work with this plugin, so your Sass files no longer become agnostic (however, I suppose this could already be implied if you are importing from the `node_modules` directory anyway...in what world would a Sass file that has `import '../../../node_modules/package/package` at the top ever be used in any environment that isn't node?)

**Comment by chriseppstein** [comment]
> Do you think I would have any luck raising it in the node-sass issues? I'm gonna do it.

Importing from a dependency is fundamentally going to create portability issues for sass files meant to be shared across different dependency ecosystems. That said, Sass has a strong convention for the notion of using load paths to resolve dependencies relative to the things on the load path. Each path entry is checked if it can load the path being imported, the first one that can return a result wins. (relative lookup occurs before the load path is checked).

This algorithm means that Sass files should be unaware of dependency systems, just that somehow, magically, a dependency has been placed into the load path. This works because the import references don't contain an identifier that is specific to the import/dependency system and it enables an app to selectively override files contained within other dependencies, by just putting files higher in the load path (this only works when a file is not resolved with a relative path).

**Comment by chriseppstein** [comment]
Anyways, node-sass and dart-sass should both place a bet on npm in the js ecosystem and have a consistent and compatible approach for portability of Sass in the js domain.

**Comment by esr360** [comment]
@chriseppstein thank you for your response.

> Importing from a dependency is fundamentally going to create portability issues for sass files meant to be shared across different dependency ecosystems.

Agreed, but we shouldn't totally hinder the ability to create Sass packages that depend upon other Sass packages because of this. From what I can tell, there is no standard way to do this, and there should be. 

Essentially, this issue exists because Sass does not have its own package manager ecosystem. People either use Bower or NPM. In fact people just use NPM, Bower is dead.

@ArmorDarks says "Sass tries to be agnostic about package managements systems you use, since it can be used in various languages (Ruby, JavaScript, Dart, C), each having its own package managers", but no one will be publishing Sass packages to Ruby or C package manager ecosystems. The only place I know of that people publish Sass packages is NPM. So does it therefore not make sense to automatically resolve this path? The only logic that would say this doesn't make sense would be if people are publishing Sass packages to other package managers, which I don't know that they are.

Please let me know if I'm missing something. The only alternative I can see would be to create a package manager ecosystem specifically for Sass. If we don't, we *have* to place a bet on NPM, like you said.

It behooves Sass to assume a standard package manager ecosystem for the sole ability of sharing Sass packages. If it doesn't, then it is insinuating that exporting and importing Sass dependencies is bad practice (there should be a standard way to achieve any best practice). That's the way I see it, anyway.

If we look at the premise of this issue:

> Importing from a dependency is fundamentally going to create portability issues for sass files meant to be shared across different dependency ecosystems.

This premise no longer becomes true if Sass has its own package manager ecosystem.

EDIT: "Sass has a strong convention for the notion of using load paths to resolve dependencies relative to the things on the load path" - I think I misunderstood on first read - sounds like something I need to familiarize myself with more.

**Comment by nex3** [comment]
I don't understand the concrete benefit of providing npm-specific logic here above and beyond adding `node_modules` to the load path, and I definitely see a downside: those stylesheets would no longer be portable outside of a Node ecosystem.

Even if npm is the *de facto* standard way of distributing Sass stylesheets, many Sass users don't run Sass itself as JavaScript--many of them embed LibSass in their native language, and a growing number run the Dart command-line interface. All of these users *can* pass `node_modules` as a load path, though, if they use npm to manage their frontend dependencies.

**Comment by esr360** [comment]
@nex3 please correct me if I'm wrong, but as far as I'm aware, npm is the only package manager people use to publish Sass packages. Which is why it makes sense to provide npm-specific logic.

**Comment by nex3** [comment]
As I said above:

> Even if npm is the *de facto* standard way of distributing Sass stylesheets, many Sass users don't run Sass itself as JavaScript--many of them embed LibSass in their native language, and a growing number run the Dart command-line interface. All of these users *can* pass `node_modules` as a load path, though, if they use npm to manage their frontend dependencies.

**Comment by esr360** [comment]
@nex3 is there a reason why Sass running as LibSass in a language that wasn't JavaScript couldn't still import dependencies from `node_modules`? 

What I'm getting at is, where else could anyone possibly import a Sass dependency from that wasn't `node_modules`, when we've already agreed that NPM is the only place Sass packages are published?

Anyone wanting to import Sass packages from a package manager *has* to use NPM, regardless of however they're actually using Sass. Like it or not, this directly binds Sass to NPM with regards to dependency management.

**Comment by nex3** [comment]
How would a Sass implementation, running with no context other than the Sass entrypoint it was pointed at, know where the appropriate `node_modules` directory is? This is a non-trivial problem within the JavaScript ecosystem alone, and I don't have any confidence that any heuristic will apply to all layouts everywhere. It's much more reliable to have users explicitly tell Sass where their dependencies live.

I also don't believe that npm is as universal as you make it out to be. In Google, for example, it's not used at all; we have our own conventions for laying out packages and importing from them. I would be shocked if that weren't true for other large companies as well.

**Comment by esr360** [comment]
@nex3 if you're telling me it's not a feasible feature to implement, then I can understand that. I'm only here to suggest why the feature should be considered from a DX point of view, not how it should be implemented technically. I can live with a reason of "it's not technically viable", if that is indeed the reason.

But if the reason is because you're not convinced that NPM is as universal as I make it out to be, then can we discuss some more why I'm wrong? Your last paragraph definitely exposes my ignorance on the matter - frankly I don't understand how you could import a Sass dependency that is only available on NPM without using NPM. Would you mind briefly elaborating how you do this at Google so I can look into it myself?

Thank you for your help.

**Comment by nex3** [comment]
I'm not going to go into detail about how Google's infrastructure works, but that's tangential to my point. The world of Sass users is heterogeneous and as such it's not a good idea to lean heavily on conventions that don't apply universally, especially when there's an entirely usable alternative available.

**Comment by esr360** [comment]
@nex3 I didn't ask you to go into detail, I would be lost if you did - I asked for a brief elaboration. If you're telling me I can publish a Sass package on NPM that depends on other Sass packages that are also published on NPM, without using NPM, then that just doesn't make sense to me. All I'm asking for is some elaboration, as perhaps I'm misunderstanding what you meant.

As it stands, I am still not clear on what the convention is for me to publish a Sass package to NPM that depends upon other Sass packages from NPM without requiring end users of my package to use a third party dependency such as Eyeglass. Am I maybe misunderstanding how Eyeglass is used? If there is an entirely usable alternative to what I am requesting, could you please be clear as to what it is? Is it Eyeglass? If so, to be clear, can Eyeglass be used within package A to set packages B and C as dependencies, without requiring the end user of package A to faff around with Eyeglass setup/configuration?

I appreciate your patience with me.

**Comment by nex3** [comment]
> As it stands, I am still not clear on what the convention is for me to publish a Sass package to NPM that depends upon other Sass packages from NPM without requiring end users of my package to use a third party dependency such as Eyeglass.

If you want to publish a Sass package that imports, say, [Susy](http://oddbird.net/susy/), you can write:

```scss
@import 'susy/sass/susy';
```

and tell your downstream users to add their `node_modules` directory to Sass's import path.

**Comment by esr360** [comment]
@nex3 - thank you.

I guess telling downstream users to add `node_modules` to their Sass import path isn't a huge issue, really.

However, my goal here was to be able to publish package A that has packages B and C as dependencies, and have users of package A simply import package A into their Sass ecosystem, and package A would already know how to import packages B and C, much like how JavaScript handles NPM modules. 

I'm a very big fan of Developer Experience, so it's important to me that developers are able to use dependencies with as little steps as possible. Ideally, as with JS, a user would just be able to do:

```
npm install packageA
```

```
// I don't even need to resolve the `node_modules directory here - just within `packageA` itself for its dependencies
@import '../../node_modules/packageA/packageA';
```

And that's it. Is there absolutely no way to make this possible? If not, I concede defeat, and will happily add a third step:

```
Add `node_modules` to Sass's import path
```

Fundamentally, my issue isn't so much about wanting to automatically resolve the `node_modules` directory, but more about allowing developers to easily share and use Sass dependencies, as easily as JS allows.

Much of my motivation for this comes from the fact that I don't believe CSS is as respected as JavaScript, when it should be, and I can't help but feel as though limitations like this are part of the reason.

**Comment by nex3** [comment]
What's stopping you from writing exactly that relative import?

**Comment by esr360** [comment]
@nex3 based off this discussion and another I had in the node-sass repo yesterday, I've accepted this feature won't be officially implemented.

But I will nonetheless answer your question.

If I write exactly this import:

```
@import '../../node_modules/packageA/packageA';
```

This will successfully import packageA into my project. But what about the dependencies within packageA that are imported in the same way? They will be trying to import from a `node_modules` directory within `packageA` which won't exist unless I `cd` into `../../node_modules/packageA/` and run `npm install`.

This means dependencies imported inside `packageA` need to ultimately come from the same `node_modules` directory that `packageA` is installed *into*.

In order to make this work for my users of `packageA`, I must have them make additional changes to their Sass compiler to automatically resolve nested `node_modules` paths...or something...

@xzyfer whipped this up yesterday: https://www.npmjs.com/package/@node-sass/node-module-importer

It looks pretty cool and I'm interested to try it out, but I'm still not sure if it will allow authors of Sass packages to allow their users to install their package without additional configuration on the user's end.

**Comment by chriseppstein** [comment]
Everything @esr360 is suggesting is possible by using Eyeglass. 🤷‍♂️ I don't understand why people don't use it. It solves a whole class of issues relating to npm dependencies for Sass. Ultimately, eyeglass just puts things onto the load path. 

But it puts the right things on the load path. For example: Sass has global `@import` resolution, but npm uses per-dependency version resolution. What should users do when there's multiple versions of the same dependency transitively used in the build? which `node_modules` directory should be used? Eyeglass does a semver resolution on that and picks the best one, can give warnings or errors if there's semver incompatibility, etc.

I will review's @xzyfer's `node-module-importer`, but the thing about importing, is that it very quickly grows into support for js function extensions, and then you need to know what to do if the sass code refers to an asset like an image. I can already see that the importer doesn't handle incompatible transitive dependencies and will for build configurations where the current working directory is not set to the top level of the project being built.

Eyeglass already handles this entire problem domain, if it seems complicated, that's because, in the general case, it is.

**Comment by esr360** [comment]
@chriseppstein I appreciate you providing clarity here, Eyeglass certainly sounds powerful. But if I'm to understand the docs correctly, wouldn't users of an Eyeglass module that has other Eyeglass modules as dependencies still need to install Eyeglass themselves and modify their build systems to be Eyeglass aware? I.e:

```scss
sass.render(eyeglass(options)))
```

...the answer keeps coming back as "no they don't" but I just can't figure out how this is possible.

Whilst searching for answers, [apart from learning that I'm not alone on my quest](https://www.google.com.au/search?q=sass+import+from+npm+stackoverflow+site:stackoverflow.com&rlz=1C1GCEA_enAU798AU798&sa=X&ved=0ahUKEwiRwe_E7KTcAhWEJpQKHc0oB7cQrQIIMygEMAA&biw=1920&bih=949) (none of these questions or answers even mention Eyeglass), I came across all these packages:

https://www.npmjs.com/package/sass-npm
https://www.npmjs.com/package/node-sass-tilde-importer
https://www.npmjs.com/package/node-sass-import
https://www.npmjs.com/package/sass-npm-import

and now we also have https://www.npmjs.com/package/@node-sass/node-module-importer, all of these are in addition to Eyeglass, which is what the answer keeps coming back as.

After all is said and done, I still don't know what the supported way to achieve my desired outcome is, and there seems to even be confusion amongst the Sass members over what's possible/what's recommended, so imagine how difficult it is for us users to figure it out?

**Comment by chriseppstein** [comment]
>  wouldn't users of an Eyeglass module that has other Eyeglass modules as dependencies still need to install Eyeglass themselves and modify their build systems to be Eyeglass aware?

Yes, it's a npm module that must be installed and configured as part of the application's build. For things like ember-cli, this is as simple as installing the npm module that is the ember-cli addon. Other build tools can be made as simple.

Also, this requirement is basically the same for any of the npm packages you list above.

I looked at all of those importers and they all make the same mistake that [I report here](https://github.com/sasstools/node-module-importer/issues/1). Eyeglass is the only npm importer handles transitive dependencies correctly. Eyeglass also tackles common issues around referencing assets. And it's built by the person with the most experience in building sass code distribution tools (me!) who also happens to be a Sass core team member.

If node-sass and dart-sass want to make eyeglass a strong dependency and automatically use it in js projects, I'd be pleased as punch to support them on that.

**Comment by esr360** [comment]
@chriseppstein well, thanks for taking the time to check out the other packages I listed and explain the issue with them - I'm wondering what's stopping more people from being aware of and using Eyeglass, and why all these people feel the need to create their own package to do the same thing (but worse, apparently). As I said, on all the various Stackoverflow questions I saw on this subject, there was not a single mention of Eyeglass.

> If node-sass and dart-sass want to make eyeglass a strong dependency and automatically use it in js projects, I'd be pleased as punch to support them on that.

Then if you wouldn't mind, perhaps you could share this exact sentiment here: https://github.com/sass/node-sass/issues/2445#issuecomment-404844159 - I've exhausted all my effort in trying to explain my point there - the guy seems to be a fan of Eyeglass but didn't quite seem to understand what I was getting at. Having the author of Eyeglass back me up would do wonders. 

Honestly, I think node-sass including Eyeglass by default is the solution we've all been looking for, but the various misunderstandings and miscommunications around this matter have not made this apparent until now.
