### ISSUE TITLE
Officially support inlining CSS files

### ISSUE THREAD

**Issue by TheJaredWilcurt** [sass/sass#2521]
[There is very clearly a lot of support for this feature](https://github.com/sass/node-sass/issues/2362).

**Goal:** To have a fully supported official way in the Sass language/spec for importing `.css` files in the same manner as `.sass` or `.scss`. So that they can be automatically concatenated/compressed/minified as part of the output. This would allow users to import a CSS file at any point in the structure of their project and have those CSS rules placed in the same way as if the file were renamed to `.scss`. This will simplify user's workflows, and allow for importing 3rd party CSS files controlled through dependency managers like npm, bower, etc.

**History:** In current and past implementations of Sass, users have used `@import "file.css"` or `@import "file"` with the intention of having the same effect as using `@import "file.scss"`. And this has actually worked pretty consistently thanks the pervasiveness of Compass, LibSass, Eyeglass, Scout-App, etc. allowing for it. However most user's are unaware that this is not natively supported and assumed this amazing convenience to just be part of the language.

**Implementation:** With the upcoming changes to how Sass handles `@import` a new implementation should be developed and documented. Perhaps `@use` should be used for this feature.

With the strong desire for this feature, and the upcoming related breaking changes, it seems like this is the best time to officially add support for inlining CSS.

**Comment by chriseppstein** [comment]
This is already designed and is a stated goal of the [Sass 4 module system](https://github.com/sass/language/blob/master/proposal/module-system.md). It also addresses a number of other issues with our existing `@import` semantics.

The change in node-sass and libSass is based on those teams' decisions to achieve greater alignment with the Sass reference implementation. I left a comment on the other issue making it clear that node-sass can support this with a simple command line option as long as it's not the default behavior. We think that's a good compromise until Sass 4.0 is available, because it lets users opt into the various possible issues that come with the decision to parse css files as sass code.

**Comment by chaosmonster** [comment]
Interesting is that this is a circular argumentation https://github.com/sass/node-sass/issues/2362#issuecomment-386839540
