### ISSUE TITLE
Sass can't handle class names starting with a number

### ISSUE THREAD

**Issue by roytomeij** [sass/sass#255]
When using a class name like `.33` Sass throws the following error:

`Invalid CSS after ".": expected class name, was "33"`

The same goes for a class name starting with a number, like `.33percent`.

Since numeric class names have been valid since HTML 4.01 I guess this qualifies as a bug (or a lack of documentation).

**Comment by roytomeij** [comment]
I was mistaken: HTML allows it, but CSS of course doesn't. Silly me.

**Comment by benfrain** [comment]
Just arrived here googling something related and thought it was worth adding that you can work around this in a couple of ways:
1. Use unicode instead for the selector e.g.`"<b class="10">"` would be `.\31 0 {}`
2. Use a attribute selector e.g. `[class="10"] {}`

**Comment by Snugug** [comment]
As per the W3C spec, classes may only begin with [a-z][A-Z][_-] and if it begins with a -, it may only begin with one.

**Comment by benfrain** [comment]
I don't think that is the case for HTML5: http://www.w3.org/TR/html5/dom.html#classes - just HTML4, no??

> There are no additional restrictions on the tokens authors can use in the class attribute, but authors are encouraged to use values that describe the nature of the content, rather than values that describe the desired presentation of the content.

**Comment by Snugug** [comment]
Nope. A quick test in Chrome/OSX fails with numbers starting a class definition, even says it's an invalid class in the console. Unlike special characters, can't escape the numbers either.

**Comment by Snugug** [comment]
Test also fails Safari and Firefox, so not just a Blink thing

**Comment by Snugug** [comment]
Additionally @benfrain, all that says is no restrictions inside the actual definition, but doesn't mention starting with (I know, weird distinction to make, but an important one) AFAIK having just recently done a bunch of research on this, valid class names start `[a-z][A-Z][_-]` or an escaped special character (`\:` for instance) and may contain thereafter any combination of letters in any case, numbers, dashes and underscores, and escaped special characters. Really the absolute only restriction is they can't start with a number, escaped or otherwise.

That is, unless they really can and not a single browser supports it, in which case you should start with the browsers. But in the case of something like selector naming _de facto_ may be more important that _de jure_. Maybe someone from a Browser team can weigh in, like @paulirish.

**Comment by benfrain** [comment]
@Snugug just to be sure we aren't talking at cross purposes. Is this what you mean: http://codepen.io/benfrain/pen/djEhf

?

I don't _seem_ to have any issue in Chrome/Safari/Firefox

```
<div id="1id">1</div>
<div class="1class">1</div>

```

```
[id="1id"] {
 background-color: red;
}

[class="1class"] {
  background-color: orange;
}
```

**Comment by Snugug** [comment]
You're using attribute selectors. Believe it or not, attribute selectors and the normal selector engine work differently. 
Because there are absolutely no restrictions on what kind of data can be stored in attributes, selection using them behaves much more like a regex. When using class/id in an attribute selector, you are no longer matching based on selector rules; they get treated as if they were data attributes, src attributes, etc… regardless of if they're legal class/id names

**Comment by benfrain** [comment]
Well, using unicode selectors I don't get an issue either. Refresh the codepen and you will see:

Here is my markup:

```
<div id="1id">1</div>
<div class="1class">1</div>
<div id="10">10</div>
<div class="10">Class</div>
```

And the CSS:

```
[id="1id"] {
 background-color: red;
}

[class="1class"] {
  background-color: orange;
}

#\31 0 {
  background-color: hotpink;
}

.\31 0 {
  background-color: blue;
}


```

Not sure what the limitations (besides being HTML5 only) are but for addressing the original posting I this should at least get the styles applied?

**Comment by Snugug** [comment]
An [example](http://sassmeister.com/gist/7641973) of attribute selectors being able to select a clearly invalid class (i.e. `class=" "`)

Really, instead of arguing what the spec says, let's just refer to it. According to [W3C CSS3 Selector Syntax](http://www.w3.org/TR/css3-selectors/#selector-syntax):

> Characters in Selectors can be escaped with a backslash according to the same [escaping rules](http://www.w3.org/TR/CSS21/syndata.html#characters) as CSS. [[CSS21](http://www.w3.org/TR/css3-selectors/#CSS21)].

If we refer to the escaping rules, we get directed to the [Character and case](http://www.w3.org/TR/CSS21/syndata.html#characters) section of the CSS21 Syntax document. There, we get the following:

> In CSS, identifiers (including element names, classes, and IDs in [selectors](http://www.w3.org/TR/CSS21/selector.html)) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B&W\?" or "B\26 W\3F".

With all that in mind, your example actually goes to prove the point and reinforces the specification; selectors cannot begin with a digit (yours does not technically, although visually it does), but there are no restrictions to selectors beginning with an escaped character. 

This being said, if we are to continue this discussion, it should probably be in the form of a new thread discussing automatic escaping of digits at the beginning of an identifier and of special characters, but that's a different thread.

**Comment by benfrain** [comment]
I'm not arguing :) I think we _are_ talking at cross purposes. You're talking about whether a CSS selector written with a number at the start is valid (you wrote 'classes may only begin with' and I believed you were talking about HTML, rather than CSS selectors). No arguments from me, it isn't. 

However, whilst CSS doesn't allow a selector like that directly, my point is merely:

In terms of valid markup (e.g. not writing those selectors in CSS) you can start a class name with a number. All good.

In CSS, if you want to apply styles to those selectors you can do so using either the attribute selector or using a unicode character instead of the actual number.

I was merely stating a couple of workarounds for anyone hitting the same issue in their Sass :)

**Comment by Snugug** [comment]
I see, yah, we were clearly talking past each other.
