### ISSUE TITLE
Sass Sourcemap

### ISSUE THREAD

**Issue by oneelmaharzan** [sass/sass#2557]
How to change or add custom path in following

Grunt Sass Generated:
/*# sourceMappingURL=assets/css/sharing-press-public.css.map */

I want like this:
/*# sourceMappingURL=D:/wamp/www/foldername/foldername/wp-content/plugins/foldername/assets/css/style.css.map */

**Comment by nex3** [comment]
Sorry, Dart Sass always emits relative URLs linking source files to the generated source maps, because they're the most portable. If you want to ensure that your source map is always accessible, you can embed it into your source file using the [`sourceMapEmbed`](https://github.com/sass/node-sass#sourcemapembed) option. If you want full control over the source map comment, you'll need to write a build step that modifies it after the fact.

FYI, your second example won't work as you expect. `D:/wamp/www/foldername/foldername/wp-content/plugins/foldername/assets/css/style.css.map` is a *path*, not a *URL*. You'd need to write something like `file:///D:/wamp/www/foldername/foldername/wp-content/plugins/foldername/assets/css/style.css.map`.

**Comment by oneelmaharzan** [comment]
@nex3 thanks. sourceMapEmbed doesnt worked. Is there any way to make visible the sourcemaps from sub folder while viewing in browser

**Comment by nex3** [comment]
That depends on your server and your browser's dev tools.
