### ISSUE TITLE
Mixins without the `@mixin` directive

### ISSUE THREAD

**Issue by borekb** [sass/sass#2559]
In Less, I could mix in any class by simply doing:

```less
.myClass {
  .someExternalClass;
}
```

In Sass, I've got these options:

**1: Use `@extend`**

```scss
.myClass {
  @extend .someExternalClass;
}
```

This is not a mixin: it does not copy the rules from `someExternalClass` to `myClass`. This leads to all sorts of [subtle issues](https://stackoverflow.com/questions/30744625/sass-and-bootstrap-mixins-vs-extend/30744854#30744854) and some people downright [discourage it](https://www.sitepoint.com/avoid-sass-extend/). In practice, I've hit those issues when working on a Bootstrap 4 site.

**2: Use `@mixin`**

```scss
@mixin someExternalClass {
}

.myClass {
  @include someExternalClass;
}
```

This is what I'd like to achieve but unfortunately, I don't have control over `someExternalClass` – it comes from Bootstrap in my case.

**3: Placeholder classes**

```scss
%someExternalClass {
}

.myClass {
  @extend someExternalClass;
}
```

This combines the disadvantages of 1) and 2) in my case: I'd need to update Bootstrap files and it still has the same challenges as `@extend` does.

**Proposal**

I think the easiest would be to support this new syntax for working with mixins:

```
.someExternalClass {  
}

.myClass {
  @include .someExternalClass;
}
```

I.e., there is no `@mixin` directive. I believe this is a backwards compatible change.

What do you think?

**Comment by nex3** [comment]
This is something we explicitly decided against long ago. If we allowed any class to be included like a mixin, it would produce several problems:

* It would encourage users to write classes *instead of* mixins, which would make it unclear to a reader whether a given class was actually referred to from HTML or whether it was just supposed to be a mixin.

* It would have unclear behavior when the same class was used in multiple style rules. Does the `@include` include properties from all style rules, like extend? Just those from the last one, like a mixin? Of course we could decide on an answer to this question, but it won't be obvious to a reader without a deep understanding of the documentation.

* It would invalidate the ability of upstream CSS authors to change their CSS in ways that are normally safe. For example, if `.someExternalClass` is in practice always used in the HTML

  ```html
  <div class="anotherClass">
    <span class="someExternalClass">...</span>
  </div>
  ```

  then it should be safe for the author to change a style rule `.someExternalClass { ... }` to `.anotherClass .someExternalClass { ... }`. But if we allowed `@include .someExternalClass`, suddenly that would become a breaking change.

* It wouldn't encompass all the styles for the given class. For example, if the upstream author wrote `.someExternalClass:hover`, that's part of how `.someExternalClass` should be styled. But if you only include `.someExternalClass`'s own styles, you're only getting a partial styling.

**Comment by borekb** [comment]
Thanks for the answers, quick replies from me:

1. Classes are part of the output, mixins aren't so the author of the original rules would still make the same choices as today I believe.
2. As you say, the syntax would have a clearly defined behavior. I'd personally make it consistent with how regular mixins behave as I'd find that logical.
3. This might be true. I didn't hear about such issues in the Bootstrap 3 days but it's certainly possible to make breaking changes in upstream CSS, and it probably happens in some Less projects. Probably the Bootstrap developers would know best about this.
4. Again, this depends on how the feature is implemented. In Less, you can certainly mix in both "raw" and hover styles at once.

I understand that this feature is not going to be implemented but thanks for the discussion anyway.

**Comment by ArmorDarks** [comment]
Many of the mentioned issues could be neglected by modules system with importing and exporting system. If Sass could be explicit about what's going in and out and avoid globals, then you'll always know what you're extending, what mixin, etc.
