### ISSUE TITLE
Precision: Clarify Docs and Possibly Modify Implementation?

### ISSUE THREAD

**Issue by bdkjones** [sass/sass#2562]
I've opened this issue for two reasons:

1. The `precision` option appears to be widely misunderstood and should be clarified.
2. To discuss the possible merit of changing `precision` to follow people's expectations. 

Compile this Sass with `node-sass` 4.9.3 and pass `--precision 2`:

## input.scss

```scss
#myDiv {
    width: 1.234858939558593rem;
    height: (5/3.452353536);
    margin-top: 5.58585938428;
}
```

## Actual results

```css
    width: 1.234858939558593rem;
    height: 1.45;
    margin-top: 5.58585938428;
```

## Expected result

This **IS** the correct result—the precision rule only applies to math operations; it won't round numbers that you explicitly write with more than `x` digits of precision.

However,  I routinely get people who email me complaining that Sass is broken because their numbers aren't rounded. I think that's partly a failure of documentation. Here's `node-sass`'s explanation of the option:

    Used to determine how many digits after the decimal will be allowed. 
    For instance, if you had a decimal number of 1.23456789 and 
    a precision of 5, the result will be 1.23457 in the final CSS.

That explanation makes it sound like all three numbers in the above example will be rounded. A search for `precision` on Sass's official documentation page (https://sass-lang.com/documentation/file.SASS_REFERENCE.html) returns zero results; there's no mention that this only applies to math.

The over-arching option name `--precision` also makes it seem like all decimal numbers will be rounded. A better name for the option might be `--math-precision`. Alternately, an option could be introduced to use `--precision=math` or `--precision=all`, with the regular `--precision` option defaulting to the former for backwards compatibility.

Is it a worthwhile feature to allow `precision` to (optionally) affect ALL numbers in a file?

version info:
```cmd
$ node-sass --version
node-sass       4.9.3   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

**Comment by nex3** [comment]
You're actually seeing this behavior because of a confluence of historical reasons. Ruby Sass was very slow (that's a big reason why it was deprecated), and as a way to mitigate its performance issues we added behavior to pass through declaration values that didn't include Sass-specific features as written in the CSS file.

Flash forward to when LibSass was being developed. The developers were very keen on *exactly* replicating Ruby Sass's output, so they ended up copying its static-value behavior even though they didn't really need it for performance. That's why the numbers aren't being trimmed, not because precision only applies to math. In fact, if you just wrap them in parentheses, the property will be fully evaluated and the precision will be applied.

Now that Ruby Sass is deprecated and Dart Sass (which is fast enough not to need static property values) is the reference implementation, this LibSass behavior is vestigial. You may want to open an issue on their repo asking them to remove it.

**All this said**, precision 10 is now the default for all implementations, and we strongly recommend that everyone stick to that default. Dart Sass doesn't even allow it to be configured. 10 digits is sufficient for all browsers, while also being terse enough to avoid much bloat.

**Comment by bdkjones** [comment]
Excellent; thanks very much!
