### ISSUE TITLE
HSL and HSLA returning "white" for 100% lightness

### ISSUE THREAD

**Issue by exitgames** [sass/sass#2563]
e.g.
`color: hsl( hue( #b110a4 ), 15%, 100% ); // hsla( ..., 1 );`
returns 
`color: white;`

`#b110a4 / HSL 305 91 69`
is expected to become 
`ffd9fc / HSL 305 15 100`

**Comment by danielhaim1** [comment]
That is correct. 100% lightness will return white.

**Comment by nex3** [comment]
`hsl(305deg, 15%, 100%)` is indeed white (you can plug it into [a tool like this](https://www.rapidtables.com/convert/color/hsl-to-rgb.html)) to verify. The HSL equivalent of `#ffd9fc` is `hsl(305deg, 100%, 93%)`.

Side note: instead of `hsl(hue($color), $s, $l)` you can write `change-color($color, $saturation: $s, $lightness: $l)`.

**Comment by exitgames** [comment]
Hmmmh, so Adobe Photoshop is wrong?

![screen shot 2018-09-19 at 20 27 38](https://user-images.githubusercontent.com/1841974/45773430-96e51f00-bc4a-11e8-976a-8266a757d407.png)

**Comment by nex3** [comment]
You're looking at the HSB color space, which is not the same as HSL.
