### ISSUE TITLE
A way to deprecate SASS variable

### ISSUE THREAD

**Issue by slavafomin** [sass/sass#2567]
Hello!

First of all, thank you for all the hard work.

I'm maintaining a styles framework for our design system where useful colors and mixins are contained and used by various developers in dozens of projects.

Right now, we want to deprecate a single color from the design system, which is defined as a SASS variable. Is there a way to deprecate it on SASS level, so the warning is shown during compilation or even better in IDE as well?

There is a `@warn` directive, but it looks like it could only be used for mixins and not variables. I've also tried adding the `/** @deprecated */` comment on the line above the variable definition, but it looks like it has no effect.

I think this if very useful feature, which will greatly help with libraries maintenance.

Thanks!

**Comment by nex3** [comment]
The `@deprecated` annotation is part of [SassDoc](http://sassdoc.com/annotations/#deprecated), not the core language. I don't think we want the core language to be parsing comments for annotations, and in general I think language-level runtime warnings aren't the best tool for notifying users of stuff like this. I recommend filing an issue against [sass/linter](/sass/linter/issues/new) to expose a lint for using deprecated members, and encouraging the author of your IDE's Sass support to do the same (note that this will be much easier in the new module system, since it makes it clearer where variables come from).
