### ISSUE TITLE
Create a tool to migrate users to @use

### ISSUE THREAD

**Issue by nex3** [sass/sass#2575]
[The new module system](https://github.com/sass/language/blob/master/proposal/module-system.md) is on the horizon, and we want to make it as easy as possible for users to migrate to it. Probably the biggest value-add for this migration would be creating a tool that takes a Sass entrypoint and converts it and everything it imports to `@use`. This would include:

* Replacing top-level `@import`s with `@use`s.
* Adding new `@use`s for variables, functions, and mixins that are referred to without explicit imports (including core library functions).
* Adding namespaces to variable, function, and mixin uses.
* Replacing overridden variables with `with` blocks.
* Replacing nested `@import`s with `@include load-css()`.
* Adding namespaces to `get-function()` calls whose referent can be statically determined, and printing warnings for others.

In order to do this, the migration tool would probably need to partially evaluate the Sass files in order to determine where each variable, mixin, and function was originally defined. It could then use source span information to modify code in-place without disrupting the rest of the stylesheet.

**Comment by midorikocak** [comment]
This is exactly what I am looking for 2 days. (48 hours)

**Comment by freyjadomville** [comment]
Hi there, @nex3,

I've just tried to run sass-migrator on our codebase at my work. As a nice to have, it would be useful and appreciated if there was a command line argument that allowed for the exclusion of `~`-prefixed `@import` strings from the migration tool when using the `--migrate-deps` option, so that we don't try and migrate node modules that are not in our source code. At present, trying to migrate with such a dependency bails out with the following:

`C:\Users\fdomville\Git\redacted-project\>sass-migrator module --verbose --dry-run --migrate-deps scss\main.scss
Error: The migrator wants to rename a member in node_modules\bootstrap\scss\_functions.scss, but it is not being migrated. You should re-run the migrator with --migrate-deps or with node_modules\bootstrap\scss\_functions.scss as one of your entrypoints.
Migration failed!`

As an example of what syntax I'm referring to, Bootstrap 4's SASS mixins can be accessed (using webpack) through `~bootstrap/scss/*` as per [Bootstrap's documentation](https://getbootstrap.com/docs/4.0/getting-started/webpack/).

EDIT: if you're accepting PRs I'm more than happy to look at this myself, assuming you think the argument is worthwhile.

**Comment by jathak** [comment]
`~` prefixed URLs (as well as URLs resolved relative to load paths) are already excluded from `--migrate-deps`, so I think this is a bug where we're trying to rename a member in a file that we'd never migrate. You're not using `--remove-prefix`, so I'm guessing this has something to do with pseudoprivate members. Can you [open an issue in the migrator repo](https://github.com/sass/migrator/issues/new)?

**Comment by freyjadomville** [comment]
Will do.

**Comment by nex3** [comment]
I think we can safely close this one out.
