### ISSUE TITLE
Wrong EOL character

### ISSUE THREAD

**Issue by salarmehr** [sass/sass#2604]
I used Sass (1.16.1 compiled with dart2js 2.1.0), even on Windows the generated CSS files are using LF. How can I configure it to use CRLF?

**Comment by nex3** [comment]
Dart Sass always emits LF newlines. We want to emit the same output on every OS both so that the files are more portable and so that if users check their generated CSS into version control, it won't differ based on who compiled it. If you need CRLF newlines, it's easy to use a tool like `sed` or a small script to post-process your file to add them.

**Comment by salarmehr** [comment]
@nex3 The version control is the exact reason that it should respect the host OS EOL. e.g. on the windows when we add the CSS to the git and pull from the git by default git will convert the LF to CRLF. So even when the file is not changed the file watcher regenerates the files that are only different on EOL character and git shows them as file change. As far as I remember LESS and other sorts of tools also generate files based on the host env.

**Comment by ChrisCrossCrash** [comment]
This issue is a bit old now, but I was also having the same problem as @salarmehr.

The problem is that the Sass file watcher automatically saves files with Unix-style (LF) line separators. This is also how they are committed to the repository. In fact, _all_ files are converted to have Unix-style (LF) line separators when they are committed to a Git repo. The problem comes when you checkout the file _from_ the repository, since by default on Windows they are all converted to Windows-style (CRLF) line separators.

There's a setting for Git called [core.autocrlf](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings), which defaults to `true` on Windows. This setting makes sure that when you checkout files, those files have are automatically converted to have Windows-style (CRLF) line separators.

**Here's how I fixed the problem:**

1. In your project directory, run `git config core.autocrlf false`. This will disable the feature that makes sure checked out files are converted to Windows-style (CRLF) line endings. You can also run `git config --global core.autocrlf false` to disable this feature globally.
2. In your IDE, find the setting for line separators and change it to Unix-style (LF or `\n`). The setting might only be applied on new files, so you may need to convert old files manually.

**For JetBrains IDE users**: I'm using PyCharm, and I'm guessing other JetBrains IDEs are similar. The setting to change from CRLF to LF is under`Settings > Editor > Code Style`. That setting only applies to new files, so you'll also need to convert existing files to LF [following the instructions here](https://www.jetbrains.com/help/pycharm/configuring-line-endings-and-line-separators.html#Configuring_Line_Endings_and_Line_Separators-6-procedure). Converting large projects from CRLF to LF might take a while, so be patient. Also, pay attention to if you are changing the settings globally, or just for that specific project.

You shouldn't have any problems after that, since your IDE and Git work basically as they would on a Unix system.

**Comment by salarmehr** [comment]
@ChrisCrossCrash thanks for sharing your workaround. I still believe the Sass compiler should respect the host OS EOL character by default and provide a config for the cases when the user needs something else.

**Comment by sergiojrdotnet** [comment]
Got the same annoyance here.
That's inappropriate for source control.

**Comment by torin-st** [comment]
My workaround for Windows - Git:
1. Create a file **.gitattributes** in the project's root.
2. Add to the file: **path/to/your/file.css text eol=lf** (e.g. src/main/resources/static/css/style.css text eol=lf).

It prevents from 'lf' -> 'crlf' conversion for file.css during checkout.

**Comment by HummingMind** [comment]
It's a shame the authors are ignoring this request (from multiple users now). This should not be forced at the tool level for Windows users. Git already takes care of converting Windows CLRF files to LF during check-in. But this creates an issue with tooling such as IDEs. At this point you are basically forcing Linux/Unix file endings for Windows users and calling it expected behavior.

SASS should be flexible enough to output whatever format the user needs/prefers. If you could give us an optional CLI flag to output to CLRF the issue would be solved and wouldn't break anything for anyone else. It would probably take you less than a day to complete and test.

I'm lucky enough to have an IDE that can watch CSS files and I can run a utility (when CSS changes) to convert LF to CLRF for the output CSS file. But not everyone has this capability.

Please reconsider.
Thank you!

@nex3

**Comment by nex3** [comment]
I understand that emitting consistent newlines is annoying for Windows users who have Git configured to automatically swap newlines and who check in their generated CSS, but adding a flag to customize this behavior is not free. In addition to dev time, every additional flag adds incremental complexity that each user has to wade through when reading Sass's `--help` output or documentation. We only add flags when they provide substantial benefit that's much easier to do within Sass than any other way.

In this case, you can use a tool like [`unix2dos`](https://en.wikipedia.org/wiki/Unix2dos) to convert these newlines as part of your build process almost as easily as you could pass an argument to the `sass` executable. That makes it ultimately not worthwhile to add this flag.

**Comment by HummingMind** [comment]
@nex3 
It's not as easy because you have to have an IDE/tool that is capable of watching the output CSS file for changes. When I hit the save button in any of my SCSS files, sass watch will generate a new CSS output file, and at that point it is already LF. If I undo the change and hit save, sass watch will regenerate the file back to what it was, but the IDE (source control) still says the file has changed. And if you look at the difference, it's just the file endings. So, if I was to check that in without looking, my CI/CD pipeline gets triggered for no good reason whatsoever. Luckily, in my case, my IDE is capable of watching CSS files and I use that with a utility to convert the line endings back after every time sass watch generates the CSS output file. Not everyone has an IDE that can do that.

I appreciate the comments and I understand your point of view. Ultimately though, you have this broken for a major operating system, as a design choice.

And that is 100% your call to make. I just hope you do change your mind at some point. Thank you!

**Comment by Karmalakas** [comment]
6 years later...
