### ISSUE TITLE
Rename `@forward show/hide` to `@export only/except`

### ISSUE THREAD

**Issue by glebm** [sass/sass#2645]
For the `@forward "some-module" show/hide thing` syntax, consider using `only` / `except` instead of `show` / `hide`. Also consider `@export` instead of `@forward`.

`only` and `except` are immediately clear even to those who do not fully understand the module system and haven't used languages with such terminology; `only` also indicates that no other names get exported except the listed ones.

It also reads better, VERB NOUN ADVERB NOUN instead of the somewhat clunky VERB NOUN VERB NOUN.

`@export` is similar to JavaScript, which most Sass users are likely to be at least a bit familiar with.

**Comment by nex3** [comment]
I don't know that I buy that `only` and `except` are particularly more clear than `show` and `hide`, and I think that "forward foo show bar" reads much more like an English sentence than "forward foo only bar".

I don't think using the same name as JavaScript's `export` is a benefit, actually. Sass's module system works pretty differently than JavaScript's: all members of a module are available by default, the syntax for forwarding specific members is different, and the underlying model (modules as object versus modules as syntactic construct) is different. I don't want to draw a strong parallel with JavaScript because it may encourage users to expect it to work more similarly than it actually does.

I'm curious what other people think, though.
