### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by nex3** [sass/sass#2670]
We should add continuous integration testing that can catch (at least) the following errors:

- [x] Markdown links missing a referent.
- [x] Markdown links to headings that don't exist.
- [x] Tables of contents missing heading links.

**Comment by TeresaPartidaS** [comment]
Hi! I'd like to help, can you tell me more about this?

**Comment by nex3** [comment]
We need to set up a [Travis CI](https://travis-ci.org/) config that will run a series of tests on the Markdown files in this repository to ensure links aren't broken and tables of contents include all headings in the document. I'm not sure what tools exist for this; ideally I don't want to implement something from scratch, but we'll probably need to write a plugin for table-of-contents validation. A cursory search indicates that [remark](https://www.npmjs.com/package/remark-cli)'s lint mode might be a good option, if it's extensible enough.

**Comment by nschonni** [comment]
@TeresaPartidaS I've used https://github.com/tcort/markdown-link-check for this before. I usually do a small wrapper script like this for the globbing of files https://github.com/canada-ca/digital-playbook-guide-numerique/blob/6a154f38bf406faabc492fb251ae2d09c37b987e/link-check.js. You might want an external config like https://github.com/canada-ca/digital-playbook-guide-numerique/blob/6a154f38bf406faabc492fb251ae2d09c37b987e/.markdown-link-check.json to set the site root and any links that need to be suppressed (since sometimes sites blacklist Travis-CI)

**Comment by TeresaPartidaS** [comment]
Thanks! I'm actually new to this so that's of great help

**Comment by nschonni** [comment]
No problem, there are probably also other solutions in different languages that you can find. I'm not sure if there is any preference for the CI setup.

**Comment by TeresaPartidaS** [comment]
@nex3 Hi! I managed to integrate Travis CI and created two files to catch the errors you mentioned before, I already did the PR :D
