### ISSUE TITLE
@extend supports comma-separated list of selectors in indented syntax

### ISSUE THREAD

**Issue by nathos** [sass/sass#272]
It appears that in Sass 3.1.14, you can do multiple extends on a single line w/ a comma-separated list of selectors.

e.g.:

``` sass
@extend .selector1, .selector2
```

See https://gist.github.com/1783082#gistcomment-82237 for an more complete example.

Personally, I like the behavior, but it doesn't work in SCSS at the moment and isn't reflected in the documentation.

**Comment by nex3** [comment]
I's worth noting that for class selectors, this is equivalent to

``` scss
@extend .selector1.selector2
```

Were this not already supported in the indented syntax, I'd be hesitant to support it because it muddles the semantics of `@extend` slightly. `A { @extend B }` means that `A` is styled as though it matches `B`; matching `.selector1, .selector2` technically means that it matches _either_ selector, whereas it will end up styled as though it matches _both_.

That said, it's pretty clear to a reader of the stylesheet what's going on here, and it's apparently been accidentally supported in the indented syntax all the way back to 3.0, so I'm going to go ahead and add support to SCSS.
