### ISSUE TITLE
Feature request: add a parameter to disable parsing of CSS comments

### ISSUE THREAD

**Issue by Llbe** [sass/sass#2727]
CSS comments (`/**/`) are parsed and interpolation is performed within them. This is a rational and good thing, unless you want to comment out SCSS code without using SCSS comments (`//`).

Now, if one uses `--style=compressed` that won't save the comments, parsing them isn't very useful (although existing code could behave differently if they're not parsed anymore).

I suggest adding a new parameter `--skip-comments` or similar, that simply disables parsing of CSS comments. You can use it if you want to be able to use any kind of commenting to disable code. Especially if you also use `--style=compressed`.

WDYT?

Related: https://github.com/sass/sass/issues/1123

**Comment by Llbe** [comment]
I guess this could be viewed differently by saying that this is about "adding CSS style comments to SCSS", by enabling them with a parameter.

**Comment by Llbe** [comment]
Sorry for the verbosity on this list, but `--comment-style=any|scss|css` is another option.

**Comment by nex3** [comment]
It's generally not a good practice to add flags that change the behavior of the language itself, because it makes it easier to write stylesheets that aren't portable from one user's Sass installation to another's. Since it's also possible to comment out blocks of Sass code with silent comments, which many text editors have built-in macros for, I don't think it's worth the extra complexity and unportability.
