### ISSUE TITLE
How case-sensitive should file extensions be?

### ISSUE THREAD

**Issue by alexander-akait** [sass/sass#2730]
Input:
```scss
// 1. Imports where the URL ends with .css.
@import "theme.css" // Works fine
// 2. Imports where the URL ends with .CSS.
@import "theme.CSS" // dart-sass try to resolve and send this in importer
```

But extensions is case insensitivity.

**Comment by nex3** [comment]
*(Moving this to the sass repo because it's more of a question of what the language-mandated behavior should be.)*

> But extensions is case insensitivity.

Is this generally true? According to whom?

If we were to declare that Sass extensions were *universally* case-insensitive, then we would have to check for all possible case permutations on case-sensitive filesystems (`.sAsS` and so on). This is clearly infeasible. We could make the extensions case-insensitive when written in Sass files themselves, but that raises a further dilemma: do they look for the physical files with lowercase extensions, or can they find files that can't be found with the extension-free form? @xzyfer and @mgreter, perhaps you could shed some light on LibSass's current behavior here?

It's also possible that we could *just* make case-insensitive `.css` extensions trigger the plain-CSS-import logic. That's still a little inconsistent, since Sass otherwise doesn't really acknowledge the existence of non-lowercase `.css` files, but definitely not as bad when they're not actually being loaded.

**Comment by alexander-akait** [comment]
Just for information, node-sass works with uppercase extensions. Thanks for feedback, wait answer from core developers

**Comment by mgreter** [comment]
Libsass [only looks for lowercase extensions][1] AFAICT.
Question is what OS/filesystem OP is actually using?

[1]: https://github.com/sass/libsass/blob/master/src/file.hpp#L117

**Comment by alexander-akait** [comment]
@mgreter node-sass works fine with uppercase extensions, any filesystem, it is not related to filesystem i think, it is more related to libsass and how libsass works with extensions

**Comment by mgreter** [comment]
Just tested it and this doesn't work on my linux machine with case sensitive FS and libsass ...

**Comment by nex3** [comment]
We should be clear about what "working with" multiple extensions means, since there are a number of possible options. @evilebottnawi and @mgreter, what specific cases are each of you testing?

**Comment by mgreter** [comment]
`test.scss`
```
@import "example-1";
```
`example-1.SCSS`
```
foo { bar: baz; }
```
`sassc test.scss`
```
Error: File to import not found or unreadable: example-1.
        on line 1:1 of test.scss
>> @import "example-1";
```
After `mv example-1.SCSS example-1.scss` it works.

**Comment by mgreter** [comment]
`test.scss`
``` 
@import "example-1.SCSS";
```
`example-1.scss`
```
foo { bar: baz; }
```
`sassc test.scss`
```
Error: File to import not found or unreadable: example-1.SCSS.
        on line 1:1 of test.scss
>> @import "example-1.SCSS";
```
After `mv example-1.scss example-1.SCSS` it works.

**Comment by nex3** [comment]
After discussing this with the team, we feel that we should retain the current behavior of *always* treating file extensions case-sensitively.
