### ISSUE TITLE
Combining @use with @extend

### ISSUE THREAD

**Issue by wisniewski94** [sass/sass#2755]
What @use does and @import doesn't is it requires a "prefix" like so:

``` sass
// a.sass
@mixin test($arg) ...
```

```sass
//b.sass
%extension
 ...

@mixin test($arg) ...
```

``` sass
//main.sass
@use "b"
@use "a"

.selector
 @include b.test(arg)
 @include a.test(arg)
```

But when I try to do the same with @extend, I cannot use a prefix:

``` sass
//main.sass

.selector
 @include b.%extension //error: Expected identifier.
```

This will work:

``` sass
//main.sass

.selector
 @include %extension
```
What if I have same extension name in multiple modules? How can I solve this issue?

**Comment by nex3** [comment]
If you load two modules which each use the same selector (whether that's a placeholder selector like `%extension` or a class selector like `.extension`), those selectors both become visible to the module, and there's no way to extend one without the other. One way to think about this is that the context of a single module defines the "semantic context" of the selector, so that presumably `%error` in either case refers to the same sort of error.

If you really want to work around this, you can define intermediate modules that create aliases for these selectors:

```scss
// a.scss
%extension { /* ... */ }
```

```scss
// a-wrapper.scss
@use "a";
%a-extension {@extend %extension}
```

```scss
// b.scss
%extension { /* ... */ }
```

```scss
// b-wrapper.scss
@use "b";
%b-extension {@extend %extension}
```

```scss
// main.scss
@use "a";
@use "b";

.selector {@extend %b-extension}
```

**Comment by wisniewski94** [comment]
I didn't know this hack. Thank you for sharing.

Still I would like to request for a feature with less hackish approach.
