### ISSUE TITLE
If you put in this valid 4-stop css3 gradient, it gets mangled

### ISSUE THREAD

**Issue by SimplGy** [sass/sass#277]
Super-bummed about this. I was really hoping SASS would work, but it's mangling my CSS3--these mixins are where it provides all the value, it's a shame to have them not workin'.

``` css
@mixin linGrad
  background-image: -webkit-linear-gradient (top, rgb(255,190,75) 0%, rgb(255,150,30) 50%, rgb(250,130,0) 50%, rgb(230,110,0) 100%)
  background-image: -moz-linear-gradient (top, rgb(255,190,75) 0%, rgb(255,150,30) 50%, rgb(250,130,0) 50%, rgb(230,110,0) 100%)
  background-image: -ms-linear-gradient (top, rgb(255,190,75) 0%, rgb(255,150,30) 50%, rgb(250,130,0) 50%, rgb(230,110,0) 100%)
  background-image: -o-linear-gradient (top, rgb(255,190,75) 0%, rgb(255,150,30) 50%, rgb(250,130,0) 50%, rgb(230,110,0) 100%)
  background-image: linear-gradient (top, rgb(255,190,75) 0%, rgb(255,150,30) 50%, rgb(250,130,0) 50%, rgb(230,110,0) 100%)

.button.onDark.orange
  +linGrad
```

**Comment by chriseppstein** [comment]
What output are you getting and what were you expecting.

**Comment by SimplGy** [comment]
It works if you take out the space between the word 'gradient' and the opening '('.

It's embarrassing how long this took me to figure out... Still probably should error more loudly about this--the css it kicks out if you have a space there is invalid.

**Comment by chriseppstein** [comment]
I see. @nex3 Seems like nesting a comma delimited list inside a space delimited list (as this code would be) is strange. Should it be an error?

**Comment by nex3** [comment]
@SimpleAsCouldBe It doesn't actually produce invalid CSS, as far as the grammar is concerned; `linear-gradient top, rgb(255,190,75) 0%, ...` is a valid property value.

@chriseppstein There are some difficulties in making this an error. We can't just say "no putting comma lists in space lists" since we don't want `@each (foo, bar) (bip, bop) (whiz, bang)` to randomly fail. We could make the error appear at stringification time, but I'm not sure it would be particularly clear.

I'm tempted to say that because this syntax isn't valid in CSS anyway, it's not worth worrying too much about how Sass handles it.

**Comment by chriseppstein** [comment]
Well good error messages are certainly one of Sass's benefits over plain CSS, so I thought it was worth exploring. I'll mull it over a bit more.

**Comment by SimplGy** [comment]
My understanding is that this is valid css to send to a browser:

```
.myButton {
  background-image: -webkit-linear-gradient(top, #ffbe3c 0%, #ff9614 50%, #fa8200 50%, #e66e00 100%); }
```

and this is not:

```
.myButton {
  background-image: -webkit-linear-gradient top, #ffbe3c 0%, #ff9614 50%, #fa8200 50%, #e66e00 100%; }
```

The top one is respected by Firefox and Chrome, the bottom one is not. The only difference in SASS input is whether or not you put a space after the word 'gradient' in '-webkit-linear-gradient(...)'.

I'm not sure whether it should be a parse error or not--I suppose it would be best to treat both space and no-space as the same for this case, but I'm unfamiliar with how that would affect other, similar cases.

**Comment by chriseppstein** [comment]
There's a difference between syntactically valid and "means something to the browser".

**Comment by nex3** [comment]
@SimpleAsCouldBe To elaborate on Chris's reply, Sass tries hard to avoid having specific knowledge of which properties and values exist in CSS and how they're used. It doesn't know that `-webkit-linear-gradient` is a function as opposed to, say, a border type like `solid`. This allows it to be very flexible when adapting to changing CSS standards, but it does mean we can't detect cases like this where you're doing something syntactically valid but semantically meaningless.

@chriseppstein I agree that good error messages are valuable, but I'm having a hard time figuring out how to generate a helpful error message for this case without making other cases more obscure. Since this is (I assume) a pretty uncommon error case, I'm not too worried about getting a great error for it.

**Comment by chriseppstein** [comment]
Concur.

**Comment by SimplGy** [comment]
At the risk of belaboring the point, I feel the real issue has not been understood.

It seems that a principle of the .SCSS language is to be a clean superset of .CSS. If that is true, any CSS I write in a .SCSS should come out the other end of the SASS processor working just as well. This is not the case if I enter this into a SASS parser:

```
.myButton {
  background-image: -webkit-linear-gradient (black,white);
}
```

SASS takes this and strips my parens, making the code no longer work in the browser. If the parser 'breaks' my otherwise functional CSS, it contributes to me not trusting the SASS parser and thinking it's flaky. I don't want to think it's flaky--I think it's an awesome idea and I want it to be rock solid.

As it stands, I'm adding to my arbitrary-seeming mental list of whitespace no-nos enforced by SASS:
#1 - Always put a space after a CSS property's colon
#2 - Don't put a space before the parentheses for a CSS3 method

In any case, it's a very cool and functional product.

**Comment by chriseppstein** [comment]
Regarding the first point - the indented syntax is not a superset of css. The need for a space after a property is needed to disabmiguate from a selector with a pseudo selector attached to it because there was no curly brace to change the parser's "mode".

Regarding the second point, you can't put a space between a function and the parenthesis in normal css either. Evidence:

![invalid syntax](https://img.skitch.com/20120215-jx8cfk552si32rmihd5tdwej91.png)

**Comment by nex3** [comment]
For more evidence, note the following in [the CSS spec's grammar](http://www.w3.org/TR/css3-syntax/#grammar0):

```
function
  : FUNCTION S* expr ')' S*
  ;

FUNCTION ::= ident '('
```

There is no whitespace allowed between the name of the function (an identifier) and the opening parenthesis.

**Comment by SimplGy** [comment]
Well, I guess that settles it. Still pretty wierd that the parens get stripped, but hey.

Thanks guys!

**Comment by chriseppstein** [comment]
The parens are stripped because they are a sass syntax extension.
