### ISSUE TITLE
Custom properties in SCSS mixin

### ISSUE THREAD

**Issue by clintfisher** [sass/sass#2775]
Hi there, I'm having a hard time using css vars in my sass mixins.

```
:root {
  --base-font-size: 16;
}

@mixin font-size ($font-size, $line-height) {
  $new-size: calc(#{$font-size} / var(--base-font-size));
  $new-line-height: calc(#{$line-height} / var(--base-font-size));

  font-size: #{$new-size} + rem;
  line-height: #{$new-line-height} + rem;
}

h1 {
  @include font(48, 50);
}
```
Any time I need to do some math/calculations, I'm not getting what I expect.  The computed value for the above code ends up being `16px`, where it should be `3rem`.

Any ideas/pointers on what I'm doing wrong?  Thanks!

**Comment by mirisuzanne** [comment]
The issue here is in how you are trying to mix CSS `calc()` and Sass concatenation. 

Custom properties and `calc()` functions are compiled by the browser, but you are attempting to add the `rem` units in Sass. At that point, the number is not yet calculated, and the rem units are added to a calc string:

```css
h1 {
  font-size: calc(48 / var(--base-font-size))rem;
  line-height: calc(50 / var(--base-font-size))rem;
}
```

Those values in the `h1` are not valid CSS, so they are being ignored – giving you a default  16px font size. In order to add units to a custom property or calculation, you have to do that inside the `calc` as well, by multiplying the result of your math `* 1rem`:

```css
font-size: calc(48 / var(--base-font-size) * 1rem);
```

Like this:

```scss
@mixin font-size ($font-size, $line-height) {
  $new-size: calc(#{$font-size} / var(--base-font-size) * 1rem);
  $new-line-height: calc(#{$line-height} / var(--base-font-size) * 1rem);

  font-size: #{$new-size};
  line-height: #{$new-line-height};
}
```

**Comment by clintfisher** [comment]
@mirisuzanne ahhh, thank you so much for that explanation and fix!

**Comment by clintfisher** [comment]
https://codepen.io/clintfisher/pen/xxxagEJ?editors=1100#0

I could be mistaken, but it seems the `rem` unit never gets applied. 

If you look at the inspector and computed styles it reports `px` as the unit and the value is the `px` value passed in, not the conversion `rem` value.

**Comment by mirisuzanne** [comment]
Yeah, all computed lengths are in `px` – because relative units are basically treated as calculations by the browser, and the computed value is the result of that calculation. When you put that in a `calc()` - the browser doesn't really add units, it resolves the entire function: units included. So you get the result of multiplying `1rem` (currently `16px`) by the results of your division. 

The important thing is that `1rem` remains dynamic in that calculation - and will update when the value of a `rem` unit changes. The real test is: does it react correctly to changes in the root font size? In my testing, it seems to.

**Comment by clintfisher** [comment]
Ok, I think I see what you're saying. Were you manipulating the `1rem` value in the calculation or changing the browser default font size?

I think whats throwing me off is that previously, I'd always created sass mixins to consume sass variables, this was my first time using custom properties with `calc` in my mixin.  Using sass vars, and without calc the inspector would show the `rem` units.

```
@mixin font-size ($font-size, $line-height) {
  $new-size: ($font-size / $base-font-size);
  $new-line-height: ($line-height / $base-font-size);
  font-size: ($font-size + px);
  font-size: ($new-size + rem);
  line-height: ($line-height + px);
  line-height: ($new-line-height + rem);
}
```

**Comment by mirisuzanne** [comment]
I was updating the default font size, or the font size on the root `html` element. Both `rem` and `calc()` will show up in the inspector "rules" panel - but both should be converted to `px` when you look at the "computed" panel. That seems pretty consistent across Firefox and Chrome at least.

**Comment by clintfisher** [comment]
Gotcha, thank you so much for insight and help, I really appreciate it.
