### ISSUE TITLE
Math proposal: Should incompatible units output CSS clamp() without error?

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#2788]
Similar to proposals for [`min()`/`max()`](https://github.com/sass/sass/blob/master/accepted/min-max.md) and [`calc()`](https://github.com/sass/sass/issues/2186) –  `clamp()` needs to allow for values that would be valid CSS, but not valid Sass:

```scss
$compatible: clamp(6mm, 3in, 6cm);
$valid-css: clamp(10em, 1fr, 30%);
$also-valid: clamp(12px, 10 * (1vw + 1vh) / 2, 100px);
```

(The same might be true for `hypot()` and `atan2()`, but CSS does restrict the "type" of units combined. I'm not sure if we can follow those same rules…)

**Comment by mirisuzanne** [comment]
Or is this proposal distinct because it's explicit inside the `sass:math` module rather than global? If that's the case: why the distinction?

**Comment by Awjin** [comment]
> Or is this proposal distinct because it's explicit inside the sass:math module rather than global?

Yes, exactly.

As you point out, the inputs to `clamp()` might involve lengths that are only knowable on the client side. If Sass could resolve these lengths eagerly, or somehow delegate them to browser-side processing, then we would be able to replicate the full range of what CSS's `clamp()` can do. (The same applies to `min()`, `max()`, `calc()`, `env()`.) But, since we currently don't have the infrastructure to do that, we can't implement `clamp()` in the global space. Otherwise we'd be overriding CSS's `clamp()` with one that has less functionality.

So in this case, we lean on the module system to contain our more limited version of `clamp()` and require users to invoke it explicitly through the `sass:math` module.

**Comment by mirisuzanne** [comment]
I take it this wouldn't be as simple as: 

- if the units are compatible without client-side knowledge, compile as SassScript…
- otherwise output to CSS

I believe you - I'm just missing the distinction. :)

**Comment by Awjin** [comment]
The solution to get global `min()`/`max()` was quite complex and mostly necessitated out of backwards compatibility. I think the distinction is that, moving forward we want to avoid similarly complex implementations, and instead be more intentional about grouping functionality into modules.

**Comment by mirisuzanne** [comment]
Got it - thanks!
