### ISSUE TITLE
[Math Functions] Should math functions output -0?

### ISSUE THREAD

**Issue by Awjin** [sass/sass#2794]
Some functions in the [Math Functions proposal](https://github.com/sass/sass/blob/master/proposal/more-math-functions.md) output `-0`, e.g. `sqrt(-0)`. Is it important to preserve the sign on `-0`? Can we just truncate that to `0`?

**Comment by Likewizedog** [comment]
Agreed. Nice catch

**Comment by Awjin** [comment]
Here's a more detailed example. If the output is truncated,

```
@use 'sass:math' as math;

a {
  b: math.pow(-0, 3);
}
```

outputs:

```
a {
  b: 0;
}
```

The *function* itself should output -0, but the serialized css is 0. We can verify this with the following:

```
a {
  b: math.pow(-0, 3);
  c: 1 / math.pow(-0, 3);
}
```

outputs:

```
a {
  b: 0;
  c: -Infinity;
}
```

https://github.com/sass/dart-sass/issues/807 is closely related.

If we treat all math as floating point operations, how should we represent the output?
Does `1.0` become `1` or `1.0`?
Does `-0` become `-0.0` or `0`?

An initial proposal might be that the output retains the simplest representation possible:
`1.2` => `1.2`
`1.0` => `1`
`-0.0` => `0`

**Comment by nex3** [comment]
Currently, the spec is essentially agnostic on the details of how numbers are handled. In practice, Dart Sass currently:

* Internally stores them as *either* integers or floating-point numbers, depending on how they were written in the source text and their mathematical history.
* Serializes them as integers if they're within a certain small delta of an integer.
* Serializes them as decimals otherwise.

As per https://github.com/sass/dart-sass/issues/807, we'll probably switch to always storing them as floating-point relatively soon.

This means that currently, if we do get a `-0` value, it's just emitted as `0` which I think is totally reasonable. That also makes it feasible to continue to return `-0` from the math functions, so they'll behave as expected with respect to floating point weirdness.

**Comment by Awjin** [comment]
> This means that currently, if we do get a -0 value, it's just emitted as 0 which I think is totally reasonable.

Sounds good. Followup question: the current proposal draft is specifying the output of the function (`-0`). Should it specify the outputted CSS (`0`) instead?

> As per sass/dart-sass#807, we'll probably switch to always storing them as floating-point relatively soon.

Should we move forward with this to avoid special-casing for `-0`? Currently it gets parsed as an integer and stored as `0`.

**Comment by nex3** [comment]
I don't think we need to let sass/dart-sass#807 block math functions. `-0` and integer `0` are nearly indistinguishable in Sass anyway, so I think just making the internal representation be a float for this case for now should be sufficient.
