### ISSUE TITLE
slashes (/) in variable names

### ISSUE THREAD

**Issue by blowsie** [sass/sass#2798]
Are slashes valid in variable names?

I came across an issue where they work in only some orders / scenarios.

### Works: 
https://www.sassmeister.com/gist/98a5c2d7e8366a7a818043a627c03fbb
```
$tw: (
  1/2: 50%,
  12: 12px
);
```

### Fails: 
https://www.sassmeister.com/gist/5e6b942b28425de4fdec89a10d3357b9
```
$tw: (
  12: 12px,
  1/2: 50%
);
```

**Comment by nex3** [comment]
That looks like a bug in LibSass. Please file it in https://github.com/sass/libsass.

Tangentially, I think you may have a slightly wrong mental model here. `1/2` in both of these cases isn't a variable name, it's a map key; and the slash isn't part of it, it's just part of how it's evaluated. Because `1/2` returns `0.5`, these are (or should be) equivalent to writing `0.5: 50%`.

**Comment by blowsie** [comment]
The reason I had a map key in this format was that I am exporting JS into SCSS, either way I just found it strange that it compiles correctly in one order, but not the other. 

Thanks for your input.
