### ISSUE TITLE
Undefined variable when using @forward with a library using @import

### ISSUE THREAD

**Issue by kennyjwilli** [sass/sass#2809]
I am trying to switch our sass to the new module system. We use the [Bulma](https://bulma.io/) library. If I have the follow `test.scss` file: 

```scss
@forward "../node_modules/bulma/sass/utilities/all";
@forward "../node_modules/bulma/sass/base/all";
```

And I run `npx sass test.scss test.css`, I get the following error: 

```
Error: Undefined variable.
  ╷
1 │ $body-background-color: $scheme-main !default
  │                         ^^^^^^^^^^^^
  ╵
  node_modules/bulma/sass/base/generic.sass 1:25  @import
  node_modules/bulma/sass/base/_all.sass 4:9      @forward
  test.scss 3:1                         root stylesheet
```

It thinks that the variable `$scheme-main` is undefined. It is, however defined in the file `derived-variables.sass` which is included when in the above `@forward "../node_modules/bulma/sass/utilities/all";`. 

This seems like it should work as expected. It would appear that the latter `@forward` does not have access to the variables defined in the former `@forward` when compiling. Is this expected? 

I have also tried exposing all variables in the first `@forward` like so: 

```sass
@forward "../node_modules/bulma/sass/utilities/all";
@use "../node_modules/bulma/sass/utilities/all" as *;
@forward "../node_modules/bulma/sass/base/all";
```

And I receive the same error after running `sass`. 

I am using sass `1.24.4` and bulma `0.8.0`.

**Comment by nex3** [comment]
I think you're misunderstanding what `@forward` does. It doesn't add forwarded members to the global scope—Sass with the new module system *never* has a global scope unless you use `@import`. It just means that stylesheets that `@use` your stylesheet will see the forwarded members. I recommend reading [the documentation](https://sass-lang.com/documentation/at-rules/forward) for more details.

Because `bulma/sass/base/all` doesn't `@import` or `@use` `bulma/sass/utilities/all`, there's no way for it to see members like `$scheme-main` using purely the module system. It also looks like Bulma doesn't have any sort of index file that imports everything in the correct order. I recommend filing an issue against Bulma requesting that they make their project compatible with the module system.
