### ISSUE TITLE
@use/@forward 'with' map 

### ISSUE THREAD

**Issue by Xaz16** [sass/sass#2815]
First of all thank you for such powerful tool and new delightful features, sass team!

I have a small question about new at-rules `@use` and `@forward`. Can I pass the map itself after `with` keyword and do you have a plan for such feature? I understand that what we pass after `with`
it is not map itself, due to it can have `!default` after each "key".

But I have a situation like this: 

```scss
// theme.scss
@use 'brand-variables';
@forward 'configured-ui-elements' with (...huge amount of variables which comes from brand-variables);
```
In fact I want to make theme.scss reusable as possible and don't want to know about content of brand-variables anything. I can just know that it is a variables which have !default declaration

In current @import state I have such file

```scss
// theme.scss
@import 'brand-variables';
@import 'configured-ui-elements';
``` 

And due to populating variables first in global scope and then declaring !default ones in configured-ui-elements it works perfectly... But I can't understand how to migrate to new at-rules

Can someone advice how can I migrate to new @use and @forward rules with saving of such logic?

**Comment by nex3** [comment]
I'm sorry, there's no way to pass a map object as a map of configured variable names. You'll either need to explicitly write all the variables you want to pass in to `configured-ui-elements`, or have `configured-ui-elements` use `brand-variables` itself and refer to the variables from there. I'd recommend the latter, because it's shorter and involves less indirection.

**Comment by Xaz16** [comment]
Thank you @nex3 !
