### ISSUE TITLE
Allow forward to be placed after import

### ISSUE THREAD

**Issue by max-hk** [sass/sass#2893]
Currently, it is not possible to forward an external library not designed for @use.

If we put forward after import, sass will fail to compile the file

```
// _variables.scss
@import "~bootstrap/scss/functions"; // Bootstrap v5.0.0-alpha-1
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";

@forward '~bootstrap/scss/variables' as bootstrap-*;


// Output
SassError: @forward rules must be written before any other rules.
  ╷
5 │ @forward '~bootstrap/scss/variables' as bootstrap-*;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\_variables.scss 5:1  @use
```

But if we put forward rule to the first line of the file, sass will find some mixin undefined.

```
// _variables.scss
@forward '~bootstrap/scss/variables' as bootstrap-*;

@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";

// Output
SassError: Undefined mixin.
    ╷
295 │ @include _assert-ascending($grid-breakpoints, "$grid-breakpoints");
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\bootstrap\scss\_variables.scss 295:1  @forward
  src\_variables.scss 1:1                            @use
```

If it is allowed to place @import rule before @forward rule, we will be able to forward libraries that are not designed for @use, like Bootstrap in the example.

**Comment by jathak** [comment]
This violates the [goals of the module system](https://github.com/sass/sass/blob/master/accepted/module-system.md#high-level) since allowing `@import` before `@use` or `@forward` is akin to allowing them anywhere (since `@import` can be treated as equivalent to just inlining the code from the imported file).

Even if this was allowed, it wouldn't actually work for your use case. Forwarding Bootstrap's variables file on its own doesn't work because that file implicitly depends on members defined in other files without explicitly depending on them, and loading that file as a module means that it can't reference members in the global scope.

We generally recommend waiting to migrate to the module system until all of your dependencies have migrated. If you do wish to depend on all of Bootstrap as a module, you could create one file that `@import`s all the necessary Bootstrap files and then `@forward` that all-in-one file. Since Bootstrap has an implicit dependency between these files, you can't really load them as separate modules.
