### ISSUE TITLE
@media query alternative  (@breakpoints syntax)

### ISSUE THREAD

**Issue by MatanelGordon** [sass/sass#2917]
My idea is to unite all SASS responsive code  in one  segment using this amazing syntax:

1. Define @ breakpoints statement, a custom at-root as a part of the new syntax.
`@breakpoints <media query> | <media query> ... ;` 
Example:
` @breakpoints (max-width:768px) | (min-width:769px) and (max-width:992px)| (min-width:993px) ;`

2. Declare properties with the following syntax:
`<property>:<values> | <values> | <values>; `
Example:
` position: relative | fixed | absolute;`

This syntax will translate to the following scss code:
```
@media (max-width:768px){
    position: relative;
}
@media (min-width:769px) and (max-width:992px){
    position: fixed;
}
@media  (min-width:993px){
    position: absolute;
}
```
**Notes:**
- You can define as many @ breakpoints as you need;
- You can define local breakpoints as well:
``` 
@breakpoints (max-width:992px) | (min-width:992px) and (max-width:1200px){
    padding: 8px 15px | 1rem 0.8rem;
}
```
**Advantages:**
- **Shorter code.** 
- Avoids repetition.
- Flexibility: allows you to develop  in either 'desktop first' code or 'mobile first' code, depends on your preference.

**Disadvantages:**
- Old Habits die hard - some developers are used to write code with @ media queries
Fix: @ media queries are still available
- Misconfigured @ breakpoints may cause discomfort (i.e. not having a fulll screen size coverage). 
Fix: it's still possible to define normal properties without the '|' divider.

**Help me develop it. its a great feature!**

**Comment by Awjin** [comment]
As a general rule, we do not introduce syntax in Sass that is not present in CSS. Since Sass is designed as a superset of CSS, we need to be careful about syntax that could be incompatible with CSS in the future (for example, what happens if CSS introduces a `|` delimiter that differs in meaning with your proposed delimiter)?

Further, I would argue that this syntax sacrifices readability and maintainability for the sake of brevity. Since the `@breakpoint` definition implicitly influences the `padding` style, any changes to the breakpoint could easily break the style in a hard-to-debug manner.
