### ISSUE TITLE
[Feature Request] Consider adding a @var keyword for local variables

### ISSUE THREAD

**Issue by Cosmius** [sass/sass#292]
Adding such a keyword like javascript will make assignment more secure.

``` scss
$bar: BarSetInGlobal;
@debug $bar;
@mixin FooMixin($foo) {
  @debug $bar;
  @var $bar: BarSetInFooMixin;
  @debug $bar;
}
@debug $bar;
@include FooMixin(123);
@debug $bar;
```

The code above is expected to print debug messages like:

BarSetInGlobal
BarSetInGlobal
BarSetInGlobal
BarSetInFooMixin
BarSetInGlobal

``` scss
$bar: BarSetInGlobal;
@debug $bar;
@mixin FooMixin($foo) {
  @debug $bar;
  $bar: BarSetInFooMixin;
  @debug $bar;
}
@debug $bar;
@include FooMixin(123);
@debug $bar;
```

The code above prints debug messages like:

BarSetInGlobal
BarSetInGlobal
BarSetInGlobal
BarSetInFooMixin
BarSetInFooMixin

**Comment by chriseppstein** [comment]
I think we need to re-evaluate lots of things regarding variables given that CSS-variables are a candidate recommendation now.

**Comment by nex3** [comment]
I dislike the idea of a `@var` keyword. The distinction between when to use `var` and when not to is unclear to many Javascript programmers, even those who have experience with scoping issues in other programming languages. Adding it to Sass seems unlikely to promote comprehension.

I'm closing this issue since the specific proposal is rejected. @chriseppstein, feel free to open a new issue to discuss the broader issue of how to bring our variables in line with the CSS proposal.
