### ISSUE TITLE
Ability to use css custom properties in @for loop in <expression>

### ISSUE THREAD

**Issue by stemford** [sass/sass#2926]
For now when I'm trying to use CSS custom properties as an \<expression\> of a @for loop I get an error:

"SassError: var(--grid-columns-count) is not a number."

```
@for $i from 1 through var(--grid-columns-count) {
      &.grid-xxl-#{$i} > * {
        grid-column-end: span #{$i};
      }
}
```

I would like to be able to use CSS custom properties as described.

**Comment by mirisuzanne** [comment]
This is not possible because CSS custom properties get their value from the cascade – so that value can only be determined by the browser, in relation to the HTML DOM. Like other CSS properties, they are scoped by selectors & elements, so a reference to a custom property outside that context is meaningless. That is one of the core differences between a Sass variable & a CSS custom property.
