### ISSUE TITLE
incorrect examples for transparentize and opacify in documentation

### ISSUE THREAD

**Issue by pixelass** [sass/sass#293]
While playing around I found following incorrect examples in the sass reference.

http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html

<h3>copied from the examples:</h3>

The alpha channel of a color can be adjusted using the opacify and transparentize functions. For example:

```
$translucent-red: rgba(255, 0, 0, 0.5);
p {
  color: opacify($translucent-red, 0.8);
  background-color: transparentize($translucent-red, 50%);
}
```

is compiled to:

```
p {
  color: rgba(255, 0, 0, 0.9);
  background-color: rgba(255, 0, 0, 0.25); }

```

<h3>but it results as:</h3>

```
/*
Syntax error: Amount 50% must be between 0 and 1 for `transparentize'
*/
```

<h4>While</h4>

```
$translucent-red: rgba(255, 0, 0, 0.5);
p {
  color: opacify($translucent-red, 0.8);
}
```

<h4>would result as:</h4> 

```
p {
  color: rgba(255, 0, 0, 0);
}
```

<h3>The documentation is as follows:</h3>

```
//transparentize
  transparentize(rgba(0, 0, 0, 0.5), 0.1) => rgba(0, 0, 0, 0.4)
  transparentize(rgba(0, 0, 0, 0.8), 0.2) => rgba(0, 0, 0, 0.6)
//opacify
  opacify(rgba(0, 0, 0, 0.5), 0.1) => rgba(0, 0, 0, 0.6)
  opacify(rgba(0, 0, 17, 0.8), 0.2) => #001
```

<b>...yet it would be very useful to transparentize by 50% of the current value.</b>
Is this an issue or just an incorrect example (as I assumed)?

**Comment by mikefowler** [comment]
Your assumption is correct in that the examples are just out of date. As you can [see in the source](https://github.com/nex3/sass/blob/master/lib/sass/script/functions.rb#L627), the function accepts numbers between 0 and 1, as noted by the error output. Updated the documentation and submitted a pull request.

That being said, it would be nice to provide the ability to punch in a percentage for those functions as well. I would assume  either that was the plan and it never made it from documentation to the actual function, or it was in the function at one point and has since been removed.

**Comment by Anahkiasen** [comment]
I would love really love it if all the major functions (opacify/rgba/etc) accepted percentages. Coming from LESS I'm really used to the fade(color, 40) syntax and I just think it's much much easier to use than to have to use .4 and such.

Plus it will make the LESS -> SASS transition easier for people wanting to switch, because that will reduce the amount of modifications needed to convert the code.

**Comment by mikefowler** [comment]
@nex3 or @chriseppstein: Did either of these functions previously accept percentages? I find it odd that a percentage would have made it into the documentation if they didn't at one point.

The way they are right now, in any case, doesn't translate to percentages. They don't actually multiply the starting alpha value but simply increase or decrease the original value by the value passed to the function.

**Comment by pixelass** [comment]
if we have for example `$translucent-red: rgba(255,0,0,0.5);` and want `$super-translucent-red` to always be `50% opacity of $translucent-red` we would have to use `$super-trans-red: transparentize($translucent-red,0.25);`

Now if we change to 

 `$translucent-red: rgba(255,0,0,0.3);`  

`$super-translucent-red` would be  `rgba(255,0,0,0.05);` 

but we want it to be `rgba(255,0,0,0.15);` 
so we need to change `$super-translucent-red` to `$super-trans-red: transparentize($translucent-red,0.15);`

So we would have to change 2 variables which kind of kills the idea.
Now this is only a simple example but I guess you can imagine how complex it could get if a lot of `transparentize` and `opacify` results depend on variables of the same kind

**Comment by mikefowler** [comment]
I agree that it would make situations like the one you describe here easier.

Not to get off-topic, but the above could be easily remedied:

``` SCSS
$opacity: 0.3;
$trans-red: rgba(255, 0, 0, $opacity);
$super-trans-red: transparentize($trans-red, $opacity * 0.5);

body {
  color: $trans-red;
  color: $super-trans-red;
}
```

**Comment by pixelass** [comment]
That is just about the way I am doing this. Of course we could use variables for anything .

``` scss
$r: 255;
$g: 100;
$b: 55;
$a: 0.3;
$my-color: rgba($r, $g, $b, $a);
```

But it just doesn't feel right, does it?
So I would really like to see the percentage option in future releases
...BTT

**Comment by Anahkiasen** [comment]
Well in the meantime you can always do

```
@function fade($color, $opacity)
    @return rgba($color, ($opacity / 100))
```

**Comment by nex3** [comment]
Let me try to address all the points in this issue one at a time:
- The documentation was incorrect and has been updated.
- We use decimals rather than percentages for opacity because that's what CSS does. It would have been nice if CSS had started out using percentages, but at this point remaining consistent is the most important thing.
- If you want to scale the opacity rather than adjusting it absolutely, you can use the `scale-color` function. For example, `scale-color($color, $alpha: -50%)` will make the color half as transparent as it was before. This function does use percentages because it's scaling by percentages of the original color value.

**Comment by pixelass** [comment]
the main issue was that there were incorrect examples in the documentation. The rest just evolved from that fact. I'm absolutely fine with the way it works
