### ISSUE TITLE
How to fix "Invalid CSS after "@debug map":"

### ISSUE THREAD

**Issue by kashchei23** [sass/sass#2969]
The documentation on the site says to use the `map.get()` function to return a map's values:

<img width="495" alt="Screen Shot 2020-12-03 at 10 57 53 AM" src="https://user-images.githubusercontent.com/62617506/101075106-6c938980-3556-11eb-9b90-bb6f0ac037d4.png">

However, this will throw an error message: 
<img width="519" alt="Screen Shot 2020-12-03 at 11 05 46 AM" src="https://user-images.githubusercontent.com/62617506/101075917-7ff32480-3557-11eb-9e5c-0bb7203db4b8.png">

**Instead, change to `map_get()`**`

**Comment by mirisuzanne** [comment]
That documentation assumes you are using Dart Sass, and have `@use`d the `sass:map` module:

```scss
@use 'sass:map';

// the "get()" function in the "map" module
@debug map.get($font-weights, 'medium');

// the legacy "map_get()" function
@debug map_get($font-weights, 'medium');
```

**Comment by snuup** [comment]
I am confused about Sass and Dart. The docs about map have not any mention about super exotic Dart: https://sass-lang.com/documentation/values/maps/

**Comment by nex3** [comment]
Sass is implemented in Dart because it has good support for our major distribution requirements: a highly efficient stand-alone compiler, a reasonably efficient pure-JS package, and a highly-efficient JS wrapper of a stand-alone executable.

The [`sass:map` documentation](https://sass-lang.com/documentation/modules/map/) does mention that the module was added in Dart Sass 1.23.0 and is not supported in LibSass or Ruby Sass, as well as the global function names that can be used in unsupported implementations.

**Comment by snuup** [comment]
Thank you, what confused me are the different docs: 

https://sass-lang.com/documentation/values/maps/ language 

versus 

https://sass-lang.com/documentation/modules/map/ language with split by implementation.

My problem is that examples in the lang doc do not work on my machine, I use easycompile inside vscode which references https://www.npmjs.com/package/sass which is the Dart version. At least I understand that I use the Dart version now so could raise another issue if such problem comes up again.

**Comment by nex3** [comment]
https://sass-lang.com/documentation/values/maps/ documents maps as a type, while https://sass-lang.com/documentation/modules/map/ documents the built-in functions that operate on maps. Note that all references to the functions in the former link to the latter, because that's where the full documentation of those functions lives, including documentation of their various levels of platform support.
