### ISSUE TITLE
Output of SASS function as value for CSS variable

### ISSUE THREAD

**Issue by svenvdvoort** [sass/sass#3004]
Hello,

A few days ago I ran into this problem. I want to assign the output of a SASS function to a CSS variable. This is the syntax that should achieve that:
```
@function foo {
    @return 5;
}
p {
    --variable: foo();
}
```

**Expected compiled output:**
```
p {
    --variable: 5;
}
```

**Actual compiled output:**
```
p {
    --variable: foo();
}
```

**Workaround:**
```
@function foo {
    @return 5;
}
p {
    --variable: #{foo()};
}
```

This looks like a bug to me, but maybe it's intended behaviour?
Thanks in advance for looking into this issue.

**Comment by mirisuzanne** [comment]
That workaround is the [proper syntax](https://sass-lang.com/documentation/style-rules/declarations#custom-properties) for using Sass script in CSS variables. CSS allows almost any text at all in variable declaration values, including most Sass. In order to support all valid CSS, `#{}` interpolation is required to use Sass inside a CSS variable.
