### ISSUE TITLE
Proposal: rgba() function with hexa and whitespace syntax

### ISSUE THREAD

**Issue by johannpinson** [sass/sass#3036]
Hello,

Actually, the built-in function `rgb[a]()` function allow some signatures, included the CSS Level 4 Syntax, also called the "whitespace syntax" on MDN.

But the Sass function, doesn't allow to combine hexa value in this syntax: 

```scss
// NPM sass:1.32.8 (dart)

$color: #f00;
@debug rgba($color, 0.5);
// DEBUG: rgba(255, 0, 0, 0.5)

@debug rgba($color / 0.5);
// SassError: Undefined operation "#f00 / 0.5".
```

Actually, it need to decompose the color to use it, and the result doesn't look good:

```scss
@use "sass:color";
$color: #f00;

@debug rgba(color.red($color) color.green($color) color.blue($color) / 0.5);
@debug rgba(255 0 0 / 0.5);

// assets/sass/app.scss:429 DEBUG: red --> Looks like a bug?!
// assets/sass/app.scss:430 DEBUG: rgba(255, 0, 0, 0.5)
```

The proposal is to allow the whitespace syntax with a hexa value as initial color.

```scss
rgba($color, $alpha); // actually works
rgba($color / $alpha); // reject error
```

The same logic will be added to the `hsl[a]()` function.

For information, this may be not possible due to the `/` character how seems to make a division instead of treat it as a delimiter, but I don't know the Dart lang to figure out if it's possible or not.

Thanks for your feedback,

**Comment by nex3** [comment]
We're not interested in further expanding the syntax of `rgba()` beyond what's already standard in CSS. Also, generally speaking, Sass-specific functionality should use Sass's standard comma-based calling conventions, and new-style spaces-and-slashes calling conventions should be reserved for behavior defined by the CSS spec.

**Comment by nanxiaobei** [comment]
`rgba(#000, 0.1)` has become a habit and is widely used.
It seems strange not to support `rgb(#000 / 0.1)`(Level 4).

**Comment by doug-stewart** [comment]
This should be reopened as it currently breaks standard usage. For example:

```
$values: 255 255 255;
color: rgba($values / 20%);
```

This breaks due to missing values but the CSS `rgba(255 255 255 / 20%)` is valid and to [spec](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb). Since we can't choose to use or not use the Sass function this is a breaking issue and requires us to write more complex CSS.

Interpolating the value and the funciton also both do not work.

**Comment by nex3** [comment]
@doug-stewart The behavior you're seeing is because `/` is being interpreted as an operator rather than a separator. We're working on changing that behavior (see https://sass-lang.com/d/slash-div), but until we do so you'll need to write `rgba(list.slash($values, 20%))` instead.

It's also worth noting that Sass still does maintain CSS compatibility here: literally writing `rgba(255 255 255 / 20%)` works as expected, it just starts to get hairy when variables are involved.

**Comment by doug-stewart** [comment]
Ah, that makes sense. That also explains why the other workaround my team has been using works:

```
$color: 255, 255, 255;
--color: #{$color};
color: rgba(var(--color) / 20%);
```

**Comment by nachtfunke** [comment]
This is one of those quite frustrating things. The `rgba()` is not nice, because it's legacy syntax. And the `list.slash()` workaround will get people complaining, unless they're aware of why it is necessary.

***

I'm writing this not with the intent of complaining, but with the intent of expressing how important I consider this to be. It is one of those things that as a developer working with sass, forces me to add specific code to maintain compatibility and it's very frustrating. Especially, considering that so many of us started using Sass because it allowed us to work with color with such ease, and now it is quite frustrating to do so, without relying on "legacy" syntax.

I hope that makes sense. I love sass and I use it everyday.
