### ISSUE TITLE
Bug - Syntax - Wrong Type - (exploding head emoji)

### ISSUE THREAD

**Issue by babakfp** [sass/sass#3038]
Hi

```scss
$some: (
  (some: some)
);
@debug type-of($some); // map

$some: (
  (some: some),
);
@debug type-of($some); // list
```

### What is wrong
Did anyone notice the difference? Just a `,` :)

### What is expected
To this code be a list type because there is no such concept of key and value.
```scss
$some: (
  (some: some)
);
```

Or it can't be possible to write a list type value with `()`.

**Comment by Awjin** [comment]
Hi @babakfp, good question. `((some: some))` actually *is* a map. Sass requires a special syntax for single-expression lists—you need to add a [comma after the first element](https://sass-lang.com/documentation/values/lists), which you've done correctly in `$some: ((some: some),);`.

You can verify this special behavior by comparing it to a list that also doesn't have commas, but contains more than one expression:

```scss
$some: ((some: some) (some: some));
@debug type-of($some); //=> list
```

A nicer way to achieve this would be to use square brackets instead of parentheses. This makes it explicit to Sass that you are using a list:

```scss
$some: [(some: some)];
@debug type-of($some); //=> list
```

**Comment by babakfp** [comment]
Hey
I didn't respond sooner because you gave me a solution. I didn't want the solution because I already have it. Basically, I'm forcing myself to write this comment. Now I want to respond because SASS is a great tool and I want it to be better. 

This can't be a map type, because keys and values are the only concepts behind the map. We shouldn't be able to create a map without the key and the value.
We shouldn't be able to create a list with `( )`, because we need consistency.
```scss
$some: ((some: some));
@debug type-of($some); // map

// What is expected?:
// ERROR, map expected to have a key and a value. If you are trying to create a list, use `[ ]` instead of `( )`.
```

@Awjin 
Please don't close the issue immunity, because it's disrespectful. Maybe wait 3 days or something.
