### ISSUE TITLE
How to use @use to import css from url

### ISSUE THREAD

**Issue by prad1386** [sass/sass#3043]
Hi, 

In SCSS how we can use @use to load external css from url?
@use url("http://someurl.com.sample.css");
@use "http://someurl.com.sample.css";
Above statements doesn't work.

**Comment by Awjin** [comment]
Sass does not download stylesheets from external URLs. Instead, you can use the CSS import syntax `@import url("http://someurl.com.sample.css");` in your Sass, and it will compile unchanged to CSS.

Otherwise, if you want Sass to resolve the import, you could have your build system download the CSS at the external URL before running the Sass compilation. In that case, use the downloaded CSS with `@use "path/to/downloaded.css"`.
