### ISSUE TITLE
Is it possible to create a :first-of-class selector?

### ISSUE THREAD

**Issue by joshuacookdev** [sass/sass#3044]
I know that CSS Selectors Level 4 is supposedly implementing a pseudo-class for this, but I'm wondering if it's possible to create a scss call that would compile to something similar? I know it would be a placeholder until other browsers support the call, but it would be pretty awesome to have.

#### Some links for investigation:
[Blog post describing options until selector works](https://philna.sh/blog/2018/03/18/css-first-of-class/)
[Codepen of examples for each](https://codepen.io/philnash/pen/WzoNwG/)

**Comment by Awjin** [comment]
Since Sass is a superset of CSS, it shouldn't add alternate syntax that duplicates CSS behavior, especially so if that behavior is already specified in CSS Selectors Level 4. Otherwise we'd have to go through the entire process of proposing, designing, and programming a language feature into Sass, only to deprecate it once the CSS feature lands.

**Comment by joshuacookdev** [comment]
That's what I had figured - I was more-or-less looking for a stand-in until it dropped. I appreciate the response!
