### ISSUE TITLE
Feature request - check if variable is default

### ISSUE THREAD

**Issue by saltavenger** [sass/sass#3071]
I would like if there was a way to determine if a variable is marked as default or not. Something very similar to "global-variable-exists", except for defaults.

Use case:
I am writing a mixin that gets my variables with `meta.module-variables`. It loops through them and outputs css custom properties. Ideally, I would only be making a corresponding property for variables marked as `!default` but I don't have a way of differentiating between them.

```
@use "sass:meta";
@use "sass:map";

@use "../variables";

@mixin set-css-custom-properties {
    $_config: meta.module-variables("variables");

    @each $name, $value in $_config {
        --bdx-#{$name}: #{meta.inspect($value)};
    }
}
```

There are several ways I can work around this just via structuring my project differently or writing slightly more duplicative code, but it's something I thought I'd suggest as a "nice to have."

**Comment by jathak** [comment]
Whether or not a variable is marked as `!default` isn't really part of a module's API, so we wouldn't want to expose this via a `meta` function. For a use case like this, you should instead put the variables that you want to convert to CSS custom properties in a map instead of just using raw Sass variables.
