### ISSUE TITLE
Undefined Variable Error with @Use

### ISSUE THREAD

**Issue by RoboZoom** [sass/sass#3094]
## Issue: 

A partial .scss file incorporating variables from a .sass file using the `@use` keyword leads to the error: `SassError: Undefined Variable`.  When the `@use` is replaced with `@import` the variables are recognized.  

UPDATE:  Issue localized to variable naming nomenclature.  Variables named `$--` do not propagate.  Traditionally named variables `$Foo` function as expected.  This appears to be a bug, or undocumented behavior with the SASS Language.

## Setup:

The first line of the main stylesheet: `@use "libs/shared/angular/util/theme/src/lib/style/index"`

The index file looks like this:
```scss
@forward "css-variables"
@forward "colors"
@forward "default-theme" // Error when default-theme is loaded
@forward "helper-functions"
```
The file _css-variables.sass looks like this:
```scss
$--primary: --primary
$--accent: --accent
$--header-color: --header-color
$--on-header-color: --on-header-color

@debug "CSS-Variables Accessed"
```

The default theme file looks like this:
```scss
@use 'css-variables' as *; // Same error whether I scope or do not scope it.  No error when changed to import
@use 'colors';

@debug "Post - css var import - still doesn't work";

$default-theme: (
  $--primary: colors.$colors(blue), // Error here - $--primary is undefined
  $--accent: colors.$colors(pink),
  $--header-color: colors.$colors(dark-grey),
  $--on-header-color: colors.$colors(white),
);
```

I setup a debug helper to ensure I was importing the files in the right order, which as shown below it appears as if they are:

```
DEBUG: CSS-Variables Accessed
DEBUG: Colors File Accessed
DEBUG: Post - css var import - still doesn't work
```

## Expected Behavior

Variables named `$--Foo` should behave no differently than other variables.  Or it should be documented that this is a semantic limitation.

## Actual Behavior

The variables in the css-variable are not recognized in the theme file while using the `@use` keyword.

UPDATE:  After further debugging, the syntax `$--Foo` appears to be causing the variable export issue.  When these variables are refactored to `$Foo`, the compilation performs as expected.

Maybe this is user error, which I would love community feedback if I've somehow set this up improperly.

**Comment by mirisuzanne** [comment]
@RoboZoom the definition and behavior of "private members" (prefixed with `_` or `-`) is [documented here](https://sass-lang.com/documentation/at-rules/use#private-members). Closing, since it's the expected/documented behavior, and we try to reserve this board for bugs & features.

I'm not clear what problem these variables are meant to solve, since the variable name and string name are identical. From what you've provided here, my instinct is just to remove the `--` prefixed variables entirely, and use the strings when setting up your default-theme. Alternately, you could change the names to be `$css-*` instead of `$--*`, or something like that.

**Comment by RoboZoom** [comment]
@mirisuzanne - I definitely missed that part of the documentation.  You are right to close the issue.  Thanks for correcting me.
