### ISSUE TITLE
Migrating from node-sass(lib-sass) to dart-sass breaks tests, whitespace gone

### ISSUE THREAD

**Issue by phun-ky** [sass/sass#3118]
We are currently deprecating `node-sass` for `dart-sass`, but we are stuck with an issue. The production build of the `*.scss` files now results in removal of white space between `@supports (display` (less and stylus produces the left one correctly) -> scss does this now: `@supports(display`. Resulting in:

![Screenshot from 2021-08-12 09-55-04](https://user-images.githubusercontent.com/1714029/129175323-38588a54-596e-445c-9afd-1fd3f8fbc08f.png)

What can we do to fix this?

**Comment by jathak** [comment]
`@supports(display` is valid CSS, and Sass doesn't guarantee a particular output format. It looks like you're using the `--compressed` output, which generally removes unnecessary whitespace. This shouldn't be something you need to fix.

**Comment by phun-ky** [comment]
Well we do need to fix this, it breaks our tests because of a breaking change you did. The compress functionality should remove whitespace, not add whitespace, like depicted above. Seems more of a bug than a feature Sendt fra min Galaxy

**Comment by jathak** [comment]
How does it break your tests? `@supports(display` and `@supports (display` are identical when it comes to CSS semantics.

**Comment by phun-ky** [comment]
We have a design system that has less, stylus and scss files. These files cannot be generated. To be able to make sure that all preprocessor files produce the same styling, we run tests that generate css from all of the preprocessor files and diff them. Sendt fra min Galaxy

**Comment by jathak** [comment]
Changes to whitespace are not breaking changes and should not be tested, as those tests would be incredibly fragile. 

`@supports(display` and `@supports (display` are both equally correct CSS, so Dart Sass's output and Node Sass's output are both valid (ditto Less and Stylus).

If you really need to test the equivalence of multiple CSS outputs, you have a few options:

1. Use the expanded output format for all of your preprocessors (for Sass, that would mean passing in `--style=expanded` or just omitting the flag entirely). This has most of the same problems, but as a temporary workaround, it may be good enough, since Sass at least (not sure about the other preprocessors) is less likely to change the source's whitespace in the expanded output format.
2. Normalize the output from each preprocessor before comparing them using a postprocessor like [cssnano](https://github.com/cssnano/cssnano). This is less fragile because using a common minifier should generally keep the whitespace consistent. Your tests would still be fragile to non-whitespace differences in CSS with equivalent semantics though.
3. Even better, consider setting up screenshot tests instead of literally comparing the generated CSS from multiple incompatible preprocessors. If you want to ensure that different CSS files result in the same styling, you might as well just test the actual rendered styles.

**Comment by phun-ky** [comment]
Hm, will look into a different solution @jathak , but here is my take on the proposed options:

1. Will see if there is less and stylus equivalents for this
2. We already use cssnano and normalize
3. Screenshot testing will results in more hours spend developing the test, and to flag off false positives, since we release updates to the design system 0-20 times a day.

Thanks for the reply.
