### ISSUE TITLE
Division is no longer a thing!?! Please stop these deprecation warnings!

### ISSUE THREAD

**Issue by ghost** [sass/sass#3131]
Come on, guys, really? I have come across these deprecation warnings on countless projects. People have raised this issue again and again. They are causing a major accessibility barrier for me, as I am legally blind, and I need clean logs, especially when the error messages do not pertain to anything under my control.

I mean, really? Some genius decided that inline division is no longer acceptable because it could possibly, maybe, plausibly interfere with a future CSS spec in a FUTURE version of sass, 2.0, which may or may not ever be released, and which component libraries could take months or years to update to, if/when it is released. I mean, we are on v1.38.1 and there is no 2.0.0.alpha version on npm in sight. So why warn us over and over again NOW??? With no way to turn it off?

Please let us TURN THESE DEPRECATION WARNINGS OFF!!! At LEAST let us turn them off in any file under node_modules.

**Comment by nex3** [comment]
Posting an angry rant with 3k lines of messages (which I've edited out) is not an appropriate way to bring up an issue anywhere, let alone on an open source repository where hard-working people do their very best to balance the needs of tends of thousands of different people, the vast majority of whom pay nothing for the privilege. This is a clear and egregious violation of the [Sass Community Guidelines](https://sass-lang.com/community-guidelines), and as such you are now blocked from this org.

To clear up any misconceptions for anyone else coming along this later:

* Division certainly is still "a thing". You can write division using the `math.div()` function or (as soon as https://github.com/sass/dart-sass/pull/1452 is released) within `calc()`.

* It's not true that `/`-as-division is only theoretically in conflict with CSS. `/` has been used as a separator in the `font` shorthand syntax since CSS 2.1, and has recently expanded to be used as a separator in [Colors 4](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb()) and [Grid Layout 3](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column) (supported in all modern browsers).

* It's not true that Dart Sass 2.0.0 may not ever be released.  Sass has more funding and a more concrete roadmap now than it ever has before, so the release of 2.0.0 is a question of "when" not "if". The main variable that we're looking at in determining the timing is what will minimally disrupt the ecosystem.

* There are flags available to disable deprecation warnings both in total and specifically for dependencies. The `--quiet` CLI flag disables all warnings, and the `--quiet-deps` flag specifically disables deprecation warnings in dependencies. The `quietDeps` option in the JS API does the same, and https://github.com/sass/sass/issues/2979 is in progress to provide the ability to silence all warnings in the JS API as well.
