### ISSUE TITLE
First-Class Calc: min/max are backwards-incompatible

### ISSUE THREAD

**Issue by SnakeO** [sass/sass#3142]
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: 0.25rem and 0 are incompatible.
  ╷
9 │       $return: append($return, max($value, 0));
  │                                    ^^^^^^ 0.25rem
  │                                            ━ 0
  ╵
  node_modules/bootstrap/scss/mixins/_border-radius.scss 9:36   valid-radius()
  node_modules/bootstrap/scss/mixins/_border-radius.scss 19:20  border-radius()
  node_modules/bootstrap/scss/_images.scss 18:3                 @import
  node_modules/bootstrap/scss/bootstrap.scss 14:9               @import
```

**Comment by nex3** [comment]
Sorry for the trouble, folks! This is the result of an unintentional backwards incompatibility in first-class calc support: we're now parsing `min()` and `max()` expressions as calculations if they're valid calculations, but we didn't take into account the fact that calculations are a bit stricter about units than the old global `min()` and `max()` functions. We'll need to take some time to design a more compatible way of handling this, but for the time being I'm going to partially revert this behavior:

* `min()` and `max()` functions that appear outside of calculations will be parsed the same way they were in 1.39.2, as global function calls if they contain any Sass-specific arguments and as unquoted strings if they don't.
* `min()` and `max()` functions *within* calculations will continue to be parsed as calculations, since they could never have been parsed as global function calls in the first place.

**Comment by Jeffery-Young** [comment]
same error, could rollback it first?

**Comment by nex3** [comment]
I've unpublished the npm package. On other platforms, there's not really a meaningful way to "roll back", so you'll need to wait for 1.40.1, which should be published within the hour.

**Comment by nex3** [comment]
Sass 1.40.1 has been released with the fix. I'm going to keep this open to track the progress of re-enabling `min()` and `max()` calculations.

**Comment by maoxiaoke** [comment]
> Sass 1.40.1 has been released with the fix. I'm going to keep this open to track the progress of re-enabling `min()` and `max()` calculations.

Seems not working!
![image](https://user-images.githubusercontent.com/13417006/133235480-488d51d2-5a83-4a07-a5be-e15b66f68371.png)

![image](https://user-images.githubusercontent.com/13417006/133235579-bbd68432-2824-4765-b2c6-32226fe89e6a.png)

**Comment by Jeffery-Young** [comment]
> > Sass 1.40.1 has been released with the fix. I'm going to keep this open to track the progress of re-enabling `min()` and `max()` calculations.
> 
> Seems not working!
> 
> ![image](https://user-images.githubusercontent.com/13417006/133235480-488d51d2-5a83-4a07-a5be-e15b66f68371.png)
> 
> ![image](https://user-images.githubusercontent.com/13417006/133235579-bbd68432-2824-4765-b2c6-32226fe89e6a.png)

same error:

![image](https://user-images.githubusercontent.com/12166600/133244381-dad6b5f2-ec91-4c58-877b-31067e9f8472.png)

**Comment by mattiaerli97** [comment]
A similar error is happening to me with Sass 1.40.1
![image](https://user-images.githubusercontent.com/45450225/133271033-b198d71c-767f-44f0-8ff2-c4d87d8078a6.png)
![image](https://user-images.githubusercontent.com/45450225/133271078-f51a62c0-2b10-4431-abb0-c2c0b5b00e11.png)

If I downgrade to Sass 1.39.2 is working, so I believe is a bug in the newer versions.
Can you please help me?
Thanks

**Comment by nex3** [comment]
@Jeffery-Young @mattiaerli97 Since those don't have to do with min/max, it would be better to file separate bugs for them.

@Jeffery-Young Your issue doesn't seem like it would have produced valid CSS in 1.39. If I write `29px + calc(4px/2)`, 1.39.2 produces `29pxcalc(4px/2)`. Producing an error there seems like an improvement over silently producing an invalid value.

@mattiaerli97 I've filed https://github.com/sass/sass/issues/3144 to track that.

**Comment by nex3** [comment]
We talked over various possibilities for addressing this long-term today. There are two broad options:

1. Continue to parse top-level `min()` and `max()` functions that contain Sass features as references to global Sass functions, and only parse `min()` and `max()` calculations when they contain only plain CSS, or when they appear within other calculations.

   This has the advantage of minimal change to the status quo, but it could be very confusing to users especially as they become more familiar with first-class calc. When users expect to be able to use variables and Sass functions in a calculation context, they're likely to be very surprised when arithmetic like `1px + 1%` *doesn't* work in `min()` and `max()`.

2. Parse all `min()` and `max()` functions that are valid calculations as calculations, as we did in 1.40.0, but loosen the restrictions on unit arithmetic within those calculations. All `min()` and `max()` calculations would allow unitless numbers to be mixed with units, including within `+` and `-` operations.

   This should preserve backwards-compatibility while also providing access to the benefits of calculations within `min()` and `max()`. There are two downsides: one is that we may be missing another case where calculations have different behavior than the equivalent SassScript syntax (although I don't think we are); the other is that this "infects" the new calculation type with legacy unit behavior that doesn't match CSS and produces some very strange behavior (try running `math.max(1in, 2, 3px)`).

We've decided to go with option 2, although we're open to feedback on this during the fast-track review process that I'll kick off later today. Although option 2 is conceptually messier and will likely leave us with behavior we'll eventually need to deprecate and then remove, we feel that meeting users' positive expectations ("this reasonable input should work") is more important than meeting negative expectations ("this unreasonable input should fail").
