### ISSUE TITLE
Should a module be able to @use its parent index file?

### ISSUE THREAD

**Issue by slynagh** [sass/sass#3211]
I don't know if this is a bug.

What is expected behaviour if a module loads its parent index file? In effect it is loading itself?

In a project all mixins and components are defined in their own file and forwarded through `mixins/_index.scss`.

`mixin-a.scss` @uses `../mixins` to access `mixin-b`.

`component-a` then @uses `../mixins`.

This creates a module loop error.

![image](https://user-images.githubusercontent.com/7286688/144991230-ccbe6115-7161-452f-91e5-46e6b782afd9.png).

`mixin-a` could simply `@use "mixin-b"` directly but then the syntax becomes
`@include mixin-b.mixin-b();` which reads terribly.

`mixin-a` could `@use "mixin-b" as *` but this leads to namespace conflicts. 

What is the best approach to take here?

_Originally posted by @slynagh in https://github.com/sass/sass/issues/3202#issuecomment-987672919_

**Comment by jathak** [comment]
Whoops. Just saw that you opened a new issue for this. Copying my response from the other thread:

That is working as intended. You're not allowed to create a dependency loop. If you have multiple files that need to depend on each other and you want to expose them as a single module, you can still forward them all through one entrypoint for downstream users, but they should @use each other directly when necessary.

If the members of the two files are so intermingled that you truly need them to share the same global namespace, it probably makes more sense to just make them a single source file.

**Comment by xuld** [comment]
I have come into a situation where dependency loop is required.

I have two modules: `variables.scss` and `mixins.scss`, 

`variables.scss` defines some configurable variables default, some of the default value is calculated by minxins.darken

// variable.scss
```scss
@use "mixins";
$dark-mode: true;

$primary: blue;
$primary-dark: mixins.darken($primary);
```

But the implement of `mixins.darken` requires back `$dark-mode` in `variable.scss`:

// mixins.scss
```scss
@use "variables";
@mixins darken($color) {
     @if (variables.$dark-mode) {
            // ...
     } @else {
            // ...
     }
}
```

My current workaround is use to `@import` instead of `@use`.

**Comment by nex3** [comment]
It sounds like you might be better off organizing your files based on what the members they export are *for*, rather than *what type* of members they export. For example, you could have a `_configuration.scss` file that contains global configuration values like `$dark-mode`, and then a `_colors.scss` file that uses `_configuration.scss` and contains both color variables like `$primary` and `$primary-dark` *and* color mixins like `darken()`.
