### ISSUE TITLE
Parameters of @content should be optional

### ISSUE THREAD

**Issue by xuld** [sass/sass#3221]
In javascript, what if all callback parameters should be listed even if it's not used:
```js
// Error: the callback for forEach requires 3 parameters 
[1, 2, 3].forEach(value =>console.log(value))

// OK:
[1, 2, 3].forEach((value, index, array) => console.log(value))
```

The current sass implmentation is making my code too verbose:
```scss
@mixin a(){
    @content(red, yellow);
}

// Error: requires 2 parameters 
@include a using($color1) {}

// OK: $color2 is not used.
@include a using($color1, $color2) {}
```

**Comment by nex3** [comment]
This is a very unusual feature of JavaScript. Almost no other programming languages allow users to silently pass too many arguments into a function call, because it makes it very easy to make mistakes and accidentally call a function differently than you intended. Sass has a similar policy as most programming languages here.
