### ISSUE TITLE
`@import` deprecation

### ISSUE THREAD

**Issue by Semigradsky** [sass/sass#3223]
In https://github.com/sass/sass/blob/main/accepted/module-system.md#timeline:
> One year after both implementations launch support for the module system or two years after Dart Sass launches support for the module system, whichever comes sooner (**1 October 2021 at latest**): Deprecate `@import` as well as global core library function calls that could be made through modules.

As I understand `@import` wasn't deprecated yet, so shouldn't the date be updated?

**Comment by KoenigAlfonz** [comment]
I for one hope, it will not get deprecated, at least not in the new future, since the deprecation would a) lead to constraints in building greater structures with lots of shared variable usage and b) most people are still using @import anyway, either because of a) or because they are not aware of the module system.

I think the best thing would be to enhance the @import implementation and keep it along side the module system, that way all beautiful and low complexity superpowers of Sass could be preserved.

**Comment by Semigradsky** [comment]
It looks like in most cases `@import 'some-file.scss';` can be safely replaced by `@use 'some-file.scss' as *;`. Migrating shouldn't be very hard.

**Comment by KoenigAlfonz** [comment]
Sure, in smaller projects, migrating should be fairly easy. In more complex structures though, you are running into problems pretty fast. In this topic #3218, I explained one case, where the absence of @import is creating a lot of trouble.

**Comment by nex3** [comment]
The proposals in `accepted/` are no longer living documents. They represent the state of the proposal at the point it was implemented. In this case, we chose to push out the date of deprecating `@import` to reflect the fact that it's taking the ecosystem a while to migrate off of Node Sass and to avoid adding more friction than necessary to that migration. We don't currently have a firm date in place for that deprecation, although we do plan to go forward with it at some point.
