### ISSUE TITLE
Add css cascade layer functionality to use & forward rules?

### ISSUE THREAD

**Issue by mirisuzanne** [sass/sass#3240]
The new [cascade layers](https://www.w3.org/TR/css-cascade-5/) feature is [starting to roll out in all three major browser engines](https://caniuse.com/css-cascade-layers), and I think there might be room for preprocessors to help people adopt and use layers better. 

Layers are a tool for encompassing specificity, and explicitly defining how styles should interact in the cascade. For example, an author can specify that their `reset` styles are lowest priority, followed by some `defaults`, and then a third-party `framework`, then `themes` and finally `components`. This is a broadly organizational concern, with different layers often coming from different parts of a team, or even third-party vendors – so CSS provides a `layer()` function and `layer` keyword on imports, in addition to the `@layer` rule. However, CSS imports tend to be less performant than linked (or merged) styles, and it's unclear when or if HTML will provide a more performant way of layering while linking.

It seems to me that this concern aligns very clearly with the use and purpose of Sass partials and package imports. These features help us organize styles, and merge them together for production. 

I wonder if we could add a `layer(<name>)` function to both `@forward` and `@use`. 

- when a layer is provided in a `use` rule, any output from the used file is wrapped in an `@layer` rule block
- `forward` rules could also append layer names, which would output as nested `@layer` blocks

I think this could help with adoption of Cascade Layers, but it would also remain useful in the long run after layering is widely adopted. Even if/when html adds support for layered css links, it is still often useful to concatenate files in a preprocessor.

**Comment by mirisuzanne** [comment]
(we could either support the anonymous `layer` keyword syntax as well, to output an unnamed layer, or allow the layer function to be empty)

**Comment by nex3** [comment]
I'm not a huge fan of this, since we're generally trying to encourage users to move away from writing a bunch of files that all directly emit CSS and towards exposing mixins that the entrypoint can compose as it chooses. In this case, you can already effectively model most of this behavior using `meta.load-css()`:

```scss
@use 'sass:meta';

@layer reset {
  @include meta.load-css('reset');
}
```

**Comment by mirisuzanne** [comment]
While I'm not sure the everything-in-a-mixin pattern makes sense for all projects, I do think this is a good solution that works across more use-cases. 👍🏼

**Comment by MagnusOxlund** [comment]
> we're generally trying to encourage users to move away from writing a bunch of files that all directly emit CSS and towards exposing mixins that the entrypoint can compose as it chooses.

Is there somewhere I can read more about the rationale behind this decision?

**Comment by nex3** [comment]
We don't have a central document anywhere but I can summarize here. When a Sass stylesheet emits styles automatically and unavoidably when loaded, it's pretty much universally less flexible—the person loading the file doesn't have any control over whether those styles are emitted, and they have very little control over _where_ they're emitted. They are difficult to parameterize and even if you do set up parameters with `!default` it's difficult to emit the styles multiple times with multiple parameters. All of these issues are solved by just putting the styles in mixins that get `@include`d by the downstream user.

In a broader sense, this is a specific instance of the general programming style principle of "avoid global state in libraries". A non-entrypoint stylesheet is just a type of library, and emitting styles directly is _effectively_ writing to the global state of the output stylesheet. It's bad for all the same reasons that, for example, a JavaScript library editing properties on `window` when it's loaded would be bad.

**Comment by matthew-dean** [comment]
@mirisuzanne 

> While I'm not sure the everything-in-a-mixin pattern makes sense for all projects

Same. Especially if the contents of your layer are third-party. For example:

```less
@import "modern-normalize/modern-normalize"; // <-- this needs to go in `@layer reset`
```
Ultimately, I solved this with:
```less
@layer reset {
  @include meta.load-css("modern-normalize/modern-normalize");
  @include reset($fontFamily, $bodyBg, $bodyFg);
}
```
...but that made the import patterns very messy and verbose, since I neither wanted a different mechanism to load a node module's CSS than my local SCSS, nor did I want to wrap my reset style sheet in a mixin and have to pass variables.

What I really wanted was:
```less
// theme.scss
@layer reset {
  @import "../reset.scss";
}

// reset.scss
@import "modern-normalize/modern-normalize";

// other reset styles...
```
However, Sass ignored the `@layer` entirely and dumped it at the root.

**Comment by Goodwine** [comment]
`@import` is deprecated and will be removed for Dart Sass 2.0. It has many many problems as it has already been discussed. It seems like you found a working solution, so that's great!

Regarding your example, I am getting the results you want with the provided inputs. I don't see `@layer` being ignored as shown below 🤔 . My best guess is that you have something else in your setup, like a `@use` at-rule somewhere.

Since you already found a workaround, I recommend sticking to it, or redesigning your solution to be `@use`-based rather than `@import`-based.

---

Given:
```scss
// main.scss
@layer foo { @import "foo"; }
@import "bar";
```
```scss
// foo.scss
.foo { foo: foo }
```
```scss
// bar.scss
.bar { bar: bar }
```
I get:
```css
@layer foo {
  .foo {
    foo: foo;
  }
}
.bar {
  bar: bar;
}
```
Which IIUC is what you want, no?

**Comment by Goodwine** [comment]
If you find that there's actually a bug somewhere, please file a separate issue and include the exact repro steps if you can. However, if the issue is not a bug, consider asking the question to the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass). We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
