### ISSUE TITLE
Allow inline // comments?

### ISSUE THREAD

**Issue by alanhogan** [sass/sass#326]
Really butters my loins, or rankles my cankles, or whatever, when I attempt to do something like:

```
.foo
  bar: baz // explanation
```

and sass (in the .sass syntax) chokes on it.

This is honestly the only reason I prefer .scss.

**Comment by Anahkiasen** [comment]
Would also prevent sass-convert from puttin inline comments _after_ the line they're supposed to comment when converting from scss/css to sass.

**Comment by nex3** [comment]
Sass supports inline silent comments in a number of places, including in the example you gave. It doesn't support them everywhere due to the nature of parsing the indented syntax; it's not set up for that kind of flexibility. That's one of the built-in advantages of SCSS.

**Comment by alanhogan** [comment]
How can you tell which places inline comments are allowed and which places they are not?

**Comment by nex3** [comment]
They're allowed on their own line or in SassScript and selector contexts. They're generally disallowed everywhere else.

**Comment by scalisi** [comment]
I apologize if this is the wrong place to ask this question, but are inline comments not meant to be used after `!default` in Sass's indented syntax? For example, the first two comments in the following code don't cause an error, but the third comment does:

``` sass
$x: 1            // 1st comment
$y: 2 !important // 2nd comment
$z: 3 !default   // 3rd comment
```

I'm sorry if the subject of inline comments with the indented syntax has been beaten to death. I've been using the indented syntax happily for months, and only today after I wrote a comment following `!default` did I learn that there can be issues when using inline comments with the indented syntax.

**Comment by SimplGy** [comment]
I found this a big surprise, too! I've been using the indented syntax every day for at least a year--I'm not an expert on the edge cases of the language, but a competent user I'd say I must be.

Apparently inline comments are not supported, or intended to be supported. I've been using them all along and had no idea. The new -pre version of sass that supports source maps causes some failures on inline comments that previously used to work, this is how I found out.

Here is the note I raised, and @nex3 pointing out that it's not really intended to be used.
https://github.com/nex3/sass/issues/895

Just a heads up for all who may come after!
(though reliable inline comments would be really extra special... :)

**Comment by chriseppstein** [comment]
@nex3 I think this is a bug.

**Comment by nex3** [comment]
I'm willing to leave this open, but it would require a major rewrite of the parser for the indented syntax, and I'm unlikely to be able to do that anytime soon.

**Comment by SimplGy** [comment]
I'm not sure how you guys feel about this, but the idea occurred to me and I thought it had enough merit to float to the group.

I think it's fair to say SASS and Coffeescript are syntax cousins, and since they both precompile and are used in front end work I think it's common for developers to use both on the same projects.

What if we added support for inline comments using the `#` symbol? Would using a new symbol make the parsing rule easier to implement, or would it get confused with #IdSelectors?

The `//` syntax could be left at whatever level of support it is and one line comments could be handled robustly on the new char.

Just a thought :)

Thanks again for a great tool that makes my styling work more productive and fun.

**Comment by nex3** [comment]
The issue isn't that `//` is ambiguous, it's that the indented syntax parser isn't set up in a way to make any sort of inline comment support feasible.

**Comment by Arcovion** [comment]
This needs to be included in the changelog. The only thing I found pertaining to it was:

> Comments following selectors in the indented syntax will be correctly converted using sass-convert.

Which is weird since Sass 3.3.x now removes support for comments following selectors anyway...

It was an easy fix of course but it took me a while to figure out the cause - there's really no error message about it and I just kept getting red herrings like:

```
Sass::SyntaxError: Properties are only allowed within rules, directives, mixin includes, or other properties.
Sass::SyntaxError: Extend directives may only be used within rules.
```

It would be really great if the indented syntax had proper support for inline comments, it'd also be neat to have `#` style comments as mentioned above, but that's just a personal preference.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because Dart Sass and LibSass both support inline comments everywhere, so this is now specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.

**Comment by michael-odonovan** [comment]
> Really butters my loins, or rankles my cankles, or whatever, when I attempt to do something like:
> 
> ```
> .foo
>   bar: baz // explanation
> ```
> 
> and sass (in the .sass syntax) chokes on it.
> 
> This is honestly the only reason I prefer .scss.

Yep, I use sass but have started thinking of migrating to scss for this reason.
