### ISSUE TITLE
Sould sass be installed as a 'dependency' or as a 'devDependency?

### ISSUE THREAD

**Issue by VirtueAndTerror** [sass/sass#3263]
Should sass be installed as a 'dependency' or as a 'devDependency'?

In the [npm page](https://www.npmjs.com/package/sass#usage) says: " You can also add it to your project using npm install --save-dev sass." 

But in the [Install Sass page](https://sass-lang.com/install) there is no information about this topic.

I have it like this and it works:

```
  "devDependencies": {
    "@parcel/transformer-sass": "^2.3.2",
    "parcel": "^2.3.2"
  },
  "dependencies": {
    "normalize.css": "^8.0.1",
    "sass": "^1.49.8"
```
  }

But I wonder whether I should better have it as a devDependency.

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.

**Comment by PjotrB** [comment]
I found an article that explains it quite well (archive.org copy):
https://web.archive.org/web/20230602154817/https://jsramblings.com/do-dependencies-devdependencies-matter-when-using-webpack/

TL:DR; it does not matter a lot, it is mostly a convention to help people know if a package is intended to be used for build only (like SASS) or if its code actually ends up running in the web browser, because if so then vulnerabilities are much more a concern.
