### ISSUE TITLE
Provide a way to share resources across multiple compilations

### ISSUE THREAD

**Issue by sapphi-red** [sass/sass#3296]
* [Proposal](https://github.com/sass/sass/blob/main/proposal/shared-resources.d.ts.md)

---

It seems currently sass-embedded starts one process for each compile request and stops it after compilation.

When using Vue components with sass, Vite requests one compile request for one file. This makes many compile requests and it slows down by process creation overhead.

[esbuild reuses process](https://github.com/evanw/esbuild/blob/e8768569a042be09be0b01445fbe399ed043793b/lib/npm/node.ts#L245-L356) to avoid this situation. I suppose the performance can be improved in the same way.

**Comment by ntkme** [comment]
A quick benchmark with sass-embedded-host-ruby as it is capable of reusing compiler process:

``` ruby
require 'benchmark'
require 'sass-embedded'

n = 1000
Benchmark.bm do |x|
  x.report('reuse') do
    n.times do
      Sass.compile_string('')
    end
  end
  x.report('  new') do
    n.times do
      sass = Sass::Compiler.new
      sass.compile_string('')
      sass.close
    end
  end
end
```

```
       user     system      total        real
reuse  0.148874   0.068218   0.217092 (  0.446515)
  new  0.694413   1.849822  12.046062 ( 10.330498)
```

You can see the overhead of starting a new compiler process in my environment is about 12 milliseconds. For a project with tons of files to compile, the overhead can add up to something noticeable.

**Comment by nex3** [comment]
This is something we'd like to add, but it's non-trivial from a design standpoint. We'd need a way for the user to represent when a shared process should be spun up and when it should be disabled, and we'd want to make sure that API will work well for integration with various frameworks that tend to do many different Sass compilations over time. Ideally it would also "rhyme" with the API for sass/sass#2745, since that represents a more intense version of the same underlying "shared resources across compilations" logic.

I'm going to move this to the language repo, since it will require a JS API proposal, even if that proposal will only be (usefully) implemented in the embedded host.

**Comment by ntkme** [comment]
@nex3 I think there are two stages of optimization here. The first one would be simply reuse the same dart-sass-embedded process but do not share resources across requests, which is possible today without the need of changing the API. I think that is what @sapphi-red and I are talking about in terms of process creation overhead. The shared resources, e.g. shared cache, would be another optimization that would need discussion in language repo.

**Comment by nex3** [comment]
By "shared resources", I just mean "the underlying process" (for the embedded host; other implementations could theoretically have other resources they might want to share). #2745 is tracking shared *state*, which is indeed a more complex level of optimization.

**Comment by NathanBeddoeWebDev** [comment]
I've been doing some investigation into this issue, as someone who has 70 scss files to build into 70 css files.

If I'm doing a synchronous compilation with the current release, it takes ~20 seconds to build these files, whereas if I make the SyncEmbeddedCompiler export a single instance of the compiler, then it cuts down to ~5 seconds, and I still get the same output in my CSS.

From what I've read, the dart process should be long running, with writes to stdio occurring, and listening to stdout. Does changing the Compiler classes to export singleton objects solve this issue? I am making some assumptions that there are added benefits of in memory caching within the same dart process that has compounded the speed improvements I've seen.

I'm not well versed in this project, so I'll be very happy to learn more about why it was done in this manner, and the downsides to the singleton approach (ie. the async compiler doesn't work in it's current state as a singleton).

**Comment by ntkme** [comment]
For the performance of the majority of the use cases, having a single embedded compiler process kept running would be the best. Thus that another option we should consider is to change the default behavior to use a kept-alive process (share resources by default), and then later provide an API for users to control if they want to manually control more resources.

**Comment by nex3** [comment]
Keep a process alive _by default_ essentially amounts to building in a memory leak on purpose—we'd be silently allocating a bunch of resources the first the the user compiles Sass without any way of managing the lifetime of those resources. That's why I want an explicit API for managing the compiler lifetime.

**Comment by ntkme** [comment]
I do agree having explicit control would be nice. However, allocation from first-time use should not cause too much problem as long as the leak does not grow overtime. - Nowadays machine are pretty powerful that waste a few mb of memory is not a really big deal. 

The whole reason I think delivering support for shared resource should be prioritized is that for many use cases we have seen sass-embedded currently would perform significantly worse than the dart transpiled JS due to restarting the process, so it totally defeats its selling point that dart-vm will run faster than JS.

**Comment by nex3** [comment]
There are other reasons than just memory consumption that allocating a global, unfreeable resource isn't likely to be a good idea. And while I agree that solving this would be very high-value, I want to make sure we do it in a way that won't paint the API into an undesirable corner in the future.

One relatively low-overhead option would be to expose a `sass.Compiler` class that provides the same API as the top-level `sass` namespace, with an additional `dispose()` method. Then you could write:

```js
import {Compiler as SassCompiler} from 'sass-embedded';
const sass = new SassCompiler();
```

...and then use the API as normal otherwise. We could then extend that later on to support https://github.com/sass/sass/issues/2745 by adding an `assumeNoChanges` option to `new Compiler()`.

**Comment by lucasenicora** [comment]
Hi all!
I've just stumbled upon this issue while trying to update our current setup from node-sass to dart-sass, since the former is currently deprecated. Our project has to compile tons of different SCS files, and build times have doubled after implementing sass-embedded.

So I would like to ask you wether there's any update on this topic. We would like to move forward using sass-embedded, but most probably we would prefer to wait for this issue to be fixed. So, do you have any approximate estimation on when this issue might be resolved?

Thanks in advance!

**Comment by NathanBeddoeWebDev** [comment]
@lucasenicora I actually got a build up and running of this using a reused process, and it halved build times on our project of about 100 scss files being built to 100 css files. Not sure if it could be optimized further, but there's definitely a speed benefit.

**Comment by ntkme** [comment]
@NathanBeddoeWebDev There is also https://github.com/sass/dart-sass/issues/1959

It depends on how you are sending compilation requests to sass. If you are sending them concurrently to a single compiler backend, they will likely be blocked and ended up running sequentially on the compiler side. This need to be fixed in the compiler but there is other performance trade off in doing so. You can see the issue for more discussion there.

Given what we have with compiler as it is today, another possible optimization is to pre-start multiple reused compiler instances, and distribute the compilation requests amount multiple instances so that they can truly be parallelized without blocking each other. Again, this will significantly increase the implementation complexity and will only benefit if requests are submitted concurrently.

**Comment by lucasenicora** [comment]
Hi both of you, and thanks a lot for your answers.

I understand that there seems to be a way of accomplishing this, but it's not yet ready for adding it to the library, due to other side effects.

What I'm curious is, @NathanBeddoeWebDev how did you manage to get this working? Could you give me some more detailed info, or link to a repo? I'm honestly not familiar at all with the internal code of this library.

Also, @ntkme you're suggesting to **_pre-start multiple reused compiler instances, and distribute the compilation requests amount multiple instances_**. Is this something that can be accomplished using the JS API? Or are you referring to something that can be done by modifying the internal code of the library?

**Comment by ntkme** [comment]
> Is this something that can be accomplished using the JS API? Or are you referring to something that can be done by modifying the internal code of the library?

This requires heavy modification on embedded-host-node.

**Comment by NathanBeddoeWebDev** [comment]
> What I'm curious is, @NathanBeddoeWebDev how did you manage to get this working? Could you give me some more detailed info, or link to a repo? I'm honestly not familiar at all with the internal code of this library.

It took a fair amount of changes in embedded-host-node, pretty much exporting a Compiler class. I'll try and clean up my code and let you know.

Sync and Async were faster on a 100 css file project, by about 1/2 (12s became 6s) but I didn't see a difference between sync and async (which I think is due to something blocking still, not sure).

**Comment by dmichon-msft** [comment]
To explore the performance of reusing SASS compiler processes, I used the following chunk of wrapper code (I'm still running against 1.49.11 right now due to compatibility in my repository's sass files):

```ts
import type { CompileResult, Options } from 'sass-embedded';

const { AsyncEmbeddedCompiler } = require('sass-embedded/dist/lib/src/async-compiler');
const { FunctionRegistry } = require('sass-embedded/dist/lib/src/function-registry');
const { ImporterRegistry } = require('sass-embedded/dist/lib/src/importer-registry');
const { PacketTransformer } = require('sass-embedded/dist/lib/src/packet-transformer');
const { MessageTransformer } = require('sass-embedded/dist/lib/src/message-transformer');
const { Dispatcher } = require('sass-embedded/dist/lib/src/dispatcher');
const {
  InboundMessage,
  OutputStyle
} = require('sass-embedded/dist/lib/src/vendor/embedded-protocol/embedded_sass_pb');

interface IImporterRegistry {
  importers: unknown[];
  import(request: unknown): unknown;
  fileImport(request: unknown): unknown;
  canonicalize(request: unknown): unknown;
}

interface IFunctionRegistry {
  call(request: unknown): unknown;
}

interface IDispatcher {
  logEvents$: {
    subscribe(callback: (event: ILogEvent) => void): void;
  };
  sendCompileRequest(
    request: unknown,
    callback: (err: Error | undefined, response: ICompileResponse) => void
  ): void;
}

interface IAsyncEmbeddedCompiler {
  exit$: Promise<void>;
  stdout$: unknown;
  close(): void;
  writeStdin(buf: Buffer): void;
}

interface IPacketTransformer {
  outboundProtobufs$: unknown;
  writeInboundProtobuf(packet: unknown): void;
}

interface IMessageTransformer {
  outboundMessages$: unknown;
  writeInboundMessage(message: unknown): void;
}

interface ICompileRequest {
  setImportersList(importers: unknown[]): void;
  setGlobalFunctionsList(functions: unknown[]): void;
  setSourceMap(sourceMap: boolean): void;
  setSourceMapIncludeSources(sourceMapIncludeSources: boolean): void;
  setAlertColor(alertColor: boolean): void;
  setAlertAscii(alertAscii: boolean): void;
  setQuietDeps(quietDeps: boolean): void;
  setVerbose(verbose: boolean): void;
  setStyle(outputStyle: number): void;
  setPath(path: string): void;
}

interface ILogEvent {
  getFormatted(): string;
}

interface ICompileResponse {
  getSuccess(): ICompileSuccessResponse;
  getFailure(): string;
}

interface ICompileSuccessResponse {
  getCss(): string;
  getLoadedUrlsList(): string[];
}

export class SassCompilerPool {
  private readonly _instances: SassCompilerProcess[];
  private _minQueueDepth: number = 0;

  public constructor(options: Options<'async'>, concurrency: number) {
    this._instances = [];

    const functions: IFunctionRegistry = new FunctionRegistry(undefined);
    const importers: IImporterRegistry = new ImporterRegistry(options);
    const handlers: unknown = {
      handleImportRequest: (request: unknown) => importers.import(request),
      handleFileImportRequest: (request: unknown) => importers.fileImport(request),
      handleCanonicalizeRequest: (request: unknown) => importers.canonicalize(request),
      handleFunctionCallRequest: (request: unknown) => functions.call(request)
    };

    for (let i: number = 0; i < concurrency; i++) {
      const instance: SassCompilerProcess = new SassCompilerProcess(importers, handlers);
      this._instances.push(instance);
    }
  }

  public getInstance(): SassCompilerProcess {
    const minQueueDepth: number = this._minQueueDepth;
    let minFoundQueueDepth: number = Number.MAX_SAFE_INTEGER;
    let minFoundCompiler: SassCompilerProcess | undefined = undefined;
    for (const instance of this._instances) {
      const { queueDepth } = instance;
      if (queueDepth === minQueueDepth) {
        return instance;
      }

      if (!minFoundCompiler || queueDepth < minFoundQueueDepth) {
        minFoundQueueDepth = queueDepth;
        minFoundCompiler = instance;
      }
    }

    this._minQueueDepth = minFoundQueueDepth;
    return minFoundCompiler!;
  }

  public async disposeAsync(): Promise<void> {
    await Promise.all(this._instances.map((instance) => instance.disposeAsync()));
    this._instances.length = 0;
  }
}

export class SassCompilerProcess {
  public queueDepth: number = 0;
  private readonly _importerRegistry: IImporterRegistry;
  private readonly _process: IAsyncEmbeddedCompiler;
  private readonly _dispatcher: IDispatcher;

  public constructor(importers: IImporterRegistry, handlers: unknown) {
    this._importerRegistry = importers;
    this._process = new AsyncEmbeddedCompiler();

    try {
      const packetTransformer: IPacketTransformer = new PacketTransformer(
        this._process.stdout$,
        (buffer: Buffer) => this._process.writeStdin(buffer)
      );
      const messageTransformer: IMessageTransformer = new MessageTransformer(
        packetTransformer.outboundProtobufs$,
        (packet: unknown) => packetTransformer.writeInboundProtobuf(packet)
      );
      this._dispatcher = new Dispatcher(
        messageTransformer.outboundMessages$,
        (message: unknown) => messageTransformer.writeInboundMessage(message),
        handlers
      );
      this._dispatcher.logEvents$.subscribe(handleLogEvent);
    } catch (err) {
      this._process.close();
      throw err;
    }
  }

  public async compileFileAsync(filePath: string): Promise<CompileResult> {
    ++this.queueDepth;

    const request: ICompileRequest = new InboundMessage.CompileRequest();
    request.setImportersList(this._importerRegistry.importers);
    request.setGlobalFunctionsList([]);
    request.setSourceMap(false);
    request.setSourceMapIncludeSources(false);
    request.setAlertColor(true);
    request.setAlertAscii(false);
    request.setQuietDeps(false);
    request.setVerbose(false);
    request.setStyle(OutputStyle.EXPANDED);
    request.setPath(filePath);

    const compileResponse: ICompileResponse = await new Promise((resolve, reject) => {
      this._dispatcher.sendCompileRequest(request, (err: Error | undefined, response: ICompileResponse) => {
        --this.queueDepth;
        if (err) {
          return reject(err);
        }
        resolve(response);
      });
    });

    return handleCompileResponse(compileResponse);
  }

  public async disposeAsync(): Promise<void> {
    this._process.close();
    await this._process.exit$;
  }
}

function handleLogEvent(event: ILogEvent): void {
  console.error(event.getFormatted());
}

function handleCompileResponse(response: ICompileResponse): CompileResult {
  const success: ICompileSuccessResponse = response.getSuccess();
  if (success) {
    const result: CompileResult = {
      css: success.getCss(),
      loadedUrls: success.getLoadedUrlsList().map((url: string) => new URL(url))
    };
    return result;
  }

  const failure: string = response.getFailure();
  if (failure) {
    throw new Error(failure);
  }
  throw new Error('Compiler sent empty CompileResponse.');
}
```

Integrating directly in embedded-host-node would obviously be more ergonomic (and not hardcode as many options as I did here), but when testing concepts I find it easier to work from a consuming repository.

I needed to set up the pool for comparison because my baseline involves parallel invocation of 1 SASS process per core iterating through 121 .scss files (some of which are partials and get skipped). The main difference I see is that that baseline spent 750 ms in child_process.Spawn, whereas a pool of 8 parallel long-lived processes spends about 50 ms and takes a similar total duration.

**Comment by ntkme** [comment]
Note that node.js event loop supports concurrency but concurrent tasks do not run in parallel as the after all JavaScript is single threaded unless you use `Worker`. With this model, the node host can be bottlenecked on event loop handling I/O when compiling lots of small files, even if you use multiple compilers.

In the ruby host I have tried the idea of connection pool as well. CRuby has GVL (Global Virtual Machine Lock) so that it can only handle one response at a time, however, blocking I/O thread in CRuby are truly parallel. On a 10-core M2 Macbook Pro, I see about 1.6x throughput improvement for repeated compiling `a {b: c}` with two to four persisted compilers over one persisted compilers; however, adding more persisted compilers into the pool would reduce the throughput as bottleneck shifts.

**Comment by nex3** [comment]
This proposal is now out for review. It's relatively simple, so I'll give it a month for public comment before approving.

**Comment by sgarfinkel** [comment]
Two quick questions on this: Has there been any update on adopting this proposal and implementing it? And also, when implemented will this enable incremental compilation (or at least the pieces needed to get something like that working)?

**Comment by ntkme** [comment]
> Has there been any update on adopting this proposal and implementing it?

Both the formal proposal and the implementation are out for review:

- https://github.com/sass/sass/pull/3744
- https://github.com/sass/sass-spec/pull/1954
- https://github.com/sass/embedded-host-node/pull/261
- https://github.com/sass/dart-sass/pull/2134

> And also, when implemented will this enable incremental compilation (or at least the pieces needed to get something like that working)?

If you mean directory watch / auto-reload kind of incremental compilation, this is not even a blocker. Incremental compilation can be implemented without this change, only performance will be slower without this change.

If you mean a compiler cache for parsed sass  partial, that is a different feature than this issue is tracking.

**Comment by nex3** [comment]
There's been plenty of time for public comment here, and we now have a functional implementation, so I'm going to mark the proposal as accepted.

**Comment by jgerigmeyer** [comment]
> I'm going to mark the proposal as accepted

@nex3 I'm not sure what all that entails, but note that https://github.com/sass/sass/pull/3744 does move the proposal to the `accepted/` folder.

**Comment by NathanBeddoeWebDev** [comment]
Brilliant effort to everyone involved, I've been looking forward to this coming into fruition.
