### ISSUE TITLE
3.1.0.alpha.50: Sass::Plugin.options[:always_check] = false doesn't work in Rails 2.3.10

### ISSUE THREAD

**Issue by agibralter** [sass/sass#33]
`Sass::Plugin.options[:always_check] = false` doesn't work but `Sass::Plugin.options[:never_update] = true` seems to do the trick... all my production servers were running almost 10x slower since I launched them with Sass 3.1.0.alpha.50. Added `:never_update` and things went back to normal.

**Comment by nex3** [comment]
#35 confirms this on Rails 3 as well. It's also worth noting that this dramatically affects test times.

**Comment by nex3** [comment]
I'm having trouble reproducing this in either production or test. You're not spinning up a new server or otherwise causing global state to get reset for each request, are you? Can you provide me a sample rails app in which running a production server or tests locally demonstrates the issue?

To make it clear whether or not it's happening, include this snippet somewhere in your app:

```
module Sass::Plugin
  def update_stylesheets_with_instrumentation(*args)
    puts "Updating stylesheets"
    update_stylesheets_without_instrumentation(*args)
  end
  alias_method_chain :update_stylesheets, :instrumentation
end
```

This will print "Updating stylesheets" whenever Sass is going to touch the filesystem.

**Comment by agibralter** [comment]
Ok -- so I have
    Sass::Plugin.options[:always_check] = false
    Sass::Plugin.options[:never_update] = true
in `config/environments/development.rb` and I put
    RAILS_GEM_VERSION = '2.3.10' unless defined? RAILS_GEM_VERSION
    require File.join(File.dirname(**FILE**), 'boot')
    Rails::Initializer.run do |config|
      # ...
      config.after_initialize do
        # ...
        module Sass::Plugin
          def update_stylesheets_with_instrumentation(_args)
            ::Rails.logger.info "\n\n\n---Updating stylesheets---\n\n\n"
            update_stylesheets_without_instrumentation(_args)
          end
          alias_method_chain :update_stylesheets, :instrumentation
        end
      end
    end
in `config/environment.rb`. I restarted and ran `tail -f log/development.log` only to find `---Updating stylesheets---` appearing in my log...

**Comment by nex3** [comment]
Did you see it more than once? Sass always checks your stylesheets once when the app starts up, but if :always_check is false it shouldn't appear again.

If you do see it more than once, could you produce a minimal Rails app that demonstrates the issue and send it to me?

**Comment by agibralter** [comment]
Yeah so I see it on every request.

I'll try to set up an example app to recreate the problem. Just FYI, I'm using Bundler 1.0.7, Rails 2.3.10, and Passenger 3.0.2.

**Comment by agibralter** [comment]
Ok so I made a fresh app and I'm still getting the output from the copy/pasted code: https://github.com/agibralter/rails-sass-test

```
def update_stylesheets(individual_files = [])
  ::Rails.logger.info options[:never_update]
  return if options[:never_update]
  compiler.update_stylesheets(individual_files)
end
```

is showing me that options[:never_update] is indeed true and therefore the function is returning and the filesystem is not getting touched by the compiler.

However,

```
def check_for_updates
  return unless !Sass::Plugin.checked_for_updates ||
      Sass::Plugin.options[:always_update] || Sass::Plugin.options[:always_check]
  ::Rails.logger.info "Foo!"
  update_stylesheets
end
```

is printing `"Foo!"` even though `Sass::Plugin.options[:always_check] = false`.

Perhaps `checked_for_updates` never gets set to true?

**Comment by mocoso** [comment]
I have the same issue.

After a little debugging it looks like the problem is that there are two separate  @checked_for_updates instances variables.

The Sass::Plugin#checked_for_updates method returns the instance variable @checked_for_updates on the Sass::Plugin module. This never changes and is always false.

When the Sass::Plugin::Compiler#update_stylesheets method runs it sets it's own instance variable @checked_for_updates to true and but this is not the variable that is checked when deciding whether to update the stylesheets (see above).

It looks like the source of the problem is commit 82671fc when the compiler code was refactored out of the plugin module.

We have side stepped the issue for the moment by setting the SASS to never update in production but I could provide a patch if you wish.

**Comment by mocoso** [comment]
See for a patch to fix this https://github.com/econsultancy/sass/commit/600b07e901e1808ddc623eb1a5c76ea7eda622cf

**Comment by agibralter** [comment]
Is this still an issue in Rails 3.1?
