### ISSUE TITLE
formatting of a mixin with a lot of variables

### ISSUE THREAD

**Issue by chrisdrackett** [sass/sass#330]
I have a mixin that takes a lot of variables. Is it currently possible to define these on multiple lines in a .sass file?

example:

```
=some_mixin($variable, $variable2, $variable3, $variable4, $variable5, $variable6)
```

as:

```
=some_mixin(
    $variable,
    $variable2,
    $variable3,
    $variable4,
    $variable5,
    $variable6
)
```

**Comment by nex3** [comment]
No, this is not currently possible.

**Comment by chrisdrackett** [comment]
can I make this a feature request then? it works in other white space aware languages like python, and would make my sass code much easer to read.

**Comment by nex3** [comment]
I'll consider it. It seems reasonable, but is pretty low-priority relative to other things that need attention.

**Comment by Anahkiasen** [comment]
I support this, both for the declaration and the inclusion of mixins. Some like gradients, box-shadows or text-shadows can get extremely crowded very fast, and the _limitation_ of having to keep everything inline is an enormous readability issue. 
Take the following box-shadow statement : 

``` sass
+box-shadow(inset 0 -20px 10px fade($color, 50), inset 0 -5px 0 darken($color, 20), inset 0 0 20px fade(black, 25), 0 0 0 5px $color, 0 0 10px 6px fade(black, 20))`` 
```

It would be 100 times easier to read like that : 

``` sass
+box-shadow( 
    inset 0 -20px 10px fade($color, 50), 
    inset 0 -5px 0 darken($color, 20), 
    inset 0 0 20px fade(black, 25), 
    0 0 0 5px $color, 
    0 0 10px 6px fade(black, 20)) 
```

Please consider it, I'm part of the crowd that will just never leave the simplicity and cleanliness of the indented syntax, but some adjustments do need to be made in order to keep it competitive with the SCSS syntax - and to me that's what "keeping support" means, there shouldn't be one syntax completely late on the other, the both should have their pros and cons.

**Comment by chriseppstein** [comment]
This is the primary reason I've taken to using scss over sass.

**Comment by nex3** [comment]
Duplicate of #216.

**Comment by firedev** [comment]
What's the syntax now?
