### ISSUE TITLE
@mixin brings too much duplicate code

### ISSUE THREAD

**Issue by sanriqing** [sass/sass#3326]
```
@mixin half-px-top-border($color) {
    width: 200%;
    height: 1px;
    background-color: $color;
    position: absolute;
    left: 0;
    top: 0;
    transform-origin: left top;
    transform: scale(0.5);
}
```
We use `@mixins` like this to help us code quickly，But the duplication of code in production increases as we use it. in this case the duplication of code should be  
```
width: 200%;
    height: 1px;
    position: absolute;
    left: 0;
    top: 0;
    transform-origin: left top;
    transform: scale(0.5);
``` 
 
 So we're going to try to extract the invariant part and call it `@extend`. But this brings up another problem, the different `@import` or `@use` file can bring up extra duplicate code... It's really sad.
 
 
 Is there any good way to solve this problem? Maybe we could have a global module? To ensure easy reference of utility functions?
 
 Looking forward to your reply. : )

**Comment by nex3** [comment]
If you're very concerned about code size, a tool like [cssnano](https://cssnano.co) may be able to help you by re-ordering and compressing your CSS after the fact.

Sass is primarily a tool for expressing styles rather than compressing them, but if you really want to avoid duplicating declarations your plan of using `@extend` could work. The `@use` rule ensures that each module you use is only loaded once, so that should prevent any placeholder selectors you declare from being duplicated.
