### ISSUE TITLE
Sass should be packageable as a jar file for JRuby

### ISSUE THREAD

**Issue by tomwhoiscontrary** [sass/sass#333]
This is a bit of an odd request. I don't know if this is a bug report or a feature request.

I'd really like to be able to programmatically use Sass in JRuby, and i'd like to do that with Sass packaged in a jar file. The simplest way to do that is to just package the contents of the lib directory from the gem; JRuby will readily require sass.rb from such a jar.

At the moment, however, there are a few things Sass does which mean it doesn't work when packaged in this way, all to do with accessing files which do not exist when the code is packed into a jar.

In css.rb:

``` ruby
require File.dirname(__FILE__) + '/../sass'
```

In version.rb:

``` ruby
require File.dirname(__FILE__) + '/../sass'
```

And:

``` ruby
      numbers = File.read(scope('VERSION')).strip.split('.').
        map {|n| n =~ /^[0-9]+$/ ? n.to_i : n}
      name = File.read(scope('VERSION_NAME')).strip
```

version.rb contains some other uses of files, in revision_number, but i think they're benign, in that if the files aren't found, there's no error. compiler.rb also contains use of files for loading fssm, but again, this is benign, because if fssm is already on the load path, it's not used, and if it's not, the watch feature is the only thing that's unusable.

Is there any way that the code could be structured so as not to need to explicitly access files?

For the requires, what is it in the top-level sass.rb that is actually needed? Could the relevant bits be moved into a file inside the sass directory, so a simple relative require would work?

For the version numbering, could the version be supplied by some other means? How about by generating a small Ruby file which just defines constants, and is included in the sass directory?

**Comment by chriseppstein** [comment]
@nex3 I think a simple version.rb file would suffice, but I think there are build scripts that are not checked in that depend on the current scheme.

**Comment by rsim** [comment]
Got the same issue when trying to bundle sass in a jar file for JRuby. The following line fails

```
require File.dirname(__FILE__) + '/../sass'
```

because it resolved to `classpath:/...path.to,gem.location.../sass-3.2.1/lib/sass/../sass` and JRuby cannot load files from classpath if they contain relative `..` path components.

In general I think such require is not a good practice because when I just normally do

```
gem 'sass'
require 'sass'
```

then sass.rb is loaded twice as first time it is loaded with relative 'sass' path and second time with full path (including ..) from sass/version.rb.

Would be much better to avoid such hack which is causing troubles when trying to require gems not from normal file system.

**Comment by robertodecurnex** [comment]
+1 i'm with rsim.

We have just remove the require from the version.rb in order to make it work on production.

I know is still needed for development :cry:  

I'll try to take a closer look at that if I manage to get some time tonight.

**Comment by chriseppstein** [comment]
FYI: I use Sass from a jruby jar. it works fine for me.
