### ISSUE TITLE
Css variable within mix function

### ISSUE THREAD

**Issue by levipadre** [sass/sass#3367]
Is it possible to use css variable within mix function? It doesn't seem to work, but it would be great.
https://jsfiddle.net/up5t7a3x/1/

```
:root {
    --root-color1: #ff0000;
}

$color2: #ffff00;

.test {
    background-color: mix(var(--root-color1), $color2, $weight: 50%);
}
```
Thank you.

**Comment by Goodwine** [comment]
Sass doesn't consider CSS variables because Sass compiles into an immutable CSS file, but CSS variables could be changed at runtime.

You can learn more about it here:
- https://css-tricks.com/difference-between-types-of-css-variables/
- [Difference between SCSS variables and CSS variables?](https://stackoverflow.com/a/67016495)
