### ISSUE TITLE
Example of project structure after migrating from @import to @use

### ISSUE THREAD

**Issue by Zylvian** [sass/sass#3397]
After using the sass migrator to start implementing @use as opposed to @import, I'm unsure of the project structure of my  projects. 

Is there a point to having a global import file - as a lot of projects have - if all individual .scss files import variables individually?
Furthermore, when having nested files, I have to keep track of the directory structure to correctly import files (such as `@use "../../abstracts/variables";`).

I would love some official documentation of how the Sass team imagines a proper Sass project file structure using @use, and other pointers regarding the migration.

**Comment by jathak** [comment]
Since members from a `@use`-d file are only accessible in the file that uses them, the pattern of having a global import that is used everywhere isn't really possible in the module system. You could have a module that is `@use`-d in most (or all) other files, but you will need to have a `@use` rule to make it explicit each time (this is by design, as we want it to always be clear where members are coming from).

Different projects will use different structures, so it's difficult to give hard and fast rules about how projects in general should be structured (beyond want's implicitly encouraged by the design of the module system itself). You may find it useful to look at other projects that have already migrated, such as [Material Components](https://github.com/material-components/material-components-web) (which we were directly involved in migrating) or [Angular Components](https://github.com/angular/components).
