### ISSUE TITLE
Color Spaces: Units in color channels

### ISSUE THREAD

**Issue by nex3** [sass/sass#3404]
The current definition of colors says that channel values are floating-point—that is, they're stored without reference to a unit. However, there's no explicit conversion from Sass numbers (which may have units) to floating-point numbers (which may not) either in [Parsing Color Components](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md#parsing-color-components) or [`color()`](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md#color-2).

This raises a few questions:

* [CSS Colors 5](https://www.w3.org/TR/css-color-5/#color-function) only allows raw numbers or percentages for custom colors. Should we do the same for unknown color spaces? Or is the risk of forwards-incompatibility with potential new predefined polar color spaces too great?

* If we do allow unknown color spaces to specify channels with circular units, do we have to store that fact? Can we just serialize those colors with a unitless value for that channel? Is there a risk of a new predefiend color space with a polar channel that defaults to turns instead of degrees?

* If we allow unknown color spaces to specify channels with circular units, do we allow _any_ units, or just unitless/percent/circular?

* The existing channel-access functions `color.hue()`, `color.saturation()`, `color.lightness()`, `color.whiteness()`, and `color.blackness()` return values with units. However, `color.channel()` is specified never to do so—so `color.channel($color, 'hue')` isn't a drop-in replacement for `color.hue($color)`. Is this a problem?

**Comment by mirisuzanne** [comment]
> [CSS Colors 5](https://www.w3.org/TR/css-color-5/#color-function) only allows raw numbers or percentages for custom colors. Should we do the same for unknown color spaces? Or is the risk of forwards-incompatibility with potential new predefined polar color spaces too great?

We can distinguish between valid custom spaces (with a dashed-ident) and potential future unknown spaces here:

- For true custom spaces (dashed-ident), we can follow colors-5: angles are not allowed, and we throw an error
- For unknown predefined spaces (not a dashed-ident), we're treating them like special strings, and output directly to CSS

I think that gives us a decent balance of mostly future-proof, while also following the current specs? This limits the potential future issue to custom spaces, not new predefined spaces. (alternately, we could extend the 'unrecognized syntax is output as CSS' to both unknown and custom spaces, rather than throwing an error)

> If we do allow unknown color spaces to specify channels with circular units, do we have to store that fact? Can we just serialize those colors with a unitless value for that channel? Is there a risk of a new predefiend color space with a polar channel that defaults to turns instead of degrees?

No, I don't think we'll get polar-angle channels with a different default. Since all angle units are allowed already, and serialized in CSS as degrees without units, there's very little reason for CSS to change how hue angles are defined. I expect all future polar channels to continue being serialized in deg-without-units.

> If we allow unknown color spaces to specify channels with circular units, do we allow _any_ units, or just unitless/percent/circular?

n/a, if we follow the approach proposed above. 

> The existing channel-access functions `color.hue()`, `color.saturation()`, `color.lightness()`, `color.whiteness()`, and `color.blackness()` return values with units. However, `color.channel()` is specified never to do so—so `color.channel($color, 'hue')` isn't a drop-in replacement for `color.hue($color)`. Is this a problem?

I'm not sure? I think there's something _nice_ about having units on the return - it ensures you know what the number is intended to represent. I imagine we would add those units in the `color.channel` definition, and not store them in the color object?

**Comment by nex3** [comment]
When you say "output directly to CSS", do you mean that the expression `color(unknown 1 2 3)` wouldn't return a Color value at all but instead the unquoted string `"color(unknown 1 2 3)"`? At first glance, it seems undesirable to return a color that can't be inspected or edited at all when, at least in principle, we have the ability to make it so.

If we do go that direction, I think we should go all the way and make custom colors return strings as well, because that at least allows us to provide the invariant that anything for which `type-of($value)` returns `'color'` can be converted to any other color space, simplifying a bunch of internal logic and external reasoning substantially—we could even get rid of addressing channels by index in `color.channel()` and `color.change()`.

**But** going in that direction would make it much more painful to add support for unconvertible colors later on if we decided to do so. The case we're likely to face soonest is `device-cmyk()`—a color space that's not intrinsically convertible *but* that's officially-supported enough that we'll probably want to have an easy way to access its channels. At the very least we'll want to be able to provide a way to convert it to sRGB using the naive conversion algorithm.

Given all that, my preferences are:

* (Strong) Either support _no_ unconvertible color values or support _both_ custom spaces and unknown predefined spaces as color values.
* (Medium) Do the latter so that we can accurately represent `device-cmyk()` and allow users to read/manipulate the fields of unknown/custom colors.
* (Weak) Store all channels as raw doubles, and have `color.channel()` add the unit `%` or `deg` for known color spaces where appropriate.
* (Weak) Allow circular units for unknown predefined color spaces, then convert to `deg` before storing as a raw double.

WDYT?

**Comment by mirisuzanne** [comment]
After some discussion, we decided to remove support for unknown/custom spaces entirely for now - since they are not yet supported in browsers. Once CSS Color Level 5 is more stable, we can revisit.

**Comment by nex3** [comment]
Given the result of this discussion, I think we should (for now) drop support for accessing/setting channels by index in `color.channel()`, `.change()`, `.adjust()`, and `.scale()`. I don't think there's really a strong use-case for it now that there aren't colors with nameless channels.

**Comment by mirisuzanne** [comment]
I think we've decided:

- Unknown/custom spaces are invalid, and throw an error.
- We no longer need a process for 'normalizing a color space name'
- We no longer need a channel indexing, or syntax to access/manipulate channels by their position
- Channel values can be stored without units, since each channel in a known space has a defined meaning for unitless values, or else a defined unit for serialization. Either way, we can safely remove/attach units as needed.

What's the best way to capture that final part? I'm not familiar with the term 'raw double'. Is it fair to keep channel values as floating-point numbers, and then make sure we have guidance for adding/removing units as appropriate?

The channel normalization/validation processes (which could technically be combined) already now convert all values into unitless values where possible, or use `%` or `deg` in a few cases. Appending them where appropriate is simple enough. I think we would ideally want to remove them as part of 'creating a color' - maybe we can note that in the definition of the color object, that units are removed on creation? Or do we need to build that into various processes?

**Comment by nex3** [comment]
> What's the best way to capture that final part? I'm not familiar with the term 'raw double'. Is it fair to keep channel values as floating-point numbers, and then make sure we have guidance for adding/removing units as appropriate?

Yes, that's what I mean. The term "double" (in a Sass context) is defined [in the Number spec](https://github.com/sass/sass/blob/main/spec/types/number.md#double) and basically just means "a 64-bit floating point number". We should try to use "double" in the spec rather than "floating-point number" because it's more explicit about the size and gamut of the number in question.

> The channel normalization/validation processes (which could technically be combined) already now convert all values into unitless values where possible, or use `%` or `deg` in a few cases. Appending them where appropriate is simple enough. I think we would ideally want to remove them as part of 'creating a color' - maybe we can note that in the definition of the color object, that units are removed on creation? Or do we need to build that into various processes?

I think generally it's a good idea to try to avoid having logic in definitions, so if it's feasible to keep that in processes that would be ideal. It shouldn't require too much verbosity—just saying "`hue`'s value" is enough to make it clear that you mean the double it contains.

**Comment by mirisuzanne** [comment]
- add units in: `channels()` and serialization
- remove units in normalization

**Comment by mirisuzanne** [comment]
Resolved in draft 1.2
