### ISSUE TITLE
Vulnerability CVE-2018-7467 with SASS in Next.js

### ISSUE THREAD

**Issue by Oceanestars** [sass/sass#3423]
Hi!

When I ran grype on my application I got the  [CVE-2018-7467](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2018-7467) vulnerability. The only way I was able to found to get rid of that vulnerability was to uninstall SASS. I love SASS and I'd love to be able to use it without getting that vulnerability.

I tried version 1.53 and 1.55
Thanks!

(I do apologize if I'm missing anything to this issue)

**Comment by nex3** [comment]
It's unclear to me what, if anything, CVE-2018-7467 has to do with Sass. The reference link in the CVE database is broken, but it looks like the issue is with AxxonSoft Axxon Next, not with Sass. It also looks like it's a "Directory Traversal" vulnerability, which is not a class of vulnerability Sass is vulnerable to because Sass doesn't intend to restrict any path resolution to a specific directory in the first place. I think this is a bug in grype.
