### ISSUE TITLE
Feature request: Include full path in error message instead of just relative path

### ISSUE THREAD

**Issue by pickhardt** [sass/sass#3427]
Feature request:

I can't find where in the code this happens, but when I get the error "File to import not found or unreadable" it'd be really useful to output the full path it's looking for. The relative path, while helpful, doesn't tell the full story. It'd help with debugging where it's looking and how I should be writing the path in the file.

**Comment by nex3** [comment]
This would actually be quite difficult to do in practice. Loads in Sass don't just map unambiguously to a single file—they go through every importer you have installed and ask it if it recognizes the load, and if it says "no" they move on to the next one. That means there are multiple, potentially *very many*, files that could potentially exist to satisfy a given load. We could list all of these in theory, but in order to do so we'd need to expand the importer API to have a way to ask them "what URLs could exist that would match this load?" Modifying that API is quite difficult, and probably not worth the pain. What's more, the output would be very messy, since even for a simple filesystem load there are _at minimum_ eight different files that could exist for any given relative URL.
