### ISSUE TITLE
[Color Spaces] One-argument functions should return multi-argument plain CSS strings

### ISSUE THREAD

**Issue by nex3** [sass/sass#3454]
In the [current color spaces proposal PR](https://github.com/sass/sass/pull/3426), the definition of `hsl($channels)` says:

> If parsed is null, return a plain CSS function string with the name "hsl" and the argument `$channels`.

This turns out to be a breaking change from the current behavior. Currently, `hsl(var(--foo) 2% 3% / 0.4)` does a partial polyfill of its input for browsers that don't yet support the space-separated syntax and returns `hsl(var(--foo), 2%, 3%, 0.4)`. We should maintain compatibility with this behavior. (I believe the same thing is true for `rgb()` and `hwb()`.)

**Comment by mirisuzanne** [comment]
It looks like we only do this when we can ensure that all the individual components are there, which is good. eg `hsl(var(--foo) 3% / 0.4)` is not converted in this way, since we can't add the comma inside `--foo`. And it seems like we also don't do the conversion when the special value is adjacent to the slash. I maintained that behavior.

In order to avoid re-parsing the entire `$channels` argument, I put this functionality in the component-parsing process. It now returns a string rather than `null` when the result should be output as CSS. Generally that's a string representation of the `input` value, but when we have all the channels of a legacy space without any `/`-adjacent special value, we re-build a comma-separated list, and return a string representation of that. See 6417935
