### ISSUE TITLE
[Color Spaces] Explicitly specify deprecated color functions

### ISSUE THREAD

**Issue by nex3** [sass/sass#3455]
The [current color spaces proposal PR](https://github.com/sass/sass/pull/3426) doesn't explicitly specify how to handle most of the deprecated color functions. It's reasonable to assume they work more or less the same way they always did, but as I get into the weeds of the implementation I'm realizing that because the internal representation of colors has changed so much these functions should probably also get explicitly defined.

Some particular questions I've run into:

* Should functions like `adjust-hue()` return a color in the original space or in HSL? (Probably original to match our general design principle that only `color.to-space()` changes the color space.)

* Should `hue()` return the hue `% 360deg`? We currently _store_ the hue as written, but taking the mod here would preserve some edge-case backwards compatibility.

* Should channel-access functions like `red()`, `hue()`, and so on even allow legacy colors? My current implementation forbids them.

**Comment by mirisuzanne** [comment]
> Should channel-access functions like red(), hue(), and so on even allow legacy colors? My current implementation forbids them.

Do you mean the opposite of this? I would expect that they _only_ allow legacy colors?

**Comment by mirisuzanne** [comment]
I take it you're looking for full definitions of all these functions? Or at least updates to their current definition? That might not be a small undertaking, but I can start on it.
  
> * Should functions like `adjust-hue()` return a color in the original space or in HSL? (Probably original to match our general design principle that only `color.to-space()` changes the color space.)

I don't know - for deprecated legacy functions, wouldn't it be more important to maintain legacy behavior?

> * Should `hue()` return the hue `% 360deg`? We currently _store_ the hue as written, but taking the mod here would preserve some edge-case backwards compatibility.

This makes sense because it does maintain legacy behavior, rather than following the new approach. Seems strange that we would update one to the new behavior, but keep the other one legacy?

> * Should channel-access functions like `red()`, `hue()`, and so on even allow legacy colors? My current implementation forbids them.

I guess I'm confused about how the deprecation process works. Why would these now error on legacy colors (and non-legacy colors, I assume?) while the other functions mentioned here continue to support their legacy behavior, or get updated to match the new behavior? I'm not seeing the different logic behind handing these all in different ways.

**Comment by mirisuzanne** [comment]
- define in terms of aliases to new functions
- ensure that rgb values are rounded
