### ISSUE TITLE
Color Spaces: Should we deprecate alpha?

### ISSUE THREAD

**Issue by nex3** [sass/sass#3465]
The [Color Spaces proposal](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md) currently deprecates all channel accesor functions _except_ `alpha()`/`color.alpha()`. Was this an oversight or did we have some justification for it?

**Comment by mirisuzanne** [comment]
Good question. I don't remember if we discussed that. It does seem like there's a valid distinction we could make there - since every color is guaranteed to have an alpha value, no matter what space it is in. Getting direct access to alpha could be a useful shortcut for authors – but that's all it would be. And the more useful shortcut would allow adjusting/setting alpha. So I don't think I'd make a strong case for keeping it around.

**Comment by nex3** [comment]
I think we should just deprecate it. No sense leaving it around and not the rest of them.
