### ISSUE TITLE
Would be nice if you had a non-sexist logo/tagline/naming convention

### ISSUE THREAD

**Issue by adrienne** [sass/sass#349]
**Please note: This is not a technical issue, but it is an issue that affects some percentage of your user base.**
## Expected Behavior:

SASS' website should be inviting and not offputting to all members of the potential user community.
## Steps to Reproduce Issue:
1. Visit the web page at http://sass-lang.com
2. Examine logo and release name
## Observed Results:

Website creates an unpleasant impression for (some) women because of the logo and general atmosphere. 
### Detail:

I mean, really -- the vintage-style blonde with the phone, as your logo? "Brainy Betty" is the current release? I love SASS, seriously. But i hate going to your website, because it reminds me every damn time that women in tech are curiosities at best and objects of derision at worst.

This stuff matters. Not by itself, in isolation -- but it's not IN isolation; it's part of a giant set of sexualized and gender-stereotyping depictions of women all over the tech world. And in the aggregate, it really does make some women -- potentially a lot of women -- feel invisible, othered, diminished.  And why would you WANT that, if you can avoid contributing to the problem?
## Suggestions for Fixing:

Here's a couple of useful resources for educating oneself:
- http://geekfeminism.wikia.com/wiki/Sexualized_environment  (What's a sexualized environment? Why should people care?)
- http://www.microaggressions.com/  (This blog is a collection of stories. Microaggressions are examples of exactly the sort of thing that your logo is -- just a tiny reminder that my gender matters to people, and not in a positive way.) 
#### Note: when looking for a fix, avoid the following; they have been tried before and are known to be faulty strategies for dealing with similar issues.
- http://geekfeminism.wikia.com/wiki/Category:Excuses_for_sexist_incidents

**Comment by nex3** [comment]
The Sass website is currently undergoing the beginnings of a major redesign. Sexist implications of the current logo and branding are definitely a consideration in that redesign; we certainly don't want to contribute to the sexism in the tech community.

It may be worth noting that the release names alternate between male and female names with an alliterative adjective that's meant to describe some aspect of the current major release. It's not particularly meant to be part of the rest of the branding, and I hope it wouldn't register as sexist without the context of the rest of the website.

**Comment by adrienne** [comment]
Nathan -- Thanks so much for the reply! (And for not yelling at me -- I will admit that I was frankly a little shaky about submitting this bug. I'd been thinking about it for awhile, and finally got up the gumption to do it.) 

Makes sense, on the release names -- I didn't remember the name of the previous release, I'm afraid, so that's my fault. It was definitely the _conjunction_ of "airheaded girl on a phone" branding with the release name that was the issue.

Thanks for listening, and taking this seriously. I definitely don't want to come across as "OMG you people are horrible!" because you're not. But it is a drop in a very large bucket, and it does get wearing. I'm glad you're willing to take it into account.

**Comment by nex3** [comment]
I'm glad you spoke up about this. I've seen this sort of discussion go sour way more times than I'd like, so I appreciate the risk you took in posting the issue.

It looks like @jina, the designer in charge of the redesign, is on board with re-doing the logo, so I'm going to close this issue.

**Comment by jeanlauliac** [comment]
Didn't know how it was 1 year ago, but looks like nothing really changed with the logo.

**Comment by HamptonMakes** [comment]
The site redesign is still ongoing. The work has been speareheaded by the awesome @jina and can be seen at https://github.com/sass/sass.github.com --- any help on that effort is very much appreciated!

And, as the selector of the original branding package, I always find this line of commentary surprising. I'll start with the statement though that intention is NOT the most important thing, but impression is. So, if its seen as sexist and negative against women, then by definition it is.

To me, the Sass woman is not at all a "blonde airhead". This branding was meant to go along with the original Haml branding, which was a similar-style drawing of a young boy. Both of them, to me, seem to say "I'm very clever and I have a mischievous secret"... which is how I originally thought of both Sass and Haml. As tools that a minority would use, but would have great power because of it. 

Also, I wanted to do strongly "female" branding as a way to address my being gay head on with a public branding of my work as effeminate. At the time for me, it was a strong statement for me. Less so as I've gotten older and am able to be more publicly out.

The way I was thinking about it was...: "Why do technologies have to be so "male" all the time? Why be afraid of some pink? I need a counterpoint to the male-centric branding of Haml."

Again, the fact that several people over the years have felt that the branding was insulting... that is a great regret to me, as it was never where my heart was. And so, we are trying to replace this branding at the moment.

But! The new branding package exists... it holds onto the feminine branding, but (hopefully) removing the iconography that can read as "airhead". We're hoping to launch the site before SassConf in October.

**Comment by kelly** [comment]
Am I the only one that prefers the old logo mark to the new one? The new logo seems to be void of the original humor and character. It's a trendy script type, but it seems to push the feminine branding a little too much. It more closely resembles a line of lipstick than a development product. I'm all for pushing the edge, but I'm not sure this particular branding fits well with the objectives of sass.

**Comment by robwierzbowski** [comment]
> I'll start with the statement though that intention is NOT the most important thing, but impression is. So, if its seen as sexist and negative against women, then by definition it is.

:clap: :clap: :clap: :clap: :thumbsup:. That's the type of tech community I want to belong to. 

I always thought of the Sass logo as a powerful business minded woman, with a little irreverence on the side. Really enjoyed reading about the ideas behind its creation.

**Comment by cimmanon** [comment]
> So, if its seen as sexist and negative against women, then by definition it is.

If I see the UPS logo as sexist and negative against women, that means it is?  You have to make a reasonable attempt at proving your claim in order for it to be true.  All the OP has is "the logo is a picture of a woman on a phone" and the version's nickname has a woman's name in it (and the adjective that goes with it is a positive one that implies the woman is intelligent).

The OP is trying to read something into the logo that simply isn't there.  Are pictures of women talking on phones sexist?  No.  The fact that she is on a "tech" website doesn't change this.  If was implied that "girls aren't smart enough to program, so they should stay in the kitchen where they belong" or "girls are only good at talking on the phone" then the OP would have a point.

All this "I can't stand going to the website because the logo hurts my feelings" is nonsense because the logo isn't even on the pages that are useful for a returning user (Sass reference, functions list).  Or am I the only person in the world who's figured out how to bookmark the pages they actually use?

All I can hear when I read the OP is "I want attention so I am going to pretend to be insulted".  I say this as a woman who's used to being the only girl in what's commonly thought of as a "man's world" (chess club, video games, programming).  If you act like a unicorn, people treat you like one (this is true for all minorities, not just women).  I'm not implying that you should roll over and accept being treated inappropriately, just that when you stand up for yourself, it looks bad when you're just being irrational.

You aren't going to please everyone, don't let a few overly sensitive whiners rain on your parade.  For what it's worth, when I see the logo, I see a woman who's telling all of her friends about this cool thing called Sass.

**Comment by throwawayaccount11** [comment]
It seems to me that if you depict a female in your logo at all, or even just something "feminine" like a script font in pink, someone is going to cry "sexism" and demand an explanation, an apology, and a change, as though any image at all of a woman is inherently "sexualized".

What exactly is sexualizing or stereotyping about a woman holding a phone to her ear? Is talking on phones an activity exclusive to women? "Blonde airhead"? How does one even assume her hair isn't red, given that the image is monochrome vector art? Far from an objective observation, this is a personal bias being projected on the logo and then labeled as a "microaggression".

Is there any way a woman could be used in the image without being offensive to you? How about a man? How about any person at all? Maybe we should just refrain from depicting persons in logos for the time being, until all humanity grows up enough to view images of other people without making them feel invisible, othered, and diminished.

Sexism is still a problem in society, and certainly in the tech world. But this? I'm sorry, but I just don't see it.

**Comment by chriseppstein** [comment]
Have you ever stubbed your toe really bad and all of a sudden it's like you keep bumping into things all the time and it hurts so bad, even though you know you must bump into these things all the time and it never hurt before. Sexism in tech is like this. It's pervasive and it has created a sore spot which has created sensitivities to things that might not be there in a different context. Knowing that context, We're okay with taking extra care to protect that sore spot from becoming further inflamed. It's not a big deal for us, and it really helps them. I have this phrase I like to say "Do you want to be right, or do you want to be effective." Sometimes you need to take a stand on principle. This is not one of those times.

**Comment by kbrec85** [comment]
It seems like you have this covered and while this might not be the best place to ask this question it seemed pertinent to the conversation to me.

Does the OP feel that issues like this mean that any injection of stereo-typically effeminate design elements (pink) or a woman that could be construed as attractive doing something stereo-typical (talking on the phone) on a tech website means that it is sexist? Wouldn't we want to support a tech site that is shunning the typical masculine trend, or would we rather the SASS site just go to a regular old programmers site?

**Comment by chriseppstein** [comment]
@willwallace85 We have no intention of making the sass website into "a regular old programmers site" and such a thing was never requested. This feels like a strawman to me.

**Comment by jacaetevha** [comment]
I feel inclined to agree with @cimmanon's and @throwawayaccount11's comments. I don't think your comparison to the stubbed toe is really applicable.

**Comment by robwierzbowski** [comment]
The site is maintaining its unique and feminine branding, while removing the possible-to-see-as-ditzy character from the logo. This issue wasn't the primary reason for redesigning the logo, but redesigning the logo gave the Sass design team opportunity to address these concerns while they were at it. @nex3, @hcatlin, @jina, and the Sass design team have already taken care of this. It's a win-win — everybody has already won.

The Sass community needs to be inclusive, and if there are easy steps to make it more inclusive without any negative side effects those steps should be taken. When someone points to code that works but with trivial effort can be re-written to be more elegant, we re-write it. That doesn't mean the original code was inherently wrong or bad, and all those who used and enjoyed it are shamed by proxy. It just means together we've found a better way to write it.

@chriseppstein, I appreciate your metaphor.

**Comment by nex3** [comment]
I think everything that needs to be said about this has already been said. I encourage anyone who's legitimately interested in understanding more about sexism in tech to go read any of the many excellent blog posts and articles written by women in the industry on the subject. This issue, however, is not the place to discuss it.

Lacking the ability to close comments on this issue, I'll just delete any further comments not by @chriseppstein, @hcatlin, or myself.

**Comment by bpainter** [comment]
Just a last quick note incase anybody stumbles onto this issue in the future. It is officially closed. @adrienne had some good points and we took them into account while working on the new branding and website redesign. 

The logo [redesign is complete](http://dribbble.com/shots/760641-Getting-Sassy-Final-Logo).

We're working to complete the full site redesign to launch at http://sassconf.com/. All issues pertaining to the redesign should probably happen over at https://github.com/sass/sass.github.com.

**Comment by adrienne** [comment]
Love the new logo, and i want to say thank you very much to @chriseppstein, @hcatlin, and @nex3 for listening. (And @hcatlin, thanks even more for the story about why you were going for a "feminine" vibe in the first place! As a woman in tech i really do appreciate the intent; the execution was just frustrating. "Woman on telephone in '50s/'60s clip art style" totally reads as "secretary" to me. (cf these actual retro images: http://thehose.net/wp-content/uploads/2012/03/secretary.jpg and http://www.illustrationsof.com/royalty-free-phone-clipart-illustration-1049789.jpg) And as noted in my bug report, there are just So Damn Many reminders to women that we "don't belong here" in the industry, so it is easy to feel excluded by little things that weren't intended that way.)

**Comment by nex3** [comment]
The new site had launched! @adrienne, what do you think?

**Comment by adrienne** [comment]
@nex3 I love it! Thanks for letting me know! :) And thanks again for listening.
