### ISSUE TITLE
SASS converts CSS code (breaks linter)?

### ISSUE THREAD

**Issue by toby1kenobi** [sass/sass#3553]
I'm using SASS in a project along with Boostrap. A line in Bootstrap's _type.scss looks like this:

`.blockquote-footer::before {
  content: "\2014\00A0"; // em dash, nbsp
}`

SASS seems to convert this to:

`
.blockquote-footer::before {
  content: "- ";
}`

(although in Sublime that content displays as "-<0xa0>"). 

When I run that through Stylelint (14.2.0) it fails, with "Unexpected irregular whitespace  no-irregular-whitespace".

Is SASS right to convert the characters, is Stylelint wrong to complain?

**Comment by nex3** [comment]
First, it's probably not a good idea in general to run Sass _output_ through Stylelint. It's better to lint your input files, because you have more control over the formatting.

Sass is emitting CSS that's equivalent to the input. Sass will generally convert Unicode escapes to literal characters, with a few exceptions that don't cover this case. Stylelint isn't necessarily _wrong_ in the sense that, as a stylistic decision, it's probably confusing to write irregular whitespace characters in your source files, but it's certainly valid CSS that means the same thing as the input which is the guarantee Sass offers.
