### ISSUE TITLE
Use proto3 optional fields

### ISSUE THREAD

**Issue by stof** [sass/sass#3575]
proto3 has experimental support for `optional` on scalar fields as of 3.12. In the current 3.14 release, this is still guarded by the `--experimental_allow_proto3_optional`. However, all code generators I checked (all the ones listed in [the protobuf readme](https://github.com/protocolbuffers/protobuf#protobuf-runtime-installation) plus the [swift one](https://github.com/apple/swift-protobuf)) have already implemented support for the feature. So there is a chance that the feature gets unguarded.

If the feature becomes available unguarded soon enough compared to the stable release, it might make sense to use that feature for optional fields (for instance `LogEvent.stack_trace`)

**Comment by nex3** [comment]
I'll talk to the protobuf team and see if I can get a sense of how likely this is to become stable, and how quickly that might happen.

**Comment by stof** [comment]
As of protoc 3.15.0, the feature is available without an experimental flag.

**Comment by nex3** [comment]
I think we can do this backwards-compatibly, since optional fields are encoded the same way on the wire as the "default values" that we currently use to signal that fields don't exist. We probably want to explicitly specify that both endpoints should treat "default values" the same way they treat absent values until we make a breaking version release, though.
