### ISSUE TITLE
Preserve author's color format

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#363]
Unless the output format is compressed, we should preserve the format that the author used when creating a color.

Formats being:
- color name
- hex
- rgb/rgba
- hsl/hsla

The format should be sticky to derived values in as much as possible.

**Comment by jleclanche** [comment]
Short of adding more and more command line flags, there is the solution of metavariables; has sass ever considered those?

eg at the top of the file, something like `$sass-color-format: preserve;` (vs `$sass-color-format: compress;`)

or maybe `@sassoption color-format preserve;`

**Comment by chriseppstein** [comment]
I don't think we need new configuration here. This is a good default, no?

**Comment by shaneriley** [comment]
@chriseppstein To reference your comment in the previous issue (#343), you state that the keywords are used to reduce space. If SASS were really trying to conserve the number of bytes it outputs, shouldn't it actually convert #ffffff and #000000 to #fff and #000 since those are each 2 bytes less rather than their keywords?

In any event, this is still something that needs to be a configuration option. If you are supporting IE and want to output background gradients using DXImageTransform.Microsoft.gradient, you must pass it a hex color. See http://msdn.microsoft.com/en-us/library/ms532997(v=vs.85).aspx for more information on it. Your own Compass has a hack for this, which I think is the wrong way to go about things. https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/css3/_images.scss#L87

**Comment by chriseppstein** [comment]
@shaneriley sass does do that. Except it seems that it doesn't do it when it doesn't have to fully parse the property value. This is a bug IMO. @nex3 should weigh in.

Try running:

``` scss
$c1: #ffffff; $c2: #000000;
div { color: $c1; background-color: $c2; }
```

thru: `scss -t compressed`

and you'll get:

``` css
div{color:#fff;background-color:#000}
```

The compass function exists and is now in Sass itself. It exists because IE has a non-standard treatment of alpha channels where hex takes the form of `#AARRGGBB` and also because they do not support `rgb()` or even shorthand hex. Therefore this is the one place in all of CSS where the output format matters and therefore a hack exists to accomodate the hack that is IE filters.

As such, I do not see a reason to add a configuration option for this. when in non compressed modes, preserving css-valid author formats makes sense as the behavior. That said, feel free to make other use cases if you like, maybe one of those will convince me.

**Comment by nex3** [comment]
@shaneriley I agree with Chris, configuration is not the correct solution for IE filters. It would put you into a situation where your stylesheets would only work correctly with a certain configuration, which is not something we want. `ie-hex-str` is a pretty good solution, given the awfulness that is IE.

@chriseppstein We don't fully parse simple static properties for performance reasons. If we did, parse time for stylesheets would increase dramatically. It's possible it's worth the tradeoff in compressed mode, but I'm skeptical. I think it would just register as "my stylesheets suddenly take a lot longer to compile" for many people.

At some point we may want to introduce a `-O` flag to control the optimization/time tradeoff explicitly.

**Comment by chriseppstein** [comment]
@nex3 I'll do a perf test to see how much cost comes from that change to compressed mode for our app. If it's small enough (~1-2%) I think it's worth it.

**Comment by shaneriley** [comment]
You know, I thought SASS might have had that already, so I looked through the functions in the documentation before coming across this issue. I still see no mention of this function, though. Can we get that added to the documentation?

**Comment by nex3** [comment]
@shaneriley Could you create a new issue for that?

**Comment by plindelauf** [comment]
Any news on this issue? I keep having trouble with the IE gradient filter when SASS converts six character color codes to three character color codes! This happens in my Rails production environment (on Heroku) only.

**Comment by chriseppstein** [comment]
@plindelauf the current solution is to use ie-hex-str($color) to emit filter-safe color values.

**Comment by plindelauf** [comment]
Thanks for your reply Chris. However, it does not seem to work out of the box with Rails 3.2.6, sass 3.1.19 and sass-rails 3.2.5. Is there something more I need?

Op 29 jun. 2012, om 17:36 heeft Chris Eppstein het volgende geschreven:

**Comment by chriseppstein** [comment]
The ie-hex-str function is in Sass 3.2. It is also in Compass until 3.2 has a stable release.

**Comment by chriseppstein** [comment]
Note that we can't do this as a default behavior until HSL is supported by ~98% of browsers. Currently hsl breaks in more than 20% of browsers. So this would need to be an opt-in compilation option that would change to an opt out later.

http://caniuse.com/#search=hsl

**Comment by jacobrussell** [comment]
This is a real pain.  While I appreciate what SASS is doing to clean up my CSS in general, if I put a color in as #ffffff I don't want it compiled to white and I certainly don't want #f5f5f5 compiling to whitesmoke.  In my code I want hex codes or RGB as opposed to color names because they're more descriptive, and because using just one type of color declaration creates consistency.  If some of my colors in the compiled file are hex and some are color names because of SASS, that's no good for me.

The people using this are web developers, lets at least assume we can choose our own color declarations, at least by default.

**Comment by chriseppstein** [comment]
The maintainers of this project work for free, let's at least assume that they deserve to be spoken to respectfully and that things work the way they do for a reason.

**Comment by homeworkprod** [comment]
I would also prefer unchanged color codes.¹

What's the deal with another command-line flag? The docutils command-line tools, like `rst2html`, have dozens of them. Still, it doesn't harm usability.

¹) Is it even specified that, say, `#ffffff` may be abbreviated as `#fff`? And `#666666` equals `#666`? (And do browsers adhere to the spec in that regard?)
I always assumed the short would expand to `#f0f0f0`/`#606060` and, thus, completely avoided 3-character hex color codes to keep it unambiguous.

**Comment by nex3** [comment]
> What's the deal with another command-line flag? The docutils command-line tools, like `rst2html`, have dozens of them. Still, it doesn't harm usability.

Every additional option is a usability burden. It makes it harder for users to find the options they really care about.

> Is it even specified that, say, `#ffffff` may be abbreviated as `#fff`? And `#666666` equals `#666`? (And do browsers adhere to the spec in that regard?)

Yes and yes.

**Comment by jacobrussell** [comment]
A new option aside, the default behavior here still is non-intuitive.  The default, ideally, would be that it leaves colors alone so that the developer can input colors in a format that's best for their project.  I can see compressing 6 char to 3 char hex codes, but changing hex to the color name remains an odd choice.

**Comment by gsmith85** [comment]
A big +1 for:

> The default, ideally, would be that it leaves colors alone so that the developer can input colors in a format that's best for their project.

**Comment by joevandyk** [comment]
Also big +1 for not changing colors. If I write `#ffffff`, that's what I want in all versions of the stylesheet, compressed or not. It's surprising when it's changed and has caused problems for me.

**Comment by chriseppstein** [comment]
@joevandyk We will be continuing to change colors to their smallest possible output in compressed mode. If you don't want fully compressed, the compact mode is probably best for your needs.

**Comment by battaglr** [comment]
A huge +1 for preserve author's color format.

**Comment by pascalduez** [comment]
+1 for leaving authors colors untouched, unless we specifically decide to. For all modes except compressed.

**Comment by homeworkprod** [comment]
For the sake of completeness, this is the specification I was missing (emphasis mine):

> The three-digit RGB notation (#rgb) is converted into six-digit form (#rrggbb) by **replicating digits, not by adding zeros**. For example, #fb0 expands to #ffbb00.

Source: http://www.w3.org/TR/css3-color/#rgb-color

**Comment by pyronaur** [comment]
I wouldn't mind Sass changing my color names if it did it consistently.
But #FFFFFF is translated to white where #FFF isn't, which is less than ideal.

**Comment by nex3** [comment]
@justnorris That's not true in my tests:

```
$ echo 'foo {$var: #fff; a: $var}' | ./bin/sass --scss
foo {
  a: white; }
$ echo 'foo {$var: #ffffff; a: $var}' | ./bin/sass --scss
foo {
  a: white; }
$ echo 'foo {$var: #fff; a: $var}' | ./bin/sass --scss --style compressed
foo{a:#fff}
$ echo 'foo {$var: #ffffff; a: $var}' | ./bin/sass --scss --style compressed
foo{a:#fff}
```

In uncompressed mode, both are translated to `white`, and in compressed mode, both are translated to `#fff`.

**Comment by jeremyabrahams** [comment]
Gotta put another +1 for preserve author's color format. At least leave it as the default. And it should stay the same regardless of the compile type.

**Comment by chriseppstein** [comment]
> And it should stay the same regardless of the compile type.

Compressed output exists to create the smallest possible output. The expectation is that it would change color output if there is a smaller representation.

Also, note that with sourcemaps, it is easy to get back to your sass source where the color is defined.

**Comment by joevandyk** [comment]
@chriseppstein The problem is that changing the color names breaks things in some cases. 

I have to maintain a fork of sass (https://github.com/joevandyk/sass/commit/e48a18e247819b70f4524a56629c3ca5397b0733) just for this reason (as I want compressed output, but with the colors as I enter them).

**Comment by nex3** [comment]
You shouldn't write code that depends on a specific output format for your colors. If you want color-name strings, you should use strings instead.

**Comment by joevandyk** [comment]
I don't write code that depends on a specific output format for colors. The CSS that SASS generates is parsed/read by software far out of my control (example: Microsoft Outlook, IE, etc). And for it to work properly, the color names need to match what I specify.

I'm not sure what you mean by "if you want color-name strings, you should use strings instead". I don't want color names in the generated CSS, I'd like what I type in.  :)

**Comment by joevandyk** [comment]
But we've already been over this before (https://github.com/nex3/sass/issues/343), so that's why I've been maintaining my fork. 

It does appear there is recent support from other people for not changing color names, so I was hoping we could revisit.

**Comment by chriseppstein** [comment]
@joevandyk We're going to add this behavior because it enables more efficient debugging -- not to support specific implementations of css parsers. Just don't use the compressed output and you'll be fine.

**Comment by jeremyabrahams** [comment]
Chris, maybe this isn't the place to ask (feel free to move) but how would I go about controlling this when I am generating my CSS through codekit? I ran a quick test and all four output types changed # ff0000 to red. Compressed then finally changed # 006600 to the shorter # 060

**Comment by dtipson** [comment]
"Compressed output exists to create the smallest possible output." 

I agree with that, but I would think most users would assume that that's the "smallest possible output... without causing things to work differently than they did in other output formats."  The cases in which compressed output would act differently may be edge cases, but they're not obscure.  They also reduce the viability of sass variables being used in plugins or other extensions because the output is no longer as reliable (compression format choice affects the type of output format).

Just my two cents: I can see both sides of this.

**Comment by sm9** [comment]
Another +1 to preserve the author's colour format.

**Comment by quoo** [comment]
+1

**Comment by arxpoetica** [comment]
This is why I prefer Stylus to SASS, FYI. `#f5f5f5` converted to `whitesmoke`? I can't understand the rationale. It rains in my heart. Whence comes this malady? http://www.youtube.com/watch?v=OnakR1yMtUU

**Comment by pyronaur** [comment]
Could it at least be optional in a sass config somewhere when compiling?

**Comment by nex3** [comment]
Due to issue #1001, it looks like we'll need to preserve the author's format for hex colors regardless of whether we're emitting in compressed mode or not, since `#fff` could potentially be an id as well as a color.

**Comment by pyronaur** [comment]
Is there any milestone ?

**Comment by joevandyk** [comment]
@nex3 there an eta of when this will get released?

**Comment by nex3** [comment]
Not anything concrete. It'll be in the 3.4 release, which we'd like to have out three or four months after 3.3, but that's a very vague plan that's liable to change.

**Comment by micahgodbolt** [comment]
I know this is closed, but I also want to point out that data attributes were being converted as well. data-color="white" was changed to data-color="#fff"

**Comment by kratsg** [comment]
Hi guys, I know this is closed. I'm still seeing some conversion that I'm not sure are expected?

sass

``` sass
test
  color: hsl(120, 100%, 50%)
```

compiles to

``` css
test {
  color: lime;
}
```

If you use `hsla` - it converts that to `rgba` in general as well.

There is no way to force it to maintain the input color (eg: hsl output)?

**Comment by nex3** [comment]
Colors that are defined by function are sort of a special case. They go through custom Sass functions that interpret a broader set of input arguments than the CSS functions do, so it's not possible in general to preserve the input format. For `hsl()` and `hsla()` in particular, there's spotty support among older browsers so to be safe we just avoid ever emitting them.

If you want to force an actual HSL declaration, the following function will do so:

``` scss
@function force-hsl($args...) {
  // Allow the function to be called with with a single color (e.g. force-hsl($color)),
  // or with the same arguments as hsl() (e.g. force-hsl(120, 100%, 50%)).
  $color: if(length($args) == 1, nth($args, 1), hsl($args...));
  @return unquote("hsl(#{hue($color)}, #{saturation($color)}, #{lightness($color)})");
}
```

**Comment by adamward84** [comment]
@nex3 any chance that there is a similar force function for rgb? can't seem to find it in the docs.

**Comment by pyronaur** [comment]
You know the code is broken whenever developers ( users ) are looking for
workarounds to your "feature". This makes no sense to me at all.

**Comment by kratsg** [comment]
@justnorris - In my case, it makes a lot of sense to automatically convert given a non-dominative browser support. Overall, it makes more sense to convert to the smallest equivalent color possible when you're talking about minifying code. For standard output, I agree it shouldn't be trying to parse it into a smaller / different type/format.

**Comment by pyronaur** [comment]
Yeah, I think code minifiers/beautifiers should do that, not a pseudo
language like Sass. I hope that this is fixed some day....

**Comment by adamward84** [comment]
Just to add a potentially different perspective, I'm evaluating Sass for use in an application that uses CSS standard to drive something other than web content. We have our own properties, and our own formatting requirements, which are still CSS compliant. I am surprised (and a little miffed) to find a bunch of browser-specific workarounds/hacks/considerations baked into the APIs, to such an extent that they aren't even optional. 

I'd really like to see this fixed, but at this point, I'd settle for a force-routine, no matter how sub-optimal that is. Yes, I am that desperate.

**Comment by adamward84** [comment]
Aaaaaaand, I'm a lazy idiot. I just wrote my own force-rbga based on the force-hsl method above from @nex3. Here it is for anyone else who wants to be lazy like I did:

``` scss
    @function force-rgba($r, $g, $b, $a) {
      @return unquote("rgba(#{$r}, #{$g}, #{$b}, #{$a})");
    }
```

**Comment by nex3** [comment]
> You know the code is broken whenever developers ( users ) are looking for workarounds to your "feature". This makes no sense to me at all.

@justnorris This is a naïve perspective. No feature will be best for everyone all the time. The current behavior works well for the most common use case, and is easy to work around when different behavior is desired.

> Just to add a potentially different perspective, I'm evaluating Sass for use in an application that uses CSS standard to drive something other than web content. We have our own properties, and our own formatting requirements, which are still CSS compliant.

@adamward84 Sass guarantees that, for valid CSS input, it will produce semantically identical CSS output. Per spec, the representation of a color doesn't matter. Why is it important to you?

> I am surprised (and a little miffed) to find a bunch of browser-specific workarounds/hacks/considerations baked into the APIs, to such an extent that they aren't even optional.

They are optional in the sense that you can write (and have written) a mixin to produce different behavior. I'm a big fan of the mixin approach since it makes it very explicit where you're varying from standard behavior and why.

Here's a slightly more flexible version of that mixin:

``` scss
@function force-rgb($args...) {
  // Allow the function to be called with with a single color (e.g. force-rgb($color)),
  // or with the same arguments as rgb() (e.g. force-hsl(100, 100, 200)).
  $color: if(length($args) == 1, nth($args, 1), rgb($args...));
  @return unquote("rgb(#{red($color)}, #{green($color)}, #{blue($color)})");
}
```

**Comment by brianreavis** [comment]
If anyone's interested, here's one for forcing to hex:

``` scss
@function force-hex($color) {
    @if type-of($color) == 'color' {
        $hex: str-slice(ie-hex-str($color), 4);
        @return unquote("\##{$hex}");
    }
    @return $color;
}
```

**Comment by plumpNation** [comment]
Forcing colours to those strings is not solving the issue if you use SASS functions.

Say are creating a style library and you store the hsl string output in a variable, it can't be used in other functions, because it's not been converted.

For instance, you want your colours to be used in linear-gradient() you'll get a color stop error if you try and use the force-hsl() solutions posted above.

I really appreciate the community's efforts on this and other surrounding software, this is not a complaint.

**Comment by sdhull** [comment]
I know this is closed, but we're having the inverse problem. We're stuck on sass 3.2.19 because of dependency hell, and we are using color names in variables which are then converted to their hex values. This isn't great when we want to use them in class names like `.panel-white` and it comes out as `.panel-#fff`.

Amusingly, it appears that in **compressed** mode, hex values are **not** converted to colornames, but in non-compressed mode they are. The inverse occurs with colornames, ie in compressed mode they're converted to hex values, but in non-compressed mode they're left as hex values. I'm just like... wat?

```
! echo 'foo {$var: #fff; .panel-#{$var}: $var}' | sass --scss --style compressed
foo{.panel-#fff:#fff}

! echo 'foo {$var: #fff; .panel-#{$var}: $var}' | sass --scss
foo {
  .panel-white: white; }

! echo 'foo {$var: white; .panel-#{$var}: $var}' | sass --scss --style compressed
foo{.panel-#fff:#fff}

! echo 'foo {$var: white; .panel-#{$var}: $var}' | sass --scss
foo {
  .panel-white: white; }

# finally figured out quotes were the way to solve my problem:
! echo 'foo {$var: "white"; .panel-#{$var}: unquote($var)}' | sass --scss --style compressed
foo{.panel-white:white}
```

The problem is the difference between development and production environments. This results in one of the dreaded "but it works for me" problems where the issue only manifests once deployed.

I realize that it's actually a difference in the _options_ being used to cause this difference between environments, but these options are opaque to Rails developers. So IMO these things should work the same in both cases, to avoid this "gotcha".

**Comment by cimmanon** [comment]
@sdhull No, the problem is that you are using the wrong type.  It has been a long standing problem over and over and over again where users think that because `foo == 'foo'` that `white == 'white'` (meanwhile forgetting that `2 != '2'`).

**Comment by sdhull** [comment]
@cimmanon that's a fair point, and I'll admit I'm not super familiar with sass script. `$var1: foo; $var2: "foo"; .panel-#{$var1} { color: white; }; .panel-#{$var2} { color: white; };` outputs `.panel-foo` rule twice. Confusing or naw?

Anyway you're kinda glossing over my point -- which is that (in Rails), development environments and production environments should work as close to the same as possible. As I demonstrated in that snippet, they actually work _opposite_ -- in production, hex remains hex and color names are converted to hex; in development hex is converted to color names and color names remain color names. Do you see my point here?

``` scss
/* development */
$var1 = white; /* => white */
$var2 = #fff; /* => white */

/* production */
$var1 = white; /* => #fff */
$var2 = #fff; /* => #fff */
```

While I agree that in _my particular case_, the problem was developer error, can you not see how it was compounded by this tool behaving differently in production than development environments?  If it behaved the same in both environments, we would have noticed our error before deploying to production and fixed it. Meanwhile we were able to make styles work as expected locally only to have them break upon deploy.

**Comment by xak** [comment]
I've run into a problem trying to use `data:image/svg+xml` where Firefox has a bug if a hash is used in the SVG, thus I need a color value output as an RGB value.

```
$color__form--error: rgb(204,124,127); //#cc7c7f;
background-image: url('data:image/svg+xml;utf8,
<svg width="9" height="6" viewBox="0 0 9 6" xmlns="http://www.w3.org/2000/svg">
<path d="M4.662 5.873l-.012.01L.345 1.58l.85-.852 3.477 3.476L8.138.74l.85.85-4.304 4.305-.022-.022z" 
fill="#{$color__form--error}" fill-rule="evenodd"/></svg>');
```

the SASS compiles to a HEX value and the SVG does not appear in Firefox.

**Comment by cimmanon** [comment]
@xak It's not a bug when a browser ignores invalid CSS.  See https://github.com/sass/sass/issues/1642

**Comment by davidkpiano** [comment]
@xak You need to encode the hash, so `#cc7c7f` becomes `%23cc7c7f`. I wish Sass had a native `encode()` function (my Sassdash library does have `_encode()`, though), but yeah, it's not a bug.

**Comment by evenfrost** [comment]
I am having exactly same problem as @xak, looking forward to this.

**Comment by xak** [comment]
@cimmanon thanks! 
@evenfrost i opted to use the workaround `fill="#{rgba($color__form--error, 0.999999)}"` works fine.

**Comment by defaye** [comment]
IE filter breaks when using a contracted hex value for me because SASS is contracting hex from `white`/`#ffffff` to `#fff`. I would rather not have to go through the minified stylesheet to correct this. 

`filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#{$headerColour1}', endColorstr='#{$headerColour2}', GradientType=1);`

The contracted hex is ignored by this function.

**Comment by cimmanon** [comment]
@defaye You're supposed to use the `ie-hex-str` function when using filters.

``` scss
.foo {
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#{ie-hex-str($headerColour1)}', endColorstr='#{ie-hex-str($headerColour2)}', GradientType=1);
}
```

Note that if your color happens to have transparency, ie-hex-str will generate the correct value for that.

**Comment by defaye** [comment]
@cimmanon ah thanks! Thanks for the tip. Had no idea about that.

**Comment by javierpose** [comment]
contracted hex value is bad for emails

**Comment by fristys** [comment]
+1 On this feature. Let me decide what colour I consider "compatible".

**Comment by pete-willard** [comment]
Thanks for the workaround, @cimmanon !!! Just ran into the exact same problem with Firefox and SVG.

**Comment by zbjornson** [comment]
We hit an issue with `rgba(0, 0, 0, 0)` and `transparent` rendering differently in MS Edge. Even though they should be semantically the same, they're not, and we have to use `rgba` for that reason. One more vote for not touching the color values.

**Comment by DanielGibbsNZ** [comment]
I'm using `sass-extract` to extract some variables so they can be used in JavaScript, and it would be nice if I could assume that the values will always be in a certain format (e.g. the format that I specify them in, `#rrggbb`). When node-sass turns `#ffffff` into `white` it completely breaks this assumption.

**Comment by wayofthefuture** [comment]
This is killing our programmatic color manipulation

**Comment by scottwhudson** [comment]
This bit my team today. And reading through this, I don't quite agree with the argument that color names are more human-readable than hex values for a variety of reasons. 

One of the things that makes Sass great is the functionality it provides to manipulate color values programmatically. I _love_ not having to write the logic to do all of the math involved in transforming colors. But that ability to manipulate colors programmatically is limited because there are cases when the output type isn't what the designer/developer expects. The lack of output type consistency clearly causes problems for some users here who demand precision in their color output and not able to achieve it without workarounds and digging into the Sass implementation. Sass is (almost always) awesome because I don't have to know how it's built in order to use it.

But the underlying question I have is: **are hex values really less readable than color names?** 

Sure, they're spelled out in English, but that means pretty much nothing to a designer or developer trying to do anything sophisticated (which is why Sass is so helpful in the first place). How many times have you ever thought "I really wish this was using color names instead of hex?" I know it's zero for me because color names don't tell me _enough_ about the color. I mean, who here could recite the hex value for the color `"LightCoral"` off the top of their head?  That color name is no clearer in its value than a hex code. Yeah, it's a word I can read, but I have no idea what value it represents. If I try to build a gradient using a color name, I'm probably going to have to look up it's hex value to make sure that the diff between the two values makes sense. The color name has now become useless to me in that case.

Not to mention it's _very_ easy to get a visual color representation of a hex value in 2019, many modern editors ship with color swatch features enabled by default. I've never struggled to figure out what color a hex value represents, there are just too many good solutions out there for that to be a problem.

How often do designers truly complain about the hex format? I've never run into that problem but it's entirely possible others have. Either way, having an option that strictly enforces output types is clearly something that many in the community want. 

+1 for color type enforcement!

**Comment by nex3** [comment]
@zbjornson I realized I never followed up with your comment here; Sass emits all transparent colors as `rgba()` for IE compatibility as of https://github.com/sass/sass/pull/2337, which was released in Ruby Sass 3.5.0. Dart Sass has emitted `rgba()` since version 1.0.0.

@scottwhudson I understand why you feel that hex colors are more readable. Ultimately, that's an aesthetics call, and I hope you can understand that we came to a different aesthetic conclusion than you did, and that we're unlikely to change it. Changing the CSS output of such a fundamental feature can be quite disruptive to users, and if we were willing to make that disruption, we'd probably choose `hsl()` as the most readable representation anyway since it most closely corresponds to how humans perceive color.

I do want to challenge your use of the term "type", though. There's no difference in type between `green`, `#008800`, `rgba(0, 128, 0)`, or `hsl(120, 100%, 25%)`. All of those values have the type "color". There's only a difference in *syntax*, and any tool consuming CSS should be able to handle any of these syntaxes.

**Comment by scottwhudson** [comment]
Thanks for the quick response! I really appreciate that. I totally understand that I'm but one person in a large sea of opinions, I'm certainly not trying to start battles here.

> we'd probably choose hsl() as the most readable representation anyway since it most closely corresponds to how humans perceive color.

I'd be totally down for that. If there was one syntax that could exist on its own without needing to rely others at all, that would be a major win in my book.

> any tool consuming CSS should be able to handle any of these syntaxes.

But should they? I have a little color picker that just outputs hex, eventually being transformed by a function to another hex code (except in a few cases). The format of my I/O in this path is very straightforward 99% of the time. But the Sass engine is forcing me to be able to adhere to another syntax that I otherwise have no need for. Why should my simple style configurator _need_ to know about all of the different ways in which a style can be codified? Why isn't one subset of the language good enough? I can't make that happen easily without adding more dependencies, which doesn't really make sense given my limited functionality here. It seems a little leaky that the system requires me to support the entire syntax when supporting one subset would work just fine.

And internally, each syntax variant may all be of the same "type", but some developers clearly aren't using them or thinking about them in that way. Each syntax codifies the data differently, and those differences do define separate (and not implicitly interoperable) domains in which those values are meant to be parsed and understood. That's what I meant by "type", which may not have been the best word there.

Anyway, I love Sass, and this is literally the first time I've ever come across behavior in this tool that I didn't expect.

**Comment by nex3** [comment]
Sass is a tool designed for producing CSS, and that has to be the priority when we make design decisions. The priority is not intermediate tools; those tools are welcome to consume Sass's output, but if they do so, they must do it with the understanding that CSS is the standard Sass targets and so it should be the standard they consume. There are many useful tools for consuming CSS, such as [PostCSS](https://postcss.org/), which should generally make this pretty straightforward.

**Comment by dlewand691** [comment]
I recently ran into this issue wanting to use rgba colors but they were compiling into hex. I found that this answer provided the solution but seems like a hacky workaround

https://github.com/sass/sass/issues/1642#issue-57828213

Also using the rgba function like rgba(#000000, 1) did not work. You have to use rgba(0,0,0,0.999999999) to retain the true rgba value that rounds alpha to 1.

**Comment by petko** [comment]
You can also use this hack here: https://github.com/sass/node-sass/issues/2395#issuecomment-392137923

**Comment by mayfield** [comment]
Just to pile on to this 10 year old discussion, I use various color formats in my scss based on context and it's a bit of a hassle to fine tune my colors in dev tools, which by default uses the "As Authored" color format and then have to always cycle through the color formats until I get back to the one I actually authored vs the one sass decided was best for me.

I think I read most of the discussion but it wasn't clear to me why a command line arg wouldn't be an acceptable recourse for this?

**Comment by jathak** [comment]
@mayfield: What version of Sass are you using? Starting in Dart Sass 1.49.10, your color format should generally be preserved, as long as you're outputting in expanded mode.

**Comment by mayfield** [comment]
@jathak I'm using 1.49.10 and expanded mode but hex with alpha (ie. #abcd or #aabbccdd) are still converted to rgba.  Possibly others too, but that's the one I use quite often.  Sounds like some positive strides have been made though, so that's encouraging.

**Comment by jathak** [comment]
We always convert hex-with-alpha to rgba because hex-with-alpha isn't universally supported in browsers. Our standard for browser compatibility only allows a breaking change if it affects less than 2% of browsers, but there are >7% of browsers without support.

**Comment by mayfield** [comment]
Fair enough but I feel inclined to note that `rgba()` is only 2.57% more supported (95.41%) according to caniuse.com and as Sass users, we're already happily handling compat with things like prefixing, `-webkit-foo: 1; -ms-foo: 1;`, and stacking, `overflow: overlay; overflow: auto;`.  So at the end of the day it's just an ever so mild annoyance (for me) with an otherwise near perfect tool.  I love what sass has done for the web and I love seeing things like CSS nesting getting closer to adoption because of sass.

**Comment by nex3** [comment]
If there were a more-compatible way of representing colors with non-1 alpha channels than `rgba()` we'd use that instead :slightly_smiling_face:

**Comment by Nikolasgrizli** [comment]
I also meet with this problem face2face when I maded project with css variables and light/dark theming. For me realy helped [this answer](https://stackoverflow.com/a/58662471/6869268) on stackoverflow. I hope this answer helps you.

**if you read only code it's for you:**

### Usage:
```
body {
    @include defineColorRGB(--main-color, #aa44cc);
}

.button-test {
  // With alpha function:
  color: alpha(var(--main-color), 0.5);
  // OR just using the generated variable directly
  color: rgba(var(--main-color-rgb), 0.5);
}
```


### Mixin and functions
```
@mixin defineColorRGB($color-name, $value) {
    $red: red($value);
    $green: green($value);
    $blue: blue($value);
    #{$color-name}: unquote("rgb(#{$red}, #{$green}, #{$blue})");
    #{$color-name}-rgb: $red,$green,$blue;
    #{$color-name}-r: $red;
    #{$color-name}-g: $green;
    #{$color-name}-b: $blue;
}

// replace substring with another string
// credits: https://css-tricks.com/snippets/sass/str-replace-function/
@function str-replace($string, $search, $replace: '') {
    $index: str-index($string, $search);
    @if $index {
        @return str-slice($string, 1, $index - 1) + $replace + str-replace(str-slice($string, $index + str-length($search)), $search, $replace);
    }
    @return $string;
}

@function alpha($color, $opacity) {
    $color: str-replace($color, 'var(');
    $color: str-replace($color, ')');
    $color-r: var(#{$color+'-r'});
    $color-g: var(#{$color+'-g'});
    $color-b: var(#{$color+'-b'});
    @return rgba($color-r, $color-g, $color-b, $opacity);
}
```

### Result

```
body {
  --main-color: rgb(170, 68, 204);
  --main-color-rgb: 170,68,204;
  --main-color-r: 170;
  --main-color-g: 68;
  --main-color-b: 204;
}

.button-test {
  // Generated from the alpha function
  color: rgba(var(--main-color-r), var(--main-color-g), var(--main-color-b), 0.5);
  // OR (you wrote this yourself, see usage)
  color: rgba(var(--main-color-rgb), 0.5);
}
```
