### ISSUE TITLE
Conditions or optional parameters in forward with

### ISSUE THREAD

**Issue by gerardparareda** [sass/sass#3651]
Hello! I've been adapting the stylesheets of my business website to dart sass and I am missing some functionality when overriding configurations using `@forward '...' with()`. For example:

 `_configurations.scss`:
```
$primary: #2980b9 !default;
```

 `_overrides.scss`:
```
$primary: #ac0a32;
```
`index.scss`:
```
@use 'overrides';

@forward 'configurations' with(
  $primary: overrides.$primary,
);
```
This works until `_overrides.scss` is empty or doesn't have one variable that's trying to be overriden in the `with`, which we would usually do because sometimes the default values were good enough. Since with `@import` we could easily override variables just by importing the `overrides.scss` below `configuration.scss`, I think something along these lines would be nice.

Maybe something like:

`index.scss`:
```
@use 'overrides';

@forward 'configurations' with(
  @if variable-exists(overrides.$primary) {
    $primary: overrides.$primary,
  }
);
```

Or a way to merge two forwards?

As of now, the only way of making it work is declaring all the possible overrideable variables in `_overrides.scss`, which defeats the purpose of having defaults in `_configurations.scss` because their default value will never be used.

Thanks!

**Comment by Goodwine** [comment]
I think there is a misunderstanding here in how `@forward` and `@use` work with regards to [Configuration](https://sass-lang.com/documentation/at-rules/use/#configuration).

Your example in `index.scss` works as intended, because Sass doesn't really care whether the values passed in `with($key: value)` are, as long as they are valid. If you delete the contents in `_overrides.scss`, then it make sense that the variables will be missing everywhere.

I think the idea of having `_overrides.scss` be a simple file that contains only variables meant to override other variables is not what you really want or need. If you want a library `_overrides.scss` to override the styles from `_configuration.scss`, then you must do the `@forward` in there

So instead you want:

_configurations.scss:
```scss
$primary: #2980b9 !default;
```
```scss
_overrides.scss:
@forward 'configurations' with (
  $primary: #ac0a32
)
```
index.scss:
```scss
@forward 'overrides';
```

There's no need to check if a variable exist before overriding, just don't override it in `_overrides.scss` if you don't need to.
