### ISSUE TITLE
Is SASS deprecated or dying?

### ISSUE THREAD

**Issue by martinszeltins** [sass/sass#3706]
Since there was no "Discussions" section, I thought I would open a discussion here. With libraries like Tailwind CSS and also modern CSS features, it seems like SASS usage and popularity has gone down recently. This makes me wonder if SASS is still a good choice for modern web development or is it more of a legacy framework / language for legacy projects?

It seems kind of difficult to justify starting a new project with SASS in light of more modern alternatives. What do you think? Is SASS in maintenance mode now?

**Comment by nex3** [comment]
This is not an issue, and seems like a better fit for a blog post or a conversation at a developer conference.

Since you asked, though: no, Sass is not deprecated or dying. All our metrics are positive: Sass consistently ranks highest by far in tool usage in the [State of CSS survey](https://stateofcss.com/en-US), and while they were measuring satisfaction it consistently ranked very high on that as well. Usage seems to be increasing dramatically over the past years: our best metric here is the npm weekly download count, which has increased sevenfold since we first started tracking it in 2018 (combined downloads of the `sass` and `node-sass` packages). Development is more active, we have more external contributors, and we have more engagement from users. I can tell you that Google, the company that currently pays my salary, is investing resources in moving _towards_ Sass, not away from it.

As for tools like Tailwind or new features in plain CSS: we don't consider these to be competitors. They're trying to do something fundamentally different than Sass. Tailwind, and presentational classes in general, make it very easy to quickly throw together a website with decent styles, whereas Sass is designed to make styles maintainable and consistent over the long term. Sass's core value is making it possible to define styling _logic_ and share that logic across people, teams, and projects—something that is unlikely to ever be fully possible with plain CSS by virtue of the fact that it's not actually desirable to ship a whole CSS framework to the browser when you could just ship the compiled output.

I don't know if you asked this in good faith or if you're just trying to troll, but hopefully anyone curious can get a solid answer here.
