### ISSUE TITLE
"Use list.slash()" warning for a division operation

### ISSUE THREAD

**Issue by lukastillmann** [sass/sass#3715]
I use a sass helper function which converts pixel units into rem values:

```
@function rem-calc($size) {
    @return #{math.div($size, 16px)}rem;
}
```

Since at lease version `1.63.6`,  this causes the following warning when building our application: 

```
Warning: math.div() will only support number arguments in a future release.
Use list.slash() instead for a slash separator.

10 │     @return #{math.div($size, 16px)}rem;
```

`list.slash` is not the correct operator here, since we DO want division. Is there any way to explain to sass that this is a correct use of `math.div`. Or am I ignoring an obvious error in my implementation?

**Comment by nex3** [comment]
It's hard to tell without a full reproduction, but presumably you're passing something that's not a number into `math.div()`.

It's important to note that using interpolation to add units is [strongly discouraged](https://sass-lang.com/documentation/values/numbers/#units), because it _doesn't return a number_. When you write `#{...}rem`, you get an unquoted string that just happens to look like a number. I'm guessing that you're doing the same thing for the argument you're passing into `rem-calc()`, which makes `math.div()` not work.

To solve this, you should use proper unit arithmetic:

```scss
@function rem-calc($size) {
    @return $size * math.div(1rem, 16px);
}
```

This clearly expresses your intention: you're using a one-`rem`-per-sixteen-`px` conversion ratio to convert between `px` and `rem`.
