### ISSUE TITLE
math.div() number arguments only

### ISSUE THREAD

**Issue by nachtfunke** [sass/sass#3763]
I am working with this code:

```scss
$spinner-arc-size: 180deg;
$spinner-arc-time: 1000ms;
$spinner-arc-start-rot: 75deg;

$spinner-duration: math.div(
    (360 * $spinner-arc-time),
    (strip-units($spinner-arc-start-rot + (360deg - $spinner-arc-size)))
);
```
Where I specifically want there to be a division calculation, not a separator. Yet the compiler still gives me this message:

```
Warning: math.div() will only support number arguments in a future release.
Use list.slash() instead for a slash separator.

   ╷
15 │   $spinner-duration: math.div(
   │ ┌────────────────────^
16 │ │     (360 * $spinner-arc-time),
17 │ │     (strip-units($spinner-arc-start-rot + (360deg - $spinner-arc-size)))
18 │ │ );
```

Do I understand it correctly, that we're supposed to use the platforms own `calc()` for this, _because_ it uses `deg`/`ms` units?

The `strip-units` function is supposed to already handle that:

```scss
@function strip-units($number) {
    @return math.div($number, ($number * 0 + 1));
}
```

***

I believe what I am looking for is clarity on what the intended future of this is. Is sass not going to handle these types of calculations any longer? is this a case in which sass intends authors to use css `calc()` instead?

**Comment by nex3** [comment]
I can't reproduce your warning [in the Sass playground](https://sass-lang.com/playground/#eJxtkMsOwiAQRfd8xSxMKloMxPhIu+mvUIvKAjQzgwuN/26pMT4qK5KTezkXY5pEDgqyRFWwfCxqISZ09jE6VBZ3ivzVVWC2unOH+huxDxlprQP9IGKLrPDEFWxWQ1I0+xR37E8RiNGfVYqeaTqJKbQOJdwE9KdBxwkjZJVF5y8vXsLrBjPQMAcjZS3uH65dQpvbq3d2aJwu17rPjMRl+cRfMn8n9K/lkn4FKBj9jZRSyDyvc206wMinFg+nEHF5). Can you provide a fully functional reproduction?

As a side note, we strongly recommend against using `strip-units()` functions of any kind. If you use proper unit arithmetic, you'll get the correct units in the end anyway. In this case, if you multiplied `$spinner-arc-time` by `360deg` (or `1turn`) instead of the unitless `360`, the angle units in the numerator and denominator would cancel out and `$spinner-duration` would have unit `ms` without needing to strip anything. See [this example](https://sass-lang.com/playground/#eJxtjjsOwjAQRHufYguk8DOyCwSym1xlwVZwYQftrik4PUmEhMBM+zTzxtq+coSOkdlllFvnlVrxPZUSSSNdNadndGDPJsTBfyNJeUbGmMw/iAVJNI3i4HRcmh8eKqGksTiYhYeQHmsFU6xUKrCFxrFf8P992L17GprbajNp+xAvdYDG7tULdbtSSw==).

**Comment by nachtfunke** [comment]
> I can't reproduce your warning [in the Sass playground](https://sass-lang.com/playground/#eJxtkMsOwiAQRfd8xSxMKloMxPhIu+mvUIvKAjQzgwuN/26pMT4qK5KTezkXY5pEDgqyRFWwfCxqISZ09jE6VBZ3ivzVVWC2unOH+huxDxlprQP9IGKLrPDEFWxWQ1I0+xR37E8RiNGfVYqeaTqJKbQOJdwE9KdBxwkjZJVF5y8vXsLrBjPQMAcjZS3uH65dQpvbq3d2aJwu17rPjMRl+cRfMn8n9K/lkn4FKBj9jZRSyDyvc206wMinFg+nEHF5). Can you provide a fully functional reproduction?
> 
> As a side note, we strongly recommend against using `strip-units()` functions of any kind. If you use proper unit arithmetic, you'll get the correct units in the end anyway. In this case, if you multiplied `$spinner-arc-time` by `360deg` (or `1turn`) instead of the unitless `360`, the angle units in the numerator and denominator would cancel out and `$spinner-duration` would have unit `ms` without needing to strip anything. See [this example](https://sass-lang.com/playground/#eJxtjjsOwjAQRHufYguk8DOyCwSym1xlwVZwYQftrik4PUmEhMBM+zTzxtq+coSOkdlllFvnlVrxPZUSSSNdNadndGDPJsTBfyNJeUbGmMw/iAVJNI3i4HRcmh8eKqGksTiYhYeQHmsFU6xUKrCFxrFf8P992L17GprbajNp+xAvdYDG7tULdbtSSw==).

Thank you! That makes a lot of sense.

The original problem was caused by me. Apparently, I incorrectly forwarded the file that contained the `strip-units()` function, so it got never executed. So the error message does make sense to a degree, because it tried to apply a division to the actual string `strip-units(...)`. Though the problem didn't appear to me until I some more debugging. Thank you for your help!
