### ISSUE TITLE
Allow import/export of Sass Value Types into stylesheets

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [sass/sass#3874]
I'm posting this as a question about the ability to perform this task - otherwise as a feature request.

Feature
===
Ability to import Value types from a JS module.

## Example
// sass-file.scss
```scss
@use './my-js-module';

.my-class {
  color: $my-color;
}
```

// my-js-module.js
```js
import { SassColor } from 'sass';
export default {
  '$my-color': new SassColor({ red: 0, blue: 0, green: 0 });
}
```

### Interoperability

Interoperability between JS and Sass can unlock many opportunities for library developers. For example:
1. Ability to expose JS and SASS APIs for using standard CSS values (such as what a design system/component library might do).
2. Ability to use Node.js runtime to implement conditional values based on environment settings, for example, reading an environment variable to change the URL of resources.

```js
import { SassString } from 'sass';
export default {
  '$image-url': new SassString(process.env.MY_DEPLOYMENT_ENV === 'qa' ? 'http://qa-url' : 'http://prod-url');
}
```

### Status-quo
- At the moment, developers can solve some of these problems in the following ways
  1. Pre-build step: Run a JS script that generates the SASS code that you need using your JS modules
   > The drawback of this approach is the additional build steps necessary to accomplish the task. In some cases (for library developers) the conditions we must check need to happen on the side of the library consumer, so we would need expose some CLI/script that generates Sass code for the developers. 
  > 
  > Another drawback is that the dependency link between the JS modules and SASS Modules is broken. Bundlers that provide watch-mode or dev-servers won't be able to track changes in the source JS modules that generate the SASS module in order to re-generate the final CSS bundle(s)
  2. Custom functions:  Custom functions already allow developers to use the SassValue types created in Node.
  > The drawback of this approach is multi-faceted. 
  > 1. It requires developers to configure the sass build ahead of time, so it doesn't lend itself to modularity and version management provided by package managers. (For example, if the custom function is used multiple dependency levels away from the consumer's project). 
  > 2. It defines the function globally, so it inherits all of the drawbacks of global libraries -- hard to trace definition, lack of modularity and version management, etc.

### Follow up
- At the moment, SassValue types are only exposed for custom functions and therefore are limited to value types. However, with JS as sass modules, it would be nice to allow exporting mixins. This can unlock interoperability with other CSS processors and CSS-in-JS libraries.

**Comment by nex3** [comment]
One of the major goals of Sass is to make stylesheets as platform-independent as possible. Between standalone Dart Sass, the `sass` npm package, and the various Sass embedded hosts, there are many different contexts in which a Sass stylesheet can be compiled, and only one of them can load and execute JavaScript. Although the current plugin API does have real drawbacks in terms of composability, it also has the distinct benefit that it doesn't involve directly encoding a specific host language into the stylesheets themselves. You can always re-implement any custom functions in another host language and run the stylesheets as-is there as well.

There's also a security concern here. The surface area for which code in the host language can be run by a Sass stylesheet is intentionally constrained to the set of plugins passed in to a `sass.compile()` call. Allowing any Sass file to load and execute arbitrary JavaScript would be a substantial escalation of capabilities which may violate security assumptions for some of our users. If we did add something like this, it would _need_ to be opt-in at the `sass.compile()` site (for example by passing a built-in importer). This would mitigate the value of making it more composable since the end application author still needs to properly configure their compilation to use upstream libraries with plugins.

As for custom mixins defined in the host language, the major issue there is that it would require defining and exposing an entire CSS AST API in JS as well as the embedded protocol. That's a tremendous amount of additional design and development work, not just for us but for every embedded host, and we'd need a correspondingly substantial use-case to make it clearly worth doing.

**Comment by GeorgeTaveras1231** [comment]
@nex3 thanks for the response. These are all valid points.

With the recent addition of the `NodePackageImporter`, I thought this would be a reasonable extension in the spirit of improving interoperability with NodeJs. From my limited POV it seems it wouldn't be too complex to implement a version of this as a custom importer in the user space. If I was to embark on implementing this (the scope limited to just NodeJs, not considering other embedded hosts), would you have any advice or pointers? I've implemented custom importers before so I am familiar with the API but am wondering if you foresee any potential issues other than the ones you called out. No pressure to respond but I would appreciate it 😄

**Comment by nex3** [comment]
A critical aspect of the package importer concept is that it's cross-platform—the Sass code itself just writes `@use 'pkg:packagename'`, which we took pains to make a standard format. That package can then be resolved however makes sense for the platform in question.

The importer API specifically supports loading files of _Sass source code_, not custom functions or values, so I'm not sure this is feasible for that API.

**Comment by GeorgeTaveras1231** [comment]
@nex3 From the example [here](https://sass-lang.com/documentation/js-api/interfaces/importer/#md:resolving-a-load) it seems that an importer can generate any arbitrary sass code (using the `load` function). I assumed I could use something like this.

**Comment by nex3** [comment]
Right—that's Sass source code. But you can't return custom values or functions constructed from JS.

**Comment by GeorgeTaveras1231** [comment]
The idea is I would load the JS file in the loader and convert it to valid Sass code...map objects based on their identity or type (color, string, etc) to the equivalent Sass code
