### ISSUE TITLE
Conditionally allow @extend within directives

### ISSUE THREAD

**Issue by nex3** [sass/sass#391]
As suggested by @CrowChick [on Twitter](https://twitter.com/#!/CrowChick/status/202193684765229056), rather than disallowing `@extend` in directives wholesale (see #154), we could disallow them only if they match CSS rules from outside the directive. This would allow directives containing a large amount of self-contained CSS to continue to take advantage of `@extend` while still making it clear that it's unsafe to `@extend` classes in general.

This does present some difficulty with using libraries such as Compass that expose `@extend`able classes as part of their API. This could be partially overcome by including the library in the `@media` declaration itself, which has the additional advantage of making it more explicit that all the library CSS must appear within the `@media` query. However, the following use case would still fail:

``` scss
@include "compass";

@media print {
  @include "compass";

  #main {@extend %some-compass-thing}
}
```

Since `%some-compass-thing` would be defined outside of the `@media` query as well as inside, the `@extend` would be an error. This could be avoided by making `@extend` within a directive silently ignore selectors outside of that directive, but that eliminates any indication to users that naively `@extend`ing a top-level selector won't work.

Feedback on this proposal would be appreciated.

**Comment by nearestnabors** [comment]
Some background on my use case:

I use a single CSS file for screen, print and media queries rather than 3 separate files (and thus 3 http requests instead of one). Not all that uncommon. I keep my print styles in @media print {} and my screen styles in @media screen {} exclusively. Never the twain shall intermingle since print doesn't need floats or side columns or any of that.

I use @extend heavily within the screen directive to delegate common screen-only classes and style patterns to things like forms and comment lists. It makes for understandable SCSS and conveniences me where I cannot add new classes to markup ala OOCSS.

With the latest update to Sass deprecating @extend withing media directives, naturally this doesn't work anymore. I could try to put these extendable classes and their styles outside the screen declaration, but then not only do they start affecting the print styles, but I would have to add all the classes I wanted to extend manually. That is not maintainable in this instance.

Extend is extremely handy and hard to replace (unless you're cool with the added bulk of mixins). Would love to keep a scoped version going until it's native to CSS.

**Comment by chriseppstein** [comment]
This is a hard problem. I've just realized disallowing `@extend` in `@media` breaks [my grid system](http://chriseppstein.github.com/blog/2011/08/21/responsive-layouts-with-sass/). Not in a big way, I can convert my few extends into mixins or I can move the extend outside of the media blocks. On the net, it's probably best to disallow it because I think it's ripe for mis-understanding.

I think the mental model for people is that they should extend from within the media query, but actually the way this works best is if the base classes are defined in the media query and those are extended at the global scope.

I feel like we need to introduce a module/scoping context that will, among other things, constrain the application of extends. With this, we can re-introduce extending in any scope that doesn't span a media boundary. or we can implicitly define a media query as a scope.

**Comment by nearestnabors** [comment]
As per @chriseppstein's Twitter request, I made a gist showing how I'm using extend (very simplified): https://gist.github.com/2702326

All extendable classes are scoped inside the media directives in which they are used.

**Comment by davidrivers** [comment]
I'm also trying to build a grid system that wants to extend my dynamically-generated (from an @each block) .fluid-unit-6-16 class. Since I apparently can't convert my grid classes to mixins and have them dynamically generated in the same way (Interpolation doesn't seem to work within a mixin directive itself), I'm stuck with not being able to use my grid-unit styles within this @media query altogether, unless I rewrite my grid styles in a terribly repetitive, non-flexible way. So, I can't do something like the following:

`@media only screen and (max-width: 768px) {
    .tablet-portrait-fluid-unit-12-16 {
        @extend .fluid-unit-12-16;
    }
}`

It seems that when the sass compiler encounters an @extend within a @media, it chops off the outer @media block. Whereas the following example compiles correctly (Sass doesn't change it):

`@media only screen and (max-width: 768px) {
    .tablet-portrait-fluid-unit-12-16 {
        color: red;
    }
}`

**Comment by nex3** [comment]
My current plan here is to allow `@extend` to work when the extended selector only matches rules within the current directive. It will still throw an error if any matched rules are outside the current directive, even if there are some rules within it as well.

**Comment by nearestnabors** [comment]
Sounds good to me.

**Comment by samuelvogel** [comment]
The proposed solution in this ticket would cover our use case, we just got thrown of by the #154.

**Comment by nearestnabors** [comment]
Is this a part of an official version of Sass? If so, which number?

**Comment by chriseppstein** [comment]
Pretty sure it's in the latest stable release.

**Comment by nearestnabors** [comment]
Would it be in sass-rails 3.2.5?

**Comment by chriseppstein** [comment]
sass-rails is just glue between sass and rails. you'll need to upgrade sass independently.
