### ISSUE TITLE
math.div() is undefined function in vite

### ISSUE THREAD

**Issue by Naomikho** [sass/sass#3927]
I am using ~1.78 "sass" package, which should have math.div(the function exists in the package in node_modules) but vite keeps complaining the function is undefined. Is there an alternative to the math.div() function

[plugin:vite:css] [sass] Undefined function (on math.div)

```
@use 'sass:math';

@function blend-multiply ($mix1, $mix2) {
  $red-blend: math.div(red($mix1) * red($mix2), 255);
  $green-blend: math.div(green($mix1) * green($mix2), 255);
  $blue-blend: math.div(blue($mix1) * blue($mix2), 255);

  @return @blend-normal(rgba($red-blend, $green-blend, $blue-blend, opacity($mix1)), $mix2);
}
```

**Comment by nex3** [comment]
If you can see the function defined in `node_modules`, that strongly suggests that this is an issue with Vite rather than with Sass. I recommend filing an issue there.

It's hard to say if there's a workaround because it's hard to say what exactly is compiling your Sass files, if not the actual version of Sass you have installed. Prior to the introduction of `math.div()`, you could use `/` for division, but that's not recommended as it will be removed in an upcoming version of Sass (which is why we added `math.div()` in the first place).
