### ISSUE TITLE
HEX to RGB color values are ... too long?

### ISSUE THREAD

**Issue by stefangabos** [sass/sass#3944]
I am using Grunt to compile some SASS files.

I have the `outputStyle` option set to "expanded" (but it does the same in `compressed` mode also) and I get this

```css
color: #b4d5e6
```
converted to this 

```css
color: rgb(179.7337662338,213.2337662338,229.7662337662)
```
the source color itself comes from a variable like
```css
$foo_color: #b4d5e6
```

I read through a bunch of issues about leaving the color values as authored except for converting things like `#FFFFFF` to `#FFF` but my takeaway was that no feature related to this was implemented nor does it look like it ever will be (citing browser compatibility / support)

So, my question is, since `rgb(179.7337662338,213.2337662338,229.7662337662)` is too verbose by any standards, can I do something about it? can I keep my hex colors or can i have only 2 decimals for those RGB colors?

Thank you!

**Comment by dreid** [comment]
Our CI noticed similarly long color strings being used on a PR to upgrade to 1.79.3 from 1.78.0, so I think this might be due to some recent changes to the color system.

Given:
```scss
@use "sass:color";

$red1: #ce1836;
$red1BackgroundCalculated: color.adjust($red1, $saturation: -35%, $lightness: 42%);
$red1BackgroundIntended: #edd0d4;

@debug $red1;
@debug $red1BackgroundIntended;
@debug $red1BackgroundCalculated;
```

On 1.78.0 outputs:
```
❯ npx sass@1.78.0 t.scss
t.scss:7 Debug: #ce1836
t.scss:8 Debug: #edd0d4
t.scss:9 Debug: #edd0d4
```

And with 1.79.0
```
❯ npx sass@1.79.0 t.scss
t.scss:7 Debug: #ce1836
t.scss:8 Debug: #edd0d4
t.scss:9 Debug: rgb(236.6189130435, 207.5810869565, 212.367541806)
```

**Comment by nex3** [comment]
@stefangabos I can't reproduce your issue [on the playground](https://sass-lang.com/playground/#eJwzNExUqE7Oz8kvslJQTjJJMU01qwUAQOQGQg==). A hex color with integer values should never be emitted as an `rgb()` function.

@dreid This behavior is intentional. Before CSS Color Level 4, CSS treated all color values as reducible to integer-aligned RGB values—the value `#edd0d4` was strictly identical to `rgb(236.6189130435, 207.5810869565, 212.367541806)`, and would never produce a different color on screen or behave differently in CSS functions. With Color 4, that's no longer true. There's a possibility that screens with higher color depth will be able to display colors "in between" the 16,581,375 color values represented by RGB, and the difference between red `236.6189130435` and red `237` can definitely be observed in CSS functions that work across color spaces like [`color-mix()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix) and [relative color syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors).

For Sass, preserving compatibility with CSS and not throwing away information is always going to be a higher priority than minimizing bytes. But you can use a tool like [cssnano](https://cssnano.github.io/cssnano/) on your CSS output if you know that RGB rounding errors don't matter to you—the [`colormin` optimization](https://cssnano.github.io/cssnano/docs/optimisations/colormin/) will convert all legacy color values to their smallest integer-aligned equivalent.

**Comment by stefangabos** [comment]
in case somebody stumbles upon this in the future, here's what happened and how it can be fixed:

i replaced all the calls to `darken` and `lighten` with `color.adjust` because the former are being deprecated. i was already using [clean-css](https://github.com/clean-css/clean-css) which converts by default `rgb` colors to `hex` colors. the novelty is that the colors generated by `color.adjust` have decimals while the ones generated by `darken` and `lighten` don't. and the *actual issue*, in my case, was that [clean-css](https://github.com/clean-css/clean-css) leaves values having decimals as they are and therefore i ended up having `rgb` colors in my `css` files where previously i only had `hex` colors.

my solution was to have an extra step before running clean-css in order to strip the decimal values that i don't want. i ended up stripping the decimal values for the first 3 arguments in calls to the functions `rgb`, `rgba`, `hsl` and `hsla` (keeping the "%" if present and supporting values like `.34567`) by crafting this regular expression and using it as `pattern`

```js
/(rgba?|hsla?)\(\s*([0-9]*\.?[0-9]+)?(\%)?\s*,\s*([0-9]*\.?[0-9]+)?(\%)?\s*,\s*([0-9]*\.?[0-9]+)?(\%)?/g
```
and using the following callback as `replacement`
```js
replacement: function(match, p1, p2, p3, p4, p5, p6, p7) {
    p2 = p2 ? Math.floor(parseFloat(p2)) : '0';
    p4 = p4 ? Math.floor(parseFloat(p4)) : '0';
    p6 = p6 ? Math.floor(parseFloat(p6)) : '0';
    return p1 + '(' + p2 + (p3 || '') + ',' + p4 + (p5 || '') + ',' + p6 + (p7 || '');
}
```
which takes care of values like `.34567`

**Comment by cbratschi** [comment]
Here is the solution for our Gulp based toolchain:

```JavaScript
import map from 'map-stream';

/**
 * Undo Sass 1.79 changes which add rgb() values instead of hex colors.
 *
 * Reducing the accuracy here but no problem in practice.
 */
export function convertToHexColors() {
    return map((file, done) => {
        let css = file.contents.toString();

        //debug
        //console.dir(css);

        // 1) convert rgb() to hex
        css = css.replace(/rgb\(\s*(\d*\.?\d+|none)\s*[\s,]\s*(\d*\.?\d+|none)\s*[\s,]\s*(\d*\.?\d+|none)\s*\)/ig, ($0, $1, $2, $3) => {
            //debug
            //console.log(`${$0} ${$1} ${$2} ${$3}`);

            //convert to hex
            const r = convertToHexColorChannel($1);
            const g = convertToHexColorChannel($2);
            const b = convertToHexColorChannel($3);
            const res = `#${r}${g}${b}`;

            //debug
            //console.dir(res);

            return res;
        });

        // 2) reduce rgba() digits
        css = css.replace(/rgba\(\s*(\d*\.?\d+)\s*,\s*(\d*\.?\d+)\s*,\s*(\d*\.?\d+)\s*,\s*(\d*\.?\d+)\s*\)/ig, ($0, $1, $2, $3, $4) => {
            //convert to hex
            const r = Math.round(parseFloat($1));
            const g = Math.round(parseFloat($2));
            const b = Math.round(parseFloat($3));
            const a = parseFloat($4);

            const res = `rgba(${r}, ${g}, ${b}, ${a})`;

            return res;
        });

        file.contents = Buffer.from(css);

        done(null, file);
    });
}

/**
 * Convert a color channel value to hex.
 *
 * @param {string} channel
 */
function convertToHexColorChannel(channel) {
    if (channel === 'none') {
        return '00';
    }

    return Math.round(parseFloat(channel)).toString(16).padStart(2, '0');
}
```

Still seeing some hsl() values but they are fine. Before our CSS output got about 5% larger due to this change and we stayed on an older Sass version until now.

Tried cssnano first but it did not help and changed other things.
