### ISSUE TITLE
Using modern api with typescript paths leads to error

### ISSUE THREAD

**Issue by dvdmlln** [sass/sass#3958]
Hi,

I use sass in my projects in combination with nuxt/vite. Recently I tried to use the modern sass api but encountered an error.
I have a stylesheet in my nuxt module containing default values I try to override in my project.

My .tsconfig looks like this:

```json
{
    "compilerOptions": {
        "paths": {
            "#my-module/*": [
                "../../src/runtime/*"
             ],
        }
    }
}
```

In the runtime folder I have a file `./assets/variables.scss`. When I use `@forward '#my-module/assets/variables.scss' with (...);` the following error occurs:
`Pre-transform error: [sass] Module loop: this module is already being loaded.`

Using `@forward '../../src/runtime/assets/variables.scss' with (...);` or the legacy api is working just fine.

Reproduction:
https://github.com/dvdmlln/sass-forward-path

Run `npm install && npm run dev:prepare && npm run dev`

Best regards
David

**Comment by nex3** [comment]
A few things here:

1. This seems to be an issue with how your framework's custom Sass importer is working, and so should maybe be reported there rather than here.
2. It's generally not safe to assume that any TS/JS load syntax works with Sass. Some custom importers make an attempt to match them, but that's not a guarantee and you should make sure you're aware of the differences between Sass and Node.
3. In particular, Sass loads are always URLs, which means that `#` is parsed as a [URL fragment](https://url.spec.whatwg.org/#concept-url-fragment) rather than part of resource itself. To ensure we comply with the URL spec, we're planning to deprecate the use of `#` in Sass URLs (https://github.com/sass/sass/issues/3882). We've already recommended that WebPack avoid this syntax in https://github.com/webpack-contrib/sass-loader/issues/1205.
