### ISSUE TITLE
Convert node-sass to dart sass without changing bundles

### ISSUE THREAD

**Issue by sahin52** [sass/sass#3967]
I'm trying to use dart-sass instead of node-sass in our projects. But I'm not sure how it will affect the outputs. The bundles are different. For example:  
`Min` is now `min`,  
 css.map files are different and hard to detect the cause of the difference  
`@chartset "UTF-8"` is added in a css file  
Numbers like in `line-height` or `vertical-align` is now more precise like 0.0714285718em instead of 0.07143em  

I'm using node-sass latest version 9.0.0, what is the compatible version in dart-sass?  
And I added api: "legacy" to webpack config sass-loader options but the differences still exist. Shouldn't this solve the problem?

Will using dart-sass instead of node-sass cause any problem, or do these results normal and generate the same view? And is there a compatibility table?

**Comment by nex3** [comment]
> I'm using node-sass latest version 9.0.0, what is the compatible version in dart-sass?

There is no version of Dart Sass that's byte-for-byte compatible with Node Sass. Node Sass never used a fully compatible implementation of Sass to begin with, and many improvements have been made since its last release. I'd always recommend using the latest version of Dart Sass.

> And I added api: "legacy" to webpack config sass-loader options but the differences still exist. Shouldn't this solve the problem?

The legacy versus modern JS API doesn't affect the way Sass is compiled at all. It _only_ affects the way you interact with a Sass compilation from JavaScript.

> Will using dart-sass instead of node-sass cause any problem, or do these results normal and generate the same view?

The changes you've described explicitly will all produce the same (or more accurate) visible output. There's not a universal guarantee that Dart Sass will produce semantically identical CSS to LibSass, particularly in cases where LibSass had bugs or where we've had to make major changes for CSS compatibility. That said, if you're not seeing any build errors or deprecation warnings, you're probably reasonably safe.

> And is there a compatibility table?

You can see a list of [major compatibility concerns on the LibSass tracker](https://github.com/sass/libsass/issues?q=is%3Aopen+is%3Aissue+label%3A%22Compatibility+-+P1+%E2%9A%A0%EF%B8%8F%22), but to some degree you just have to verify by hand that the output is still reasonable. If the biggest issues you're seeing are capitalization and precision diffs, you're probably in pretty good shape.
