### ISSUE TITLE
Color output format

### ISSUE THREAD

**Issue by yalogica** [sass/sass#3971]
I have such style

`background-color: color.adjust(#2271b1, $lightness: -5%);`

but after compiling I get this 

`background-color: rgb(29.8909952607, 99.3436018957, 155.6090047393);`

but I need this end format

`background-color: #1e639c;`

P.S.
As I can see it depends on $lightness value

`background-color: color.adjust(#f6f7f7, $lightness: -10%);` = `background-color: #dbdfdf;`
`background-color: color.adjust(#f6f7f7, $lightness: -5%);` = `background-color: rgb(232.5, 235, 235);`

but I need a format with hex as it was before, not rgb with decimal values.

P.S.S.
I use ` "sass": "^1.80.4"`

P.S.S.S.
I compared old sass version `"sass": "^1.71.1"` from my old project "node_modules\sass\" and new one also ^1.71.1 installed today. And they are differents. How it could be?

P.S.S.S.S.
I don't know if this is a good thing or not, but I found this solution:

```
@use "sass:color";
@use "sass:string";

@function lighten($color, $amount) {
	$new-color: color.adjust($color, $lightness: $amount);
	@return string.unquote('#' + string.slice(color.ie-hex-str($new-color), 4));
}

.container {
	background-color: lighten(#f6f7f7, -5%);      // output background-color: #E9EBEB;
}
```

**Comment by martinlynge** [comment]
In the effort to prepare for Dart Sass 2.0.0 I migrated lighten and darken to the color.adjust counter parts, and ended up with the same issue

**Comment by yalogica** [comment]
> In the effort to prepare for Dart Sass 2.0.0 I migrated lighten and darken to the color.adjust counter parts, and ended up with the same issue

Yes, I did the same thing. Converting the **darken** to **color.adjust** gives this strange result. On old projects everything is fine, the main thing is a week ago everything was fine, and now this result with **darken** call too. I don't understand what's wrong.

**Comment by nex3** [comment]
This is intentional. As of CSS Colors Level 4, fine gradations between color values are now observable in CSS, because they can affect how colors are transformed between color spaces (and potentially even render differently on screens with high color depth).

Dart Sass's [browser compatibility policy](https://github.com/sass/dart-sass?tab=readme-ov-file#browser-compatibility) guarantees that changes to the output format won't break more than 2% of the global browser marked. `rgb()` has been a specified CSS color output format at least the 1997 [CSS 2.0 specification](https://www.w3.org/TR/WD-CSS2-971104/syndata.html#h-4.2.5), and it's universally supported by browsers, so it's well within these bounds.

You don't say why you "need" a color in hex format. If you have another tool that's consuming colors generated by Sass, that tool should ideally support all color representations that the CSS spec supports—or at least those that have had universal browser support for decades. If you just want terser output, I recommend a minifier tool like [cssnano](https://cssnano.github.io/cssnano/).

**Comment by macgyver** [comment]
@nex3 thank you so much for your explanation about this, I wish I had been able to find this comment sooner!

Sass works so well that we forget to upgrade it sometimes. For anybody else who comes here trying to understand why their recent update caused hex values to now be formatted as rgb, and wondering if they can get sass to format the strings back to how their were before, this is the path I took:

we recently upgraded from an older version of sass that didn't have support high precision rgb values, so the switch from hex to rgb, while more correct, was not what we were looking for. 

We are already using `cssnano` and similarly to sass it will not format such values differently to avoid losing data, so to reproduce the previous behavior we now apply this function after mixing colors:

```scss
// reduce precision of a color such that it could represented accurately as a hex string,
// to maintain legacy values even in the higher precision world of css colors level 4
@function round-rgb($color) {
  @return rgb(
    math.round(color.red($color)),
    math.round(color.green($color)),
    math.round(color.blue($color))
  );
}

```

If anybody who understands color spaces better than me has a more correct fix to the issue, i'd love to hear it!
