### ISSUE TITLE
mixed-decls error for a mixin, unsure how to proceed/fix

### ISSUE THREAD

**Issue by reintroducing** [sass/sass#4000]
I'm slowly porting a legacy project over and using mixins for multiple things, including setting box sizing (pretty simple):
```
@mixin sizing {
  box-sizing: border-box;

  * {
    box-sizing: border-box;
  }
}
```
In a component, I then have this Sass:
```
.root {
  @include reset.sizing;
  position: relative;
  isolation: isolate;
}
```
This generates the following error:
```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> lib/gds/SplitButton/index.module.scss
8  │     isolation: isolate;
   │     ^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> lib/core/mixins/reset.scss
9  │ ┌   * {
10 │ │     box-sizing: border-box;
11 │ │   }
   │ └─── nested rule
   ╵
    lib/gds/SplitButton/index.module.scss 8:3  root stylesheet
```

if I simply move the `@include reset.sizing;` statement to be the last item inside of the `.root` declaration, the issue goes away, as is my understanding of the error and how this is meant to work. That being said, I have this sort of code sprinkled in a LOT of places in the codebase. Is it possible to modify the mixin instead of implementation to handle this error? or am I SOL and need to go through and update every usage of it to be the last line?

I know i can turn off the deprecation warnings but that just seems like prolonging an issue that will arise down the line in a future update. 

Would appreciate any guidance as to how to solve this elegantly in a way that will not cause issues in the future if that is possible.

**Comment by nex3** [comment]
Unfortunately, there's nothing you can do within the mixin to solve this, since the core issue is that declarations after a nested rule will be interpreted differently in the future to match CSS semantics and the post-nesting declarations are all outside the mixin in this case. If you don't override `box-sizing` anywhere else, it would be reasonable to just silence the deprecation, because the new ordering won't actually cause any issues in practice. The output for your example will look like this:

```css
.root {
  box-sizing: border-box;
}
.root * {
  box-sizing: border-box;
}
.root {
  position: relative;
  isolation: isolate;
}
```

but you can make that more terse by moving the top-level declaration to the bottom of your mixin.
