### ISSUE TITLE
Support for css3 filter property value: saturate

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#428]
the saturate function with one argument should return a css function as output.

**Comment by nex3** [comment]
There are a few issues with this commit:
- When you define a single `@overload` tag, it overrides the Ruby definition of the method. So the documentation now only shows the signature for the filter case.
- The convention for functions that default to plain-CSS functions is to not document that fact (see [alpha()](http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html#alpha-instance_method)). Since they "just work" when used as CSS functions, additional documentation would just serve to make it more difficult for users to process the docs. I did this differently for [grayscale()](http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html#grayscale-instance_method), but that was probably wrong.
- As a user-visible change, this should be mentioned in the Changelog.
- There are a number of other functions in the [filter effects spec](https://dvcs.w3.org/hg/FXTF/raw-file/tip/filters/index.html) that conflict with our color functions, all of which should be modified in this way.
