### ISSUE TITLE
Conditions within functions

### ISSUE THREAD

**Issue by Anahkiasen** [sass/sass#448]
I recently discovered that you can't do the following :

``` sass
@function foo($argument: 5px)
    @if($argument > 5px)
        @return black
    @else
        @return white
```

This throws the following error : `Functions can only contain variable declarations and control directives`. That's really problematic, I use functions a lot in times where I need to create a mixin but append something to the property after. Say I created a `paper-curl` function that outputs a serie of box-shadow resembling the shadow of a curved paper, I can't add other box-shadows if I use a mixin, but I can with a function. Thing is sometimes I need more liberties and without conditions that's a little complex.

I wanted to know what was the reason behind that decision ? Is it a matter of code complexity or something ?

**Comment by nex3** [comment]
Functions do allow `@if`. The trouble here is that you have a syntax error; the indented syntax requires a space between the name of a directive and anything after it. Because you have the parenthesis immediately following `@if`, the parser gets confused and thinks you have an unknown directive, causing it to print that error.

**Comment by Anahkiasen** [comment]
Ah damn. I gotta stop working with so many languages at once, sometimes it all gets mixed up without noticing. My bad, really.
