### ISSUE TITLE
Support interpolation in CSS-based imports

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#49]
```
$googlefonts:"Corben:bold|Ubuntu|Droid+Serif";
@import url("http://fonts.googleapis.com/css?family=#{$googlefonts}&subset=latin");
```

Should work.

**Comment by daz-codes** [comment]
This would be useful to be able to list all google fonts in a variable string

**Comment by McWatt** [comment]
Does this work for sass file @imports? For example, what if I want to do something like this:

``` scss
$siteID: 103;

@import "custom/_styles.#{$siteID}";
```

where the partial i'm trying to import is named "_styles.103.scss".

this returns an error...

```
Line 45: File to import not found or unreadable:
custom/_style.#{$siteID}.
```

thx!

**Comment by nex3** [comment]
I'm scaling back this feature in Sass 3.2 due to parsing concerns. The original implementation only worked when the interpolated string or `url()` was a valid string/url; this means that you couldn't include e.g. quotes or closing parentheses within the string/url (e.g. `@import "#{"foo.css"}"`). This is contrary to how interpolation worked everywhere else in Sass.

It needs to be easy for the user and the parser to tell whether a given `@import` is going to be static (compiling to a CSS `@import`) and when it's going to be dynamic (actually loading Sass from another file). Currently, there are four conditions that cause an import to be treated as static in Sass:
- It uses `url()`.
- It begins with `"http://"`.
- It ends with `".css"`.
- It specifies a media query (e.g. `@import "screen.css" screen`).

If any of these are true for an `@import`, it will be static. As we only want to allow interpolation of static imports, we should only parse interpolation for these cases, and no others. However, it's not possible to know whether an `@import` ends with `.css` or has a media query until after the import string has been parsed, which will require parsing the interpolation, if there is any.

Thus, I'm restricting interpolation to `@import`s using `url()`. This will be done via the usual deprecation in the stable releases, with appropriate warnings and upgrade instructions. `@import`s with interpolation in strings will no longer work in the next release, Sass 3.2.

**Comment by cdCorey** [comment]
"As we only want to allow interpolation of static imports [...]"

Why is this? Seems to me that we should be able to use variables for Sass includes as well (e.g., for paths).

**Comment by BenMorel** [comment]
It would definitely be useful to be able to use:

```
@import url(#{$foundation-dir}/normalize);
@import url(#{$foundation-dir}/foundation/components/grid);
```

**Comment by erotte** [comment]
:+1:

**Comment by j-walker23** [comment]
cool +1!

**Comment by treejanitor** [comment]
:pray: definitely would be nice...

**Comment by michaeljpowell** [comment]
+1

**Comment by fingermark** [comment]
Was really surprised to learn this didn't work and the issue was closed.

**Comment by stephnr** [comment]
@BenMorel  :+1:  definitely a better idea to help manage code

**Comment by dwayne-roberts** [comment]
+1

**Comment by bradwestfall** [comment]
+1

**Comment by shock** [comment]
+1

**Comment by nex3** [comment]
The title of this issue is "Support interpolation in CSS-based imports". This is not the place to discuss interpolation in other imports. That's #739.

**Comment by Jakobud** [comment]
Any status on this? Why was this closed?

**Comment by nex3** [comment]
It was closed because the feature landed.

**Comment by Jakobud** [comment]
Oh in what version is this available?

**Comment by nex3** [comment]
3.1.0 and forward.

**Comment by alejandrolechuga** [comment]
+1
