### ISSUE TITLE
Access to property values without the use of variables

### ISSUE THREAD

**Issue by maikeldaloo** [sass/sass#521]
Hello,

I'd love to see something like the following implemented in SASS/SCSS.

```
#container {
    position: absolute;
    left: 50%;
    top: 10%;
    width: 500px;
    margin-left: @width / -2; // -250
}
```

As you see on the last line, we get the value of 'width' and do some calculations to it.

**Comment by nathggns** [comment]
The only implementation possible would be an extremely limited one.

## 

Nathaniel Higgins
http://nath.is

-----Original Message-----

**Comment by nex3** [comment]
I don't think this would provide much value above and beyond using explicitly-declared variables. Also, it might add to confusion for users who would want to use it access the computed value of the variable, whereas Sass could only ever provide the value that's declared in the CSS file.

**Comment by tomsseisums** [comment]
I also approve of such functionality.

I'd find it more than useful in scenarios like:

``` scss
.row
{
    padding: 0 10px;

    &.input
    {
        padding-left: @padding-left + 65px;
    }
}
```

Because, defining variables for a shorthand property is a bit of an overkill.

It's actually the same like *_Block property access_ in Stylus, except, SASS could also resolve from shorthand definition.

---

I'd say, that this is like relative positioning (this proposition) versus absolute positioning (variables). Both can do the same, but the relativity is easier to work with in some scenarios. I think people would use this a lot if such functionality did exist.

**Comment by ghost** [comment]
For what it's worth, I'd find a lot of use for this.

**Comment by tomsseisums** [comment]
I bet there are even more people around this community who would only benefit from this.

**Comment by chriseppstein** [comment]
This is a good feature for CSS to add. Sass isn't going to add it because we can't take the document inheritance into account and so it will confuse more people than it helps.

**Comment by Grawl** [comment]
I want it too.

**Comment by dan-gamble** [comment]
This would be alot cleaner than having to use alot of nested `$padding-top` variables for example on different classes.

**Comment by dbox** [comment]
+1

**Comment by artemjackson** [comment]
+1

**Comment by KyNorthstar** [comment]
Is there any chance this could be resurrected?

**Comment by nex3** [comment]
No, the original reason for closing it still stands.

**Comment by KyNorthstar** [comment]
Awww... I had this same idea way back before I knew Sass or Less even existed. I'd started drafting [an idea for a CSS preprocessor that I called MARS](https://bluehuskystudios.github.io/MARS/), and I included such a reference with a `prop()` function, like this:

```css
button,
input[type=("button","submit","reset")] {
	padding: 0.5em 1em;
	width: ?(100% - prop(padding-left) - prop(padding-right));
}
```

Now that I'm all-in with Sass I had hopes it might gain such a feature ☺

**Comment by nex3** [comment]
@BenLeggiero Your example illustrates exactly why we don't want to support this functionality. You write a property named `padding`, but you access it as `padding-left`. That's a totally reasonable thing to try to do in a system that provides access to existing properties! But in order to support it, Sass needs to have deep knowledge of every single shorthand property, which adds a huge amount of complexity and makes it much easier for the language to fall out-of-sync with the CSS spec. That doesn't end happily for either the devs or the users.

**Comment by Grawl** [comment]
We will not be sad if prop(padding-left) will not get value of shorthand padding

**Comment by nex3** [comment]
People who've read and internalized my explanation may understand it, but that's not going to be the vast majority of users. Most people will try to use it like they expect CSS to work, and it won't work for that, and that's just a crummy experience all around.

**Comment by KyNorthstar** [comment]
I am not proposing that you parse and destruct any shorthand properties at all. I was just pointing out that I had a similar idea years ago and giving a snippet from Past Ben's mind. 

That said, it would be trivial to support all CSS1 and even CSS2 shorthands for starters. I believe that over 99.99% of uses of property-references would be okay with that.

**Comment by nex3** [comment]
A huge part of what makes Sass a pleasant language to work with day-to-day is that it avoids features that work *sometimes but not all the time*. Even if you think you'll personally understand the boundary between when they work and when they don't, and that you'll always stay within the golden path, people will run into it and it will erode their confidence in the language as a whole. So we don't add features that have those hidden pitfalls.

**Comment by Grawl** [comment]
You're right @nex3. But how this feature is done in Stylus? Property lookup is a major feature for me when I use Stylus.

The same question is for postcss-property-lookup.

**Comment by nex3** [comment]
I imagine those features have the sorts of pitfalls I'm trying to avoid.

**Comment by Grawl** [comment]
I understand. It's a large feature but a lot of people want it.

**Comment by mahnouel** [comment]
Another use case is when using `@extend` - For example I might want to get the `font-size` set in the context via the extension, but can't do so.

**Comment by nex3** [comment]
@mahnouel That's a great example of something that you might expect to work if this feature existed, but that's fundamentally impossible. `@extend`s are resolved *after* SassScript expressions—this is necessary, because expressions can be used to generate `@extend`s. So there's no conceivable way to have the way `@extend`s are resolved affect the values in expressions.

**Comment by Grawl** [comment]
it would be strange if I can get properties from `@extend`

**Comment by donut** [comment]
@nex3, can you give an example of when this might have unexpected behavior? I've used this all the time with Stylus and never ran into behavior I didn't expect.

**Comment by nex3** [comment]
@donut There are several examples already in this comment thread.

**Comment by aradalvand** [comment]
This would've been really useful. If I'm not mistaken I think Stylus had this feature.

**Comment by kenblu24** [comment]
**Quick thread summary** for those coming from Google:

No, you cannot reference the value of a property in Sass/SCSS, not even a property from the same style rule. This is to prevent the confusion of it appearing like you're referencing the computed value of a property ([which is not possible with CSS at all](https://stackoverflow.com/questions/9394514/how-to-get-the-value-of-a-css-property-in-sass)).

If this is a feature you absolutely cannot live without and are able to switch preprocessors, [Stylus ](https://stylus-lang.com/docs/variables.html#property-lookup)and [Less ](https://lesscss.org/features/#variables-feature-properties-as-variables-new-)have the ability to reference properties as variables. Both support "bubbling" to access the nearest matching property in the rule hierarchy. Neither seems to be able to reference specific values from shorthand (or at least I can't find it in their documentation).
