### ISSUE TITLE
[New Feature] Get Property Value

### ISSUE THREAD

**Issue by felquis** [sass/sass#559]
Hi Folks, I searched here for something like my idea and found nothing related, so here's my suggestion.

I wish I could have access to the value of other properties already defined selectors, as if they were variables.

Something like:

```
.my-selector {
    width: 700px;
    height: 30px;
}

.other-selector {
    height: .my-selector{height};
}
```

After compiling

```
.my-selector {
    width: 700px;
    height: 30px;
}

.other-selector {
    height: 30px
}
```

The. "My-selector" is the selector I want to get the value of some property, and what is inside {} is the property that the value I want.

This example is something that I imagine being useful in my day-to-day using Sass.

Of course it is subject to adjustments.

---

I do not know if today there is something that allows me to do that, if present, indicate me please.

Falow

**Comment by PavelDemyanenko** [comment]
Been searching for something like this, wanted to store data-attr in variable, i guess there is no way, except for js

**Comment by gavinmcfarland** [comment]
When this is a reality the whole web will explode. In a good way :smile:

**Comment by nex3** [comment]
This has come up many times before. The fundamental problem is that the value of a property that Sass understands isn't always the same as the value the browser understands. The browser is able to resolve the cascade and see which selectors apply to which real elements, but Sass can't do that; it only has the stylesheet text to work with. So you have problematic cases like this:

``` scss
.my-selector {
  height: 30px;
}

p .my-selector {
  height: 20px;
}

.other-selector {
  height: .my-selector{height}
}
```

What does that mean? How do you resolve it? It's not clear. There are many more such examples of confusing cases that come up because of the distinction between the textual values of properties and the cascade-based values. We've chosen to steer clear of this conceptual minefield and just suggest that people use variables, which have a very clear explicit meaning, instead.
