### ISSUE TITLE
[Idea] SASS Classes

### ISSUE THREAD

**Issue by ghost** [sass/sass#565]
I suggest non standart SASS (SASS++) or Classy SASS.

```
@class Sass {
  .constuctor($a: 5){
    $$a: a; //object variable
  }
  $b: 5px; //prototype
  .f(){
     color: $c;
  }
  .l(){
     left: $$a + $$b;
  }
}

$class: @new Sass(6px);

#test {
  $class.f(rgb(0, 0, 0)); //Call class function
}

#left-hand {
  $class.l();
}
```

In this example SCSS syntax.

**Comment by Anahkiasen** [comment]
I know this will be closed as the idea was thrown around several times but still. **+1**

**Comment by Snugug** [comment]
What would the output look like for this? How is this better than an intelligent mixin or a function?

**Comment by ghost** [comment]
Mixin are just functions. Class are javascript-like objects.

**Comment by Snugug** [comment]
I guess what I'm asking is what's the problem you're trying to solve that can't be solved via a mixin? Why is it more beneficial to have objects that contain "just functions" than call those functions directly? In an OO environment where you want to constrain use and keep prototype to refer to later, the advantage is clear, but for writing CSS? Do you really think we need to be prototyping our classes just so it feels more like JavaScript? The two languages function _very_ differently, with JS being runtime and CSS being compiled, I don't understand the advantage gained in code reusability or understandability. In fact, I see it as confusing the subject to _many_ new to Sass.

**Comment by ghost** [comment]
But if project very big? :)
If need very long CSS code?

**Comment by Snugug** [comment]
I deal in huge projects and seem to get along absolutely fine w/mixins, functions, and silent extendables. Because CSS is parsed procedurally, and currently cannot be parsed in any other way by the browsers, I truly feel the best mental model to be in when writing CSS is a procedural one. An OO mindset is far enough away from the parse method of CSS that it's going to become harder to glance at your code and understand what it does for anyone not familiar with the concepts of OO, and that's more likely than not the majority of Sass users.

**Comment by Anahkiasen** [comment]
One area where we at least need some kind of namespace/group/class-like function is to do per example the following :

``` sass
@class Gradient
  @mixin vertical(...)
    [...]

  @mixin horizontal(...)
    [...]

background
  +Gradient.horizontal(...)
```

I think this would be beneficial in a lot of way and would to less conflicts between mixins. If you use libraries like Compass or Bootstrap SASS you sometimes want to name mixins but can't because it would override the librarie's mixins.

**Comment by Snugug** [comment]
I'd argue that's a bad example as well. How is having a namespace for that better than naming your mixin `gradient-vertical` and `gradient-horizontal`? Is the saved ~3 characters the first time you write out your mixin really worth introducing an entire new mental model to Sass?

**Comment by Anahkiasen** [comment]
Yes, because of the modularity it brings. I made my example with two little mixins, now think about Compass, Compass Recipes; think about the dozens and dozens of libraries and the mixins they contain with sometimes the same names.

If you want to namespace them you have to manually edit each of the mixins's names and all of the places they're referenced ?
Whereas with a class you just change its name and it cascades to all the mixins contained. And you can then call `Compass.clearfix` or `Bootstrap.clearfix` or `Recipes.clearfix` all in the same file and without every having to modify anything in the vendor files.

**Comment by Snugug** [comment]
Well then the issue you should be looking at is [@import files as modules](https://github.com/nex3/sass/issues/353) which aims to namespace `@import` partials, namespacing partials and using their innards the dot syntax, but doing so without adding the mental burden of Classes and full Object Orientation.

**Comment by Anahkiasen** [comment]
No of course I was just suggesting `@class` but anything accomplishing the same job would be a hugh step forward.

**Comment by nex3** [comment]
I agree with @Snugug that this doesn't seem like it adds nearly enough utility on top of mixins. Object-orientation adds a colossal amount of conceptual overhead, so it would need to justify itself in terms of commensurate increase in ease or power of CSS generation, which I don't think this does.

@Anahkiasen We're thinking about solutions to the namespacing problem.
