### ISSUE TITLE
@extend inside +at-breakpoint even if .class is inside give @extending an outer selector from within @media is deprecated.

### ISSUE THREAD

**Issue by piermariacosina** [sass/sass#589]
```
+at-breakpoint($break)
    .wide
        +span-columns(13, $break)


    footer
        @extend .wide !optional

@media (min-width: 58.75em) {
  /* line 2, ../../app/stylesheets/partials/_960grid.sass */
  .wide, footer {
    width: 80.85106%;
    float: left;
    margin-right: 2.12766%; }
```

Everything is working properly but the terminal is full of warning and deprecation
To me looks like that the .class is inside the @media is it a bug?

**Comment by nex3** [comment]
It's very difficult to tell what's going on without the full source of your stylesheet. You're listing a lot of undefined mixins.

**Comment by Anahkiasen** [comment]
`+at-breakpoint` is a [Susy](http://susy.oddbird.net/) mixin, it nests the `@content` in a media query so it makes sense that the `@extend` would here throw a warning.

**Comment by piermariacosina** [comment]
Sorry, the project is quite big, give me some days and I will try to reproduce the error in a smaller environment :)

**Comment by robwierzbowski** [comment]
You're probably getting the deprecation warning because you've defined .wide outside of your media query as well. For example, 

**Terminal warning, no output**

```
%red {
  color:red;
}

.extend-test {
  @include breakpoint(500px) {
    @extend %red;
  }
}
```

**No warning, good output**

```
%red {
  color:red;
}

.extend-test {
  @include breakpoint(500px) {
    %green { // only defined in the @media directive.
      color:green;
    }

    @extend %green;
  }
}
```

**Terminal warning, output is _only_ @media... { .extend-test { color:darkred; } }**

```
%red {
  color:red;
  background: lightred;
}

.extend-test {
  @include breakpoint(500px) {
    %red {
       color:darkred;
    }
    @extend %red;
  }
}
```

The last warning is especially important if you're extending a class, not just a placeholder, since it's possible to declare a class multiple times in a stylesheet, making unexpected extend behavior more likely. 

All warnings seems correct, so I don't think there's a bug.

**Comment by nex3** [comment]
Closing due to unresponsiveness.
