### ISSUE TITLE
lighten doesn't work as expected ?

### ISSUE THREAD

**Issue by MoOx** [sass/sass#598]
I've an issue when I was working on a less to stylus conversion (yes it seems it's not related to Sass right ?). My problem was the lighten() function does not return the same thing for each pre processor. So I try lighten() of Sass just to see who is right. And I get:
- less lighten(#E0E3E4, 5%) => #eeeff0
- stylus lighten(#E0E3E4, 5%) => #e2e4e5
- sass lighten(#E0E3E4, 5%) => #eeeff0

So I was thinking stylus was wrong. But somebody post [this comment](https://github.com/LearnBoost/stylus/issues/328#issuecomment-11499300)

> the stylus behavior is correct, the other two are wrong. I don't believe stylus should mimic incorrect behavior. Any graphics program (e.g. photoshop) will come up with #E2E4E5 in the example you gave.
> 
> The reason for this is simple -- the way less / sass do it, lighten just "adds white", the way stylus now does it, it "lightens the specific color". With less/sass, lighten( #808080, 50% ) yields pure white, which is crazy.

So what do you think guys ?

**Comment by Snugug** [comment]
They are actually two different processes. In Sass, lighten/darken work on the HSL color spectrum's L property. Mixing with white/black is more commonly referred to as tint/shade, but is not an actual root color manipulation. If you'd like to do that, I'd suggest using the mix function.

`mix(#fff, #e0e3e4, 5%)`

Be warned that this is a hex mix and as such, works fine for mixing with white/black, but if you we're to mix yellow and blue you get a grey instead of green. You can read about that issue in the [FastCompany Article about Paper's Color Mixer](http://m.fastcompany.com/?m=fastcompany/node/3002676&url=http://www.fastcompany.com/3002676/magical-tech-behind-paper-ipads-color-mixing-perfection)

**Comment by nex3** [comment]
I think both ways of modifying a color's properties make sense in different circumstances. Sometimes you want a way to modify the properties by absolute increments; sometimes you want to scale it relatively. Sass supports both, via the [adjust-color](http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html#adjust_color-instance_method) (absolute) and [scale-color](http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html#scale_color-instance_method) (relative) methods. These days those are the best ways of manipulating colors in Sass if you want explicit control over how the adjustments are made. For example:

``` scss
scale-color(#E0E3E4, $lightness: 5%) //=> #e2e4e5
```

`lighten()` and friends work the way they do for historical reasons as much as anything.

**Comment by zhe** [comment]
Useful information. :+1:

**Comment by ygoe** [comment]
I've redefined mix, lighten and darken to work more like I'd expect it and know it from other programming environments:

```
@function strip-unit($number)
{
	@if type-of($number) == 'number' and not unitless($number)
	{
		@return $number / ($number * 0 + 1);
	}
	@return $number;
}
@function mix($color1, $color2, $amount)
{
	$amount: strip-unit($amount) / 100;
	@return rgb(
		red($color1) * (1 - $amount) + red($color2) * $amount,
		green($color1) * (1 - $amount) + green($color2) * $amount,
		blue($color1) * (1 - $amount) + blue($color2) * $amount);
}
@function lighten($color, $amount)
{
	@return mix($color, #ffffff, $amount);
}
@function darken($color, $amount)
{
	@return mix($color, #000000, $amount);
}
```
