### ISSUE TITLE
SASS `@import` relative path root not same as CSS `@import`

### ISSUE THREAD

**Issue by mxcl** [sass/sass#652]
The SASS `@import` directive calculates relative paths based on the working-directory of the shell it is invoked in.

But the CSS `@import` calculates relative paths based on the directory the CSS files resides in.

I can work around this but now I have a bug lurking in the shadows: if I should ever accidentally or deliberately change the working directory of my web server all my SASS files will stop compiling.

``` sh
$ sass --version
Sass 3.2.5 (Media Mark)
```

**Comment by nex3** [comment]
Sass `@import`s have a configurable set of load paths that are used when resolving relative imports. By default, these paths include both the directory containing the file in question and the current working directory. The file's directory takes precedence, so if you're worried about breaking your imports by changing your working directory, you can import relative to the files themselves.

**Comment by mxcl** [comment]
The bug was that SASS imports are not handled the same way as CSS imports. But I can see you don't care. Thanks.

**Comment by chriseppstein** [comment]
@mxcl That's not fair. @nex3 explained the behavior and believing it to be not a problem, he closed the issue. He didn't misunderstand it. The working directory is a good default for most users -- especially for local development, but as a production concern it could be important to invoke sass compilation with the `-I` option to specify the root of your project's sass directory so that files will always be found there even if your working directory changes.

Please note that users of compass are unaffected by this because it has a project directory context and the full sass directory is always be placed on the load path.

**Comment by mxcl** [comment]
Yeah I apologize, I was being pissy.

**Comment by chriseppstein** [comment]
Note: The current working directory being automatically placed on the Sass load path is deprecated in 3.3.
