### ISSUE TITLE
Dynamic imports?

### ISSUE THREAD

**Issue by NickHeiner** [sass/sass#658]
For my current project, I need to be able to do dynamic imports as described here:

http://stackoverflow.com/questions/14782954/dynamic-imports-for-scss

Is this possible? If not, are you amenable to a PR implementing it?

**Comment by nex3** [comment]
This is purposefully disallowed. Sass needs to be able to efficiently walk the import tree of a set of stylesheets in order to figure out the dependencies between them so it can detect which stylesheets changing need to trigger updates. This efficiency is impossible if determining imports requires Sass to compile the entire stylesheet.

**Comment by chriseppstein** [comment]
See #739
