### ISSUE TITLE
Silent classes, @extend and override

### ISSUE THREAD

**Issue by andrewckor** [sass/sass#660]
By playing around with my friend @harby testing the silent classes, we found a strange compilation issue.

If you have the following **silent class**:

```
%cool {
    font-size: 20px;
    color: red;
}
```

And then you want to **extend** this class to a btn for example but using a different colour:

```
.btn {
    @extend %cool;
    color: yellow;
}
```

The final result will be:

```
.btn {
    font-size: 20px;
    color: red;
}

.btn {
    color: yellow;
}
```

This compiles more code than the expected code:

```
.btn {
    font-size: 20px;
    color: yellow;
}
```

Have anyone notice the same issue? Looks really interesting :)

**Comment by Anahkiasen** [comment]
This has been discussed a **lot** of times and is perfectly normal behavior. If other class extend the `.btn` class they'll join the first selector, and Sass can't by itself decide what properties are to be compressed or not. But yeah mostly the first reason : extending a class just means joining its selector, otherwise there's no gain to silent selectors as all the properties are duplicated.

**Comment by andrewckor** [comment]
Didn't know how many times has been discussed. But yes you are right. But on this case is a bit off. :P
