### ISSUE TITLE
Creating a comma-separated list of space-separated lists — erroneus append() behavior

### ISSUE THREAD

**Issue by lolmaus** [sass/sass#706]
I'm trying to create a comma-separated list of space-separated lists with `append()`.

I expect to get the following meta-list: `( (1 2), (3 4) )`.

The problem is that `append()` breaks the first sub-list, producing `( 1, 2, (3 4) )`.

``` sass
$meta-list: append( ((1 2)), (3 4), comma)
@warn $meta-list
// WARNING: 1, 2, 3 4

@warn nth($meta-list, 1)
// WARNING: 1

// Just to make sure:
@warn @warn nth( ( (1 2), (3 4) ), 1)
//WARNING: 1 2
```

**Comment by Anahkiasen** [comment]
> Creating a comma-separated list of space-separated lists

Yo dawg I heard you liked lists so we put a list in your list so can loop while you loop.

**Comment by robwierzbowski** [comment]
Nesting parenthesis don't re-encapsulate lists, but that's probably a good thing or else we'd be writing a lot of code checking and unencapsulating them. I don't want `(1 2)` to be length == 1.

This definitely seems like a bug though — no matter what you do with a single dimensional list, even if it's explicitly space separated, `append()` with a comma separator turns it into a comma separated list.

``` scss
$space-list: join(1, 2, space);
@debug append($space-list, (3 4), comma); // 1, 2, 3 4
```

If you want to work around this right now you can turn `$space-list` into a multidimensional comma list with an empty value.

``` scss
$join: join(1, 2, 'space');
$join: append((), $join, comma);
$app: append($join, (3 4), comma);

@debug $join; // 1 2
@debug length($join); // 1
@debug $app; // 1 2, 3 4
@debug length($app); // 2
```

**Comment by nex3** [comment]
@lolmaus as @robwierzbowski pointed out, adding an extra set of parentheses doesn't create an extra level of list nesting. Parentheses aren't list delimiters; they just group order of operations. `($a)` is always the same as `$a`.

> This definitely seems like a bug though — no matter what you do with a single dimensional list, even if it's explicitly space separated, `append()` with a comma separator turns it into a comma separated list.
> 
> ``` scss
> $space-list: join(1, 2, space);
> @debug append($space-list, (3 4), comma); // 1, 2, 3 4
> ```

This is the expected behavior. From the [documentation of `append`](http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html#append-instance_method):

> If [the `$separator` argument] is `comma` or `space`, that is always the separator; if [it] is `auto` (the default), the separator is the same as that used by the list.

**Comment by robwierzbowski** [comment]
@nex3 You're right, this is the documented behavior. I don't mind the way things work, but in general I think people are surprised when append transforms existing list separators.

Correct me if I'm wrong, but I believe parenthesis can be list delimiters.

``` scss
$paren-list: (1 2) (3 4 5);
@debug length($paren-list); // 2
```

**Comment by nex3** [comment]
> @nex3 You're right, this is the documented behavior. I don't mind the way things work, but in general I think people are surprised when append transforms existing list separators.

The returned list has to have a separator. If you want it to keep the old separator, don't pass an argument to `$separator`. If you're passing `$separator`, I don't understand how it's unexpected for the returned list to have that separator. What result would you expect for  `append(1 2, 3, $separator: comma)` other than `1, 2, 3`?

> Correct me if I'm wrong, but I believe parenthesis can be list delimiters.
> 
> ``` scss
> $paren-list: (1 2) (3 4 5);
> @debug length($paren-list); // 2
> ```

That's just using them for expression grouping. You're grouping the expressions `1 2` and `3 4 5` so that the inner list-separation operators are performed before the outer list-separation operator. It's the same principle behind `(1 + 2) * (3 + 4 + 5)`.

**Comment by robwierzbowski** [comment]
Expression grouping: good to know. 

When I first started manipulating lists in Sass I expected the same thing as @lolmaus. A space-list appended to a space-list with a comma would equal a comma-list of space-lists.

``` scss
@debug append(1 2, 3 4, comma); // Often expected: 1 2, 3 4
```

The confusion occurs when people think `$separator` is the separator for this append only, not the separator for the entire resulting list. Creating multidimensional sass lists by switching from comma separators to space separators puts you in that mindset. You assume that append is working more like a serial string constructor: "append with a comma", "append with a space", "append with whatever separator the list is using".

To re-iterate, I'm fine with the current behavior.

**Comment by nex3** [comment]
In that case, `append($a, $b, comma)` would be identical to just writing `$a, $b`.
