### ISSUE TITLE
Why #aabbcc instead of #abc?

### ISSUE THREAD

**Issue by bradcater** [sass/sass#733]
I find long form (6-digit) hex codes in my generated CSS when the short form (3-digit) hex codes are possible even if I use a 3-digit code in a .sass file. Is there a reason to prefer 6 digits to 3 digits?

**Comment by Symb** [comment]
The problem with the shorthand version (3-digit) is that older browsers might not be able to interpret as a valid value. This would be more apparent in cases where you'd write your styles inline using the style tag. Websafe color values are marked with the six-digit variant.

**Comment by cimmanon** [comment]
@Symb Which browsers have problems with 3-digit hex values?  I doubt there are any, but if there are, you'd have to go all the way back to the earliest browsers that support CSS (Netscape 4, IE 3 or 4, Opera 4 or 5) to find one.

@bradcater Sass chooses the color format based on the compression setting and makes all colors the same format when possible, regardless of how you originally wrote them.  If you want the 3-digit format, use a more compact setting.

**Comment by Symb** [comment]
Well yes, you'd have to go back a whole lot. As i sayd, the problem might have occured when the shorthand was used in inline styles (that no one should use anyway). The shorthand is described in the CSS specification not HTML, that's why it could cause errors. Modern browsers should'nt have problems with this. Anyway i like your answer, i guess i went a bit off-topic with this.

**Comment by nex3** [comment]
@cimmanon is correct; the output format for colors doesn't take into account their input format. #363 is tracking this.
