### ISSUE TITLE
Deprecation warnings for working code

### ISSUE THREAD

**Issue by mgerring** [sass/sass#776]
Hi fellas. I developed a workaround for SCSS's crazy nonsense about not allowing `@extend` within media queries. It works really well. So it turns out,

`It can only work once @extend is supported natively in the browser.`

is a lie.

But one of my placeholders references an outer selector — the HTML element, for feature detection — and now I'm getting "deprecation warnings".

The fact is, this code works fine, and I don't understand why your compiler, which handles this very well, is now telling me it won't in the future, just because you think browsers ought to support `@extend`.

Please stop. Even if browsers did support `@extend`, they won't do so reliably for years, and in the meantime I would like my code to keep working.

Thanks!

**Comment by chriseppstein** [comment]
The definition of `A { @extend B; }` is "Style elements matching selector A as if they also matched selectors applying to the simple selector B." When you put an `@extend` statement in a media query (or any runtime conditional like `@supports`, `@page`, etc) then you are asking Sass to only apply the inheritance when the condition is true. But Sass cannot know if that condition is true or false and if we apply the inheritance globally across the stylesheet we will simply break many people's websites and violate their unrealistic expectations of what Sass is capable of doing. We know this because before we introduced this many people came to us asking why Sass was broken.

You don't post any code, so I can't really help you find a solution to your problem in a way that doesn't use `@extend` in a nonsensical manner. And, frankly, given the tone of this post, I'm not inclined to want to help you. So I invite you to read through the several issues in the issue tracker that are both open and closed and you will see much advice on how to address your problem and you will also see that we are working on ways to make this less of an issue.

**Comment by mgerring** [comment]
The thing is, SASS can, and does, know if it's matching a media query. Here's what I came up with earlier today:

```
@mixin responsive-placeholder($name) {
  %#{$name} {
    @content;
  }

  %#{$name}-response {
    @include media-breakpoint ('tablet-up')     { @content; }

    @include media-breakpoint ('desktop-up')    { @content; }

    @include media-breakpoint ('widescreen-up') { @content; }

    @include media-breakpoint ('desktop-down')  { @content; }

    @include media-breakpoint ('tablet-down')   { @content; }

    @include media-breakpoint ('phone-down')    { @content; }
  }
}
```

The `media-breakpoint` mixin is a shortcut allowing my team to use named breakpoints, I assume you're familiar with this pattern.

When I do this:

```
.my_thing {
  @include media-breakpoint('tablet-up') {
    @extend %foo-response;
  }
}
```

SASS does the right thing, e.g.

```
@media only screen and (min-width : 48em) {
  .my_thing {
    //the rules from %foo;
  }
}
```

Similarly, if I have this:

```
@include responsive-placeholder('off-canvas') {
  display:none;
  html.csstransforms:not(.csstransforms3d) & {
    display:block;
    -webkit-transform: translate(-100%,0);
    -moz-transform: translate(-100%,0);
    -ms-transform: translate(-100%,0);
    -o-transform: translate(-100%,0);
    transform: translate(-100%,0);
  }
  html.csstransitions.csstransforms3d & {
    display:block;
    -webkit-transform: translate3d(-100%,0,0);
    -moz-transform: translate3d(-100%,0,0);
    -ms-transform: translate3d(-100%,0,0);
    -o-transform: translate3d(-100%,0,0);
    transform: translate3d(-100%,0,0);
  }
}
```

And I do this:

```
.my_thing {
  @include media-breakpoint('tablet-up') {
    @extend %off-canvas-response;
  }
}
```

SASS does the right thing again, but throws a compiler error to let me know that it won't in the future. It's not clear from your post why this way of using 'extends' is 'nonsensical'.

**Comment by chriseppstein** [comment]
Please seek support on the mailing list.
