### ISSUE TITLE
Add support for Plugins to register visitors

### ISSUE THREAD

**Issue by tav** [sass/sass#78]
It would be great if the `Sass::Plugin` API could be extended so that one could register custom visitors that would also be called during the various compilation phases of sass.

For example, I recently added support for doing automatic transformation of the CSS properties and values to their right-to-left equivalents. This could have been implemented as a plugin if I had been able to modify the `node.resolved_name` and `node.resolved_value` before `visit_prop()` got called.

**Comment by nex3** [comment]
I can't say I'm entirely comfortable with the idea of making it easier for people to violate the invariant that plain CSS is compiled to plain CSS. Nor am I fond of the idea of multiple subtly-different dialects of Sass, which it seems like this would encourage.

That said, due to the need to explicitly enable these plugins, I'm not entirely opposed. However, I want to hear more use-cases than doing internationalization transformations on certain properties.
