### ISSUE TITLE
Sass ignores linebreaks of combined selectors when referencing parent selector

### ISSUE THREAD

**Issue by djesse** [sass/sass#800]
Typically Sass respects linebreaks between combined selectors. But when referencing parent selector, they will be ignored. 

``` scss
a {
  &:focus,
  &:hover,
  &:active {
    ...
  }
}
```

will be (even in expanded mode) compiled to:

``` css
a:focus, a:hover, a:active {
  ....
}
```

instead of:

``` css
a:focus,
a:hover,
a:active {
  ....
}
```

Please fix this problem. Sadly, these so output configuration to force this output style.

**Comment by joyeusenoelle** [comment]
This issue should be closed per the previous commit.

**Comment by nex3** [comment]
@joyeusenoelle That commit was never merged; it looks like #2157 was abandoned.

**Comment by nex3** [comment]
I'm moving this issue to [the new Ruby Sass repository](https://github.com/sass/ruby-sass) because it's specific to Ruby Sass's implementation. Once it's there, I'm going to close it as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.

**Comment by boompsy** [comment]
I'm still seeing this behavior even with Dart Sass -- please see https://www.sassmeister.com/gist/8b4e2c8a8ed5f049f9dbd5300b44bdac

It seems specific to pseudo-elements/pseudo-classes.
Also seems related to https://github.com/sass/sass/issues/1976
