### ISSUE TITLE
Add command line switch to print dependencies

### ISSUE THREAD

**Issue by Boldewyn** [sass/sass#809]
There are situations, where one is interested only in dependencies for a specific Sass file, e.g., in Makefiles. It would be great, if Sass could provide such a list. For example:

```
// file foo.scss
@import "bar";

// file _bar.scss
@import "baz";

// file _baz.scss
// ...some Sass...
```

Then imagine this call and response:

```
$ sass --print-dependencies foo.scss
_bar.scss
_baz.scss
```

It would be great to have for auto-generating dependency files for your build tool of choice, e.g. GNU make:

```
$ echo "foo.scss: $(sass --print-dependencies foo.scss)" > foo.scss.mk
```

**Comment by chriseppstein** [comment]
I like this. In #739, I'm proposing that we change sass so that the dependencies are dynamically discovered upon the first compile and then kept up to date. I'm pretty sure this strategy will still work because even if there's no currently known dependencies, the css file would still be considered out of date because it doesn't exist. This assumes that you do not check in your css files (or if you do, you'd also need to check in the dependency data)

**Comment by nex3** [comment]
I don't think this is something that should be part of the `sass` executable. The option space there is very precious, and this flag is going to be useless to the vast majority of our users. In addition, it's easy to write a simple Ruby script that does this.

**Comment by chriseppstein** [comment]
> The option space there is very precious

How much does option space cost? :stuck_out_tongue_closed_eyes:

> this flag is going to be useless to the vast majority of our users

how many users need `--check`? This would be easy to write in a simple ruby script.

The fact is, people simply ignore things they don't understand. I bet I could poll 100 people who have read the output of `-h` and only a few of them would know that `--check` exists.

**Comment by nex3** [comment]
> How much does option space cost? :stuck_out_tongue_closed_eyes:

It's marginal, but it compounds over each user and over each additional option that's added. It doesn't make sense to add every option that would be useful to anyone.

> how many users need `--check`? This would be easy to write in a simple ruby script.

I'm down with deprecating `--check`.

**Comment by chriseppstein** [comment]
The sass command line tool is a tool for compiling sass files. As a unix-style utility it exists to integrate with users _and_ the tools they use. It's why we approved allowing an option to emit errors in JSON format. I find your stance on this subject inconsistent. Make is an important build tool.

**Comment by nex3** [comment]
Printing dependencies is not an aspect of compiling Sass files. There exists a tool for inspecting the contents of Sass files; it's the Sass API. You can even make a fair go at invoking it from the command line:

```
ruby -rsass -e 'Sass::Engine.for_file(ARGV.first, {}).to_tree.children.each {|n| puts n.imported_filename if n.is_a?(Sass::Tree::ImportNode)}'
```

Emitting the same output we normally do in a machine-readable format is different. The issue isn't that `sass` shouldn't integrate with other tools; it's that listing dependencies is outside its purview. A secondary issue is that this is a narrower use-case than warrants the cost of adding a new option.

**Comment by chriseppstein** [comment]
> Printing dependencies is not an aspect of compiling Sass files. 

As demonstrated, it is an aspect of integrating with a build tool for compiling sass files. `gcc` provides this ability via the `-M` command line option. From the man page for gcc, the `-M` option: "Instead of outputting the result of preprocessing, output a rule suitable for make describing the dependencies of the main source file."

> Emitting the same output we normally do in a machine-readable format is different

Newline separated lists is a very machine readable format designed for use with numerous unix utilities. For example: `sass --dependencies foo.scss | xargs vim` and now I've opened every dependency of my file in my text editor. It also works great with grep.

> You can even make a fair go at invoking it from the command line 

That's not a fair go at it. It doesn't take import paths into account. It doesn't take relative imports into account. Doing these things correctly is non-trivial.

> The issue isn't that sass shouldn't integrate with other tools; it's that listing dependencies is outside its purview.

The claim is that listing dependencies is a form of tool integration. A code example was provided by @codifferous  showing this to be true. Simply stating that the purview of sass is one form of tool integration but not another is not founded in a rational basis. You have made a value judgement that one tool is more important to integrate with than another and that the first one is worth working on and the second one is not.

> this is a narrower use-case than warrants the cost of adding a new option.

This is really the core of your argument. You simply don't think it's worth supporting `make` out of the box. I disagree. Make continues to be an important build tool and I don't find the cost of having this option in the `-h` output onerous. But, to be fair, GCC doesn't list the `-M` option in the `--help` output, it only mentions it in the man page.

>  It doesn't make sense to add every option that would be useful to anyone.

Every option should be evaluated independently. I've certainly rejected many of them. No one has claimed that every option should be added, and using a slippery-slope argument is not productive.

**Comment by Boldewyn** [comment]
As a matter of fact, I know and use `--check` (in several of my Makefiles). :smile:

Unfortunately I don't know Ruby to do this myself, otherwise I would've given it a shot in creating a script. However, I figured that this makes sense as part of the Sass tool. To paraphrase @chriseppstein from above, the cli command is an interface from the Sass world to other Unix tools in the user's shell. As such I think, that

```
$ sass --dependencies foo.scss
```

is more natural than, e.g., a new command

```
$ sass-dependencies foo.scss
```

**Comment by ichernev** [comment]
+1

I guess for the time being the "one liner" can be used instead, but there is no doubt that a `--dependencies` option would look better.

**Comment by monsanto** [comment]
This would be very useful. +1

**Comment by subhaze** [comment]
I was just searching for this option to use in a Makefile. I've used lessc's -M flag quite often in build processes and was hoping to accomplish the same with sass :/ browserify has this flag as well.

**Comment by Lochlan** [comment]
I would also like this feature, some of us prefer the ubiquity and simplicity of GNU Make for build systems.

Stylus [recently](https://github.com/LearnBoost/stylus/tree/0.43.1) added this as the --deps option, it would be great if Sass followed suit.

**Comment by chriseppstein** [comment]
Here's a script I made that does dependency extraction. It could be a good starting point for implementing this feature. Please send Pull Requests if you need to tweek it:

https://github.com/chriseppstein/extract_sass_dependencies/blob/master/extract-sass-dependencies.rb

**Comment by mietek** [comment]
:+1:

**Comment by antitoxic** [comment]
Anything planned on this? Right know I work with https://github.com/xzyfer/sass-graph as a workaround.

**Comment by nex3** [comment]
This is not planned.
