### ISSUE TITLE
Multiplication error

### ISSUE THREAD

**Issue by karellm** [sass/sass#83]
12px \* 60px returns the following error:

Syntax error: 720px*px isn't a valid CSS value.

Is that normal?

**Comment by nex3** [comment]
Yes, this is normal. The multiplication isn't returning the error; the error only occurs when you try to use the result in your stylesheet. When you multiply two numbers with units, you get a number with a new unit, in this case `px*px`. This works just like unit multiplications in real life (e.g. 2 feet times 2 feet = 4 square feet). Since CSS doesn't understand what "square pixels" are, Sass throws an error when you try to use them.

**Comment by karellm** [comment]
I know my math but why does it behave like this within sass? Why would you need squared units?

And how can I work around this limitation?

Thanks

**Comment by nex3** [comment]
It's often useful to define ratios and scaling factors within Sass. For instance, setting `$font-ratio: 14px/1em` allows you to then do `5em * $font-ratio` and have it work properly. In addition, this is simply the way that arithmetic works when using units in any context; it makes sense for Sass to be consistent with other domains.

**Comment by karellm** [comment]
Thanks, it is clearer to me now.

Is there a function to trim the unit from a variable in Sass? I can't find nothing like that in the documentation.

**Comment by chriseppstein** [comment]
You can just divide by 1px to remove one of the px units.

**Comment by bwilkins** [comment]
What is the use-case for this with regards to percentages? I can't even begin to fathom what a 'square-percentage' would mean... (90%*100% == 9000%*% makes no sense at all)

**Comment by Anahkiasen** [comment]
Oh so that's what the famous `px*px` error I get sometimes mean. That should be made clearer somewhere because even if that is how it _is_ supposed to work, I don't think that's how most people will expect it to work. Maybe if no square unit exist, just automatically strip it for the sake of the multiplication. It's not user friendly at all.

**Comment by chriseppstein** [comment]
Making nonsensical calculations work without an error is not user friendly.

**Comment by bwilkins** [comment]
@chriseppstein How about the case of percentages? 90% of 100% is still 90%, as far as I can tell.

**Comment by chriseppstein** [comment]
Percent in sass is a CSS unit.

**Comment by bwilkins** [comment]
And %*% is not a CSS unit... But surely a percentage should be treated like a percentage in mathematics, considering the original argument for closing this bug was to maintain the way units are treated in real-life?

My expectation when multiplying a percentage with anything is to find the desired percentage of the other value, then return the resulting value with the original unit from the other value. this would allow for much more powerful arithmetic, and would still work out properly if the 'other' unit was also a percentage.

Would a pull request be preferable, rather than arguing?

**Comment by nex3** [comment]
@Anahkiasen We're certainly willing to consider more helpful error messages here, if you have suggestions.

@bwilkins The semantics of `%` in CSS are somewhat muddied. `75%` is not considered to be the same as `0.75`; in most contexts, it means "75 units, each 1/100 the width/height of the parent element". Because of this semantic strangeness, we decided not to treat `75%` and `0.75` as the same for the purposes of arithmetic. If you're looking for such behavior, I suggest you use decimals and then convert to percentages using the `percentage()` function once you're done with all calculations.
