### ISSUE TITLE
Strange behavior of the subtraction operator

### ISSUE THREAD

**Issue by piouPiouM** [sass/sass#853]
I noticed the `-` operator needs to be wrapped by spaces in order to work as intented. Operation `1-1` for example, will return a list and not 0.

What is the origin of this unexpected behavior?

Thx.

Some examples:

``` shell
$ sass -v
Sass 3.3.0.alpha.184 (Bleeding Edge)
$ sass -i
>> 1 - 1 // returns a number
0
>> 1- 1 // returns a number
0
>> 1 -1  // returns a list and not a number
(1 -1)
>> 1-1  // returns a list and not a number
(1 -1)
>> a-b
"a-b"
>> b-a
"b-a"
>> a-2 // returns a string as expected
"a-2"
>> 1-b // returns a list and not a string
(1 "-b")
```

**Comment by KittyGiraudel** [comment]
This is probably due to the fact `-` is used as both a hyphenation mark and a substraction operator. In order to differenciate the two, I believe the operator needs to be wrapped by spaces.

I'd love to hear a word of Nathan / Chris on this though. :)

**Comment by nex3** [comment]
This is expected behavior, although unfortunately kind of unintuitive at the margins. In Sass, `-` can be part of an identifier, part of a negative number, a binary subtraction operator, or a unary negation operator. Being an identifier/number has the highest precedence; unary negation has the lowest. This gives rise to all the cases you listed. Let's go over them one by one:

In `1 - 1` it's unambiguously subtraction. Easy peasy. `1- 1` is the same; since `1-` isn't a valid number, the `-` must be the subtraction operator.

`1 -1` starts to get tricky. `-1` is parsed as a number before Sass ever starts to look for operators. This follows the [CSS grammar](http://www.w3.org/TR/WD-css3-syntax-20030813/#grammar0). `1-1` is parsed the same way.

`a-b` is a valid CSS identifier, so it's parsed as an unquoted string. Same for `b-a` and `a-2`.

`1-b` is similar to the `1 -1` case; `-b` is a valid identifier, so it gets parsed as that before any operators are parsed.

**Comment by KittyGiraudel** [comment]
Thanks for detailed explanations Nathan.

**Comment by piouPiouM** [comment]
Thx for taking the time to explain it so clearly Nathan!
