### ISSUE TITLE
darken giving different color in 3.2.10

### ISSUE THREAD

**Issue by chinchang** [sass/sass#883]
I recently updated from 3.2.5 to 3.2.10 and all the color values in CSS which were generated through darken function have now changed slightly. I see nothing related to change in color algorithms in the changelog.

Whats causing the change?

**Comment by chriseppstein** [comment]
Can you please provide examples for what changed?

**Comment by chinchang** [comment]
So if you see the diff here: https://github.com/chinchang/hint.css/commit/aa6681db349c94692226febbcd6e93b1f431869b#L2L174

You'll notice that the colors have changed slightly. Those styles are generated from the line: https://github.com/chinchang/hint.css/blob/master/src/hint-color-types.scss#L19

All I did was update my sass from 3.2.5 to 3.2.10.

**Comment by chriseppstein** [comment]
There is no change to the darken function between those releases.

Based on your files, I constructed this sass file:

``` scss
.darken {
  color: darken(hsl(38, 46%, 54%), 25%);
}
```

In both versions, this file produces:

``` css
.darken {
  color: #6c5328; }
```

I'm closing this, because I think it's not a bug. If you can provide a sass file that produces different results with only the sass version changing, I will reopen.
