### ISSUE TITLE
Add @unless directive

### ISSUE THREAD

**Issue by samme** [sass/sass#889]
Just a little sugar.

**Comment by nex3** [comment]
Writing `@if not` isn't difficult enough to warrant a new directive.

**Comment by adamjgrant** [comment]
I don't think @samme or myself want this directive to solve for difficulty, but code readability. Sass wouldn't be the first to implement such a directive when `if not` already exists. Just my 2 cents.

**Comment by ghost** [comment]
`@if not` is more readable because the condition that's met is always associated with the main block of the statement, and the negative of that is associated with the `@else`. `@unless` moves these blocks around so that the negative is on top and the positive is on the bottom, which leaves more room for mistakes.

**Comment by adamjgrant** [comment]
"the condition that's met is always associated with the main block of the statement"
How is that not true for `@unless`? If `@unless` is a direct map to `@if not`, how could that be true?

"`@unless` moves these blocks around so that the negative is on top and the positive is on the bottom"
This is referring to a poor usage of `@unless`, where the user has used an `@else` condition at all. The value in using an `@unless` is to create a single condition block with a single directive.

```
@unless $fluid {
  max-width: 100px;
}
```

Again, it's not killing me to not have it. I can live with `@if not`. It's not more work or more code, I just think it should be pointed out that difficulty is not the problem being solved.

```
@if not $hasUnlessDirective {
  oh well;
}
```

**Comment by lolmaus** [comment]
`unless` exists in Ruby and CoffeeScript and nobody suffers from it. If you don't like it you just don't use it. I use it all the time.

PS Note that in Ruby `unless` is forbidden to have an `else` clause for the sake of comprehensiveness. But sometimes it is convenient to inverse the `if`-`else` statement so that the short block goes first and the long block goes last. It's trivial in CoffeeScript but in Ruby i have to revert to `if !()` which sucks.

**Comment by nex3** [comment]
Ruby and CoffeeScript have very different design philosophies than Sass. It's much more important for Sass to keep its surface area as small as possible than it is for Ruby and CoffeeScript, since so many of its users are designers by training and don't come in familiar with programming language idioms. The learning curve of `@unless` may not be very high on its own, but to someone still figuring out control structures at all having yet another new thing to learn is a serious burden.

**Comment by dbox** [comment]
+1
