### ISSUE TITLE
CSS-style multiline comments

### ISSUE THREAD

**Issue by Grawl** [sass/sass#896]
CSS [doesn't require](http://www.w3.org/TR/CSS2/syndata.html#comments) an asterisk on each line to comment a block.
I mean this:

``` css
/*
this code
is commented
*/
```

But Sass requires an asterisk on each line and [calls it “CSS comments” in Reference](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#comments). Hate it.

**Comment by lydell** [comment]
The documentation you link to [uses the SCSS syntax](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#syntax). SCSS supports CSS comments like your example.

The indented syntax does actually not require an asterisk on each line. It just requires the subsequent lines to be indented. And since the documentation you link to uses a space to align all the asterisks, each line actually _is_ indented. You can read more about the [indented syntax in the docs](http://sass-lang.com/docs/yardoc/file.INDENTED_SYNTAX.html#comments).

**Comment by nex3** [comment]
@lydell is correct; neither SCSS nor the indented syntax require an asterisk on each line of a comment.

**Comment by Grawl** [comment]
Thank you guys!
