### ISSUE TITLE
using multiple @extend rules

### ISSUE THREAD

**Issue by ghost** [sass/sass#99]
I was wondering, why when using the @extend rule you have to write the
 following code in case you want to extend your object with multiple
 classes:

 .test {@extend .class1; @extend .class2; @extend .class3;}

 It seems to be far easier and more like "classic" css to do it like
 this, don't you think?:

 .test {@extend .class1, .class2, .class3;}

**Comment by albeva** [comment]
+1

**Comment by zofrex** [comment]
I decided this was such a good idea I went and implemented it, luckily I took a TDD approach and wrote the tests first as the tests passed! Turns out this feature is already done and this issue can be closed :)

(And there's no need for a pull request as there are already tests and documentation written, too... #readingfail)

**Comment by nex3** [comment]
Closing since this already works.
